### ISSUE TITLE
Extract `fliud.evaluator` to `fluid.layers.metrics` and `fluid.average`

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#7785] opened 2018-01-23 08:46 UTC
The calculation of metrics and the average is coupled in the `fluid.evaluator`. It is wrong since accuracy and loss could both be averaged. We could apply any average strategy to loss, such as simple moving average, exponential moving average, etc. They should not be coupled.

Tensorflow does not provide [the unified way to average metrics](https://stackoverflow.com/questions/40788785/how-to-average-summaries-over-multiple-batches) and have [many types of metrics](https://www.tensorflow.org/api_docs/python/tf/metrics).

Firstly, I think we need a package, `fluid.layers.metrics`, to provide the layer of all metrics.

Secondly, I think we need provide `Average` classes. The base API of `Average` is

```python
class Average(object):
  def append_value(self, value_to_averge):
     pass

  def average(self):
     """return the averaged value. may create operators inside"""
     pass
```

The example usage is

```python
avg = LinearAverage()
...
avg.append_value(loss)

if get_or_create_global_step() % 1000 = 0:
   print(avg.average())  # create a print op
```

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
