### ISSUE TITLE
add "axis" arg to softmax layer 

### ISSUE THREAD

**Issue by xhuanlc** [PaddlePaddle/Paddle#14749] opened 2018-12-05 08:31 UTC
The current softmax layer,  i.e. paddle.fluid.layers.softmax, only computes softmax along the last dimension. Can you guys add and an "axis" argument to this layer? so the dimension along which to compute softmax can be assigned by users.

**Comment by NHZlX** [comment] 2018-12-06 05:19
Thank you very much for your suggestion. This requirement has been recorded and will be implemented in the future.  If you need this feature urgently, you can try transpose the (N,C,H,W) input into (N,H,W,C) format, and then reshape to shape (NHW, C) , then you can use the softmax op.

**Comment by lucywsq** [comment] 2018-12-20 13:13
Thanks for your suggestion : )
Since this issue has not been updated in the past month. we will close it today for the sake of other user’s experience.If you still need to follow up on this question after closing, please feel free to reopen it.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-12-20 13:13 UTC
Labels: User
