### ISSUE TITLE
"Fluidless" 0.12.0

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/Paddle#10468] opened 2018-05-07 22:26 UTC
If we do not actively plan to promote `v2` in upcoming releases, perhaps we should also consider hiding `fluid` from the user?

Going from: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/label_semantic_roles/no_test_label_semantic_roles.py

to: 
https://gist.github.com/varunarora/a1b195660295a4e4410b935eacd8ef2f

What do you think?

**Comment by sidgoyal78** [comment] 2018-05-07 22:30
Can you tell the source of the second link? I think we already merged  #10368. (https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/label_semantic_roles/no_test_label_semantic_roles.py)

**Comment by varunarora** [comment] 2018-05-07 22:32
@sidgoyal78 I made it up. It doesn't work yet. It's based on your merged code.

**Comment by jetfuel** [comment] 2018-05-07 22:32
Do you mean move from `from paddle.fluid import fluid` to just `import paddle` ? How will we distinguish between v1/v2 with fluid then?

**Comment by wangkuiyi** [comment] 2018-05-07 22:33
We are not going to actively support the v2 API because we don't have enough number of engineers. However, I don't think we should remove the `fluid` Python namespace, because users will be able to call the v2 API when they are using v0.12.0 PaddlePaddle.

**Comment by varunarora** [comment] 2018-05-07 22:52
@wangkuiyi I see, but if a significant majority of usage from `v0.12.0` will come from `fluid` users, shouldn't `v2` be the thing they take extra effort for?

Yes, `v0.12.0` users should still be able to use `v2` without changing their code. The proposed import changes from the gist does not affect them at all. They will continue to import from the `v2` namespace in `paddle` like:

```
from paddle.v2 import ...
```

 The only suggestion here is to promote all the fluid API up to the top-level, so that one can imports like:

```
from paddle.layers import data, embedding, fc, \
                          sums, dynamic_lstm, crf_decoding, linear_chain_crf, \
                          exponential_decay, mean
```

...and have access to `CUDAPlace` and `CPUPlace` all from `paddle.`

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
