### ISSUE TITLE
Training stops on out of memory at [/root/paddle_paddle/paddle/fluid/platform/profiler.cc:114]

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#12530] opened 2018-08-03 09:24 UTC
When trying training on GPU, training terminates after couple thousands of iterations. In this example after 17518th but on a different machine it would stop after some other iteration. Consequently always after the same one on the same machine.
You can see what happened in attached log:
[tail_paddleresnet50v2.log](https://github.com/PaddlePaddle/Paddle/files/2256764/tail_paddleresnet50v2.log)

**Comment by gongweibao** [comment] 2018-10-10 11:18
Try to set FLAGS_fraction_of_gpu_memory_to_use=0.1?

**Comment by lucywsq** [comment] 2018-10-26 04:22
Hello, this issue has not been updated in the past month. We will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 04:22 UTC
Labels: Intel
