### ISSUE TITLE
Loss falls too fast on CPU with Parallel Executor 

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/Paddle#11830] opened 2018-06-29 05:08 UTC
When I try to reproduce  ResNet50 MKL training benchmark with the scripts you provided https://github.com/PaddlePaddle/Paddle/issues/11620 
with 
`export CPU_NUM=32`
`python train_resnet.py --display_step=1 --warmup=0 --use_gpu=false --number_iteration=20 --skip_first_steps=5 --batch_size_per_trainer=2`

I found that loss value falls strangely fast from 6.96 to  0.00363376 during 60 iterations. You can see it from below figure. 
![image](https://user-images.githubusercontent.com/33643817/42074080-cf556668-7b9c-11e8-9e5c-eabb8ec4433d.png)

And in terminal it shows like
iter=1, cost=[6.252923  7.693817  3.2148707 4.397045  5.3967113 9.496346  6.123
 7.934104  6.7035007 4.5136    6.7307415 4.4311924 6.7108507 5.036504
 3.4734368 3.4763126 5.2846932 7.3034186 5.367194  5.7510066 6.9367847
 6.790395  5.0552273 6.684619  5.2520103 6.255669  4.306356  6.4348125
 6.512989  5.10154   5.6753993 5.3312235], elapse=3.214684, img/sec=19.908644
...........
iter=60, cost=[0.00378809 0.00383809 0.00307401 0.00253306 0.00312129 0.00501569
 0.00363376 0.00403982 0.00445763 0.00315989 0.0048361  0.00389746
 0.00403049 0.00344865 0.00267492 0.00406973 0.0040324  0.00297461
 0.00392356 0.00426814 0.00393742 0.00341895 0.00339337 0.00265923
 0.00298006 0.00394307 0.00436897 0.00385214 0.00301216 0.00441125
 0.00428081 0.00403039], elapse=2.242080, img/sec=28.544923

When I run with parallel do , the loss converges much more slowly than using parallel executor.
 Look forwards to your response.

**Comment by luotao1** [comment] 2018-06-29 05:22
#11620 用的是随机数据，不是flowers数据集。

**Comment by bingyanghuang** [comment] 2018-06-29 05:40
我加了一下使用flowers数据的train_reader
train_reader = paddle.dataset.flowers.train()
 train_reader = feeder.decorate_reader(
        paddle.batch(
           #train(), batch_size=args.batch_size_per_trainer),
           train_reader, batch_size=args.batch_size_per_trainer),
      multi_devices=True)

line213 这样的修改是正确的么？如果是的话，loss还是下降的很快。

**Comment by chengduoZH** [comment] 2018-06-29 06:23
@bingyanghuang 是这样的  #11620 用到的脚本每次训练都是使用同样的数据，这是通过fix_data_in_card控制的，这是为了测parallelExecutor的计算速度。
如果要做训练的话，需要把fix_data_in_card改成false.

**Comment by shanyi15** [comment] 2018-08-15 10:19
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:19 UTC
