### ISSUE TITLE
Paddle CAPI什么时候才能支持在一个进程里加载多个模型进行预测？

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#8877] opened 2018-03-08 09:52 UTC
Paddle CAPI什么时候才能支持在一个进程里加载多个模型进行预测？

**Comment by ranqiu92** [comment] 2018-03-08 10:39
暂时没有支持计划

**Comment by luotao1** [comment] 2018-03-08 10:55
https://github.com/PaddlePaddle/Paddle/issues/8260#issuecomment-364313673 是已经支持的了，具体是碰到什么问题了呢

**Comment by wangkuiyi** [comment] 2018-03-09 01:41
我看了 https://github.com/PaddlePaddle/Paddle/issues/8260#issuecomment-364313673 及其上下文。至少在 issue 8260 里描述的这个问题，我以为按照 micro-service 的原则，应该是两个进程，每个进程加载一个模型才是正解？请见：
 https://github.com/PaddlePaddle/Paddle/issues/8260#issuecomment-371684952

**Comment by shanyi15** [comment] 2018-08-15 11:37
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:37 UTC
Labels: User
