### ISSUE TITLE
提交mpi任务时，模型库中ctr wide & deep例子的数据格式，需要设置--use_remote_sparse 0这个参数吗

### ISSUE THREAD

**Issue by macomzzl** [PaddlePaddle/Paddle#10053] opened 2018-04-19 07:25 UTC
提交mpi任务时，模型库中ctr wide & deep例子的数据格式，需要设置`--use_remote_sparse 0`这个参数吗

**Comment by macomzzl** [comment] 2018-04-19 08:57
http://www.paddlepaddle.org/docs/develop/models/ctr/README.cn.html

**Comment by typhoonzero** [comment] 2018-04-19 11:03
设置成`--use_remote_sparse 1`吧，任务提交的命令都开启端口就行，决定是否使用sparse更新可以在python代码中决定。

**Comment by 357589873** [comment] 2018-04-28 05:36
这个可以用GPU吗？

**Comment by shanyi15** [comment] 2018-08-15 10:28
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:28 UTC
Labels: User
