### ISSUE TITLE
The make process generates many filename_pb2.py out of the build directory

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9419] opened 2018-03-27 22:11 UTC
All intermediate files generated by the building process must be in the build directory, other than in the source directory. However, our current build process generates many *_pb2.py files in the source directory. When we build in Docker containers, these files would have the root role.

**Comment by abhinavarora** [comment] 2018-04-05 17:53
Hi @wanglei828 Thank you for reporting this issue. I could not reproduce it. Could you please help me in reproducing this. I did not find _*pb2.py_ files outside of build directory. It would be great if you could give me the exact steps that you used to encounter this. Thank you.

**Comment by wanglei828** [comment] 2018-04-05 17:55
please run "git status --ignored", then you can see these files. because these files have been added into  git ignore file list.

**Comment by typhoonzero** [comment] 2018-05-30 12:14
I think this is fixed now, closing this issue due to low activity, you may reopen it at any time!

**Closed by typhoonzero** 2018-05-30 12:14 UTC
Labels: User
