### ISSUE TITLE
Benchmark of Fluid CPU multi-thread

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#11620] opened 2018-06-21 03:57 UTC
### Environment
- Machine: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, 2 socket, total 40 cores
- Model: ResNet50
- Input: 3 * 224 * 224
- docker images:
   - paddlepaddle/paddle:latest (for MKLML)
   - paddlepaddle/paddle:latest-openblas (for OpenBlas)
- v2 results: https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/IntelOptimizedPaddle.md
- scripts: https://github.com/chengduoZH/benchmark/tree/add_resnet_50_v2/fluid/ResNet_50
### Training
ensure that `CPU_NUM * batch_size_per_trainer = batch_size`, for example, batchsize=64, threads=8
```
export CPU_NUM=8
python train_resnet.py --display_step=1 --warmup=0 --use_gpu=false --number_iteration=20 --skip_first_steps=5 --batch_size_per_trainer=8 
```
The Result (images/second) is as follows:

|core | 1 | 8 | 16 |32| 40|
|---|---|---|---|---|---|
|OpenBlas (Fluid)|1.6342|10.7300|18.9921|30.3432|---|
|MKLML (Fluid) |2.6408|15.874|28.2036|33.9912|---|
|OpenBlas (V2-0.11.0)|---|---|---|---|25.22|
|MKLML (V2-0.11.0) |---|---|---|---|32.52|
### Inference
ensure that `--batch_size_per_trainer=1`, only change the `CPU_NUM`, for example, batchsize=8, threads=8
```
export CPU_NUM=8
python train_resnet.py --display_step=1 --warmup=0 --use_gpu=false --number_iteration=20 --skip_first_steps=5 --batch_size_per_trainer=1 --with_test=True
```
The Result (images/second) is as follows:

| BatchSize | 1     | 2      | 4      | 8      | 16     |
|-----------|-------|--------|--------|--------|--------|
| OpenBLAS (Fluid)  | 4.7254  | 8.6016   | 16.7441  | 33.9707  | 59.2398   |
| MKLML (Fluid)     | 8.4839  | 13.60  | 24.8657  | 48.3597  | 74.5651  |
| OpenBLAS (V2-0.11.0)  | 3.31  | 6.72   | 11.59  | 13.17  | 9.27   |
| MKLML (V2-0.11.0)     | 6.33  | 12.02  | 22.88  | 40.53  | 63.09  |

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
Labels: Intel
