### ISSUE TITLE
基于C++训练库的demo trainer在MKLDNN下报segmentation fault

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/Paddle#19922] opened 2019-09-23 03:08 UTC
###错误描述

基于C++训练库的demo trainer在MKLDNN下报segmentation fault: http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=171521&_focus=6744

本地编译时选择 WITH_MKL=ON, WITH_MKLDNN=ON是出错，WITH_MKL=ON, WITH_MKLDNN=OFF时正常运行, 应该是MKLDNN的问题。

### 错误排查
错误出现在运行这一行时：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/train/demo/demo_trainer.cc#L83

经过排查，是在tensor.cc里面，holder_.reset()时出的错：

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/tensor.cc#L55

### 如何复现这一错误？

```shell
cmake .. -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DON_INFER=ON

make -j40 fluid_lib_dist
make -j40 inference_lib_dist
```

然后，在Paddle/paddle/fluid/train/demo文件夹下：

```shell
set -x

PADDLE_ROOT=your_Paddle/
TURN_ON_MKL=ON # use MKL or Openblas

# download models
function download() {
    wget -q http://paddle-tar.bj.bcebos.com/train_demo/LR/main_program
    wget -q http://paddle-tar.bj.bcebos.com/train_demo/LR/startup_program
}

download

# build demo trainer
fluid_install_dir=${PADDLE_ROOT}/build/fluid_install_dir

mkdir -p build
cd build
rm -rf *
cmake .. -DPADDLE_LIB=$fluid_install_dir \
         -DWITH_MKLDNN=ON \
         -DWITH_MKL=$TURN_ON_MKL
make

cd ..

# run demo trainer
build/demo_trainer
```

**Comment by mapingshuo** [comment] 2019-09-23 03:14
related pull request: https://github.com/PaddlePaddle/Paddle/pull/19885

**Comment by luotao1** [comment] 2019-09-23 03:15
@bingyanghuang Please help see this issue!

**Comment by bingyanghuang** [comment] 2019-09-23 03:32
@grygielski @jczaja  Could you help investigate this issue?
This segmentation fault is caused by with `cmake .. MKLDNN=ON` and you can reproduce this error by following the above steps.

**Comment by jczaja** [comment] 2019-09-23 17:31
I would like to ley you  know that I started to work on this issue and would like to present current status.

Two different segmentation fault cases are encountered when demo_training is executed. One is related to MKL-DNN one is no-MKL-DNN related.

1. MKL-DNN related problem. This is work in progress, but problem seems to be that some paddle code assumes that Tensor::holder_ is first entity in Tensor eg. Address of Tensor == Tensor->holder_ . This is **not** true for MKL-DNN build, as first entity is Tensor::format_ . Dirty fix is to move format_ at the end of Tensor and then crash goes away. This issue is still under investigation I will present PR (1-2 days) on that one.

2. no MKL-DNN related problem. After each execution of : 
   `executor.Run(*train_program, &scope, 0, false, true);`
   loss value is presented (var: mean_0.tmp_0) . But allocation of related tensor does not exist, at that moment, because it is destroyed by `DeleteUnusedTensors() ` right after mean_op finish its execution. I'm not looking further on that segfault and I hope @luotao1 @mapingshuo will have this fixed/explained.

**Comment by mapingshuo** [comment] 2019-09-24 05:26
> I would like to ley you know that I started to work on this issue and would like to present current status.
> 
> Two different segmentation fault cases are encountered when demo_training is executed. One is related to MKL-DNN one is no-MKL-DNN related.
> 
> 1. MKL-DNN related problem. This is work in progress, but problem seems to be that some paddle code assumes that Tensor::holder_ is first entity in Tensor eg. Address of Tensor == Tensor->holder_ . This is **not** true for MKL-DNN build, as first entity is Tensor::format_ . Dirty fix is to move format_ at the end of Tensor and then crash goes away. This issue is still under investigation I will present PR (1-2 days) on that one.
> 2. no MKL-DNN related problem. After each execution of :
>    `executor.Run(*train_program, &scope, 0, false, true);`
>    loss value is presented (var: mean_0.tmp_0) . But allocation of related tensor does not exist, at that moment, because it is destroyed by `DeleteUnusedTensors() ` right after mean_op finish its execution. I'm not looking further on that segfault and I hope @luotao1 @mapingshuo will have this fixed/explained.

1. After moving format_ to end of tensor, the first segmentation fault is gone, thx very much.

2. I got segmentation fault after the program runs for 10 steps, it seems like a problem of memory free. This error happens only when I compile paddle lib with "MKLDNN=ON", so I guess it is still related to MKLDNN. When setting GLOG_vmodule=2, I got no "Erase variable" logs, this means that mean_0.tmp_0 is not deleted by  DeleteUnusedTensors().

**Comment by jczaja** [comment] 2019-09-24 09:27
@mapingshuo 

Regarding,

1. So I will work on PR for that issue?
2. I 'm guessing you are using release build. Try Debug one. When I build paddle with WITH_MKLDNN=OFF and CMAKE_BUILD_TYPE=Debug and demo_trainer also with CMAKE_BUILD_TYPE=Debug then I got segfault at print time of loss var although there is no MKL-DNN used/linked. Try this experiment and let me know the results. 
3. I will continue to check if for 10 iterations for MKL-DNN there some other segfaults.

**Comment by mapingshuo** [comment] 2019-09-24 10:47
> @mapingshuo
> 
> Regarding,
> 
> 1. So I will work on PR for that issue?
> 2. I 'm guessing you are using release build. Try Debug one. When I build paddle with WITH_MKLDNN=OFF and CMAKE_BUILD_TYPE=Debug and demo_trainer also with CMAKE_BUILD_TYPE=Debug then I got segfault at print time of loss var although there is no MKL-DNN used/linked. Try this experiment and let me know the results.
> 3. I will continue to check if for 10 iterations for MKL-DNN there some other segfaults.

2. I build paddle with CMAKE_BUILD_TYPE=debug, and got no bug with demo trainer. Below are comands build paddle and run demo trainer.

build paddle
```shell
cmake .. -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DON_INFER=ON -DWITH_MKLDNN=OFF -DCMAKE_BUILD_TYPE=Debug

make -j40 fluid_lib_dist
make -j40 inference_lib_dist
```

run demo trainer:
```shell
set -x

PADDLE_ROOT=$1 # a/b/Paddle
TURN_ON_MKL=$2 # ON

# download models
function download() {
    wget -q http://paddle-tar.bj.bcebos.com/train_demo/LR/main_program
    wget -q http://paddle-tar.bj.bcebos.com/train_demo/LR/startup_program
}

download

# build demo trainer
fluid_install_dir=${PADDLE_ROOT}/build3/fluid_install_dir

mkdir -p build
cd build
rm -rf *
cmake .. -DPADDLE_LIB=$fluid_install_dir \
         -DWITH_MKLDNN=OFF \
         -DWITH_MKL=$TURN_ON_MKL
make

cd ..

# run demo trainer
build/demo_trainer
```

**Comment by jczaja** [comment] 2019-09-24 13:06
@mapingshuo 

I have analyzed more closely issue 1 eg. Inconsistency class Tensor among Paddle with MKL-DNN and Paddle without MKL-DNN. So proper fix is that you update CMakeLists.txt of demo_trainer:

 `add_executable(demo_trainer demo_trainer.cc)`
 
 `if(WITH_MKLDNN)`
`+  add_definitions(-DPADDLE_WITH_MKLDNN)`
`     include_directories("${PADDLE_LIB}/third_party/install/mkldnn/include")`
`   if(WIN32)`
`     set(MKLDNN_LIB ${PADDLE_LIB}/third_party/install/mkldnn/lib/mkldnn.lib)`

Reason is that demo_trainer.cc is including tensor_utils.h which includes tensor.h and without
PADDLE_WITH_MKLDNN Tensor definition will be diffrent to what Paddle for MKL-DNN is using.

So, Please revert workaround I proposed eg. moving format_ to end of Tensor class and test just this
fix. Let me know if it works for you.

**Comment by mapingshuo** [comment] 2019-09-24 14:07
it works for me, Thx.

**Comment by jczaja** [comment] 2019-09-24 14:18
As for other segfaults I reported. 

You build Paddle with ON_INFER=ON , this to my understanding does enable optimization that are targeting fast inference and for training we should not use ON_INFER=ON. This Test : demo_trainer is to test training(?).  With ON_INFER=ON all pass for me. If ON_INFER=OFF then There is a segmentation fault. Here is part of output when ON_INFER=OFF , for GLOG_v=10 ./build/demo_trainer:

`I0924 06:41:01.166036 156863 naive_best_fit_allocator.cc:87]   pointer=0x7f9ffe4b9080`
`I0924 06:41:01.166103 156863 operator.cc:185] CPUPlace Op(mean),`
`inputs:{X[square_error_cost_0.tmp_1:float[2, 1]({})]}, outputs:{Out[mean_0.tmp_0:float[1]({})]}.`
`I0924 06:41:01.166141 156863 executor_gc_helper.cc:166] Erase variable square_error_cost_0.tmp_1`
`I0924 06:41:01.166146 156863 executor_gc_helper.cc:166] Erase variable mean_0.tmp_0` <-- Erasing mean_0.tmp_0
`I0924 06:41:01.166153 156863 naive_best_fit_allocator.cc:94] Free pointer=0x7f9ffe4b7080 on CPUPlace`

Should ON_INFER=ON be used for this test?

**Comment by luotao1** [comment] 2019-09-24 14:26
> Should ON_INFER=ON be used for this test?

For train demo, we should not use `ON_INFER=ON`

**Comment by jczaja** [comment] 2019-09-24 14:42
Ok,

One more comment, To use PaddlePaddle with MKL-DNN , apart from having it(PaddlePaddle) MKL-DNN build, we need a way to tell paddle to set use_mkldnn ops attribs to true. For C-API (Predictors) this is done with Passes and for python API this is done by exporting FLAGS_use_mkldnn=True . In this situation training from C API, MKL-DNN does not work eg. I do not know how to enable it for demo_training. So once this PR is merged It would be good to start to work on enabling demo_training for mkl-dnn by providing a way for C-API training aps to Enable MKL-DNN. 

Perhaps combining demo_training with GFLAGS would help to enable MKL-DNN

Issue to track enabling of demo_training for MKL-DNN: #19977

**Closed as completed** 2019-09-26 02:56 UTC
Labels: Intel
