### ISSUE TITLE
Paddle inference raise segmentation fault error for quantized ocr recognition model

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#28578] opened 2020-11-12 08:50 UTC
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version
commit id:72c78e4dbbdf74fe9995d9b0757ca6e5832c79d7
cmake: cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON ..
-CPU: CPUMKL/MKLDNN
-GPU: 
-OS Platform:  Ubuntu 16.04.5 LTS   gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5
-Python version: 3.7
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**

Download code and modes(url: https://pan.baidu.com/s/1y8OLGP6WajnSkM_f4_FNKg  password: y0qp) and refer to the readme.md.

**Other info / logs**

![image](https://user-images.githubusercontent.com/52520497/98916830-9b45b380-2506-11eb-8030-11b4d4d40288.png)

**Comment by lidanqing-vv** [comment] 2020-11-16 00:06
data and model is downloaded at `shanghai-6271-ip:/data/issue_28578`

**Comment by wojtuss** [comment] 2020-11-18 08:08
@juncaipeng 
The issue is caused by the faulty `fc_lstm_fuse_pass` (some input and output variables are not set properly in the fuse). The pass is executed during transformation of the quant model into int8 model (during saving the int8 model), and is not executed during inference of the fp32, quant or int8 model - that is why the problem occurs only during int8 inference. It is not related to the quantization process nor mkldnn.
I have proposed a fix for the issue: https://github.com/PaddlePaddle/Paddle/pull/28709.

**Comment by juncaipeng** [comment] 2020-11-20 08:59
@wojtuss  Thank you for solving the segmentation fault.
Compared to the origin model, the results of quantized model is wrong, so please check again.

**Comment by wojtuss** [comment] 2020-11-24 13:04
@juncaipeng ,
After disabling quantization but enabling optimization passes (either all or only non-mkldnn) the output I get is:
```
I1123 08:38:11.626078  7530 model_test.cc:59] input[0]:-0.403922
--
I1123 08:38:11.626096  7530 model_test.cc:60] input[-1]:0
I1123 08:38:11.707707  7530 model_test.cc:79] Threads:1, average cost:15.4ms
I1123 08:38:11.707741  7530 model_test.cc:85] Output save_infer_model/scale_0.tmp_0
I1123 08:38:11.707747  7530 model_test.cc:96] output[0]: 5492
I1123 08:38:11.707753  7530 model_test.cc:96] output[1]: 2696
I1123 08:38:11.707758  7530 model_test.cc:100] Output save_infer_model/scale_1.tmp_0
I1123 08:38:11.709888  7530 model_test.cc:111] output[0]: 1.19614e-09
I1123 08:38:11.709901  7530 model_test.cc:111] output[1]: 2.37613e-10
I1123 08:38:11.709905  7530 model_test.cc:111] output[2]: 3.2994e-11
I1123 08:38:11.709908  7530 model_test.cc:111] output[3]: 1.71248e-12
I1123 08:38:11.709913  7530 model_test.cc:111] output[4]: 9.33774e-13
I1123 08:38:11.709915  7530 model_test.cc:111] output[5]: 8.78324e-10
I1123 08:38:11.709918  7530 model_test.cc:111] output[6]: 1.33439e-08
I1123 08:38:11.709921  7530 model_test.cc:111] output[7]: 3.65979e-11
I1123 08:38:11.709925  7530 model_test.cc:111] output[8]: 8.11972e-10
I1123 08:38:11.709928  7530 model_test.cc:111] output[9]: 4.00257e-11
I1123 08:38:11.716387  7530 model_test.cc:113] max value:1
```
Is it correct?
It differs from the output of fp32 and quant models, which was:
```
I1123 08:08:41.678112  6677 model_test.cc:59] input[0]:-0.403922
--
I1123 08:08:41.678129  6677 model_test.cc:60] input[-1]:0
I1123 08:08:42.011580  6677 model_test.cc:79] Threads:1, average cost:127.194ms
I1123 08:08:42.011606  6677 model_test.cc:85] Output save_infer_model/scale_0.tmp_0
I1123 08:08:42.011612  6677 model_test.cc:96] output[0]: 389
I1123 08:08:42.011617  6677 model_test.cc:96] output[1]: 519
I1123 08:08:42.011620  6677 model_test.cc:96] output[2]: 472
I1123 08:08:42.011622  6677 model_test.cc:96] output[3]: 519
I1123 08:08:42.011626  6677 model_test.cc:100] Output save_infer_model/scale_1.tmp_0
I1123 08:08:42.013337  6677 model_test.cc:111] output[0]: 1.87588e-08
I1123 08:08:42.013348  6677 model_test.cc:111] output[1]: 1.32461e-08
I1123 08:08:42.013350  6677 model_test.cc:111] output[2]: 1.21617e-08
I1123 08:08:42.013353  6677 model_test.cc:111] output[3]: 3.32012e-08
I1123 08:08:42.013355  6677 model_test.cc:111] output[4]: 3.81083e-09
I1123 08:08:42.013357  6677 model_test.cc:111] output[5]: 1.23054e-09
I1123 08:08:42.013360  6677 model_test.cc:111] output[6]: 1.43666e-09
I1123 08:08:42.013362  6677 model_test.cc:111] output[7]: 6.18276e-09
I1123 08:08:42.013365  6677 model_test.cc:111] output[8]: 2.0969e-09
I1123 08:08:42.013366  6677 model_test.cc:111] output[9]: 6.70895e-08
I1123 08:08:42.018697  6677 model_test.cc:113] max value:1
```

**Comment by juncaipeng** [comment] 2020-11-25 11:57
@wojtuss  Base on your test results, the outputs of opted int8 model is incorrect. 
As the outputs of quant model are the same to the fp32 model, I think the MKLDNN inference still has errors.

The OCR model has two outputs, please modify the demo to check more output data.

**Comment by lidanqing-vv** [comment] 2020-11-26 21:50
Hi @juncaipeng  Today I tried many ways, my conclusion is as follows. 
1. The output may not measure accuracy.
The rec_crnn_quant and rec_crnn_fp32 output are also different. Maybe the `max value` in the output is for accuracy. Could you please verify again what does all these outputs mean? Or could you provide some doc describing this model.
2. Small possibility that the scales are not collected properly. Since I checked with this
```
        graph = self._gather_weight_scales_from_fake(graph)
        graph = self._gather_output_scales_from_attr(graph)
        graph = self._gather_input_scales_from_fake(graph)
        graph = self._remove_fake_ops(graph)
        graph = self._dequantize_weights(graph)
        graph = self._optimize_fp32_graph(graph)
        graph = self._compute_weight_scales(graph)
        graph = self._update_relu_output_scales(graph)
        graph = self._propagate_scales(graph)
      # graph = self._quantize_fp32_graph(graph)
      # graph = self._final_optimizations(graph)
        graph = self._cleanup(graph)
```
Which means it does not do any quantization, only collect the scales and optimise the fp32 model, if the output is really measuring accuracy, the first dimension and second dimension of output should be the same as `rec_crnn_fp32`, because here there is no quantization at all. But the output are different from `rec_crnn_fp32` model (as Wojtek's comments). If this is really an error, then it means the scales are collected wrongly, but I scales propagation and calculation is not related with matching pattern so it should not cause the graph accuracy drop.

It is normal that accuracy drop from 0.99 to 0.92. If it is text recognition, similar text does not necessary has same decoding numbers. So what does all those outputs mean ?

**Comment by wojtuss** [comment] 2020-11-29 19:23
Hi @juncaipeng 
In addition to what @lidanqing-intel wrote above, my comments:
1. in the model: the `out_threshold` attribute in `conv2d` ops sometimes stores values 0 - we usually use them for quantization and for them to be useful they must have positive values,
2. there is possibly an effect of the above plus some problem in the quantization process: some quantization scales turn out to be `infinity`.
We are still investigating the issue.

**Comment by juncaipeng** [comment] 2020-11-30 02:26
@wojtuss  We also found that the out_threshold of some conv2d ops is equal to 0, and the quantized model is verified to be right.

**Comment by juncaipeng** [comment] 2020-12-14 12:57
@lidanqing-intel @wojtuss 

In order to check the accuracy,  the first output of the quantized model should be the same as the fp32 model, as follows:
>I1123 08:08:42.011606  6677 model_test.cc:85] Output save_infer_model/scale_0.tmp_0
>I1123 08:08:42.011612  6677 model_test.cc:96] output[0]: 389
>I1123 08:08:42.011617  6677 model_test.cc:96] output[1]: 519
>I1123 08:08:42.011620  6677 model_test.cc:96] output[2]: 472
>I1123 08:08:42.011622  6677 model_test.cc:96] output[3]: 519

For the second output,  please modify the model_test.cc in (url: https://pan.baidu.com/s/1y8OLGP6WajnSkM_f4_FNKg password: y0qp) , just print the index and value that is bigger than 1e-3, and then check the output value of quantized model and fp32 model.

**Comment by wojtuss** [comment] 2020-12-14 14:54
@juncaipeng ,
Thank you, I will give it a try.

**Comment by wojtuss** [comment] 2020-12-15 16:27
@juncaipeng ,
In the model there are two `fake_channel_wise_dequantize_max_abs` operators which has the `Scales[0]` input of all zeros (the input names: `channel_scale_40` and `channel_scale_10`). That doesn't seem to be correct, because in that case the convolution weights (`conv2_se_1_weights` and `conv2_se_2_weights`, both non-zero, fake-quantized) cannot be fake-dequantized to fp32 values before attempting to quantization of the model. It looks like the scales were not set properly in the `fake_dequantize_*` operators in the process of preparing the Quant version of the model.

**Comment by wojtuss** [comment] 2020-12-16 10:32
Below are the values of the two weight tensors from the quant model (the values are fake-quantized, i.e. quantized but kept as floats). The tensors are non-zero. However, the quantization scales saved for those tensors in input `Scales` of the operators `fake_channel_wise_dequantize_max_abs` (`channel_scale_40` and `channel_scale_10`) are tensors of zeros. In this situation conversion quant->fp32->int8 fails on transforming the quant model into fp32 model, as the weight tensors cannot be transformed (i.e. dequantized into clean fp32 model) properly.

`conv_se_1_weights`, dims: (2, 8, 1, 1), values:
```
[[[[  49.]]  [[-127.]]  [[ -38.]]  [[ 109.]]  [[-117.]]  [[ -86.]]  [[ -96.]]  [[ -73.]]]
[[[ -77.]]  [[ -70.]]  [[ 127.]]  [[   4.]]  [[  -6.]]  [[ -83.]]  [[  87.]]  [[ -61.]]]]
```
`conv_se_2_weights`, dims: (8, 2, 1, 1), values:
```
[[[[ -69.]]  [[ 127.]]]
[[[  35.]]  [[-127.]]]
[[[-127.]]  [[ -51.]]]
[[[-127.]]  [[ -18.]]]
[[[  11.]]  [[-127.]]]
[[[ -30.]]  [[-127.]]]
[[[ -87.]]  [[ 127.]]]
[[[ 127.]]  [[ -20.]]]]
```

**Comment by wojtuss** [comment] 2021-01-27 07:51
@juncaipeng , I am closing this issue. Feel free to reopen it if needed.

**Closed as completed by wojtuss** 2021-01-27 07:51 UTC
