### ISSUE TITLE
MKLDNN: Fluid High level inference API does not account for MKL-DNN

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#12195] opened 2018-07-17 17:21 UTC
Recently Inference High Level API was introduced. It does not have functionality to use MKL-DNN ops for inference. 

To use MKL-DNN for High Level API based programs it is needed to add enabling function of MKLDNN:  
`if (FLAGS_use_mkldnn) executor_->EnableMKLDNN(*inference_program_);`

Around line 92  of:
https://github.com/PaddlePaddle/Paddle/blob/f9f8fbaa5ec43e960c3054f8a76475d945cb678a/paddle/contrib/inference/paddle_inference_api_impl.cc#L88-L94

The other problem is that when Paddle is build with -DWITH_GPU=OFF , then Gflags is not initialized
in High Level API eg. GFlags is only processed for situation when GPU is used:
https://github.com/PaddlePaddle/Paddle/blob/f9f8fbaa5ec43e960c3054f8a76475d945cb678a/paddle/contrib/inference/paddle_inference_api_impl.cc#L279

I would appreciate if you can help with adding **FLAGS_use_mkldnn**  so that High Level API can take advantage of it.

**Comment by luotao1** [comment] 2018-07-18 02:39
Thanks for your suggestion, I will fix it.

**Comment by jczaja** [comment] 2018-07-18 09:16
@luotao1 Thanks very much. Looking forward to have MKL-DNN support in Inference High Level API

**Comment by lucywsq** [comment] 2018-09-20 16:21
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-09-20 16:21 UTC
Labels: Intel
