### ISSUE TITLE
所有预测值都是1.60381e-28，模型参数没有发现极大极小现象

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#9919] opened 2018-04-14 12:18 UTC
所有预估值全部是1.60381e-28，模型参数没有发现极大极小现象

求大神指教有什么方法来定位问题呢

**Comment by wanghaoshuang** [comment] 2018-04-15 00:43
可以通过print中间层的结果来debug。
如果你用的fluid API, 可以使用：[Print op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py#L150)
如果你用的v1或v2 API: 可以使用：[value_printer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/evaluators.py#L589)

**Comment by shanyi15** [comment] 2018-08-15 11:36
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
Labels: User
