### ISSUE TITLE
generic.cmake must not depends on other .cmake files

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#10558] opened 2018-05-10 04:41 UTC
generic.cmake was designed by @gangliao to mimic the behavior of Bazel. It was designed from fresh so to make our build system lean and mean. However, I noticed that recently it calls [`find_fluid_modules`](https://github.com/PaddlePaddle/Paddle/blob/62c51e44d28f93f08b1877bbb4b395e82d7e4d21/cmake/generic.cmake#L258) defined in another cmake file

https://github.com/PaddlePaddle/Paddle/blob/e90e7ab237723ddab75be247d5f29780968924f4/cmake/inference_lib.cmake#L17

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
