### ISSUE TITLE
Complete Fluid -- Function Definition and Invocation

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#10244] opened 2018-04-26 21:34 UTC
### Motivation 1. Inference Engine Calls Fluid Functions

The inference/production system are not supposed to be created by PaddlePaddle team, and not even PaddlePaddle users. They are often server programs in C++/Java/Go, or mobile inference engines in C/Objective-C.  PaddlePaddle project should provide a library, which allows
1. The users can use whatever **host language** to create the production system, and
1. they can call Fluid functions that describe the inference algorithms from their host languages.

### Motivation 2. Canonicalize IfElse/While Implementations (arguably)

The current implementation of IfElseOp and WhileOp is kind of hacky -- values passing in/out the blocks are in a hacky way, involving some hacky concepts like **InLink** and **OutLink**, which should have been **arguments** and **return values** and should have been implemented using FuncCallOp, which implements a canonical calling convention which will be explained in the rest of this document.

## Technical Viability

An argument is the Fluid is a **differenetial langauge**, but if the FuncCallOP differentable?

I think the answer is Yes, because the function call is basically insert the sequence of operations of a block (the callee's body) into the caller's body.  As long as the sequential execution is differentiable, the function call should be differentiable -- with the help of [scope-hierarchy](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/concepts/scope.md).

### A Function

A function is composed of the following staff:

1. function *signature*
   1. function name
   1. inputs, or arguments,
   1. outputs, or return values
1. function *body*

Currently, Fluid has the `framework.BlockDesc` message that can be used to represent the function body, but not the signature.

### A Program

A program (imagine a C program) is composed of one or more functions, where one of them (with the name `main`) is the default entry-point, which might call other functions.

Other functions might be entry-points too -- consider a C program that is built into an .so file.  In the case of Fluid, we need similar feature, e.g., to allow a C++ function (in the inference engine program) to call a Fluid function (which implements the inference algorithm).

Currently, a Fluid program (a `ProgramDesc` message) cannot have function definitions, so instead, it looks something like a Python script, or a block-hierarchy, where the root block is the entry-point of the "Python script".

**Comment by helinwang** [comment] 2018-04-26 21:56
Agree, we are missing function representation in the program desc. I want to point out that the new API design is fully compatible with the solution of this issue:

```Python
class Word2Vec(fluid.Program):
  @network("firstw", "secondw", "thirdw", "forthw", "nextw")
  def train_step(self):
    # ...
  @network("firstw", "secondw", "thirdw", "forthw")
  def infer(self):
    # ...

word2vec = Word2Vec().Compile()
avg_cost = word2vec.train_step(data[0], data[1], data[2], data[3], data[4])
next_word = word2vec.infer(1,2,3,4)
```

The `Compile` function in `word2vec = Word2Vec().Compile()` can put the method name `train_step` and `infer`, as well as their arguments into the program desc.

**Comment by wangkuiyi** [comment] 2018-04-26 21:57
### Fluid Programs and Functions

Basing on the following facts:

- A program is a collection of function definitions, where one of them is the default entry-point.
- Each function has a signature and a body (block).
- Each block includes some 
  - operator calls, which are like invocations of built-in or standard functions,
  - Fluid function calls, which are like invocations of user-defined functions.
  These function calls can access
  - local variables
  - function parameters and return values (if the block is a function body)
  - variables defined in parent blocks.

I propose to change our `ProgramDesc` and `BlockDesc` message definitions as following:

``protobuf
message ProgramDesc {
  repeated FunctionDesc functions = 1; // the first function is the entry-point, or the main function.
}

message FunctionDesc {
  required string name = 1;
  repeated VarDesc args = 2;
  repeated VarDesc rets = 3;
  BlockDesc block = 4;
}
```

**Comment by putcn** [comment] 2018-04-26 22:38
> Each return value of a function is an index referring to a variable defined in the caller function's body block.
does that mean function caller is tightly bonded with function definition?

**Comment by shanyi15** [comment] 2018-08-15 10:28
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:28 UTC
