### ISSUE TITLE
 no_kernel_op_set in framework need to do a code clean up

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#10860] opened 2018-05-23 04:23 UTC
Currently, our python framework contains the op without kernel set, it should be a c++ method and exported to python.
https://github.com/PaddlePaddle/Paddle/blob/8655904be21df4731c2c8f2fd380027d670cefda/python/paddle/fluid/framework.py#L489
```
        no_kernel_op_set = {
            'feed', 'fetch', 'save', 'load', 'recurrent', 'go',
            'rnn_memory_helper_grad', 'conditional_block', 'while', 'send',
            'recv', 'listen_and_serv', 'parallel_do', 'save_combine',
            'load_combine', 'ncclInit', 'channel_create', 'channel_close',
            'channel_send', 'channel_recv', 'select', 'gen_nccl_id'
        }
```

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
