### ISSUE TITLE
question about nested RNN

### ISSUE THREAD

**Issue by Haichao-Zhang** [PaddlePaddle/Paddle#10866] opened 2018-05-23 05:50 UTC
I have a questions related to nested/hierarchical/recursive-RNN:
per the design doc on **LoD (Level-of-Detail) Tensor**,  paddle-fluid will support nested-RNN (or hierarchical/recursive-RNN) . And it seems that supporting nested-RNN is one of the main reason for the notion of "LoD". Do we have any plan for adding this? 

https://github.com/PaddlePaddle/Paddle/blob/236dc7be458d7e508ac62db03d3b7c9c51f88941/doc/fluid/design/concepts/lod_tensor.md

![image](https://user-images.githubusercontent.com/21375027/40405505-b3cb15a8-5e11-11e8-92cc-a0e807480a2b.png)

**Comment by panyx0718** [comment] 2018-05-31 00:45
@guoshengCS do we have support for recursive RNN now?

**Comment by guoshengCS** [comment] 2018-05-31 05:14
I guess we cann't support nested-RNN currently because of some operators' limit on LoD. Our [gru_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/gru_op.h#L91) and [lstm_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lstm_op.h#L108)'s codes limit the LoD level to be 1 . Additionally, some operators in DynamicRNN such as also limit the LoD level to be 1 currently, such as [reorder_lod_tensor_by_rank_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/reorder_lod_tensor_by_rank_op.cc#L124).  I'm not sure how many operators have LoD limits and if it is can be directly, maybe it needs further discussion.

**Comment by Haichao-Zhang** [comment] 2018-05-31 05:26
@guoshengCS  thanks for the reply! My personal feeling is that if we just limit the LoD level to be 1 when we implement the relevant ops, we lose the benefit of LoD and this makes the notion of LoD less powerful and useful. Do we have any plan along this direction?

**Comment by Haichao-Zhang** [comment] 2018-06-07 18:34
A related PR: https://github.com/PaddlePaddle/Paddle/pull/11297/files

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
