### ISSUE TITLE
在Fluid中增加selu激活函数，https://arxiv.org/abs/1706.02515

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Paddle#8072] opened 2018-02-02 02:51 UTC
The activation function of SNNs are "scaled exponential linear units" (SELUs), which induce self-normalizing properties.

**Comment by cheradam** [comment] 2018-03-28 01:24
At the issue-triage meeting，marked this issue as low priority。

**Comment by shanyi15** [comment] 2018-08-15 11:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by TomorrowIsAnOtherDay** [comment] 2018-11-14 08:04
Hi, any news about the development of "SELU" activation function?

**Comment by mapingshuo** [comment] 2018-11-15 02:21
Hi, @TomorrowIsAnOtherDay, I am developing the "selu" activation op, soon it will be release.

**Comment by TomorrowIsAnOtherDay** [comment] 2018-11-15 02:23
Thanks a lot for your reply!
It's really a very helpful activation function in many models.
Looking forward to having this op in fluid.

**Comment by mapingshuo** [comment] 2018-11-15 02:29
Thanks for your interest in this issue :)

**Closed** 2018-11-21 02:54 UTC
Labels: NewOp
