### ISSUE TITLE
请问 Paddle c-api 中的 paddle_arguments 类型有序列化/反序列化方法吗 

### ISSUE THREAD

**Issue by usafchn** [PaddlePaddle/Paddle#8802] opened 2018-03-06 12:20 UTC
背景是模型部署在 server 端，client 通过 rpc 访问，输入参数(paddle_arguments)在 client 端生成并通过网络发送到 server 端，server 调用 paddle_gradient_machine_forward 完成预测。现在的问题是paddle 是否有提供序列化/反序列化 argument 对象的方法？

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC
