### ISSUE TITLE
训练中通过feed参数给数据，如果发生数据不存在的错误，程序不会退出

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#11507] opened 2018-06-15 05:29 UTC
如以下方式:
train_reader = paddle.batch(reader.train(), batch_size=train_batch_size)
for batch_id, data in enumerate(train_reader()):
            loss, acc1, acc5 = train_exe.run(fetch_list, feed=feeder.feed(data))

如果train_reader出错，比如某个图片不存在，这种情况下reader会报错，但是报错后主程序也不会退出，只能强制杀掉。

**Comment by shanyi15** [comment] 2018-08-15 11:34
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:34 UTC
Labels: User
