### ISSUE TITLE
paddle v2 api (precision_recall)

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#10861] opened 2018-05-23 04:48 UTC
![image](https://user-images.githubusercontent.com/15082798/40403883-5642c4e6-5e87-11e8-9032-fa8f61b8fe5b.png)
图中的simple usage，估计是写错了。
另外对于positive_label，感觉不像是一个layer，而是一个int型的label。

**Comment by Superjomn** [comment] 2018-05-23 05:29
@shanyi15 单老师可以帮看看是文档转换还是注释有问题吗

**Comment by Superjomn** [comment] 2018-05-23 05:30
v2 有自己实现 evaluator 的文档吗？ @jacquesqiao

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
Labels: User
