### ISSUE TITLE
Use standardized CMake functions

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11584] opened 2018-06-20 00:30 UTC
https://github.com/PaddlePaddle/Paddle/blame/develop/paddle/fluid/operators/math/CMakeLists.txt#L3

Could we use functions defined in generic.cmake instead of defining `math_library` here?

**Comment by wangkuiyi** [comment] 2018-06-20 00:31
A related issue is https://github.com/PaddlePaddle/Paddle/issues/11583

**Comment by wangkuiyi** [comment] 2018-06-20 00:31
Another related issue is https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/reader/CMakeLists.txt#L4

@reyoung

**Comment by luotao1** [comment] 2018-06-20 09:26
@wangkuiyi 
In function `math_library`, we use `cc_library`, `nv_library` defined in `generic.cmake`
https://github.com/PaddlePaddle/Paddle/blob/80f63642e63a0f6c6207a10b4154eb426527ed73/paddle/fluid/operators/math/CMakeLists.txt#L26-L32
The sake of `math_library` is to reduce and simpify the cmake code. For example, the original cmake likes:
```
cc_library(concat SRCS concat.cc DEPS math_common_deps device_context framework_proto)
nv_library(concat SRCS concat.cu DEPS math_common_deps device_context framework_proto)
```
but if we use `math_library`, it becomes:
```
math_library(concat)
```

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
