### ISSUE TITLE
Paddle V4 API - Word to Vec

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#10214] opened 2018-04-25 22:27 UTC
API design: https://github.com/PaddlePaddle/Paddle/issues/10152

```Python
import paddle.fluid as fluid
import paddle

IS_SPARSE = True
BATCH_SIZE = 32
NUM_EPOCHS = 3
N = 5


class Word2Vec(fluid.Program):
  EMBED_SIZE = 32
  HIDDEN_SIZE = 256

  def __init__(dict_size, is_sparse):
      self.dict_size = dict_size
      self.is_sparse = is_sparse

  def predict(self):
      embeds = []
      num_embeds = 4
      for i in range(num_embeds):
        # every embedding will share the same parameter
        with fluid.var_scope("shared_embedding"):
            embed = fluid.layers.embedding(
                input=first_word,
                size=[self.dict_size, EMBED_SIZE],
                dtype='float32',
                is_sparse=self.is_sparse)
            embeds.append(embed)

      concat_embed = fluid.layers.concat(
          input= embeds, axis=1)
      hidden1 = fluid.layers.fc(input=concat_embed,
                                size=HIDDEN_SIZE,
                                act='sigmoid')
      predict_word = fluid.layers.fc(input=hidden1,
                                     size=self.dict_size,
                                     act='softmax')
      return predict_word

  @network("firstw", "secondw", "thirdw", "forthw", "nextw")
  def train_step(self):
      first_word = fluid.layers.data(name='firstw', shape=[1], dtype='int64')
      second_word = fluid.layers.data(name='secondw', shape=[1], dtype='int64')
      third_word = fluid.layers.data(name='thirdw', shape=[1], dtype='int64')
      forth_word = fluid.layers.data(name='forthw', shape=[1], dtype='int64')
      next_word = fluid.layers.data(name='nextw', shape=[1], dtype='int64')
      with fluid.var_scope("predict"):
         predict_word = self.predict(first_word, second_word, third_word, forth_word)
      cost = fluid.layers.cross_entropy(input=predict_word, label=next_word)
      avg_cost = fluid.layers.mean(cost)
      sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.001)
      sgd_optimizer.minimize(avg_cost)
      return avg_cost

  @network("firstw", "secondw", "thirdw", "forthw")
  def infer(self):
      first_word = fluid.layers.data(name='firstw', shape=[1], dtype='int64')
      second_word = fluid.layers.data(name='secondw', shape=[1], dtype='int64')
      third_word = fluid.layers.data(name='thirdw', shape=[1], dtype='int64')
      forth_word = fluid.layers.data(name='forthw', shape=[1], dtype='int64')
      with fluid.var_scope("predict"):
          predict_word = self.predict(first_word, second_word, third_word, forth_word)
      return predict_word

# training and infer begins here
word_dict = paddle.dataset.imikolov.build_dict()
word2vec = Word2Vec(len(word_dict), IS_SPARSE).Compile()
train_reader = paddle.batch(
    paddle.dataset.imikolov.train(word_dict, N), BATCH_SIZE)

for epoch_id in range(NUM_EPOCHS):
    for data in train_reader():
        avg_cost = word2vec.train_step(data[0], data[1], data[2], data[3], data[4])

next_word = word2vec.infer(1,2,3,4)

# save inference parameters
fluid.save_parameters(word2vec.infer, "./infer_params")

# load inference parameters example
# `Compile` initializes the parameters, but will be overridden by `fluid.load_parameters`.
word2vec_new = Word2Vec(len(word_dict), IS_SPARSE).Compile()
fluid.load_parameters(word2vec_new.infer, "./infer_params")
next_word = word2vec_new.infer(1,2,3,4)
```

**Comment by wangkuiyi** [comment] 2018-04-26 21:29
Thanks for this design!

I understand that this design proposes a way to define and call (from Python) Fluid functions. My concern is that the definition of Fluid functions depends not only on Fluid blocks, but also Python decorator `@network`; however, given that Fluid functions might be called from other host languages (C++, Java, Go) other than Python, we'd prefer Fluid function definitions implemented only in Fluid.

**Comment by helinwang** [comment] 2018-04-26 21:38
> However, given that Fluid functions might be called from other host languages (C++, Java, Go) other than Python, we'd prefer Fluid function definitions implemented only in Fluid.

Agree, we need to store function signature in Fluid program desc just like the exported functions in a shared library. In this way a program desc can be called from other languages.

> In particular, the definition of Fluid functions depends not only on Fluid blocks, but also Python decorator `@network`.

To me `@network` is just a front-end language syntax, marking the to-be-compiled function and its inputs. The Python `Compile` function can save this information to program desc.

> I think that Fluid functions might be called from other host languages is due to the way we do inference -- the form of the Fluid inference engine could be a gRPC server in C++, Java, or Go, an Objective-C program built for ARM, etc; anyway, they need to be able to call the Fluid function describing the inference process.

Agree.

**Comment by Superjomn** [comment] 2018-04-27 00:44
To my understanding, the user syntax has two layers, the underlying layer implements the basic but flexible elements which can cover 100% use cases, trivial but complete, just like the TF; the upper layer makes some encapsulation to make the 80% frequent use cases easier, like Keras or other wrappers.

I wonder whether this is the mix of these two layers or the underlying layer?

**Comment by Superjomn** [comment] 2018-04-27 00:57
```python
def predict(self):
    # every embedding will share the same parameter
    with fluid.var_scope("shared_embedding"):
        embed_first = fluid.layers.embedding(
            input=first_word,
            size=[self.dict_size, EMBED_SIZE],
            dtype='float32',
            is_sparse=self.is_sparse)
    with fluid.var_scope("shared_embedding"):
        embed_second = fluid.layers.embedding(
            input=second_word,
            size=[self.dict_size, EMBED_SIZE],
            dtype='float32',
            is_sparse=self.is_sparse)
    with fluid.var_scope("shared_embedding"):
        embed_third = fluid.layers.embedding(
            input=third_word,
            size=[self.dict_size, EMBED_SIZE],
            dtype='float32',
            is_sparse=self.is_sparse)
    with fluid.var_scope("shared_embedding"):
        embed_forth = fluid.layers.embedding(
            input=forth_word,
            size=[self.dict_size, EMBED_SIZE],
            dtype='float32',
            is_sparse=self.is_sparse)
```
can be rewritten to 

```python
def predict(self):
    embeds = []
    num_embeds = 4
    # every embedding will share the same parameter
    with fluid.var_scope("shared_embedding"):
        for i in range(num_embeds):
            embed = fluid.layers.embedding(
                input=first_word,
                size=[self.dict_size, EMBED_SIZE],
                dtype='float32',
                is_sparse=self.is_sparse)
            embeds.append(embed)
```

also

```python
word_names = 'firstw secondw thirdw forthw nextw'.split()
@network(*word_names)
def train_step(self):
    words = []
    for name in word_names:
        word = fluid.layers.data(name='firstw', shape=[1], dtype='int64')
        words.append(word)
```

**Comment by helinwang** [comment] 2018-04-27 01:00
Thanks @Superjomn ! That is a very good question!

Sorry maybe the title is a little misleading, this issue mainly tries to address how to do cross language invocation (e.g., Python calls Fluid program). It is primarily done by using the `@network` decorator and the `Compile` function. It also address scope sharing, the compiled program shares a same scope.

The issue you raise is indeed very important, however I don't think it's the focus for this issue. The example "network construction" code is taken from our fluid example directly. We need to answer this question in another discussion. Perhaps my title is to general.

**Comment by helinwang** [comment] 2018-04-27 01:08
@Superjomn thanks!!! The first code change actually should be:

```Python
def predict(self):
    embeds = []
    num_embeds = 4
    # every embedding will share the same parameter
    for i in range(num_embeds):
        with fluid.var_scope("shared_embedding"):
            embed = fluid.layers.embedding(
                input=first_word,
                size=[self.dict_size, EMBED_SIZE],
                dtype='float32',
                is_sparse=self.is_sparse)
            embeds.append(embed)
```
`with fluid.var_scope("shared_embedding"):` resets the unique name generator with the new scope.

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
