### ISSUE TITLE
seq2seq 的10w分类预测，各个指标异常问题

### ISSUE THREAD

**Issue by majiayuanyuan** [PaddlePaddle/Paddle#5307] opened 2017-11-02 08:32 UTC

**Comment by majiayuanyuan** [comment] 2017-11-02 08:36
具体网络结构如下：   
    data = paddle.layer.data("word",
                             paddle.data_type.integer_value_sequence(input_dim))
    emb = paddle.layer.embedding(input=data, size=emb_dim)

    fc1 = paddle.layer.fc(
        input=emb, size=hid_dim, act=linear, bias_attr=bias_attr)
    lstm1 = paddle.layer.lstmemory(
        input=fc1, act=relu, bias_attr=bias_attr, )
    inputs = [fc1, lstm1]
    for i in range(2, stacked_num + 1):
        fc = paddle.layer.fc(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=para_attr,
            bias_attr=bias_attr)
        lstm = paddle.layer.lstmemory(
            input=fc,
            reverse=(i % 2) == 0,
            act=relu,
            bias_attr=bias_attr,
            )
        inputs = [fc, lstm]

    fc_last = inputs[0]
    lstm_last = inputs[1]
    if cost_type == 'classification':
        word_fea = paddle.layer.fc(
            input=[fc_last, lstm_last],
            size=hid_dim,
            act=linear,
            bias_attr=bias_attr,
            param_attr=para_attr)

        output = paddle.layer.fc(
                input=[word_fea],
                size=class_dim,
                act=paddle.activation.Softmax(),
                bias_attr=bias_attr,
                )

        lbl = paddle.layer.data("label", paddle.data_type.integer_value_sequence(class_dim))
        
        cost = paddle.layer.classification_cost(input=output, label=lbl)

**Comment by shanyi15** [comment] 2018-08-15 11:12
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:12 UTC
Labels: User
