### ISSUE TITLE
机器翻译异步比同步训练慢太多 

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#11707] opened 2018-06-26 03:36 UTC
**paddle版本：v0.14**
**代码库地址**：https://github.com/xuezhong/transformer-nist/tree/master/transformer_cloud
**代码增加异步参数：**
```bash
 parser.add_argument(
        '--async_mode',
        action='store_true',
        default=False,
        help='Whether start pserver in async mode to support ASGD')
```
```bash
t = fluid.DistributeTranspiler()
        t.transpile(
            trainer_id,
            pservers=pserver_endpoints,
            trainers=trainers,
            sync_mode=not args.async_mode)
```
**异步训练参数和结果如下：**
```bash
Namespace(async_mode=True, batch_size=4096, iterations=100, local=False, opts=[], pass_num=1000, pool_size=10000, shuffle=True, shuffle_batch=True, sort_type='pool', special_token=['_GO', '_EOS', '_UNK'], src_vocab_fpath='./nist06n/cn_30001.dict', train_file_pattern='./nist06n/train_split/part-*', trg_vocab_fpath='./nist06n/en_30001.dict', use_gpu=True, use_token_batch=True, val_file_pattern='./nist06n/test/part-*')
```
trainer0 训练结果：
```bash
epoch: 0, batch: 100, sum loss: 313298.500000, avg loss: 10.325572, ppl: 30502.746094
Total examples: 2851800, total time: 789.28266, 3613.15430 examples/sed
```
**同步训练参数和结果如下：**
```bash
Namespace(async_mode=False, batch_size=4096, iterations=100, local=False, opts=[], pass_num=1000, pool_size=10000, shuffle=True, shuffle_batch=True, sort_type='pool', special_token=['_GO', '_EOS', '_UNK'], src_vocab_fpath='./nist06n/cn_30001.dict', train_file_pattern='./nist06n/train_split/part-*', trg_vocab_fpath='./nist06n/en_30001.dict', use_token_batch=True, val_file_pattern='./nist06n/test/part-*')
```
trainer0 训练结果如下：
```bash
epoch: 0, batch: 100, sum loss: 313971.250000, avg loss: 10.253127, ppl: 28371.123047

Total examples: 2850244, total time: 159.39233, 17881.93945 examples/sed
```

**Comment by jacquesqiao** [comment] 2018-06-27 01:40
好的，我看一下

**Comment by jacquesqiao** [comment] 2018-06-27 01:42
正在和金华对这个问题

**Comment by shanyi15** [comment] 2018-08-15 11:00
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:00 UTC
