### ISSUE TITLE
English version of document is needed

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#7376] opened 2018-01-10 03:07 UTC
In the model page of English paddle [website](http://www.paddlepaddle.org/docs/develop/models/README.html), several links refers to documents written in Chinese.

Need to create documents in English for the following:
[Hsigmoid加速词向量训练](https://github.com/PaddlePaddle/models/tree/develop/hsigmoid)
[使用噪声对比估计加速语言模型训练](https://github.com/PaddlePaddle/models/tree/develop/nce_cost)
[使用循环神经网语言模型生成文本](https://github.com/PaddlePaddle/models/tree/develop/generate_sequence_by_rnn_lm)
[文本分类](https://github.com/PaddlePaddle/models/tree/develop/text_classification)
 For this one, the text that provides the link is `Sentiment analysis based on DNN / CNN
`, which should be fixed to `Text classification based on DNN / CNN`
[排序学习](https://github.com/PaddlePaddle/models/tree/develop/ltr)
[命名实体识别](https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner)
[图像分类](https://github.com/PaddlePaddle/models/blob/develop/image_classification/README.md)
[convert Caffe model file to PaddlePaddle model file](https://github.com/PaddlePaddle/models/blob/develop/image_classification/caffe2paddle/README.md)
[convert TensorFlow model file to PaddlePaddle model file](https://github.com/PaddlePaddle/models/blob/develop/image_classification/tf2paddle/README.md)

**Comment by shanyi15** [comment] 2018-08-15 11:39
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:39 UTC
