### ISSUE TITLE
How to apply the L2 regularization in Adam and Adamax.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#5901] opened 2017-11-24 09:55 UTC
- The current implementations of Adam and Adamax do not take weight decay rate into consideration (https://github.com/PaddlePaddle/Paddle/issues/5836). 
- PaddlePaddle uses a different way to implement the L2 regularization which potentially causes a problem in Adam and Adamax.
    - A related issue is: https://github.com/PaddlePaddle/Paddle/issues/5899

As a result, how to implement the L2 regularization for Adam and Adamax is not very clear (for me).

This PR https://github.com/PaddlePaddle/Paddle/pull/5900 adds the L2 weight decay by following the AdamW in the paper: [Fixing Weight Decay Regularization in Adam](https://arxiv.org/pdf/1711.05101.pdf)  (but still not exactly the same).

![image](https://user-images.githubusercontent.com/5842774/33205064-8ce020ae-d140-11e7-8890-2a3b076e74bb.png)

**Comment by shanyi15** [comment] 2018-08-15 11:12
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed** 2020-05-22 08:14 UTC
