### ISSUE TITLE
使用paddle2onnx转商品识别模型中检测模型ppyolov2_r50vd_dcn_mainbody_v1.0_infer为onnx，3个操作不支持！

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#34949] opened 2021-08-17 01:11 UTC
(paddle) D:\vison_software\paddle\Paddle2ONNX-develop>paddle2onnx --model_dir D:\vison_software\paddle\Paddle2ONNX-develop\models\ppyolov2_r50vd_dcn_mainbody_v1.0_infer\ --save_file onnx_models/resnet50_onnx/det_model.onnx --opset_version 11 --enable_onnx_checker True --model_filename inference.pdmodel --params_filename inference.pdiparams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\paddle\Scripts\paddle2onnx-script.py", line 33, in
sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 142, in main
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 114, in program2onnx
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 77, in program2onnx
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 32, in export_onnx
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 229, in build
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 75, in init
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 185, in update_opset_version
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\op_mapper\op_mapper.py", line 119, in get_recommend_opset_version
File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\op_mapper\op_mapper.py", line 160, in check_support_status
NotImplementedError:
There's 3 ops are not supported yet
=========== conditional_block ===========
=========== logical_not ===========
=========== select_input ===========

**Comment by jiangjiajun** [comment] 2021-08-18 07:52
Duplicate of https://github.com/PaddlePaddle/Paddle2ONNX/issues/303

此问题原因是导出模型时，将控制流导了出来，需要PaddleClas对齐PaddleDetection导出PPYOLOv2的方式

**Comment by littletomatodonkey** [comment] 2021-08-18 09:42
你好，主体检测模型已经更新，感谢反馈

**Closed as completed** 2022-08-26 08:54 UTC
Labels: status/close
