### ISSUE TITLE
Error "dictionary changed size during iteration" in ops.py

### ISSUE THREAD

**Issue by skylian** [PaddlePaddle/Paddle#12141] opened 2018-07-13 20:25 UTC
When using functions in [ops.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/ops.py), I got the error "dictionary changed size during iteration". The problem lies in the following code snippet, which appears in every function in `ops.py`.
```
kwargs = dict()
for name in locals():
    val = locals()[name]
    if val is not None:
        kwargs[name] = val
```
Inside the for loop, a new variable `val` is added into `locals()`, causing the error.

**Comment by jacquesqiao** [comment] 2018-07-14 00:58
Can you paste the code that will cause the error?

**Comment by skylian** [comment] 2018-07-14 06:25
@jacquesqiao  The error is not related to Fluid. Simply try this will get you the error.
```
def test():
    x = 1
    for v in locals():
        v = locals()[v]

test()
```

**Comment by skylian** [comment] 2018-07-18 20:21
@reyoung Can you help us here when you have time? Thanks!

**Comment by emailweixu** [comment] 2018-07-19 20:56
Changing to the following code should make it work. Though it not clear to me why we need the step of converting to kwargs.

```python
def _make_kwargs_(vars):
   kwargs = dict()
   for name in vars:
     val = vars.get(name)
     if val is not None:
        kwargs[name] = val
   return kwargs

def cumsum(x, axis=None, exclusive=None, reverse=None):
  return _cumsum_(**_make_kwargs_(locals()))
```

**Comment by JiayiFeng** [comment] 2018-08-23 08:15
能否简单地贴几个会触发ops.py里这个bug的调用Fluid的语句？我们验证一下。

**Comment by lucywsq** [comment] 2018-10-10 08:41
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-10 08:41 UTC

**Comment by VitoRazor** [comment] 2019-03-16 15:10
> Changing to the following code should make it work. Though it not clear to me why we need the step of converting to kwargs.
> 
> ```python
> def _make_kwargs_(vars):
>    kwargs = dict()
>    for name in vars:
>      val = vars.get(name)
>      if val is not None:
>         kwargs[name] = val
>    return kwargs
> 
> def cumsum(x, axis=None, exclusive=None, reverse=None):
>   return _cumsum_(**_make_kwargs_(locals()))
> ```

这个方法很好用，！感谢！！！
