### ISSUE TITLE
shape_inference.{h,cc} should use proto::VarDesc instead of its I/O helper

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11895] opened 2018-07-02 20:20 UTC
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/shape_inference.h#L28

**Comment by lucywsq** [comment] 2018-08-28 02:08
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed** 2018-08-28 02:09 UTC
