### ISSUE TITLE
如何写attention代码

### ISSUE THREAD

**Issue by lucywsq** [PaddlePaddle/Paddle#10793] opened 2018-05-21 04:48 UTC
示例中虽然有attention示例，但是
却不清楚，比如我的起始标签不为0该怎么写，比如解码代码：
targ_embedding = paddle.layer.embedding( 
input=paddle.layer.data( 
name='target_language_word', 
type=paddle.data_type.integer_value_sequence(target_dict_dim)), 
size=word_vector_dim, 
param_attr=paddle.attr.ParamAttr(name='_target_language_embedding')) 
group_inputs.append(trg_embedding)
 
这个targ_embedding怎么获取的？我如果初始化的起始标签不为0该怎么修改

**Comment by jacquesqiao** [comment] 2018-05-21 09:10
这个问题正在跟进哈，我需要看下代码

**Comment by pearlcurly** [comment] 2018-05-22 02:31
https://github.com/PaddlePaddle/book/tree/develop/08.machine_translation
这种是标签不为0的例子

**Comment by pearlcurly** [comment] 2018-05-22 10:37
具体描述下：

我是这么调用的

def infer_batch_probs(self, infer_data, feeding_dict):
"""Infer the prob matrices for a batch of speech utterances.

:param infer_data: List of utterances to infer, with each utterance
consisting of a tuple of audio features and
transcription text (empty string).
:type infer_data: list
:param feeding_dict: Feeding is a map of field name and tuple index
of the data that reader returns.
:type feeding_dict: dict|list
:return: List of 2-D probability matrix, and each consists of prob
vectors for one speech utterancce.
:rtype: List of matrix
"""
# define inferer
if self._inferer == None:
self._inferer = paddle.inference.Inference(
output_layer=self._loss, parameters=self._parameters)
adapted_feeding_dict = self._adapt_feeding_dict(feeding_dict)
adapted_infer_data = self._adapt_data(infer_data)
# run inference
infer_results = self._inferer.infer(
input=adapted_infer_data, feeding=adapted_feeding_dict)
pdb.set_trace()

其中self._loss就是下面的beam_result

decode_first = paddle.layer.first_seq(input=back_ward_gru)
decoder_boot = paddle.layer.mixed(
size=decoder_size,
act=paddle.activation.Tanh(),
input=paddle.layer.full_matrix_projection(decode_first))
def gru_decoder_with_attention(enc_vec, enc_proj, current_word):

decoder_mem = paddle.layer.memory(
name='gru_decoder', size=decoder_size, boot_layer=decoder_boot)

context = paddle.networks.simple_attention(
encoded_sequence=enc_vec,
encoded_proj=enc_proj,
decoder_state=decoder_mem)

#decoder_inputs = paddle.layer.fc(
# act=paddle.activation.Linear(),
# size=decoder_size * 3,
# bias_attr=False,
# input=[context, current_word],
# layer_attr=paddle.attr.ExtraLayerAttribute(
# error_clipping_threshold=100.0))
decoder_inputs = paddle.layer.mixed(
size=decoder_size * 3,
input=[
paddle.layer.full_matrix_projection(input=context),
paddle.layer.full_matrix_projection(input=current_word)
])

gru_step = paddle.layer.gru_step(
name='gru_decoder',
input=decoder_inputs,
output_mem=decoder_mem,
size=decoder_size)

out = paddle.layer.mixed(
size=dict_size,
bias_attr=True,
act=paddle.activation.Softmax(),
input=paddle.layer.full_matrix_projection(input=gru_step))
#out = paddle.layer.fc(
# size=dict_size,
# bias_attr=True,
# act=paddle.activation.Softmax(),
# input=gru_step)
return out

decoder_group_name = 'decoder_group'
group_input1 = paddle.layer.StaticInput(input=encoded_vector)
group_input2 = paddle.layer.StaticInput(input=encoded_proj)
group_inputs = [group_input1, group_input2]

trg_embedding = paddle.layer.GeneratedInput(
size=dict_size,
embedding_name='_target_language_embedding',
embedding_size=1024)
group_inputs.append(trg_embedding)

beam_gen = paddle.layer.beam_search(
name=decoder_group_name,
step=gru_decoder_with_attention,
input=group_inputs,
bos_id=0,
eos_id=1,
beam_size=5)
return beam_gen

**Comment by shanyi15** [comment] 2018-08-15 11:02
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:02 UTC
Labels: User
