### ISSUE TITLE
Book05 recommendation systems: GPU version loss convergence comparison.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#7168] opened 2018-01-03 09:36 UTC
Train avg_cost:

| Pass |  V2(GPU) | Fluid(GPU) |
|---------------  | ---------------  | ------------------- |
|0 | 4.226966 | 4.16706371 |
|1 | 3.779494 | 3.80107117 |
|2 | 3.467989 | 3.51753068 |
|3 | 3.296482 | 3.30209255 |
|4 | 3.226758 | 3.19562411 |

Test avg_cost:

| Pass |  V2(GPU) | Fluid(GPU) |
|---------------  | ---------------  | ------------------- |
|0 | 3.830757 | 3.843338 |
|1 | 3.587178 | 3.665707 |
|2 | 3.371065 | 3.390050 |
|3 | 3.323481 | 3.319620 |
|3 | 3.299066 | 3.293895 |

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
