### ISSUE TITLE
How to do joint optimization using PaddlePaddle

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2975] opened 2017-07-20 02:20 UTC
I am copying this question from Andrew to here:

---------

How do I optimize multiple cost functions jointly? Can I do `paddle.layer.classification_cost(...) + paddle.layer.classification_cost(...)` to optimize two classification costs?

**Comment by lcy-seso** [comment] 2017-07-20 02:42
Here is a GoogleNet example which defines 3 cost functions, you can take it as an example.
1.  just define multiple cost layers: https://github.com/PaddlePaddle/models/blob/develop/image_classification/train.py#L54
2.  provide all the defined cost to the `train` interface: https://github.com/PaddlePaddle/models/blob/develop/image_classification/train.py#L99

--- 
Some explanation:
* if the three defined costs are specified by the `cost` parameter of the `train` interface, in the log, the sum of the three loss will be printed.

    ```python
       trainer = paddle.trainer.SGD(
        cost=[loss1, loss2, loss3],
        parameters=parameters,
        update_equation=optimizer)
    ```

* `cost` and `extra_layers` are used to define the end of a network to induce the entire network topology, which usually are loss functions and evaluators.
* loss function specified by `cost` will be a print to the training log, while loss function specified by `extra_layers` will not be printed to the training log.

**Comment by shanyi15** [comment] 2018-08-15 11:13
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:14 UTC
