### ISSUE TITLE
Check failed: dimN + offset.aCol_ <= this->width_ (

### ISSUE THREAD

**Issue by zyz282994112** [PaddlePaddle/Paddle#10596] opened 2018-05-11 09:43 UTC
F0511 16:48:32.948879 21324 BaseMatrix.cu:97] Check failed: dimN + offset.aCol_ <= this->width_ (18446744071704817472 vs. 2290233152)
*** Check failure stack trace: ***
    @     0x7f776d7eb27d  google::LogMessage::Fail()
    @     0x7f776d7eed2c  google::LogMessage::SendToLog()
    @     0x7f776d7eada3  google::LogMessage::Flush()
    @     0x7f776d7f023e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f776d69c87a  paddle::BaseMatrixT<>::applyBinary<>()
    @     0x7f776d69cd80  paddle::BaseMatrixT<>::add()
    @     0x7f776de695a9  paddle::SgdThreadUpdater::threadUpdateDense()
    @     0x7f776de6aacf  _ZNSt17_Function_handlerIFvimEZN6paddle16SgdThreadUpdater11finishBatchEfEUlimE_E9_M_invokeERKSt9_Any_dataim
    @     0x7f776d74b0ec  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7f776c7a18a0  execute_native_thread_routine
    @     0x7f77738811c3  start_thread
    @     0x7f7772ea912d  __clone
    @              (nil)  (unknown)

网络第一层为词典的embedding，词典维度为3000w，embedding size=16时没问题，等于64时报错。
代码地址：http://10.87.106.14:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20180511152805-7158/workspace/conf/trainer_config.conf

**Comment by shanyi15** [comment] 2018-08-15 11:02
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:02 UTC
Labels: User
