### ISSUE TITLE
fluid.nets.simple_img_conv_pool error TypeError: set_attr(): incompatible function arguments. The following argument types are supported

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7851] opened 2018-01-25 07:57 UTC
Run below code error on develop branch, build using docker image: `paddlepaddle/paddle_manylinux_devel:cuda7.5_cudnn5`, with options: `WITH_GPU=OFF WITH_DISTRIBUTED=ON`

```python
conv_pool_1 = fluid.nets.simple_img_conv_pool(
    input=images,
    filter_size=5,
    num_filters=20,
    pool_size=2,
    pool_stride=2,
    act="relu")
```

```
Traceback (most recent call last):
  File "dist_test.py", line 29, in <module>
    act="relu")
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/nets.py", line 39, in simple_img_conv_pool
    use_cudnn=use_cudnn)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/layers/nn.py", line 1042, in conv2d
    default_initializer=_get_default_param_initializer())
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/layer_helper.py", line 129, in create_parameter
    dtype=dtype, shape=shape, **attr.to_kwargs(with_initializer=True))
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/framework.py", line 686, in create_parameter
    kwargs['initializer'](param, self)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/initializer.py", line 214, in __call__
    "seed": self._seed
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/framework.py", line 707, in prepend_op
    op = Operator(self, op_desc, *args, **kwargs)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/framework.py", line 475, in __init__
    self.desc.set_attr(attr_name, attrs[attr_name])
TypeError: set_attr(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.v2.fluid.core.OpDesc, arg0: unicode, arg1: boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<long, std::allocator<long> > >) -> None

Invoked with: <paddle.v2.fluid.core.OpDesc object at 0x7f3da9ff5990>, u'shape', (20L, 1L, 5L, 5L)
```

**Comment by typhoonzero** [comment] 2018-01-29 02:06
Need to find why. I suppose this issue may due to incompatible gcc or pybind versions.

**Comment by emailweixu** [comment] 2018-02-01 23:24
pybind itself does not handle boost variant. It might be because the variant_caster at paddle/pybind/protobuf.cc has some bug. A related issue #7369

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
