### ISSUE TITLE
paddle_gradient_machine_destroy core

### ISSUE THREAD

**Issue by yttbgf** [PaddlePaddle/Paddle#10845] opened 2018-05-22 12:59 UTC
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff13d22ff in paddle::ModelConfig::~ModelConfig() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#2  0x00007ffff10cd069 in paddle::NeuralNetwork::~NeuralNetwork() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#3  0x00007ffff10cd17f in paddle::MyNeuralNetwork::~MyNeuralNetwork() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#4  0x00007ffff12394b6 in paddle::RecurrentGradientMachine::~RecurrentGradientMachine() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#5  0x00007ffff12397d1 in paddle::RecurrentGradientMachine::~RecurrentGradientMachine() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#6  0x00007ffff1112f5c in paddle::RecurrentLayerGroup::~RecurrentLayerGroup() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#7  0x00007ffff10c9019 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#8  0x00007ffff10cd044 in paddle::NeuralNetwork::~NeuralNetwork() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#9  0x00007ffff10cd17f in paddle::MyNeuralNetwork::~MyNeuralNetwork() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#10 0x00007ffff10c9019 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#11 0x00007ffff10caecf in paddle_gradient_machine_destroy () from /home/gaofei09/fusion_houston/baidu/idg/houston/src/../../../../baidu/adu-3rd/paddle-capi/lib/libpaddle_capi_shared.so
#12 0x00007ffff794da7a in adu::planning::BaseModel::~BaseModel (this=0x7fffffffd5f0, __in_chrg=<optimized out>) at /home/gaofei09/fusion_houston/baidu/idg/houston/src/offline_decider/change_lane/occassion/model/paddle/base_model.cpp

**Comment by dzhwinter** [comment] 2018-07-16 05:21
It's model config error, is there any more config file information can be provided?
Thanks

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
Labels: User
