### ISSUE TITLE
`save_params()` and `load_params()` in `fluid.io` are unavailable

### ISSUE THREAD

**Issue by JiayiFeng** [PaddlePaddle/Paddle#7163] opened 2018-01-03 08:31 UTC
`save_params()` and `load_params()` are used to implement model saving and loading. The model is supposed to be able to continue its training after a saving and loading. However, using `save_params()` and `load_params()` cannot satisfy the needs.

The `save_params()` only save `Parameters`. But in the `Program` there are some other critical `Variable`s who are not `Parameter`, such as optimizers' learning rates and momentums.

The `load_params()` takes a serialized `ProgramDesc` protobuf object as its input, and load all `Parameters` in it. However, there is no such concept of `Parameter` in the protobuf. All `Parameter`s degrade to normal `Variable`s during flushing into protobuf. Therefore, nothing will be loaded by `load_params()`.

Using `save_persistables()` and `load_persistables_if_exist()` seems an avaiable but ungainly substitution.

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
