### ISSUE TITLE
split_selected_rows performance is low when running distributed training

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#10099] opened 2018-04-20 11:37 UTC
running model with 4x4 cluster training:

code:  https://github.com/typhoonzero/fluid_gpu_benchmark/blob/master/lm/gru_lm.py

```
thread0::send                    526         107833      91.0687     513.198     205.006
thread0::split_selected_rows     526         3969.97     3.52768     57.6451     7.54748
thread0::gru_grad                526         3709.28     3.15802     69.1087     7.05186
thread0::gru                     526         2579.74     2.13914     61.5332     4.90445
thread0::concat                  2630        631.228     0.058368    41.3972     0.240011
thread0::mul_grad                1052        601.758     0.096256    42.4724     0.572014
thread0::elementwise_add_grad    1052        534.124     0.078848    35.2727     0.507722
thread0::softmax                 526         421.595     0.52736     31.6549     0.801511
thread0::mul                     1052        373.266     0.104448    7.04512     0.354815
thread0::softmax_grad            526         366.07      0.387072    42.1274     0.69595
thread0::split                   2104        306.855     0.067584    7.73427     0.145844
thread0::elementwise_add         1052        255.04      0.064512    33.6497     0.242434
thread0::elementwise_div         526         200.593     0.109568    37.8532     0.381356
thread0::lookup_table            526         138.445     0.064512    43.3705     0.263203
thread0::lookup_table_grad       526         127.613     0.110592    6.56589     0.242609
thread0::fetch                   526         104.168     0.034592    34.9803     0.198039
thread0::elementwise_pow         526         100.448     0.078848    7.92678     0.190966
thread0::cross_entropy_grad      526         95.4362     0.09728     15.1224     0.181438
thread0::elementwise_mul         526         90.0792     0.074752    3.91066     0.171253
thread0::floor                   526         59.051      0.037856    19.8963     0.112264
thread0::mean                    526         49.7572     0.052224    2.98086     0.0945954
thread0::cross_entropy           526         43.4687     0.037888    2.88973     0.0826402
thread0::mean_grad               526         43.0501     0.034816    2.16986     0.0818443
thread0::feed                    1052        23.5154     0.009216    0.178176    0.0223531
thread0::increment               526         10.9506     0.012288    0.043008    0.0208186
thread0::cast                    526         10.4551     0.012288    0.078848    0.0198766
```

**Comment by shanyi15** [comment] 2018-08-15 10:28
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:28 UTC
