### ISSUE TITLE
API doc problems of linear_chain_crf, crf_decoding

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#9062] opened 2018-03-14 08:35 UTC
#### 单词拼写、遗漏和语法等问题未列出，修改时请注意
*请参考[API注释标准](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md)！*
------
源文件：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py

- linear_chain_crf
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#linear-chain-crf
  - 无注释

- crf_decoding
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#crf-decoding
  - 无注释

**Comment by shanyi15** [comment] 2018-08-15 11:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:07 UTC
Labels: PythonAPI, 文档
