### ISSUE TITLE
why is so difficult to converge using paddle to train coco obj detection?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#12402] opened 2018-07-27 03:38 UTC

**Comment by lucywsq** [comment] 2018-10-18 08:13
Excuse me ,could you please describe more details of  your problem, by some screenshots or something else?

**Comment by lucywsq** [comment] 2018-10-26 04:04
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 04:04 UTC
