### ISSUE TITLE
fluid版本的很多参数没有做类型兼容处理

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#8797] opened 2018-03-06 10:09 UTC
我在使用paddle的fluid版本的例子时，发现存在的一个问题就是没有做类型的兼容性处理，比如说我定义一个全连接层，里面使用了NormalInitializer，scale设为1，如下所示。
fc1 = fluid.layers.fc(input=drop, size=4096, act=None, bias_attr=fluid.ParamAttr(initializer=NormalInitializer(loc=0.0, scale=1, seed=0)))
以修改Paddle/python/paddle/fluid/tests/book/test_image_classification.py 的89行为例，结果会出现：
```
Traceback (most recent call last):
  File "test_image_classification.py", line 252, in test_vgg_cpu
    main('vgg', use_cuda=False)
  File "test_image_classification.py", line 237, in main
    train(net_type, use_cuda, save_dirname, is_local)
  File "test_image_classification.py", line 105, in train
    net = vgg16_bn_drop(images)
  File "test_image_classification.py", line 89, in vgg16_bn_drop
    fc1 = fluid.layers.fc(input=drop, size=4096, act=None, bias_attr=fluid.ParamAttr(initializer=NormalInitializer(loc=0.0, scale=1, seed=0)))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 193, in fc
    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 385, in append_bias_op
    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 312, in create_parameter
    dtype=dtype, shape=shape, **attr.to_kwargs(with_initializer=True))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 810, in create_parameter
    kwargs['initializer'](param, self)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/initializer.py", line 239, in __call__
    "seed": self._seed
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 834, in prepend_op
    op = Operator(self, op_desc, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 484, in __init__
    self.desc.check_attrs()
EnforceNotMet: Cannot get attribute std by type f, its type is i at [/paddle/Paddle/paddle/fluid/framework/attribute.h:131]
```
而我如果将scale=1改成scale=1.0的话，这个问题就解决了。
类似的还有
fluid.optimizer.Momentum(momentum=0, learning_rate=1e-3）
会报类似的错误，将momentum改成0.0就不会报错。
这是一个比较明显的没有做类型兼容处理的问题。

**Comment by lcy-seso** [comment] 2018-03-12 03:20
Got this problem.  @guoshengCS Please help to fix this ASAP. Thank you for the help.

**Comment by lcy-seso** [comment] 2018-03-12 04:35
It is also highly appreciated if you can contribute a PR to fix this problem.

**Comment by cheradam** [comment] 2018-03-28 01:13
At the issue-triage meeting，marked this issue as low priority。

**Comment by shanyi15** [comment] 2018-08-15 11:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:07 UTC
Labels: enhancement
