### ISSUE TITLE
try "date -d @1524668094" if you are using GNU date

### ISSUE THREAD

**Issue by hawk199** [PaddlePaddle/Paddle#10207] opened 2018-04-25 15:02 UTC
# error message:

```
I0425 14:54:49.188958   132 Util.cpp:166] commandline:  --use_gpu=False
W0425 14:54:49.188998   132 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available o
n your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
I0425 14:54:49.329326   132 GradientMachine.cpp:94] Initing parameters..
I0425 14:54:49.384299   132 GradientMachine.cpp:101] Init parameters done.

Pass 0, Batch 0, Cost 32.000000, {'classification_error_evaluator': 0.5}
...........................................................Thread [139999181010688] Forwarding __lstmemory_0__,
*** Aborted at 1524668094 (unix time) try "date -d @1524668094" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f53ff91d6de) received by PID 132 (TID 0x7f541973f700) from PID 18446744073702332126; stack trace: ***
    @     0x7f5419316390 (unknown)
    @     0x7f53ff91d6de paddle::LstmCompute::backwardOneSequence<>()
    @     0x7f53ff91d96d paddle::LstmCompute::backwardBatch<>()
    @     0x7f53ff88c16e paddle::LstmLayer::backwardBatch()
    @     0x7f53ff88c7ce paddle::LstmLayer::backward()
    @     0x7f53ff879081 paddle::NeuralNetwork::backward()
    @     0x7f53ffb5b999 GradientMachine::forwardBackward()
    @     0x7f53ff7fb2ac _wrap_GradientMachine_forwardBackward
    @           0x4c30ce PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4eb30f (unknown)
    @           0x4e5422 PyRun_FileExFlags
    @           0x4e3cd6 PyRun_SimpleFileExFlags
    @           0x493ae2 Py_Main
    @     0x7f5418f5b830 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Floating point exception 
```
# my code
```
# -*- coding: utf-8 -*-

import os,sys
import json
import numpy as np
import paddle.v2 as paddle

with_gpu = os.getenv('WITH_GPU', '0') != '0'


def load_train_data():
    filename="/work/footballOdds.json"
    data=load_data(filename)
    
    size=len(data)
    def reader():
        for i in range(size):
            lvalue=0
            if data[i][2]>data[i][3]:
                lvalue=0
            elif data[i][2]==data[i][3]:
                lvalue=1
            else:
                lvalue=2
            
            yield data[i][4],lvalue
    return reader

def load_test_data():
    filename="/work/footballOddsTest.json"
    data=load_data(filename)
    size=len(data)
    def reader():
        for i in range(size):
            lvalue=0
            if data[i][2]>data[i][3]:
                lvalue=0
            elif data[i][2]==data[i][3]:
                lvalue=1
            else:
                lvalue=2
            
            yield data[i][4],lvalue
    return reader
def row_to_array_forodds(row):
    return [row['hometeam'],
            row['guestteam'],
            row['homescore'],
            row['guestscore'],
            row['odds_data']]



def load_data(filename):
    fo = open(filename, "r")
    data=[]
    for line in fo:
        item=json.loads(line)
        data.append(row_to_array_forodds(item))
    return data

def convolution_net(input_dim, class_dim=2, emb_dim=128, hid_dim=128):
    data = paddle.layer.data("word",
                             paddle.data_type.dense_vector_sequence(input_dim))
    #emb = paddle.layer.embedding(input=data, size=emb_dim)
    conv_3 = paddle.networks.sequence_conv_pool(
        input=data, context_len=3, hidden_size=hid_dim)
    conv_4 = paddle.networks.sequence_conv_pool(
        input=data, context_len=4, hidden_size=hid_dim)
    output = paddle.layer.fc(
        input=[conv_3, conv_4], size=class_dim, act=paddle.activation.Softmax())
    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))
    cost = paddle.layer.classification_cost(input=output, label=lbl)
    return cost, output


def stacked_lstm_net(input_dim,
                     class_dim=2,
                     emb_dim=128,
                     hid_dim=512,
                     stacked_num=3):
    """
    A Wrapper for sentiment classification task.
    This network uses bi-directional recurrent network,
    consisting three LSTM layers. This configure is referred to
    the paper as following url, but use fewer layrs.
        http://www.aclweb.org/anthology/P15-1109

    input_dim: here is word dictionary dimension.
    class_dim: number of categories.
    emb_dim: dimension of word embedding.
    hid_dim: dimension of hidden layer.
    stacked_num: number of stacked lstm-hidden layer.
    """
    assert stacked_num % 2 == 1

    fc_para_attr = paddle.attr.Param(learning_rate=1e-3)
    lstm_para_attr = paddle.attr.Param(initial_std=0., learning_rate=1.)
    para_attr = [fc_para_attr, lstm_para_attr]
    bias_attr = paddle.attr.Param(initial_std=0., l2_rate=0.)
    relu = paddle.activation.Relu()
    linear = paddle.activation.Linear()

    data = paddle.layer.data("word",
                             paddle.data_type.dense_vector_sequence(input_dim))
    #emb = paddle.layer.embedding(input=data, size=emb_dim)

    fc1 = paddle.layer.fc(
        input=data, size=hid_dim, act=linear, bias_attr=bias_attr)
    lstm1 = paddle.layer.lstmemory(input=fc1, act=relu, bias_attr=bias_attr)

    inputs = [fc1, lstm1]
    for i in range(2, stacked_num + 1):
        fc = paddle.layer.fc(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=para_attr,
            bias_attr=bias_attr)
        lstm = paddle.layer.lstmemory(
            input=fc, reverse=(i % 2) == 0, act=relu, bias_attr=bias_attr)
        inputs = [fc, lstm]

    fc_last = paddle.layer.pooling(
        input=inputs[0], pooling_type=paddle.pooling.Max())
    lstm_last = paddle.layer.pooling(
        input=inputs[1], pooling_type=paddle.pooling.Max())
    output = paddle.layer.fc(
        input=[fc_last, lstm_last],
        size=class_dim,
        act=paddle.activation.Softmax(),
        bias_attr=bias_attr,
        param_attr=para_attr)

    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))
    cost = paddle.layer.classification_cost(input=output, label=lbl)
    return cost, output


if __name__ == '__main__':
    # init
    paddle.init(use_gpu=with_gpu)

    #data
    #print 'load dictionary...'
    #word_dict = paddle.dataset.imdb.word_dict()

    #print word_dict
    dict_dim = 4
    class_dim = 3
    train_reader = paddle.batch(
        paddle.reader.shuffle(
            load_train_data(), buf_size=500),
        batch_size=4)
    test_reader = paddle.batch(load_test_data(), batch_size=4)

    feeding = {'word': 0, 'label': 1}
    lists = []
    # network config
    # Please choose the way to build the network
    # by uncommenting the corresponding line.
    #[cost, output] = convolution_net(dict_dim, class_dim=class_dim)
    [cost, output] = stacked_lstm_net(dict_dim, class_dim=class_dim, stacked_num=3)

    # create parameters
    parameters = paddle.parameters.create(cost)

    # create optimizer
    adam_optimizer = paddle.optimizer.Adam(
        learning_rate=2e-3,
        regularization=paddle.optimizer.L2Regularization(rate=8e-4),
        model_average=paddle.optimizer.ModelAverage(average_window=0.5))

    # create trainer
    trainer = paddle.trainer.SGD(
        cost=cost, parameters=parameters, update_equation=adam_optimizer)

    # End batch and end pass event handler
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                print "\nPass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)
            else:
                sys.stdout.write('.')
                sys.stdout.flush()
        if isinstance(event, paddle.event.EndPass):
            with open('./params_pass_%d.tar' % event.pass_id, 'w') as f:
                trainer.save_parameter_to_tar(f)

            result = trainer.test(reader=test_reader, feeding=feeding)
            print "\nTest with Pass %d, %s" % (event.pass_id, result.metrics)
            lists.append((event.pass_id, result.cost,
                          result.metrics['classification_error_evaluator']))

    # Save the inference topology to protobuf.
    inference_topology = paddle.topology.Topology(layers=output)
    with open("./inference_topology.pkl", 'wb') as f:
        inference_topology.serialize_for_inference(f)

    trainer.train(
        reader=train_reader,
        event_handler=event_handler,
        feeding=feeding,
        num_passes=20)

     # find the best pass
    best = sorted(lists, key=lambda list: float(list[1]))[0]
    print('Best pass is %s, testing Avgcost is %s' % (best[0], best[1]))
    print ('The classification accuracy is %.2f%%' % (100 - float(best[2]) * 100))

```

# my data
`
[[2.58, 3.25, 2.9, 2.0], [2.53, 3.25, 2.95, 27.0], [2.51, 3.25, 3.0, 47.0], [2.49, 3.25, 3.0, 55.0], [2.47, 3.3, 3.0, 120.0], [2.42, 3.3, 3.05, 152.0], [2.44, 3.3, 3.05, 212.0], [2.47, 3.3, 3.0, 243.0], [2.44, 3.3, 3.1, 283.0], [2.44, 3.2, 3.1, 910.0], [2.44, 3.15, 3.1, 1058.0], [2.42, 3.15, 3.15, 1289.0], [2.42, 3.05, 2.75, 1857.0], [2.39, 3.05, 2.8, 5735.0], [2.39, 3.2, 2.7, 6625.0], [2.35, 3.2, 2.75, 6626.0], [2.39, 3.2, 2.7, 6627.0]]`

I Run PaddlePaddle in Docker.
If anyone has any ideas, I would be very grateful!

**Comment by wowuhuaihuai** [comment] 2018-06-08 06:11
That's what happened to me

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
