### ISSUE TITLE
Paddle v1 data reader 数据时间穿越问题

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#7483] opened 2018-01-12 08:42 UTC
使用的是paddle v1，翻看[文档](http://doc.paddlepaddle.org/release_doc/0.9.0/doc_cn/ui/data_provider/pydataprovider2.html#id5)
提到，
`PaddlePaddle将train.list中的每一行，都传递给process函数，从而生成多个generator`。
这个意味着paddle会先将满足train_data_path里的M个文件写到train_list，然后在运行N个结点mpi程序时，每个结点会下载M/N个part。然后每个结点上会同时运行M/N个data_reader。

我现在的需求是，为了避免训练数据的时候时间上出现穿越，想要时间在前的数据先处理，这个有办法实现么？

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
