### ISSUE TITLE
Rename mixed_vector.h into vector.h

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11780] opened 2018-06-27 16:32 UTC
This file https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/mixed_vector.h was named `mixed_vector.h`; however, the class defined in there has name `Vector`.

Should we rename `mixed_vector.h` into `vector.h`?

**Comment by wangkuiyi** [comment] 2018-06-27 16:34
It seems that there is no file in paddle/fluid who has the name vector.h. This means it is safe to rename mixed_vector.h into vector.h.

```
yi@WangYis-iMac:~/work/paddle/paddle/fluid (develop)$ du -a | grep -i vector
24	./framework/mixed_vector.h
8	./framework/mixed_vector_test.cu
```

**Comment by wangkuiyi** [comment] 2018-06-27 17:56
I made a quick fix to this problem, but in the tape repo, which supports times faster CI and supports @tonyyang-svail and @kexinzhao 's work. Anyone feel free to cherrypick my fix from https://github.com/wangkuiyi/tape/pull/14

**Comment by shanyi15** [comment] 2018-08-15 10:20
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:20 UTC
