### ISSUE TITLE
Should enhance FillZerosLikeOp to support array

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7823] opened 2018-01-24 09:16 UTC
trace stack:

> paddle.v2.fluid.core.EnforceNotMet: Variable dynamic_rnn_mem_array_0 type_id St6vectorIN6paddle9framework9LoDTensorESaIS2_EE, expect LoDTensor/SelectedRows. at [/home/work/yangyaming/softwares/Paddle/paddle/framework/operator.cc:435]
> PaddlePaddle Call Stacks:
> 0       0x7f53fac68806p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
> 1       0x7f53fb53b890p paddle::framework::RuntimeInferShapeContext::GetDim(std::string const&) const + 256
> 2       0x7f53fb53b35dp paddle::framework::RuntimeInferShapeContext::GetInputDim(std::string const&) const + 61
> 3       0x7f53fafc1c61p paddle::operators::FillZerosLikeOp::InferShape(paddle::framework::InferShapeContext*) const + 225
> 4       0x7f53fb5383fep paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 94
> 5       0x7f53fad014b3p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1251
> 6       0x7f53fb247b8bp paddle::operators::WhileGradOp::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 5003
> 7       0x7f53fad014b3p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1251
> 8       0x7f53fac7d74cp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 524
> 9       0x7f53fac781cap pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2602
> 10      0x7f54380303d4p PyEval_EvalFrameEx + 25956
> 11      0x7f5438031120p PyEval_EvalCodeEx + 2240
> 12      0x7f543802f491p PyEval_EvalFrameEx + 22049
> 13      0x7f5438031120p PyEval_EvalCodeEx + 2240
> 14      0x7f5438031232p PyEval_EvalCode + 50
> 15      0x7f543804b61cp
> 16      0x7f543804b6f0p PyRun_FileExFlags + 144
> 17      0x7f543804cbfcp PyRun_SimpleFileExFlags + 220
> 18      0x7f543805e4bcp Py_Main + 3164
> 19        0x318ae1ecddp __libc_start_main + 253
> 20            0x400659p

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
