### ISSUE TITLE
Faster RCNN latency raised after blocking "unknown option"

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#38921] opened 2022-01-13 07:52 UTC
After this commit: https://github.com/PaddlePaddle/Paddle/commit/adb54eb0bb8b44e8a29c1eabadaf7933e44beff8 the big one latency rising of inference of faster RCNN COCO was observed.

It seems that despite the fact that it is unknown, it was an important option that conditioned the quick operation of the faster_RCNN model. Perhaps this is true of other models that have used these flags.

It was observed on three different processors: CLX, SKX and CPX. Below presented results for CLX
![image](https://user-images.githubusercontent.com/10847947/149286521-a29571a2-b721-416a-9e94-8f2675ba79b7.png)
### CPU 
```
                Turbo: OFF
                 Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
                Model: 85
               Family: 6
              Sockets: 2
     Cores per socket: 20
     Threads per core: 2
```
### Run command:
``
python /root/models/PaddleDetection/deploy/python/infer.py --model_dir=/data/PaddlePaddle/models/faster_rcnn_r50_fpn_1x_coco --image_file=/root/models/PaddleDetection/demo/000000570688.jpg --device=CPU --enable_mkldnn=True --run_benchmark=True  --batch_size=1
``
### CMAKE Flags:
``
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DPY_VERSION=3.6
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8
```

For the attention of: @jczaja @tsocha

**Comment by betterpig** [comment] 2022-01-13 09:10
Hello, I'm sorry that Faster RCNN's performance turned to worse. According to the picture, the problem seems to be caused by my commit. But theoretically speaking, my modification only change windows platform's variable definition and has nothing to do with linux platform such as Unbuntu. 

Could you please check carefully if Faster RCNN's performance is affected by my commit, just discard my modification in Paddle/cmake/configure.cmake and test again to see whether the perfomance become good as before. If so, I am gladly to make a change to suit the modle's requirement.

Looking forward your reply.

**Comment by pmajchrzak** [comment] 2022-01-13 10:29
@tsocha : Could you pls check this?

**Comment by tsocha** [comment] 2022-01-13 11:07
> Hello, I'm sorry that Faster RCNN's performance turned to worse. According to the picture, the problem seems to be caused by my commit. But theoretically speaking, my modification only change windows platform's variable definition and has nothing to do with linux platform such as Unbuntu.
> 
> Could you please check carefully if Faster RCNN's performance is affected by my commit, just discard my modification in Paddle/cmake/configure.cmake and test again to see whether the perfomance become good as before. If so, I am gladly to make a change to suit the modle's requirement.
> 
> Looking forward your reply.

I think it could be related to your change because:
![image](https://user-images.githubusercontent.com/24435886/149318679-e02590d4-e4ab-4482-af09-544b8af77744.png)
I drew lines to show scope of ifs.
As you can see before your change both `-DPADDLE_WITH_AVX` and `-DPADDLE_WITH_SSE3` were set.
Now we set only `-DPADDLE_WITH_AVX` if AVX is detected.

**Comment by betterpig** [comment] 2022-01-13 11:15
> 



> > Hello, I'm sorry that Faster RCNN's performance turned to worse. According to the picture, the problem seems to be caused by my commit. But theoretically speaking, my modification only change windows platform's variable definition and has nothing to do with linux platform such as Unbuntu.
> > Could you please check carefully if Faster RCNN's performance is affected by my commit, just discard my modification in Paddle/cmake/configure.cmake and test again to see whether the perfomance become good as before. If so, I am gladly to make a change to suit the modle's requirement.
> > Looking forward your reply.
> 
> I think it could be related to your change because: ![image](https://user-images.githubusercontent.com/24435886/149318679-e02590d4-e4ab-4482-af09-544b8af77744.png) I drew lines to show scope of ifs. As you can see before your change both `-DPADDLE_WITH_AVX` and `-DPADDLE_WITH_SSE3` were set. Now we set only `-DPADDLE_WITH_AVX` if AVX is detected.

I see. It indeed will cause `-DPADDLE_WITH_SSE3` not set whhen WITH_AVX AND AVX_FOUND. I will make a fix soon.

**Comment by betterpig** [comment] 2022-01-14 03:33
[fix](https://github.com/PaddlePaddle/Paddle/pull/38931) has been merged, the problem should be solved. Please make a check.

**Comment by baoachun** [comment] 2022-01-20 07:38
Hi @pmajchrzak , chould you please verify that the issue is resolved? Thanks

**Comment by pmajchrzak** [comment] 2022-01-20 07:44
Yes :)
Now is going so fast, we can feel the wind in the hair. Thank you!
![image](https://user-images.githubusercontent.com/10847947/150294860-68871670-c126-4885-9170-94cca0a3856c.png)

**Closed as completed** 2022-02-14 12:18 UTC
Labels: Intel
