### ISSUE TITLE
同样的代码和数据，cpu模式正常训练，gpu模式之前正常，后来开始报Floating point exception

### ISSUE THREAD

**Issue by wchange** [PaddlePaddle/Paddle#8862] opened 2018-03-08 03:25 UTC
如题，cpu训练正常，且前几天进行过多次gpu模式的完整训练，均正常，昨天重启过一次docker之后开始稳定报fpe，中途没有改过代码和数据，之后再重启依然稳定报fpe

docker环境：latest-gpu          d9907b579cb9        10 weeks ago        2.661 GB
paddle version:
> PaddlePaddle 0.11.0, compiled with
>     with_avx: ON
>     with_gpu: ON
>     with_mkl: ON
>     with_mkldnn: ON
>     with_double: OFF
>     with_python: ON
>     with_rdma: OFF
>     with_timer: OFF

> I0308 03:00:08.624646   193 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
> I0308 03:00:10.451324   193 GradientMachine.cpp:94] Initing parameters..
> I0308 03:00:21.148797   193 GradientMachine.cpp:101] Init parameters done.
> *** Aborted at 1520478088 (unix time) try "date -d @1520478088" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGFPE (@0x7f90c7c5ec7e) received by PID 193 (TID 0x7f90e31aa700) from PID 18446744072766221438; stack trace: ***
>     @     0x7f90e2d84390 (unknown)
>     @     0x7f90c7c5ec7e paddle::AucEvaluator::evalImp()
>     @     0x7f90c7c5e6c6 paddle::Evaluator::eval()
>     @     0x7f90c7c32e48 paddle::CombinedEvaluator::eval()
>     @     0x7f90c7aa4866 _wrap_GradientMachine_eval
>     @           0x4cb755 PyEval_EvalFrameEx
>     @           0x4c2705 PyEval_EvalCodeEx
>     @           0x4ca7df PyEval_EvalFrameEx
>     @           0x4c2705 PyEval_EvalCodeEx
>     @           0x4ca088 PyEval_EvalFrameEx
>     @           0x4c2705 PyEval_EvalCodeEx
>     @           0x4ca7df PyEval_EvalFrameEx
>     @           0x4c2705 PyEval_EvalCodeEx
>     @           0x4c24a9 PyEval_EvalCode
>     @           0x4f19ef (unknown)
>     @           0x4ec372 PyRun_FileExFlags
>     @           0x4eaaf1 PyRun_SimpleFileExFlags
>     @           0x49e208 Py_Main
>     @     0x7f90e29c9830 __libc_start_main
>     @           0x49da59 _start
>     @                0x0 (unknown)
> Floating point exception

**Comment by dzhwinter** [comment] 2018-03-14 07:43
和重启docker没关系。把报错时候的最大最小值print出来看看？

**Comment by dzhwinter** [comment] 2018-03-14 07:44
另外，可能和GPU的ECC开关有关系？ 先排除代码上的问题

**Comment by wchange** [comment] 2018-03-14 07:47
> 把报错时候的最大最小值print出来看看？

最大最小值指的是？

**Comment by shanyi15** [comment] 2018-08-15 11:37
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:37 UTC
Labels: User
