### ISSUE TITLE
The prediction accuracy of the pcpvt_base model after mkldnn is turned on is different from that of pure CPU, and the difference is greater than 0.01.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#35574] opened 2021-09-08 06:42 UTC
Commit id：0be7157185138a5e92732225f56737d34fc532f8

PR: https://github.com/PaddlePaddle/Paddle/pull/34192

![图片](https://user-images.githubusercontent.com/22114318/132459158-ef51798a-f5eb-44c4-b51e-e1b0cdc09a9e.png)

**Comment by lidanqing-vv** [comment] 2021-09-08 14:37
@baoachun  Where is this screen shot from? With this we could not reproduce. Could you please provide command? And Is this issue must be fixed for Paddle 2.2

@jczaja  Please help watch this issue. Thanks

**Comment by baoachun** [comment] 2021-09-09 12:56
@lidanqing-intel @jczaja 
Hi, there is the test code,  https://github.com/PaddlePaddle/PaddleTest/blob/develop/inference/python_api_test/test_class_model/test_pcpvt_base.py#L64.

`python3.8 -m pytest --disable-warnings -v test_pcpvt_base.py::test_mkldnn`

**Comment by lidanqing-vv** [comment] 2021-09-09 14:09
@jczaja  This is not urgent for 2.2RC

**Comment by lidanqing-vv** [comment] 2021-09-15 12:24
@baoachun @jakpiase Baoachun updated this issue caused other 4 issues. So I revert your PR first. If you make fix PR before 17th September, please @baoachun to let him test his 5 cards first and then merge the fix PR. Thanks.
Update: This issue need to be fixed for v2.2

**Comment by lidanqing-vv** [comment] 2021-09-15 12:51
@jakpiase  Hi, I can not revert for you, because there are too many file conflicts and I m not sure if I could remove or not. Please revert it or fix it before 17th September (which is like night 16th September Poland). Keep updating under this issue. Thanks.

**Comment by baoachun** [comment] 2021-09-15 13:00
First step:
`git clone https://github.com/PaddlePaddle/PaddleClas.git`
`git checkout develop`

Second step:
Download models and images from here: https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/en/tutorials/quick_start_recognition_en.md
<img width="1091" alt="图片" src="https://user-images.githubusercontent.com/22114318/133437785-dcc1a958-8cbc-4ec9-9f50-4ce9e86c0f86.png">

~~Problem 1:
`cd PaddleClas/deploy; python python/predict_system.py -c configs/inference_product.yaml -o Global.infer_imgs=./recognition_demo_data_v1.1/test_product/daoxiangcunjinzhubing_6.jpg -o Global.use_gpu=False -o Global.use_tensorrt=False -o Global.use_fp16=False -o Global.enable_mkldnn=True`~~

~~Problem 2:
`cd PaddleClas/deploy; python python/predict_system.py -c configs/inference_vehicle.yaml -o Global.infer_imgs=./recognition_demo_data_v1.1/test_vehicle/audia4-102.jpeg -o Global.use_gpu=False -o Global.use_tensorrt=False -o Global.use_fp16=False -o Global.enable_mkldnn=True`~~

~~Problem 3:
`cd PaddleClas/deploy; python python/predict_system.py -c configs/inference_logo.yaml -o Global.infer_imgs=./recognition_demo_data_v1.1/test_logo/benz-001.jpeg -o Global.use_gpu=False -o Global.use_tensorrt=False -o Global.use_fp16=False -o Global.enable_mkldnn=True`~~

Problem 4:
`cd PaddleClas/deploy; python python/predict_cls.py -c configs/inference_cls.yaml -o Global.inference_model_dir=../inference/ShuffleNetV2 -o batch_size=1 -o Global.use_gpu=False -o Global.use_tensorrt=False -o Global.enable_mkldnn=True`

~~Problem 5:
`cd PaddleClas/deploy; python python/predict_system.py -c configs/inference_cartoon.yaml -o Global.infer_imgs=./recognition_demo_data_v1.1/test_cartoon/aisidesi-001.jpeg -o Global.use_gpu=False -o Global.use_tensorrt=False -o Global.use_fp16=False -o Global.enable_mkldnn=True`~~

**Comment by baoachun** [comment] 2021-09-16 06:20
#35794
The same question.

**Comment by jakpiase** [comment] 2021-09-16 12:37
@baoachun I couldn't find a way how to download "..inference/ShuffleNetV2" model, but I have found 

> https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/whole_chain/ShuffleNetV2_x1_0_inference.tar

And I have ran this model. It gives same result with and without oneDNN enabled. If I have tested wrong model could you please tell me how to download the correct one?
And pcpvt_base model will be fixed by: #35781(disabling reshape and squeeze ops)

**Comment by baoachun** [comment] 2021-09-16 13:14
@jakpiase 
Hi, the model that you used is correct, and the prediction result is wrong compare with CPU.
![图片](https://user-images.githubusercontent.com/22114318/133618624-6d512c54-8d92-4c53-8d30-3b026070088e.png)

**Comment by jakpiase** [comment] 2021-09-16 13:23
Hi, @baoachun, sorry for my mistake, you are right. These results are incorrect now, but I have checked and they will be fixed after #35781 is merged

**Closed as completed** 2021-09-17 11:05 UTC
Labels: Intel
