### ISSUE TITLE
多机训练 1个psserver，4个trainer，训练中psserver挂掉

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#11200] opened 2018-06-05 10:04 UTC
训练模型：resnet50；
d at 1528192764 (unix time) try "date -d @1528192764" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x42c) received by PID 7980 (TID 0x7fad3e1fc700) from PID 1068; stack trace: ***
    @     0x7fb057252390 (unknown)
    @     0x7fb05724ad44 __GI___pthread_mutex_lock
    @     0x7fb002f69c25 paddle::operators::detail::RequestGet::Process()
    @     0x7fb002f63032 paddle::operators::detail::AsyncGRPCServer::HandleRequest()
    @     0x7fb002f6847e std::thread::_Impl<>::_M_run()
    @     0x7fb04f896c80 (unknown)
    @     0x7fb0572486ba start_thread
    @     0x7fb056f7e41d clone
    @                0x0 (unknown)
Segmentation fault

**Comment by panyx0718** [comment] 2018-06-05 10:11
```
DEFINE_int32(rpc_server_handle_send_threads, 20,
             "Number of threads used to handle send at rpc server.");
DEFINE_int32(rpc_server_handle_get_threads, 20,
             "Number of threads used to handle get at rpc server.");
DEFINE_int32(rpc_server_handle_prefetch_threads, 1,
             "Number of threads used to handle prefetch at rpc server.");
```

change to threads=1?

**Comment by panyx0718** [comment] 2018-06-05 10:11
grpc_server.cc

**Comment by panyx0718** [comment] 2018-06-06 05:15
貌似两次出问题的地方不太一样

**Comment by typhoonzero** [comment] 2018-06-14 03:44
@ccmeteorljh 这个还可以稳定复现么，如果复现不了可否暂时先关闭？

**Comment by Yancey1989** [comment] 2018-06-14 04:19
> 在43个pass，第5个batch再次出现该问题

这看起来是GRPC超时引起的，具体的报错信息可能在PServer上，PS上还有其他日志吗？

另外在贴日志的时候可以用
\```bash
\```

格式化下，看起来会方便一些。

**Comment by shanyi15** [comment] 2018-08-15 11:01
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:01 UTC
