### ISSUE TITLE
有些op只能在单元测试里找到，且没有对应文档或者说明。可否加个？

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#11219] opened 2018-06-06 03:51 UTC
https://github.com/PaddlePaddle/Paddle/blob/efc094f564092646a2f70998342b3f2c4991a2a4/python/paddle/fluid/tests/unittests/test_while_op.py

**Comment by dzhwinter** [comment] 2018-06-07 01:45
这些op是自动注册的，所以需要生成脚本支持。这块的l文档会在7.5之前做完。

**Comment by shanyi15** [comment] 2018-08-15 11:01
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:01 UTC
Labels: User
