### ISSUE TITLE
The crf_layer can not be used when 'use_gpu=True'.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#6521] opened 2017-12-12 08:57 UTC
Currently, an error will occur when using crf_layer with 'use_gpu=True'.
```
F1212 16:54:29.049428 11811 CRFLayer.cpp:57] Check failed: !useGpu_ GPU is not supported
*** Check failure stack trace: ***
    @     0x7f299ef8117d  google::LogMessage::Fail()
    @     0x7f299ef84c2c  google::LogMessage::SendToLog()
    @     0x7f299ef80ca3  google::LogMessage::Flush()
    @     0x7f299ef8613e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f299ec51591  paddle::CRFLayer::forward()
    @     0x7f299eb6d01d  paddle::NeuralNetwork::forward()
    @     0x7f299eb67a13  paddle::GradientMachine::forwardBackward()
    @     0x7f299ef5d0e4  GradientMachine::forwardBackward()
    @     0x7f299eb2a7b9  _wrap_GradientMachine_forwardBackward
    @     0x7f29d7de73a3  PyEval_EvalFrameEx
    @     0x7f29d7de9130  PyEval_EvalCodeEx
    @     0x7f29d7de74a1  PyEval_EvalFrameEx
    @     0x7f29d7de9130  PyEval_EvalCodeEx
    @     0x7f29d7de74a1  PyEval_EvalFrameEx
    @     0x7f29d7de9130  PyEval_EvalCodeEx
    @     0x7f29d7de74a1  PyEval_EvalFrameEx
    @     0x7f29d7de9130  PyEval_EvalCodeEx
    @     0x7f29d7de74a1  PyEval_EvalFrameEx
    @     0x7f29d7de9130  PyEval_EvalCodeEx
    @     0x7f29d7de9242  PyEval_EvalCode
    @     0x7f29d7e0362c  run_mod
    @     0x7f29d7e03700  PyRun_FileExFlags
    @     0x7f29d7e04c0c  PyRun_SimpleFileExFlags
    @     0x7f29d7e164cc  Py_Main
    @       0x318ae1ecdd  (unknown)
Thread [139817691055872] Forwarding __crf_layer_0__,
```

**Comment by shanyi15** [comment] 2018-08-15 11:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:11 UTC
