### ISSUE TITLE
Install paddlepaddle fail

### ISSUE THREAD

**Issue by drfia** [PaddlePaddle/Paddle#11776] opened 2018-06-27 12:47 UTC
execute  `pip install paddlepaddle`
then 
> Collecting paddlepaddle
>   Could not find a version that satisfies the requirement paddlepaddle (from versions: )
> No matching distribution found for paddlepaddle

[('cp27', 'cp27m', 'macosx_10_12_x86_64'), ('cp27', 'cp27m', 'macosx_10_12_intel'), ('cp27', 'cp27m', 'macosx_10_12_fat64'), ('cp27', 'cp27m', 'macosx_10_12_fat32'), ('cp27', 'cp27m', 'macosx_10_12_universal'), ('cp27', 'cp27m', 'macosx_10_11_x86_64'), ('cp27', 'cp27m', 'macosx_10_11_intel'), ('cp27', 'cp27m', 'macosx_10_11_fat64'), ('cp27', 'cp27m', 'macosx_10_11_fat32'), ('cp27', 'cp27m', 'macosx_10_11_universal'), ('cp27', 'cp27m', 'macosx_10_10_x86_64'), ('cp27', 'cp27m', 'macosx_10_10_intel'), ('cp27', 'cp27m', 'macosx_10_10_fat64'), ('cp27', 'cp27m', 'macosx_10_10_fat32'), ('cp27', 'cp27m', 'macosx_10_10_universal'), ('cp27', 'cp27m', 'macosx_10_9_x86_64'), ('cp27', 'cp27m', 'macosx_10_9_intel'), ('cp27', 'cp27m', 'macosx_10_9_fat64'), ('cp27', 'cp27m', 'macosx_10_9_fat32'), ('cp27', 'cp27m', 'macosx_10_9_universal'), ('cp27', 'cp27m', 'macosx_10_8_x86_64'), ('cp27', 'cp27m', 'macosx_10_8_intel'), ('cp27', 'cp27m', 'macosx_10_8_fat64'), ('cp27', 'cp27m', 'macosx_10_8_fat32'), ('cp27', 'cp27m', 'macosx_10_8_universal'), ('cp27', 'cp27m', 'macosx_10_7_x86_64'), ('cp27', 'cp27m', 'macosx_10_7_intel'), ('cp27', 'cp27m', 'macosx_10_7_fat64'), ('cp27', 'cp27m', 'macosx_10_7_fat32'), ('cp27', 'cp27m', 'macosx_10_7_universal'), ('cp27', 'cp27m', 'macosx_10_6_x86_64'), ('cp27', 'cp27m', 'macosx_10_6_intel'), ('cp27', 'cp27m', 'macosx_10_6_fat64'), ('cp27', 'cp27m', 'macosx_10_6_fat32'), ('cp27', 'cp27m', 'macosx_10_6_universal'), ('cp27', 'cp27m', 'macosx_10_5_x86_64'), ('cp27', 'cp27m', 'macosx_10_5_intel'), ('cp27', 'cp27m', 'macosx_10_5_fat64'), ('cp27', 'cp27m', 'macosx_10_5_fat32'), ('cp27', 'cp27m', 'macosx_10_5_universal'), ('cp27', 'cp27m', 'macosx_10_4_intel'), ('cp27', 'cp27m', 'macosx_10_4_fat32'), ('cp27', 'cp27m', 'macosx_10_4_universal'), ('cp27', 'cp27m', 'macosx_10_3_fat32'), ('cp27', 'cp27m', 'macosx_10_3_universal'), ('cp27', 'cp27m', 'macosx_10_2_fat32'), ('cp27', 'cp27m', 'macosx_10_2_universal'), ('cp27', 'cp27m', 'macosx_10_1_fat32'), ('cp27', 'cp27m', 'macosx_10_1_universal'), ('cp27', 'cp27m', 'macosx_10_0_fat32'), ('cp27', 'cp27m', 'macosx_10_0_universal'), ('cp27', 'none', 'macosx_10_12_x86_64'), ('cp27', 'none', 'macosx_10_12_intel'), ('cp27', 'none', 'macosx_10_12_fat64'), ('cp27', 'none', 'macosx_10_12_fat32'), ('cp27', 'none', 'macosx_10_12_universal'), ('cp27', 'none', 'macosx_10_11_x86_64'), ('cp27', 'none', 'macosx_10_11_intel'), ('cp27', 'none', 'macosx_10_11_fat64'), ('cp27', 'none', 'macosx_10_11_fat32'), ('cp27', 'none', 'macosx_10_11_universal'), ('cp27', 'none', 'macosx_10_10_x86_64'), ('cp27', 'none', 'macosx_10_10_intel'), ('cp27', 'none', 'macosx_10_10_fat64'), ('cp27', 'none', 'macosx_10_10_fat32'), ('cp27', 'none', 'macosx_10_10_universal'), ('cp27', 'none', 'macosx_10_9_x86_64'), ('cp27', 'none', 'macosx_10_9_intel'), ('cp27', 'none', 'macosx_10_9_fat64'), ('cp27', 'none', 'macosx_10_9_fat32'), ('cp27', 'none', 'macosx_10_9_universal'), ('cp27', 'none', 'macosx_10_8_x86_64'), ('cp27', 'none', 'macosx_10_8_intel'), ('cp27', 'none', 'macosx_10_8_fat64'), ('cp27', 'none', 'macosx_10_8_fat32'), ('cp27', 'none', 'macosx_10_8_universal'), ('cp27', 'none', 'macosx_10_7_x86_64'), ('cp27', 'none', 'macosx_10_7_intel'), ('cp27', 'none', 'macosx_10_7_fat64'), ('cp27', 'none', 'macosx_10_7_fat32'), ('cp27', 'none', 'macosx_10_7_universal'), ('cp27', 'none', 'macosx_10_6_x86_64'), ('cp27', 'none', 'macosx_10_6_intel'), ('cp27', 'none', 'macosx_10_6_fat64'), ('cp27', 'none', 'macosx_10_6_fat32'), ('cp27', 'none', 'macosx_10_6_universal'), ('cp27', 'none', 'macosx_10_5_x86_64'), ('cp27', 'none', 'macosx_10_5_intel'), ('cp27', 'none', 'macosx_10_5_fat64'), ('cp27', 'none', 'macosx_10_5_fat32'), ('cp27', 'none', 'macosx_10_5_universal'), ('cp27', 'none', 'macosx_10_4_intel'), ('cp27', 'none', 'macosx_10_4_fat32'), ('cp27', 'none', 'macosx_10_4_universal'), ('cp27', 'none', 'macosx_10_3_fat32'), ('cp27', 'none', 'macosx_10_3_universal'), ('cp27', 'none', 'macosx_10_2_fat32'), ('cp27', 'none', 'macosx_10_2_universal'), ('cp27', 'none', 'macosx_10_1_fat32'), ('cp27', 'none', 'macosx_10_1_universal'), ('cp27', 'none', 'macosx_10_0_fat32'), ('cp27', 'none', 'macosx_10_0_universal'), ('py2', 'none', 'macosx_10_12_x86_64'), ('py2', 'none', 'macosx_10_12_intel'), ('py2', 'none', 'macosx_10_12_fat64'), ('py2', 'none', 'macosx_10_12_fat32'), ('py2', 'none', 'macosx_10_12_universal'), ('py2', 'none', 'macosx_10_11_x86_64'), ('py2', 'none', 'macosx_10_11_intel'), ('py2', 'none', 'macosx_10_11_fat64'), ('py2', 'none', 'macosx_10_11_fat32'), ('py2', 'none', 'macosx_10_11_universal'), ('py2', 'none', 'macosx_10_10_x86_64'), ('py2', 'none', 'macosx_10_10_intel'), ('py2', 'none', 'macosx_10_10_fat64'), ('py2', 'none', 'macosx_10_10_fat32'), ('py2', 'none', 'macosx_10_10_universal'), ('py2', 'none', 'macosx_10_9_x86_64'), ('py2', 'none', 'macosx_10_9_intel'), ('py2', 'none', 'macosx_10_9_fat64'), ('py2', 'none', 'macosx_10_9_fat32'), ('py2', 'none', 'macosx_10_9_universal'), ('py2', 'none', 'macosx_10_8_x86_64'), ('py2', 'none', 'macosx_10_8_intel'), ('py2', 'none', 'macosx_10_8_fat64'), ('py2', 'none', 'macosx_10_8_fat32'), ('py2', 'none', 'macosx_10_8_universal'), ('py2', 'none', 'macosx_10_7_x86_64'), ('py2', 'none', 'macosx_10_7_intel'), ('py2', 'none', 'macosx_10_7_fat64'), ('py2', 'none', 'macosx_10_7_fat32'), ('py2', 'none', 'macosx_10_7_universal'), ('py2', 'none', 'macosx_10_6_x86_64'), ('py2', 'none', 'macosx_10_6_intel'), ('py2', 'none', 'macosx_10_6_fat64'), ('py2', 'none', 'macosx_10_6_fat32'), ('py2', 'none', 'macosx_10_6_universal'), ('py2', 'none', 'macosx_10_5_x86_64'), ('py2', 'none', 'macosx_10_5_intel'), ('py2', 'none', 'macosx_10_5_fat64'), ('py2', 'none', 'macosx_10_5_fat32'), ('py2', 'none', 'macosx_10_5_universal'), ('py2', 'none', 'macosx_10_4_intel'), ('py2', 'none', 'macosx_10_4_fat32'), ('py2', 'none', 'macosx_10_4_universal'), ('py2', 'none', 'macosx_10_3_fat32'), ('py2', 'none', 'macosx_10_3_universal'), ('py2', 'none', 'macosx_10_2_fat32'), ('py2', 'none', 'macosx_10_2_universal'), ('py2', 'none', 'macosx_10_1_fat32'), ('py2', 'none', 'macosx_10_1_universal'), ('py2', 'none', 'macosx_10_0_fat32'), ('py2', 'none', 'macosx_10_0_universal'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]

**Comment by Yancey0623** [comment] 2018-06-27 14:14
I saw there is wheel package named paddlepaddle-0.11.0-cp27-cp27m-macosx_10_12_x86_64.whl  on [pypi](https://pypi.org/project/paddlepaddle/0.11.0/#files), maybe you can try to download and install it on your laptop.

**Comment by drfia** [comment] 2018-06-28 07:33
> paddlepaddle-0.11.0-cp27-cp27m-macosx_10_12_x86_64.whl is not a supported wheel on this platform.

Hello,I've tried ,but it dosen't work

**Comment by shanyi15** [comment] 2018-08-15 10:20
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:20 UTC
Labels: User
