### ISSUE TITLE
We Should Have The Alternative BN Implementation by Our Own

### ISSUE THREAD

**Issue by kaiyuyue** [PaddlePaddle/Paddle#14580] opened 2018-11-26 03:33 UTC
Hi there,

This issue is tracked by the project [Simple Baselines for Human Pose Estimation in Fluid](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/human_pose_estimation).

If BN function of cuDNN is used during training in the task of Human Pose Estimation, a known issue that training can't converge will be encountered on the Tesla P40 / P100 / V100 GPU cards , both in PyTorch and PaddlePaddle. 

PyTorch has its own BN implementation to solve this problem, revise the `torch.backends.cudnn.enabled` into `False` to disable the cuDNN BN usage in their [code](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L1458).

PaddlePaddle doesn't allow us to make this change. Luckily, training 1 image on each GPU card can ease this probelm. So, I think we should have the alternative BN implementation by our own.

Related issues in PyTorch: [Issue-0](https://github.com/Microsoft/human-pose-estimation.pytorch/issues/8) | [Issue-1](https://github.com/Microsoft/human-pose-estimation.pytorch/issues/45)

**Comment by lucywsq** [comment] 2018-12-20 13:10
Thanks for your suggestion : )
Since this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it.We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-12-20 13:10 UTC
