### ISSUE TITLE
Do we need public method Flush() for BlockDescBind and OpDescBind?

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6543] opened 2017-12-12 22:34 UTC
Flush() will be call automatically when calling Proto(), why do we still need it as a public method? For simplicity I think we need to change Flush() to private or just remove it (put into Proto()).

Currently they two are only called in these two places publicly:
```
./framework/program_desc.cc:31:    block->Flush();
./framework/block_desc.cc:104:    op_desc->Flush();
```

**Comment by helinwang** [comment] 2017-12-12 22:35
@reyoung @jacquesqiao @QiJune @tonyyang-svail how do you guys think?

**Comment by shanyi15** [comment] 2018-08-15 11:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:11 UTC
