### ISSUE TITLE
Matrix.cpp:3285] Check failed: lbl[i] >= 0 (-1 vs. 0) 

### ISSUE THREAD

**Issue by PengheLiu** [PaddlePaddle/Paddle#10751] opened 2018-05-17 12:44 UTC
报错信息：
Thu May 17 20:12:27 2018[1,2]<stderr>:F0517 20:12:27.950521  6210 Matrix.cpp:3285] Check failed: lbl[i] >= 0 (-1 vs. 0) 
Thu May 17 20:12:27 2018[1,2]<stderr>:*** Check failure stack trace: ***
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd982c827d  google::LogMessage::Fail()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd982cbd2c  google::LogMessage::SendToLog()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd982c7da3  google::LogMessage::Flush()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd982cd23e  google::LogMessageFatal::~LogMessageFatal()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd981fc875  paddle::CpuMatrix::oneHotCrossEntropy()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd9806a3b5  paddle::CostLayer::forward()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd98088562  paddle::NeuralNetwork::forward()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd9807c4c3  paddle::GradientMachine::forwardBackward()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd982a41c4  GradientMachine::forwardBackward()
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcd97f511d9  _wrap_GradientMachine_forwardBackward
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b4cb9  PyEval_EvalFrameEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4b6c52  PyEval_EvalCode
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4e1c7d  PyRun_FileExFlags
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4e3501  PyRun_SimpleFileExFlags
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x4159dd  Py_Main
Thu May 17 20:12:27 2018[1,2]<stderr>:    @     0x7fcdbd74bbd5  __libc_start_main
Thu May 17 20:12:27 2018[1,2]<stderr>:    @           0x414b71  (unknown)
Thu May 17 20:12:27 2018[1,2]<stderr>:    @              (nil)  (unknown)
Thu May 17 20:12:28 2018[1,2]<stderr>:./train.sh: line 239:  6210 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf

模型train代码如下：
```
import sys
import math
import os

import numpy
import paddle.v2 as paddle
import gzip


cluster_train_dir = "./train_data_dir/20180514"
cluster_test_dir = "./test_data_dir/20180514"
node_id = int(os.getenv("OMPI_COMM_WORLD_RANK"))

word_dict_file = "thirdparty/third_party/word_dict.txt"

with_gpu = os.getenv('WITH_GPU', '0') != '0'

embsize = 32
hiddensize = 256
N = 5

# self define the data reader
def cluster_data_reader(file_dir, word_dict, n):
    def reader_creator():
        files = os.listdir(file_dir)
        for fi in files:
            with open(file_dir + "/" + fi, "r") as f:
                UNK = word_dict['<unk>']
                for line in f:
                    line = ['<s>'] + line.strip().split('\t') + ['<e>']
                    if len(line) >= n:
                        line = [word_dict.get(w, UNK) for w in line]
                        for i in range(n, len(line) + 1):
                            yield tuple(line[i - n : i])
    return reader_creator


def wordemb(inlayer):
    wordemb = paddle.layer.table_projection(
        input=inlayer,
        size=embsize,
        param_attr=paddle.attr.Param(
            name="_proj", initial_std=0.001, learning_rate=1, l2_rate=0))
    return wordemb


# save and load word dict and embedding table
def save_dict_and_embedding(word_dict, embeddings):
    with open("word_dict", "w") as f:
        for key in word_dict:
            f.write(key + " " + str(word_dict[key]) + "\n")
    with open("embedding_table", "w") as f:
        numpy.savetxt(f, embeddings, delimiter=',', newline='\n')

def load_word_dict():
    word_dict = dict()
    with open(word_dict_file, "r") as f:
        for line in f:
            key, value = line.strip().split("\t")
            word_dict[key] = int(value)
    return word_dict

def load_dict_and_embedding():
    word_dict = dict()
    with open("word_dict", "r") as f:
        for line in f:
            key, value = line.strip().split(" ")
            word_dict[key] = int(value)

    embeddings = numpy.loadtxt("embedding_table", delimiter=",")
    return word_dict, embeddings


def main():
    paddle.init(use_gpu=False, 
            trainer_count=int(os.getenv("PADDLE_TRAINER_COUNT", "1")),
            port=int(os.getenv("PADDLE_PORT", "7164")),
            ports_num=int(os.getenv("PADDLE_PORTS_NUM", "1")),
            num_gradient_servers=int(os.getenv("PADDLE_NUM_GRADIENT_SERVERS", "1")),
            trainer_id=int(os.getenv("PADDLE_TRAINER_ID", "0")),
            pservers=os.getenv("PADDLE_PSERVERS", "127.0.0.1"))
    #paddle.init(use_gpu=False, trainer_count=3)
    #word_dict = paddle.dataset.imikolov.build_dict()
    word_dict = load_word_dict()
    dict_size = len(word_dict)
    # Every layer takes integer value of range [0, dict_size)
    firstword = paddle.layer.data(
        name="firstw", type=paddle.data_type.integer_value(dict_size))
    secondword = paddle.layer.data(
        name="secondw", type=paddle.data_type.integer_value(dict_size))
    thirdword = paddle.layer.data(
        name="thirdw", type=paddle.data_type.integer_value(dict_size))
    fourthword = paddle.layer.data(
        name="fourthw", type=paddle.data_type.integer_value(dict_size))
    nextword = paddle.layer.data(
        name="fifthw", type=paddle.data_type.integer_value(dict_size))

    Efirst = wordemb(firstword)
    Esecond = wordemb(secondword)
    Ethird = wordemb(thirdword)
    Efourth = wordemb(fourthword)

    contextemb = paddle.layer.concat(input=[Efirst, Esecond, Ethird, Efourth])
    hidden1 = paddle.layer.fc(
        input=contextemb,
        size=hiddensize,
        act=paddle.activation.Sigmoid(),
        layer_attr=paddle.attr.Extra(drop_rate=0.5),
        bias_attr=paddle.attr.Param(learning_rate=2),
        param_attr=paddle.attr.Param(
            initial_std=1. / math.sqrt(embsize * 8), learning_rate=1))
    predictword = paddle.layer.fc(
        input=hidden1,
        size=dict_size,
        bias_attr=paddle.attr.Param(learning_rate=2),
        act=paddle.activation.Softmax())

    cost = paddle.layer.classification_cost(input=predictword, label=nextword)
    parameters = paddle.parameters.create(cost)
    adagrad = paddle.optimizer.AdaGrad(
        learning_rate=3e-3,
        regularization=paddle.optimizer.L2Regularization(8e-4))
    trainer = paddle.trainer.SGD(cost, parameters, adagrad)

    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                print "Pass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)

        if isinstance(event, paddle.event.EndPass):
#            result = trainer.test(
#                paddle.batch(paddle.dataset.imikolov.test(word_dict, N), 32))
#            print "Pass %d, Testing metrics %s" % (event.pass_id,
#                                                   result.metrics)
            if not os.path.exists("model_params"):
                os.makedirs("model_params")
            with gzip.open("model_params/word2vec_params" + str(event.pass_id) + ".tar.gz", 'w') as f:
                parameters.to_tar(f)

    trainer.train(
        paddle.batch(cluster_data_reader(cluster_train_dir, word_dict, N), 32),
        num_passes=100,
        event_handler=event_handler)

    # save word dict and embedding table
    embeddings = parameters.get("_proj").reshape(len(word_dict), embsize)
    save_dict_and_embedding(word_dict, embeddings)


if __name__ == '__main__':
    main()
```

**Comment by guoshengCS** [comment] 2018-05-17 12:52
看报错这里`Check failed: lbl[i] >= 0 (-1 vs. 0)`应该是传入的label数据不太正确，出现了-1

**Comment by shanyi15** [comment] 2018-08-15 11:02
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:02 UTC
Labels: User
