### ISSUE TITLE
Fluid Faster RCNN implementation

### ISSUE THREAD

**Issue by Noplz** [PaddlePaddle/Paddle#10462] opened 2018-05-07 15:11 UTC
### According to [Detectron](https://github.com/facebookresearch/Detectron) the ops need to be implemented for Faster RCNN:
Detectron  |  Paddle Fluid
-----------|----------
[add_rpn_blobs](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/rpn.py#L62:5)|  [generate_anchors_op](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/roi_data/data_utils.py#L50:5) <br> iou_similarity_op <br> [fg_bg_target_assign_op](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/roi_data/rpn.py#L195:5) <br> argmax_op <br> box_coder_op
[generate_proposals](https://github.com/facebookresearch/Detectron/blob/master/detectron/ops/generate_proposals.py) | box_coder_op <br> [clip_and_filter_op](https://github.com/facebookresearch/Detectron/blob/0375b05e867eae12be0ca8c420c9efad687689bf/detectron/ops/generate_proposals.py#L152:31) <br> multiclass_nms_op <br>
[generate_proposal_labels](https://github.com/facebookresearch/Detectron/blob/master/detectron/ops/generate_proposal_labels.py) | [add_proposals_op](https://github.com/facebookresearch/Detectron/blob/0375b05e867eae12be0ca8c420c9efad687689bf/detectron/datasets/json_dataset.py#L328:5) <br> [add_gt_proposals_op](https://github.com/facebookresearch/Detectron/blob/a60aa096175d7c1811e0a25d26578cc24489399d/detectron/datasets/roidb.py#L68:5)<br> [target_assign_op](https://github.com/facebookresearch/Detectron/blob/0375b05e867eae12be0ca8c420c9efad687689bf/detectron/datasets/json_dataset.py#L328:5)

### Faster RCNN on Fluid

- **generate_anchors_op**: generate anchors on the fly corresponding to configs
    - Input:
    - Attr:
    - Output: anchor boxes with shape [H, W, M, 4]. H * W * M is total number of anchor box<br>
- **fg_bg_target_assign_op**:
    - Input:
        Input(1): the anchor boxes with shape [M, 4]
        Input(2): the gt boxes with shape [N, 4]
    - Attr:
    - Output: anchor to gt matched mask with shape [M, 1]<br>
- **box_coder_op**:
    - Input: Same
    - Attr:
        Attr(1): add normalize(bool)
    - Output: Same <br>
- **clip_and_fliter_op**: clip and filter proposals corresponding to input image
    - Input: 
        Input(1): decoded anchors with shape [M, 4]
    - Attr:
        Attr(1): image width and height
    - Output: 
        Output(1):cliped and filted proposals with shape [K, 1]<br>
- **add_gt_proposals_op**:
    - Input:
        Input(1): the proposals with shape [M, 4]
        Input(2): the gt boxes with shape [N, 4]
    - Attr:
    - Output: the proposals with shape [M+N, 4] <br> 
- **add_proposals_op**:
    - Input:
    - Attr:
    - Output:<br>
- **target_assign_op**:
    - Input:
    - Attr:
    - Output:<br>

**Comment by xialeiliu** [comment] 2018-07-10 16:11
Is it available now?

**Comment by kuke** [comment] 2018-07-11 07:31
@xialeiliu  Faster-RCNN is still in active development, and will be released after the performance is verified.

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
