### ISSUE TITLE
C-API build failed on cuda8+cudnn7

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#8078] opened 2018-02-02 06:01 UTC
https://paddleci.ngrok.io/viewLog.html?buildId=26932&buildTypeId=Manylinux1_Cuda8cudnn7cp27cp27mu&tab=buildLog

```bash
[19:06:03]	In file included from /paddle/paddle/cuda/include/hl_gpu.h:29:0,
[19:06:03]	from /paddle/paddle/utils/Util.h:34,
[19:06:03]	from /paddle/paddle/utils/ThreadLocal.h:25,
[19:06:03]	from /paddle/paddle/math/Matrix.h:22,
[19:06:03]	from /paddle/paddle/gserver/dataproviders/DataProvider.h:28,
[19:06:03]	from /paddle/paddle/gserver/gradientmachines/GradientMachine.h:22,
[19:06:03]	from /paddle/paddle/capi/capi_private.h:16,
[19:06:03]	from /paddle/paddle/capi/Arguments.cpp:16:
[19:06:03]	/paddle/paddle/cuda/include/hl_warpctc_wrap.h:18:17: fatal error: ctc.h: No such file or directory
[19:06:03]	#include "ctc.h"
[19:06:03]	^
[19:06:03]	compilation terminated.
```

**Comment by Xreki** [comment] 2018-02-02 08:23
```
[19:06:03]	from /paddle/paddle/capi/Arguments.cpp:16:
[19:06:03]	/paddle/paddle/cuda/include/hl_warpctc_wrap.h:18:17: fatal error: ctc.h: No such file or directory
[19:06:03]	#include "ctc.h"
[19:06:03]	^
[19:06:03]	compilation terminated.
[19:06:03]	In file included from /paddle/paddle/cuda/include/hl_gpu.h:29:0,
.
.
.
[19:06:04]	[ 85%] Linking CXX executable test_cpu
[19:06:04]	[ 85%] Built target test_cpu
[19:06:04]	[ 84%] Built target benchdnn
[19:06:04]	make[2]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/gradient_machine.cpp.o] Error 1
[19:06:04]	make[2]: *** Waiting for unfinished jobs....
[19:06:04]	make[2]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/Arguments.cpp.o] Error 1
[19:06:04]	make[2]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/Main.cpp.o] Error 1
[19:06:04]	make[2]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/Matrix.cpp.o] Error 1
[19:06:04]	make[2]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/Vector.cpp.o] Error 1
[19:06:04]	make[1]: *** [paddle/capi/CMakeFiles/paddle_capi.dir/all] Error 2
[19:06:04]	make[1]: *** Waiting for unfinished jobs....
.
.
.
[19:06:16]	Scanning dependencies of target test_gpu
[19:06:16]	[100%] Linking CXX executable test_gpu
[19:06:16]	[100%] Built target test_gpu
[19:06:16]	[ 12%] Performing install step for 'extern_warpctc'
[19:06:16]	-- cuda found TRUE
[19:06:16]	-- Torch found
[19:06:16]	-- Building shared library with GPU support
[19:06:16]	-- Configuring done
[19:06:16]	-- Generating done
[19:06:16]	-- Build files have been written to: /paddle/build/third_party/warpctc/src/extern_warpctc-build
[19:06:16]	[ 14%] Linking CXX shared library libwarpctc.so
[19:06:16]	[ 42%] Built target warpctc
[19:06:16]	[ 57%] Linking CXX executable test_cpu
[19:06:16]	[ 71%] Linking CXX executable test_gpu
[19:06:16]	[ 85%] Built target test_cpu
[19:06:16]	[100%] Built target test_gpu
[19:06:16]	Install the project...
[19:06:16]	-- Install configuration: "Release"
[19:06:16]	-- Installing: /paddle/build/third_party/install/warpctc/lib/libwarpctc.so
[19:06:16]	-- Installing: /paddle/build/third_party/install/warpctc/include/ctc.h
[19:06:16]	[ 12%] Completed 'extern_warpctc'
[19:06:16]	[ 12%] Built target extern_warpctc
[19:06:16]	make: *** [all] Error 2
[19:06:17]	Process exited with code 2
[19:06:17]	Process exited with code 2
[19:06:17]	Step C_API (Command Line) failed
```

像是依赖出了问题，`warp-ctc`里面还没下载、安装完，就编译使用`warp-ctc`的代码了。

**Comment by luotao1** [comment] 2018-02-02 08:26
和 #8076 出现的问题一样，`make clean`后，teamcity也报同样的错误。https://paddleci.ngrok.io/viewLog.html?buildId=27047&buildTypeId=Paddle_PrCi&tab=buildLog

**Comment by shanyi15** [comment] 2018-08-15 11:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:08 UTC
