### ISSUE TITLE
Make NCCLContextMap a Var in ParallelExecutor so it can be shared

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#10270] opened 2018-04-27 12:24 UTC
We find it hard to avoid user to create ParallelExecutor in a loop like this:

```python
def test(pe):
  test_pe = ParallelExecutor(share_from=pe)
  test_pe.run()

pe = ParallelExector()
for i  in range():
  pe.run()
  if i % 100 == 0:
    test(pe)
 ```

In the example above, NCCLContextMap will be created again and again, and
we suspect it triggers the crash here:
https://github.com/PaddlePaddle/Paddle/issues/10252

If we make NCCLContextMap a global var and shared among ParallelExecutor
we can save some creation time and potentially avoid the above crash

**Comment by chengduoZH** [comment] 2018-04-27 13:03
I agreed with @panyx0718. In fact, the device context of `train_exe` and `test_exe` is shared.

**Comment by shanyi15** [comment] 2018-08-15 10:27
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:27 UTC
