### ISSUE TITLE
Support CUDA 10 

### ISSUE THREAD

**Issue by cjld** [PaddlePaddle/Paddle#14514] opened 2018-11-20 13:48 UTC
Currently, the paddle is compiled by cuda9. It causes RTX series ran slowly(40% slower).
We have to support CUDA 10 for Mining the performance of RTX series.

**Comment by SoonNOON** [comment] 2018-11-21 02:09
I hope we see full support for CUDA 10 very soon.

**Comment by lucywsq** [comment] 2018-12-20 13:05
Thanks for your suggestion. We would trace it. 
Since this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it.We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-12-20 13:05 UTC

**Comment by yeyupiaoling** [comment] 2019-01-04 09:16
@cjld When you use CUDA_9.0, can you use CUDNN?
