### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by mical892524** [PaddlePaddle/Paddle#7362] opened 2018-01-09 12:31 UTC
test case:
root@975ab92920f6:/work/quiptel# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from paddle.v2.plot import Ploter
>>> title1 = "title1"
>>> title2 = "title2"
>>> plot_test = Ploter(title1, title2)
>>> plot_test.append(title1, 1, 2)
>>> plot_test.append(title1, 2, 5)
>>> plot_test.append(title2, 3, 4)
>>> plot_test.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/plot/plot.py", line 69, in plot
    self.plt.plot(data.step, data.value)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3250, in plot
    ax = gca()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 962, in gca
    return gcf().gca(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 592, in gcf
    return figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

when I set DISPLAY to Agg:  export DISPLAY=Agg
call  plot_test.plot() again, it happen:
_tkinter.TclError: couldn't connect to display "Agg"

**Comment by shanyi15** [comment] 2018-08-15 11:39
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:39 UTC
