### ISSUE TITLE
MKLDNN is slower than native CPU

### ISSUE THREAD

**Issue by yeliang2258** [PaddlePaddle/Paddle#48109] opened 2022-11-17 13:11 UTC
### 问题描述 Please describe your issue

In my model, the speed of MKLDNN is slower than that of native CPU. After profile, it is found that it is caused by the following three operators: split, concat and sub. Please help me to optimize.

Profile results of MKLDNN
![image](https://user-images.githubusercontent.com/30516196/202454056-3eef51ca-e6aa-4844-9076-7308f94d136f.png)

Profile results of Native CPU
![image](https://user-images.githubusercontent.com/30516196/202454135-ba9b8e2e-d104-4895-97bf-af36d2e22fc3.png)

My model and test script:
[model.zip](https://github.com/PaddlePaddle/Paddle/files/10031799/model.zip)

**Comment by jakpiase** [comment] 2022-11-21 18:35
Hi @yeliang2258. I have tried to reproduce the performance of this model, but when I am running your test file, the following error occurs: 
![image](https://user-images.githubusercontent.com/62569058/203132950-2ca3bc94-b525-4f45-a65d-9029befab0dd.png)
In the .`zip` file that you have send us there is only `model.pdmodel` and `test.cpp`. What about a `model.pdparams` file? Isn't it missing?

**Comment by yeliang2258** [comment] 2022-11-22 02:30
Hi @jakpiase  Sorry, the weight parameters of this model cannot be provided. I remember that it can be optimized by only providing the model structure before ?

**Comment by yeliang2258** [comment] 2022-11-22 16:47
Hi @jakpiase params file:
[model.pdiparams.zip](https://github.com/PaddlePaddle/Paddle/files/10069390/model.pdiparams.zip)

**Comment by jakpiase** [comment] 2022-11-27 21:32
Hi @yeliang2258. I have reproduced the performance of oneDNN in this model, but unfortunately we can't do much with that because the operations that are in this model are too small to make oneDNN efficient. OneDNN is designed for medium/large tensor operations while in this model there are a lot of 1x1(scalar) tensor operations. In these scenarios the overhead of creating oneDNN objects is taking significantly more time than the execution of the operation, so native operators will always be faster than oneDNN's equivalents.

The one thing that can be done to speed this model up on the native side by ~9-10% is fusing `scale` op with `log` op into `log1p` op, since scale is used just as `x` -> `x+1` operation and `log1p` equation is described as `log(x+1)`. Please let me know if you are interested in that idea or if you have any other questions

**Comment by yaomichael** [comment] 2023-03-15 02:24
@yeliang2258 @onecatcn can you close this issue?

**Closed as completed** 2023-03-15 05:39 UTC
Labels: Intel, type/others, status/close
