### ISSUE TITLE
Why not use lookup table in SelectedRows?

### ISSUE THREAD

**Issue by yingfeng** [PaddlePaddle/Paddle#12311] opened 2018-07-23 11:22 UTC
I notice that the implementation of SelectedRows is a kind of Key-Value map actually as follows:

`
Vector<int64_t> rows_;
`
`
std::unique_ptr<Tensor> value_{nullptr};
`

together with corresponding typical map operations:

`
std::vector<std::pair<int64_t, int64_t>> Get(const std::vector<int64_t>& keys,ramework::Tensor* value) const;
`
`
bool Set(int64_t key, const Tensor& value);
`
However, all `Get` and `Set` rely on lookup operations of `rows`, which is a linear scan actually:

`````
  int64_t Index(int64_t key) const {
    auto it = std::find(rows_.begin(), rows_.end(), key);
    if (it == rows_.end()) {
      return static_cast<int64_t>(-1);
    }
    return static_cast<int64_t>(std::distance(rows_.begin(), it));
  }
`````

Why not choose some kind of lookup table to replace `std::vector` within SelectedRows?

**Comment by jacquesqiao** [comment] 2018-07-23 11:34
Yes, we already have a plan to optimize this part.

**Comment by lucywsq** [comment] 2018-10-26 03:37
Thanks for your suggestion!  
This issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 03:37 UTC
