### ISSUE TITLE
fluid.layers.accuracy failed when fluid.layers.ParallelDo is used.

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#8306] opened 2018-02-09 06:08 UTC
```python
    image_shape = [3, 224, 224]

    image = fluid.layers.data(name='image', shape=image_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[1], dtype='int64')
    parallel = True
    if parallel:
        places = fluid.layers.get_places()
        pd = fluid.layers.ParallelDo(places)
        with pd.do():
            img_ = pd.read_input(image)
            label_ = pd.read_input(label)
            prediction, avg_cost, accuracy = net_conf(img_, label_, class_dim)
            test_accuracy1 = fluid.layers.accuracy(input=prediction, label=label, k=2)
            print("ok1")
            for o in [avg_cost, accuracy]:
                pd.write_output(o)

        test_accuracy2 = fluid.layers.accuracy(input=prediction, label=label, k=2)
        print("ok2")

        avg_cost, accuracy = pd()
        # get mean loss and acc through every devices.
        avg_cost = fluid.layers.mean(x=avg_cost)
        accuracy = fluid.layers.mean(x=accuracy)
    else:
        prediction, avg_cost, accuracy = net_conf(image, label, class_dim)

    test_accuracy3 = fluid.layers.accuracy(input=prediction, label=label, k=2)
    print("ok3")
    exit()
```
the output error message is as follows.  the definition of "test_accuracy2" is failed...
Can anyone help me to fix the problem?

```python
ok1
Traceback (most recent call last):
  File "resnet50_parallel.py", line 205, in <module>
    train(learning_rate=0.1, batch_size=16, num_passes=30, init_model=None)
  File "resnet50_parallel.py", line 124, in train
    test_accuracy2 = fluid.layers.accuracy(input=prediction, label=label, k=2)
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50/python-gcc482-paddle/lib/python2.7/site-packages/paddle/v2/fluid/layers/nn.py", line 1032, in accuracy
    attrs={"k": k})
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50/python-gcc482-paddle/lib/python2.7/site-packages/paddle/v2/fluid/layer_helper.py", line 45, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50/python-gcc482-paddle/lib/python2.7/site-packages/paddle/v2/fluid/framework.py", line 729, in append_op
    op = Operator(self, op_desc, *args, **kwargs)
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50/python-gcc482-paddle/lib/python2.7/site-packages/paddle/v2/fluid/framework.py", line 497, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.v2.fluid.core.EnforceNotMet: Input(X) of TopkOp should not be null. at [/paddle/paddle/operators/top_k_op.cc:26]
```

**Comment by reyoung** [comment] 2018-02-12 05:07
The prediction is an output of parallel.do, however, it is not be invoked with `pd.write_output`.

**Comment by shanyi15** [comment] 2018-08-15 11:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:08 UTC
