### ISSUE TITLE
[DRAFT]Fluid Core Framework TODOs

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#10283] opened 2018-04-28 05:22 UTC
NOTE: this is a draft version. Please feel free to modify it.

1. A better & cleaner Python API
   * It should be at least as good as paddle v2 API.
   * Since the API is the fundamental work of other works, such as more example and demos. It should be the top priority.
   * Related [issue](https://github.com/PaddlePaddle/Paddle/issues/10248)

2. Stabilize training process
   * Many of our operators could have bugs since they are non-deterministic. The unit tests are not good since they are written by using very small data and very loose.
   * The memory copy and allocation could have bugs based on our current experiments. 
   * Make sure we can use the Python API and ParallelExecutor to train all models in PaddlePaddle/book and PaddlePaddle/models and have a reasonable loss. The models should be integrated to `ModelCE`.

3. Make the ParallelExecutor/Reader/Operators cleaner.
   * `Keep the code clean and simple` is the rule of our team. Currently, ParallelExecutor, readers, and operators implementation could be optimized. The lines of code after we clean should be lesser and simpler than before.
     * There are a lot of code clean PRs right now.  [Link](https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Aopen+is%3Apr+label%3A%22Code+Cleanup%22)

4. Support data argumentation in Reader and Make ParallelExecutor Faster
   * Data processing is the key bottleneck of traning speed. To support data argumentation in Reader or by operators will significantly speed up training process.
   * Keep tuning ParallelExecutor speed based on nvprof or timeline guide.

**Comment by chengduoZH** [comment] 2018-04-28 05:27
Issues about **Stabilize training process** : #10266, #10168

**Comment by panyx0718** [comment] 2018-04-28 05:41
Thanks, it's great to see that we have put stable and robustness as one of our top goals.

**Comment by shanyi15** [comment] 2018-08-15 10:27
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:27 UTC
