### ISSUE TITLE
Results differ when doing CPU inference multiple times with MKLDNN

### ISSUE THREAD

**Issue by cryoco** [PaddlePaddle/Paddle#25507] opened 2020-07-13 13:53 UTC
**System information**
Paddle version: 1.8.2/1.8.3
Paddle With CUDA: False
OS: Ubuntu 16.04
CPU: 16  Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Python version: 3.5.2
CUDA version: 9.0.176
cuDNN version: None.None.None
Nvidia driver version: None
API information: inference configuration
```python
config.disable_gpu()
config.enable_mkldnn()
config.set_cpu_math_library_num_threads(4)
```
**To Reproduce**
1. download models
- [ocr detection model](https://paddleocr.bj.bcebos.com/ch_models/ch_det_mv3_db_infer.tar)
2. perform inference with mkldnn
code to reproduce:
[test_ocr_mkldnn_diff.txt](https://github.com/PaddlePaddle/Paddle/files/4912903/test_ocr_mkldnn_diff.txt)

This issue can be reproduced with any input. We use data with all ones here.

```python
python3 test_ocr_mkldnn_diff.py --model_file=./ch_det_mv3_db/model --params_file=./ch_det_mv3_db/params --mkldnn
```

Run inference 10 times with the same model and input, and result shifts every time(only the first result is correct).
![image](https://user-images.githubusercontent.com/12407750/87312263-e77de880-c552-11ea-93c1-82ca36e3b6aa.png)

3. perform inference without mkldnn

```python
python3 test_ocr_mkldnn_diff.py --model_file=./ch_det_mv3_db/model --params_file=./ch_det_mv3_db/params
```

The results are consistent.
![image](https://user-images.githubusercontent.com/12407750/87312389-11370f80-c553-11ea-81de-517d1ef67871.png)

**Comment by cryoco** [comment] 2020-07-14 07:03
This issue also happens in v1.8.3, with or without conv_transpose_eltwiseadd_bn_fuse_pass.

**Comment by wojtuss** [comment] 2020-07-14 14:55
@cryoco 
With PaddlePaddle v1.8.3 and the commands
```
$ python test_ocr_mkldnn_diff.py --model_file=det_mv3_db/best_accuracy.pdmodel --params_file=det_mv3_db/best_accuracy.pdparams --mkldnn
```
or
```
$ python test_ocr_mkldnn_diff.py --model_file=det_mv3_db/best_accuracy.pdmodel --params_file=det_mv3_db/best_accuracy.pdparams
```
I get the following error:
```
$ python test_ocr_mkldnn_diff.py --model_file=det_mv3_db/best_accuracy.pdmodel --params_file=det_mv3_db/best_accuracy.pdparams --mkldnn
I0714 09:52:29.858705 18665 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0714 09:52:29.887535 18665 analysis_predictor.cc:872] MODEL VERSION: 1.7.0
I0714 09:52:29.887557 18665 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.3
I0714 09:52:29.888562 18665 analysis_predictor.cc:454] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
Traceback (most recent call last):
  File "test_ocr_mkldnn_diff.py", line 66, in <module>
    pred = create_predictor(args)
  File "test_ocr_mkldnn_diff.py", line 22, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, s
td::char_traits<char>, std::allocator<char> >&&, char const*, int)
1   paddle::framework::VarDesc::tensor_desc() const
2   paddle::framework::VarDesc::GetShape() const
3   paddle::inference::LoadPersistables(paddle::framework::Executor*, paddle::framework::Scope*, paddle::framework::ProgramDesc const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
4   paddle::inference::Load(paddle::framework::Executor*, paddle::framework::Scope*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
5   paddle::inference::analysis::IrGraphBuildPass::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
paddle::framework::Scope*, paddle::platform::Place const&, bool)
6   paddle::inference::analysis::IrGraphBuildPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
8   paddle::AnalysisPredictor::OptimizeInferenceProgram()
9   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
12  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Getting 'tensor_desc' is not supported by the type of var create_py_reader_0. at (/data/repos/PaddlePaddle/Paddle/paddle/fluid/framework/var_desc.cc:209)
```

PaddlePaddle built with cmake flags:
```
cmake -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DWITH_MKLDNN=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_PROFILER=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=ON -DWITH_INFERENCE_API_TEST=ON -DWITH_NCCL=OFF ..
```

**Comment by cryoco** [comment] 2020-07-15 07:58
@wojtuss I will try reproducing on local machine. 
[This](https://paddle-inference-dist.bj.bcebos.com/temp/paddlepaddle-1.8.3-cp37-cp37m-linux_x86_64.whl) is the .whl package(for py3.7) I use.

**Comment by cryoco** [comment] 2020-07-15 08:49
@wojtuss 
Updated model [download link](https://paddleocr.bj.bcebos.com/ch_models/ch_det_mv3_db_infer.tar). Sorry for posting the wrong link. It should be ok now.

**Comment by cryoco** [comment] 2020-07-15 09:01
I tested on develop branch, and this issue seems to have been solved.

**Comment by wojtuss** [comment] 2020-07-15 11:48
@cryoco 
I have reproduced the issue using PaddlePaddle 1.8.2. The problem is within MKLDNN FP32 kernel for `conv2d` with `ResidualData` intput (when the `conv_elementwise_add_mkldnn_fuse_pass` is enabled). If you confirm the issue is no longer present in the `develop` branch, that's most probably because of the PR https://github.com/PaddlePaddle/Paddle/pull/25137. Recently we encountered another issue with FP32 `conv2d` kernel and `ResidualData` (https://github.com/PaddlePaddle/Paddle/issues/24985) fixed by that PR too.

**Comment by cryoco** [comment] 2020-07-15 11:57
@wojtuss 
We did confirm this issue is solved in develop branch, and this issue can be closed. Thanks for your efforts.
It's still strange though that it occurs in 1.8.3, which include PR#25137.

**Comment by luotao1** [comment] 2020-07-15 12:21
@wojtuss Could you find the difference between 1.8.3 and the develop branch, and then cherry-pick into release/1.8? We will release 1.8.4 later.

**Comment by wojtuss** [comment] 2020-07-15 12:31
@luotao1 , OK, I will do that.

**Comment by wojtuss** [comment] 2020-07-15 12:59
> @wojtuss
> We did confirm this issue is solved in develop branch, and this issue can be closed. Thanks for your efforts.
> It's still strange though that it occurs in 1.8.3, which include PR#25137.

@cryoco, @luotao1 
I cannot see the commit bd0b38e6718c2d9790a2764a9fbba8fa7ca444f9 in 1.8.3. Also the diff between the `develop` and `v1.8.3` tag shows the commit: https://github.com/PaddlePaddle/Paddle/compare/v1.8.3...develop (see Commits on Jun 23, 2020 section).

**Comment by luotao1** [comment] 2020-07-15 13:49
Got it. Please cherry-pick https://github.com/PaddlePaddle/Paddle/commit/bd0b38e6718c2d9790a2764a9fbba8fa7ca444f9 into release/1.8 and have a double-check!

**Comment by wojtuss** [comment] 2020-07-16 15:12
@grygielski did that: https://github.com/PaddlePaddle/Paddle/pull/25572

**Closed as completed** 2020-07-23 03:22 UTC
Labels: Bug, Intel
