### ISSUE TITLE
How to add intercept or scale for OutputLayer by rows?

### ISSUE THREAD

**Issue by nick6918** [PaddlePaddle/Paddle#7113] opened 2017-12-29 08:58 UTC
When defining a model, sometimes we want to manually add some intercepts to help training, here in my model, since label 1 is relevantly sparse, I want to set a intercept at the first several epochs to help model converge.

```python
output = paddle.layer.fc(
        input=input_dropout, size=class_dim, act=paddle.activation.Softmax())
    #change gate to 0.5+offset
    output[0] += offset
    cost = paddle.layer.classification_cost(input=output, label=lbl, weight = weight, evaluator=precision_recall_evaluator_for_vulg)
    return cost, output, lbl
```

I got error log like this:
```python
Traceback (most recent call last):
  File "my-train-cnn.py", line 247, in <module>
    cost, prob, label = convolution_net(dict_dim, class_dim=class_dim)
  File "my-train-cnn.py", line 80, in convolution_net
    output[0] += offset
TypeError: 'LayerOutput' object does not support indexing
```

Apparently, the indexing operation is not supported, so how can I implement this logic properly?

Thanks for your help.

**Comment by jacquesqiao** [comment] 2017-12-29 09:03
currently paddle does not support such kind of operation, does other framework support this?

**Comment by jacquesqiao** [comment] 2017-12-29 09:05
maybe you can add intercept on data?

**Comment by nick6918** [comment] 2017-12-29 09:05
[Sad...]

I'm not sure if TF support it, but at least those frameworks using dynamic graph like PyTorch definitely support.

**Comment by nick6918** [comment] 2017-12-29 09:06
I don't think adding intercept on data achieves same result.

**Comment by nick6918** [comment] 2017-12-29 09:08
@jacquesqiao  Does paddle support 2 OutputLayer addition? If so, which layer can I use?

**Comment by jacquesqiao** [comment] 2017-12-29 09:09
yes, paddle has a `addto` layer to do this

**Comment by nick6918** [comment] 2017-12-29 09:11
@jacquesqiao 

```python
cost = paddle.layer.classification_cost(input=output, label=lbl, weight = weight, evaluator=precision_recall_evaluator_for_vulg)
```

Sorry, Another following question, how does cost function choose final predict label, does it use argmax function, can I set an offset at this step?

**Comment by jacquesqiao** [comment] 2017-12-29 09:14
cost is calculated in C++, here do you mean the argmax of numpy?

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
