### ISSUE TITLE
运行lambdarank demo infer阶段代码报错

### ISSUE THREAD

**Issue by MiraiJ** [PaddlePaddle/Paddle#5210] opened 2017-10-30 09:31 UTC
执行ltr中的lambdarank的infer出现错误，数据为demo中mq2007中的数据。
https://github.com/PaddlePaddle/models/tree/develop/ltr
在lambda_rank.py中infer_data是array，但是到dataprovider_converter.py中dat为一个float型，错误如下，

`Traceback (most recent call last):
  File "lambda_rank.py", line 137, in <module>
    lambda_rank_infer(pass_id=args.num_passes - 1)
  File "lambda_rank.py", line 120, in lambda_rank_infer
    output_layer=output, parameters=parameters, input=infer_data)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 158, in infer
    return inferer.infer(field=field, input=input, feeding=feeding)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 93, in infer
    for result in self.iter_infer_field(field=field, **kwargs):
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 80, in iter_infer_field
    for result in self.iter_infer(**kwargs):
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 73, in iter_infer
    yield self.__gradient_machine__.forwardTest(feeder(data_batch))
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 284, in __call__
    return self.convert(dat, argument)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 133, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 269, in convert
    scanner.pre_scan(each_step)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 227, in pre_scan
    self.__inner_scanner__.pre_scan(each)
  File "/home/yitengfei/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 116, in pre_scan
    "The input should be a vector, please check your input data."
ValueError: The input should be a vector, please check your input data.`

**Comment by shanyi15** [comment] 2018-08-15 11:12
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:12 UTC
