### ISSUE TITLE
hadoop跑capi预测报内存错误

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#11587] opened 2018-06-20 02:31 UTC
之前试过小内存的机器就会报这个错误，大内存机器没问题，paddle对内存的要求很高的样子，如何降低这个要求？

0620 10:12:34.262291   426 Util.cpp:166] commandline:  --use_gpu=False 
I0620 10:12:34.328554   426 GradientMachine.cpp:94] Initing parameters..
I0620 10:12:36.696529   426 GradientMachine.cpp:101] Init parameters done.
I0620 10:12:36.696564   426 GradientMachine.cpp:83] Loading parameters from ./model-parmas-cnn-v8/
*** Aborted at 1529460756 (unix time) try "date -d @1529460756" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 426 (TID 0x7f4f9fc6a840) from PID 0; stack trace: ***
    @     0x7f4f9f847160 (unknown)
    @     0x7f4f8c0ff235 paddle_gradient_machine_forward
    @           0x401a5f main
    @     0x7f4f8b4efbd5 __libc_start_main
    @           0x4012d9 (unknown)
    @                0x0 (unknown)
sed: couldn't write 63 items to stdout: Broken pipe
cat: write error: Broken pipe
wise_paddle_qcnn_red.sh: line 14:   423 Done(1)                 cat
       424 Done(4)                 | sed -e 's/^\s*//' -e 's/\s*$//'
       426 Segmentation fault      | ./sequence_paddle

**Comment by JiayiFeng** [comment] 2018-06-20 03:42
可否先根据模型参数大小和一次送入的数据量估算一下理论内存占用情况？

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
Labels: User
