### ISSUE TITLE
inconsistent api name and doc about `create_lod_tensor` and more detaild aboud `recursive_seq_lens`

### ISSUE THREAD

**Issue by fseasy** [PaddlePaddle/Paddle#13303] opened 2018-09-08 04:34 UTC
## The api has inconsistent name

```
fluid.create_lod_tensor
fluid.create_random_int_lodtensor
```
the first `lod_tensor` and the second `lodtensor` is inconsistent.

## inconsistent api doc

as the doc:
(1) [进阶使用-如何传入序列数据](http://paddlepaddle.org/documentation/docs/zh/0.15.0/new_docs/user_guides/howto/prepare_data/feeding_data.html#permalink-4--)
(2) [api-example](http://paddlepaddle.org/documentation/api/zh/0.15.0/fluid.html#permalink-31-create_lod_tensor)

## more detailed info

What more, could give a sample about create lod_level=2 's sample or some description about how to assign `recursive_seq_lens` parameter, because that confused me: lod_level=1, but it is a nested list, how aboud a level=2? a list of list of list?

**Comment by lucywsq** [comment] 2018-10-11 04:36
Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-11 04:36 UTC
