### ISSUE TITLE
Need to generate more readable api doc

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#10974] opened 2018-05-28 10:09 UTC
http://paddlepaddle.org/docs/develop/api/fluid/en/layers.html#mean

![image](https://user-images.githubusercontent.com/2887803/40609719-1c41aa90-62a2-11e8-88ed-131ba7449f7e.png)

need to replace *args and **kwargs with actual arguments.
need to op_role and op_role_var

**Comment by panyx0718** [comment] 2018-05-28 10:12
seems generated here
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/layer_function_generator.py#L98

**Comment by shanyi15** [comment] 2018-08-15 11:35
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:35 UTC
