### ISSUE TITLE
ctc batch 预测，单batch和多batch的结果无法对齐

### ISSUE THREAD

**Issue by lemon34** [PaddlePaddle/Paddle#10856] opened 2018-05-23 03:00 UTC
*  ctc batch预测，batchsize  = 1 的时候和batchsize = 2 的时候结果无法对齐，diff 率比较高，10000张图片存在300张左右的diff

**Comment by qingqing01** [comment] 2018-05-23 04:53
1. 可否给出具体Diff值
2. 能否将改动代码提个PR

**Comment by Xreki** [comment] 2018-05-23 05:00
补充说明下@qingqing01 问的第一点：
1.1 对于存在diff的图片，单样本预测和batch预测，结果差别有多大？可否给几个预测结果看看
1.2 这10000张图片都是有label的吧，单样本预测和batch预测的准确率（sequence error）分别是多少？

**Comment by lemon34** [comment] 2018-05-23 07:00
为了和paddle v1对齐，所以是以v1的单样本预测和batch预测为标准的，目前已经根据paddle v1中的处理将fluid 中im2sequence这个op进行了修改，代码在整理中，稍后会提PR。谢谢二位回答 @Xreki @qingqing01

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
