### ISSUE TITLE
Unit test test_multi_file_reader.TestMultipleReader fails when using manylinux docker image build

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#9981] opened 2018-04-17 06:45 UTC
Run
```
docker run -it --privileged -v $PWD:/paddle --rm \
  -e "PYTHON_ABI=cp27-cp27mu" \
  -e "https_proxy=http://172.19.32.166:8899" \
  -v /home/work/wuyi/nvidia:/usr/local/nvidia/lib64 \
  paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5 \
  /bin/bash -c 'export PATH=/opt/python/cp27-cp27mu/bin:$PATH; export LD_LIBRARY_PATH=/opt/python/cp27-cp27mu/lib:$LD_LIBRARY_PATH; bash'
```
and run build script inside the docker image, and then run `ctest -R test_all_ops -V`

```
185: test_main (test_multi_file_reader.TestMultipleReader) ... terminate called after throwing an instance of 'std::system_error'
185:   what():
185: *** Aborted at 1523946654 (unix time) try "date -d @1523946654" if you are using GNU date ***
185: PC: @                0x0 (unknown)
185: *** SIGABRT (@0x7a30) received by PID 31280 (TID 0x7f949ed4f700) from PID 31280; stack trace: ***
185:     @     0x7f949e5227e0 (unknown)
185:     @     0x7f949db26495 __GI_raise
185:     @     0x7f949db27c75 __GI_abort
185:     @     0x7f9493b36a8d __gnu_cxx::__verbose_terminate_handler()
185:     @     0x7f9493b34be6 (unknown)
185:     @     0x7f9493b33b69 (unknown)
185:     @     0x7f9493b345c1 __gxx_personality_v0
185:     @     0x7f9493fae383 (unknown)
185:     @     0x7f9493fae70d _Unwind_RaiseException
185:     @     0x7f9493b34d25 __cxa_throw
185:     @     0x7f9493ad992c std::__throw_system_error()
185:     @     0x7f9461fffa5d paddle::framework::ChannelImpl<>::Send()
185:     @     0x7f9461ff2a7d paddle::operators::reader::MultiFileReader::StartNewScheduler()
185:     @     0x7f9461ff7025 paddle::operators::reader::OpenFilesOp::RunImpl()
185:     @     0x7f9461fd72fc paddle::framework::Executor::RunPreparedContext()
185:     @     0x7f9461fd7ec9 paddle::framework::Executor::Run()
185:     @     0x7f9461f69ff1 _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEJRKNS4_11ProgramDescEPNS4_5ScopeEibbEJNS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vJSO_S8_SA_ibbEJSB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_
185:     @     0x7f9461f64332 pybind11::cpp_function::dispatcher()
185:     @     0x7f949e83bce8 PyEval_EvalFrameEx
185:     @     0x7f949e83e37d PyEval_EvalCodeEx
185:     @     0x7f949e83bd70 PyEval_EvalFrameEx
185:     @     0x7f949e83e37d PyEval_EvalCodeEx
185:     @     0x7f949e83bd70 PyEval_EvalFrameEx
185:     @     0x7f949e83be9e PyEval_EvalFrameEx
185:     @     0x7f949e83e37d PyEval_EvalCodeEx
185:     @     0x7f949e7b5905 (unknown)
185:     @     0x7f949e783d33 PyObject_Call
185:     @     0x7f949e8390a2 PyEval_EvalFrameEx
185:     @     0x7f949e83e37d PyEval_EvalCodeEx
185:     @     0x7f949e7b5830 (unknown)
185:     @     0x7f949e783d33 PyObject_Call
185:     @     0x7f949e79274d (unknown)
1/1 Test #185: test_all_ops .....................***Exception: Other 50.58 sec

```

**Comment by JiayiFeng** [comment] 2018-04-17 08:13
I will check it.

**Comment by shanyi15** [comment] 2018-08-15 11:36
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
