### ISSUE TITLE
How to use local Variable for loss accumulation

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#11815] opened 2018-06-28 12:08 UTC
I want to use local variable to accumulate losses in while_op, my code is:
```python
    with while_op.block():
           ...
           ...
           fluid.layers.sums(input=[total_sum, target_sum], out=total_sum)
           counter = fluid.layers.increment(x=counter, value=1, in_place=True)
           fluid.layers.less_than(x=counter, y=until, cond=cond)
    return total_sum
```
If I use ```create_global_var```,  define ```total_sum``` as:
```
total_sum = fluid.layers.create_global_var(shape=[0], value=0, dtype='float32', persistable=True)
```
there are following errors. Do you have other better method to implement my function?
```
Traceback (most recent call last):
  File "se_resnext_metric_parallelexe.py", line 1080, in <module>
    layers=layers)
  File "se_resnext_metric_parallelexe.py", line 894, in train
    opts = optimizer.minimize(avg_cost)
  File "/home/ssd1/yancanxiang/code_paddle/code_metric/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 255, in minimize
    [error_clip_callback])
  File "/home/ssd1/yancanxiang/code_paddle/code_metric/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 556, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/ssd1/yancanxiang/code_paddle/code_metric/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 377, in _append_backward_vars_
    _append_backward_vars_(sub_block, 0, grad_to_var, grad_info_map)
  File "/home/ssd1/yancanxiang/code_paddle/code_metric/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet:  at [/paddle/paddle/fluid/operators/conditional_block_op.cc:207]
PaddlePaddle Call Stacks: 
0       0x7fabcfa477b6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fabcfeb2d2fp paddle::operators::ConditionalBlockGradInferShape::operator()(paddle::framework::InferShapeContext*) const + 975
2       0x7fabcfeb3163p std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<paddle::operators::ConditionalBlockGradInferShape, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*) + 35
3       0x7fabcfacfd59p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 873
4       0x7fabcfaa2dc5p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 213
5       0x7fabcfa57684p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
6       0x7fac295c655fp PyEval_EvalFrameEx + 29855
7       0x7fac295c5b17p PyEval_EvalFrameEx + 27223
8       0x7fac295c5b17p PyEval_EvalFrameEx + 27223
9       0x7fac295c886dp PyEval_EvalCodeEx + 2061
10      0x7fac295c59fcp PyEval_EvalFrameEx + 26940
11      0x7fac295c886dp PyEval_EvalCodeEx + 2061
12      0x7fac295c59fcp PyEval_EvalFrameEx + 26940
13      0x7fac295c886dp PyEval_EvalCodeEx + 2061
14      0x7fac295c59fcp PyEval_EvalFrameEx + 26940
15      0x7fac295c886dp PyEval_EvalCodeEx + 2061
16      0x7fac295c89a2p PyEval_EvalCode + 50
17      0x7fac295f1782p PyRun_FileExFlags + 146
18      0x7fac295f2af9p PyRun_SimpleFileExFlags + 217
19      0x7fac2960882dp Py_Main + 3149
20      0x7fac28805bd5p __libc_start_main + 245
21            0x4007a1p
```

**Comment by guoshengCS** [comment] 2018-06-29 06:26
It seems that the error is caused by the check in `conditional_block_op` https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/conditional_block_op.cc#L207 . Is there use of `IfElse` or `Switch` and the inputs are set no gradient.

**Comment by shanyi15** [comment] 2018-08-15 10:19
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:19 UTC
Labels: User
