### ISSUE TITLE
Some question about cuda thread size.

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#7081] opened 2017-12-27 12:43 UTC
In [ForRange](https://github.com/PaddlePaddle/Paddle/blob/7bf47ea40c2561feaf11da7d233cd2528eb72cc5/paddle/platform/for_range.h#L59) struct,  thread size seems to be assigned arbitrary value, the value is not multiple of the warp size.
As I read and heard that the thread size assigned to a block should be always multiple of the warp size(32), otherwise not only the remaining part of the warp goes unused and the performance is dropped too since bad memory coalescing. But I didn't find a comparative experiment on this. 

https://github.com/PaddlePaddle/Paddle/blob/7bf47ea40c2561feaf11da7d233cd2528eb72cc5/paddle/platform/for_range.h#L65-L75

**Comment by typhoonzero** [comment] 2017-12-28 03:09
I'm working on https://github.com/PaddlePaddle/Paddle/pull/7045 which I would prefer to add necessary functors for SelectedRows, then the `forrange` call can be replaced.

**Comment by chengduoZH** [comment] 2017-12-28 06:59
Currently, `forrange` is used by `adam_op`, #6601 also attempts to use `forrange`.

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
