### ISSUE TITLE
inference_api_native.image_classification_gpu  in CI failed.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#11498] opened 2018-06-14 23:58 UTC
```
[16:06:58]	[Step 1/1] /paddle/paddle/contrib/inference/test_paddle_inference_api_impl.cc:259: Failure
[16:06:58]	[Step 1/1] The difference between ref_data[i] and data[i] is 0.0044990791939198971, which exceeds 1e-3, where
[16:06:58]	[Step 1/1] ref_data[i] evaluates to 0.010122228413820267,
[16:06:58]	[Step 1/1] data[i] evaluates to 0.0056231492199003696, and
[16:06:58]	[Step 1/1] 1e-3 evaluates to 0.001.
[16:06:58]	[Step 1/1] /paddle/paddle/contrib/inference/test_paddle_inference_api_impl.cc:259: Failure
[16:06:58]	[Step 1/1] The difference between ref_data[i] and data[i] is 0.0044990777969360352, which exceeds 1e-3, where
[16:06:58]	[Step 1/1] ref_data[i] evaluates to 0.98987776041030884,
[16:06:58]	[Step 1/1] data[i] evaluates to 0.99437683820724487, and
[16:06:58]	[Step 1/1] 1e-3 evaluates to 0.001.
[16:06:58]	[Step 1/1] [  FAILED  ] inference_api_native.image_classification_gpu (273 ms)
[16:06:58]	[Step 1/1] [ RUN      ] inference_api_native.image_classification_gpu_threads
[16:06:58]	[Step 1/1] I0614 16:06:57.461799 46399 test_paddle_inference_api_impl.cc:48] dirname  /paddle/build/python/paddle/fluid/tests/book/word2vec.inference.model
```

**Comment by shanyi15** [comment] 2018-08-15 11:34
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:34 UTC
