### ISSUE TITLE
Doc for paddle.layer.kmax_sequence_score cannot be correctly generated.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6830] opened 2017-12-21 09:17 UTC
See here: http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#kmax-sequence-score

**Comment by memeda** [comment] 2018-01-09 12:31
I found it ...
And the True name in release 0.11 is `kmax_seq_score`, and has following help:

```
kmax_seq_score(*args, **xargs)
    This layer accepts one input which is scores over a sequence or a nested
    sequence, and returns indices of beam_size sequences with highest scores.

    .. code-block:: python

        kmax_indices = kmax_seq_score(input=input, beam_size)


    :param name: The name of this layer. It is optional.
    :type name: basestring
    :param input: The input of this layer. It stores scores over a sequence or
                  a nested sequence and its size must be 1.
    :type input: paddle.v2.config_base.Layer
    :param beam_size: The indices of the sequences with top beam_size scores are returned.
    :type beam_size: int
    :return: paddle.v2.config_base.Layer object.
    :rtype: paddle.v2.config_base.Layer
```

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
Labels: 文档
