### ISSUE TITLE
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#10748] opened 2018-05-17 11:25 UTC
问题描述：
1、单机单卡正常运行(无parallel executor)
2、单机多卡无法运行（有parallel executor）
运行环境：
gcc version 4.8.3 (GCC)
GPU: K40m Driver Version:Driver Version: 367.48
NCCL version：nccl_2.1.15-1+cuda8.0_x86_64
Details of the error log:
/home/vis/liushanshan/common_env/fluid/venv/lib/python2.7/site-packages/paddle/fluid/evaluator.py:64:     Warning: The EditDistance is deprecated, because maintain a modified program inside evaluator cause     bug easily, please use fluid.metrics.EditDistance instead.
  2   % (self.__class__.__name__, self.__class__.__name__), Warning)
  3 `feed_dict` is deprecated. Please use `feed=`
  4 terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  5   what():  an illegal memory access was encountered at [/home/disk1/wanghaoshuang/paddle/debug/paddle    /fluid/framework/details/op_handle_base.cc:37]
  6 PaddlePaddle Call Stacks:
  7 0       0x7f9d73e3bec6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exceptio    n_ptr, char const*, int) + 486
  8 1       0x7f9d748dbe5fp paddle::framework::details::OpHandleBase::~OpHandleBase() + 463
  9 2       0x7f9d748d8721p paddle::framework::details::FetchOpHandle::~FetchOpHandle() + 17
 10 3       0x7f9d748d634ep std::vector<std::unique_ptr<paddle::framework::details::FetchOpHandle, std::d    efault_delete<paddle::framework::details::FetchOpHandle> >, std::allocator<std::unique_ptr<paddle::fr    amework::details::FetchOpHandle, std::default_delete<paddle::framework::details::FetchOpHandle> > > >    ::~vector() + 46
 11 4       0x7f9d748d555dp paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::st    ring, std::allocator<std::string> > const&) + 3277
 12 5       0x7f9d73ee9b8dp paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::alloca    tor<std::string> > const&, std::string const&) + 365

**Comment by guoshengCS** [comment] 2018-05-17 11:41
请问这个是和 #10633 是同一个问题是么，这个在跟进中

**Comment by shanyi15** [comment] 2018-08-15 10:25
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:25 UTC
Labels: User
