### ISSUE TITLE
Increase CI speed without sacrificing test stability.

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#10557] opened 2018-05-10 03:56 UTC
As Paddle project grows, we are having more and more tests to run for each PR. We want to improve the efficiency of running these tests without making our tests unstable and randomly fail.

We have tried to increase the parallelism to 5 to speed up tests. However, as @wanglei828 pointed our, tests start to interfere with each other and cause random failures.

Hence, to increase the run parallelism, we need to first make sure the tests are properly isolated. To make an analogy, before we are doing multi-threading, we need to redesign some critical section or add locks to the proper places.

Just to throw an ideas:
We split the tests into 4 parts. Each part is assigned to 2 GPUs. 4 different parts run in parallel on 8 GPUs. Tests in each part are run sequentially.
1. Tests of different parts are isolated by different GPUs, they don't share GPU memory. They share CPU memory, which doesn't seem to be a problem as long as each test doesn't use giant piece of memory. (If they do, we should fix them).
2. Tests in a single part run sequentially, so they don't interfere with each other.

Welcome any suggestions or new ideas.

**Comment by typhoonzero** [comment] 2018-05-10 07:18
Agree, by the way, CPU tests can run in parallel since the memory is sufficient.

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
