### ISSUE TITLE
编译develop分支发生编译错误

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#10782] opened 2018-05-19 05:18 UTC
我在CUDA9.2+cuDNN7.1+NCCL2环境下编译develop分支的代码，发生了编译错误，错误如下：
> [ 29%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o
In file included from /mnt/Paddle/paddle/fluid/platform/enforce.h:47:0,
                 from /mnt/Paddle/paddle/fluid/platform/enforce.cc:15:
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h: In member function ‘decltype (ncclGroupStart(args ...)) paddle::platform::dynload::DynLoad__ncclGroupStart::operator()(Args ...)’:
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:36:35: error: ‘::ncclGroupStar’ has not been declared
       using nccl_func = decltype(&::__name);                             \
                                   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:67:3: note: in expansion of macro ‘DECLARE_DYNAMIC_LOAD_NCCL_WRAP’
   __macro(ncclGroupStart);              \
   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:72:1: note: in expansion of macro ‘NCCL_RAND_ROUTINE_EACH’
 NCCL_RAND_ROUTINE_EACH(DECLARE_DYNAMIC_LOAD_NCCL_WRAP)
 ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:41:31: error: ‘nccl_func’ does not name a type
       return reinterpret_cast<nccl_func>(p_##__name)(args...);           \
                               ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:67:3: note: in expansion of macro ‘DECLARE_DYNAMIC_LOAD_NCCL_WRAP’
   __macro(ncclGroupStart);              \
   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:72:1: note: in expansion of macro ‘NCCL_RAND_ROUTINE_EACH’
 NCCL_RAND_ROUTINE_EACH(DECLARE_DYNAMIC_LOAD_NCCL_WRAP)
 ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h: In member function ‘decltype (ncclGroupEnd(args ...)) paddle::platform::dynload::DynLoad__ncclGroupEnd::operator()(Args ...)’:
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:36:35: error: ‘::ncclGroupEnd’ has not been declared
       using nccl_func = decltype(&::__name);                             \
                                   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:68:3: note: in expansion of macro ‘DECLARE_DYNAMIC_LOAD_NCCL_WRAP’
   __macro(ncclGroupEnd);                \
   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:72:1: note: in expansion of macro ‘NCCL_RAND_ROUTINE_EACH’
 NCCL_RAND_ROUTINE_EACH(DECLARE_DYNAMIC_LOAD_NCCL_WRAP)
 ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:41:31: error: ‘nccl_func’ does not name a type
       return reinterpret_cast<nccl_func>(p_##__name)(args...);           \
                               ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:68:3: note: in expansion of macro ‘DECLARE_DYNAMIC_LOAD_NCCL_WRAP’
   __macro(ncclGroupEnd);                \
   ^
/mnt/Paddle/paddle/fluid/platform/dynload/nccl.h:72:1: note: in expansion of macro ‘NCCL_RAND_ROUTINE_EACH’
 NCCL_RAND_ROUTINE_EACH(DECLARE_DYNAMIC_LOAD_NCCL_WRAP)
 ^
paddle/fluid/platform/CMakeFiles/enforce.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o] Error 1
CMakeFiles/Makefile2:2798: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

请问如何解决？

**Comment by zhanglistar** [comment] 2018-05-19 06:10
环境贴下

**Comment by zzhzz** [comment] 2018-05-21 02:50
GPU: Tesla k40m
OS: Ubuntu 16.04
CUDA: 9.2
cuDNN: 7.1
NCCL: 2.2.12

**Comment by zzhzz** [comment] 2018-05-21 12:17
@jacquesqiao 我的nccl安装位置是在/usr/lib/x86_64-linux-gnu/目录下，请问是否要求nccl文件必须放在CUDA文件夹中？

**Comment by shanyi15** [comment] 2018-08-15 11:02
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by Shixiaowei02** [comment] 2018-10-19 06:49
@zzhzz 我去安装 nccl2 了。貌似是 nccl1 会出现这样的错误。

**Comment by typhoonzero** [comment] 2018-10-19 06:59
请参考：https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html#down 安装nccl2并尝试重新编译～

**Comment by jacquesqiao** [comment] 2018-10-19 07:00
看起来是因为nccl1造成的问题，请按照上面所述的文档重新安装测试。

**Closed by jacquesqiao** 2018-10-19 07:00 UTC
Labels: User
