### ISSUE TITLE
Documentation of data format for data reader

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#2092] opened 2017-05-10 21:19 UTC
First, the link to the "supported type" at http://paddlepaddle.org/doc/api/v2/data.html is broken.

Second, assuming the link is to api/v1/data_provider/pydataprovider2_en.rst, the description for what types can be accepted is not clear enough. For example, when numpy array is used, what the dataformat for sequence data.

**Comment by lcy-seso** [comment] 2017-05-11 05:39
This is similar to the problem reported in this issue https://github.com/PaddlePaddle/Paddle/issues/2076.

**Comment by shanyi15** [comment] 2018-08-15 11:14
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:14 UTC
Labels: 文档
