### ISSUE TITLE
Develop branch build failure

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3941] opened 2017-09-06 23:54 UTC
```
In file included from /paddle/paddle/gserver/layers/MKLDNNLayer.h:21:0,
                 from /paddle/paddle/gserver/layers/MKLDNNFcLayer.h:17,
                 from /paddle/paddle/gserver/layers/MKLDNNFcLayer.cpp:15:
/paddle/paddle/math/MKLDNNMatrix.h: In member function ‘mkldnn::engine paddle::MKLDNNMatrix::getEngine()’:
/paddle/paddle/math/MKLDNNMatrix.h:134:58: error: ‘struct mkldnn::memory::primitive_desc’ has no member named ‘get_engine’
   mkldnn::engine getEngine() { return getPrimitiveDesc().get_engine(); }
                                                          ^
[ 47%] Building CXX object paddle/gserver/CMakeFiles/paddle_gserver.dir/layers/RowConvLayer.cpp.o
In file included from /paddle/build/third_party/install/protobuf/include/google/protobuf/stubs/common.h:40:0,
                 from /paddle/build/proto/ModelConfig.pb.h:9,
                 from /paddle/paddle/gserver/layers/Layer.h:19,
                 from /paddle/paddle/gserver/layers/MKLDNNLayer.h:18,
                 from /paddle/paddle/gserver/layers/MKLDNNFcLayer.h:17,
                 from /paddle/paddle/gserver/layers/MKLDNNFcLayer.cpp:15:
/paddle/build/third_party/install/glog/include/glog/logging.h: In instantiation of ‘std::__cxx11::string* google::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/paddle/paddle/gserver/layers/MKLDNNFcLayer.cpp:35:3:   required from here
/paddle/build/third_party/install/glog/include/glog/logging.h:717:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
                                ^
/paddle/build/third_party/install/protobuf/include/google/protobuf/stubs/port.h:200:53: note: in definition of macro ‘GOOGLE_PREDICT_TRUE’
 #define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                     ^
/paddle/build/third_party/install/glog/include/glog/logging.h:717:1: note: in expansion of macro ‘DEFINE_CHECK_OP_IMPL’
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
 ^

```

**Comment by tensor-tang** [comment] 2017-09-07 03:55
hi @wangkuiyi 

I can not reproduce this issue with the latest code `commit a072ab9e74227361421e6b1fdc167b6709fcdf87`.

Can you tell me your commit id?

BTW, I set `WITH_GPU=OFF`, since has no GPU on my local machine.

**Comment by luotao1** [comment] 2017-09-07 09:00
Close this issue due to can't reproduce.

**Closed by luotao1** 2017-09-07 09:00 UTC
