### ISSUE TITLE
Some Operator Assumptions for ParallelExecutor and MemoryOptimizer to Work Correctly

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#11668] opened 2018-06-22 12:52 UTC
## Operators cannot finish before all its kernels are launched (e.g. launch kernel in a new cpu thread).

Reason: ParallelExecutor depends on events between kernels on the stream to ensure dependencies. It places a event after a computation/copy kernel on the stream. So want the next kernel wait the event, it ensures the previous computation/copy kernel has finished. However, if the kernel kernel is launched in a new cpu thread, there is no guarantee that the kernel is launched on the stream before the barrier event.

## Operators cannot use input variables' space for output variables.

Reason: Memory optimizer assumes that the output var and input var are using different underlying space as long as they are of different names. And use this assumption to make memory reuse decisions. However if a Operator make reuse decision internally, memory optimizer might think a variable's space is no longer used (based on name), but it's actually used by a variable of a different name. (which memory optimizer has no way to know

**Comment by chengduoZH** [comment] 2018-06-25 03:04
Now ParallelExecutor supports GPU and CPU, the above reason that you list is for GPU version.

When using ParallelExecutor for GPU training, **the very important point** is that the task that running in CPU side **must be finished** once the Op returns, because CUDA calling is async, when the Op returned, the CUDA calling that launched by this Op may not be executed yet.

For CPU training, we also need to ensure that the task that running in CPU side **must be finished** once this Op returns.

**Comment by shanyi15** [comment] 2018-08-15 11:00
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:00 UTC
