### ISSUE TITLE
LoDTensor Python API Change To-Do List

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#11612] opened 2018-06-21 01:00 UTC
The previous work has been summarized in #11106.

Based on the @panyx0718 's comment, there are some remaining work to do:

1. In Fluid's Python code (especially the op test code), there are variable's of name `lod` like the following:
https://github.com/PaddlePaddle/Paddle/blob/c660b471c4d4201d4fc3517896f69d44b4490003/python/paddle/fluid/data_feeder.py#L54

Since we are replacing the notion of `lod` with `recursive_sequence_lengths`, we want to change these variable names from `lod` to `recursive_sequence_lengths` or similar shorter name.

2. Change the lod_tensor.md to reflect the change in pybind API.

3. Change the mention of name `lod` to `recursive_sequence_lengths` in the document comments in python files including `nn.py` and `control_flow.py`.

4. There are another concept called `lod_level` which is essentially the depth of `lod`, so we need to repeat item 1-3 to replace the notion `lod_level` with something like `sequence_lengths_depth`. 

5. Remove the `lod`, `set_lod` deprecated API in pybind in the future.

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
