### ISSUE TITLE
unify the file mode permission 

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#8614] opened 2018-02-27 13:02 UTC
Some of our file mode permission are wrong. For example: `paddle/fluid/operators/iou_similarity_op.cu` and `paddle/fluid/operators/iou_similarity_op.cc` are wrong. These two files should not have the "X" permission.
![image](https://user-images.githubusercontent.com/6836917/36730089-2274ca9c-1c01-11e8-9f6a-9629cc9d2369.png)

Can we unify these file mode permission and write the permission check in pre-commit and travis-ci?

**Comment by shanyi15** [comment] 2018-08-15 11:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:07 UTC
