### ISSUE TITLE
paddle v2 book 08. machine translation. when set beam_size ==1, the beam_search will dump with the error

### ISSUE THREAD

**Issue by PathricLee** [PaddlePaddle/Paddle#13294] opened 2018-09-07 08:11 UTC
**the error information is shown below:**
```
Traceback (most recent call last):
  File "infer.py", line 119, in <module>
    main(args)
  File "infer.py", line 115, in main
    beam_size=args.beam_size)
  File "infer.py", line 86, in infer
    label_reverse_dict)
  File "infer.py", line 18, in _infer_a_batch
    beam_result = inferer.infer(input=test_batch, field=['prob', 'id'], feeding=feeding)
  File "/home/work/liyabo01/baidu/personal-code/value-system/python27/lib/python2.7/site-packages/paddle/v2/inference.py", line 104, in infer
    retv = [numpy.concatenate(out) for out in retv]
ValueError: zero-dimensional arrays cannot be concatenated

when the beam_size is set 2 or bigger, the  demo is ok. 
```

**Comment by guoshengCS** [comment] 2018-10-15 09:41
The result may not contain scores(`prob`) when `beam_size=1`. Try to change `beam_result = inferer.infer(input=test_batch, field=['prob', 'id'], feeding=feeding)` to `beam_result = inferer.infer(input=test_batch, field=['id'], feeding=feeding)`.

**Comment by lucywsq** [comment] 2018-10-26 06:20
Hello, this issue has not been updated in the past month. We will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 06:20 UTC
