### ISSUE TITLE
Build ERROR after Upgrade new profiler

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#40094] opened 2022-03-02 14:59 UTC
Commit 0c3f7fbcfe68bfb34b0ed5d9aad6e3a8c0cca43f caused build error, reproduced on several machines (SKX, CLX, CPX)

### CMAKE Flags:
``
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DPY_VERSION=3.6
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8
```
![image](https://user-images.githubusercontent.com/10847947/156386447-0d139d6c-f16e-4896-acc0-9d6ec4645c07.png)

**Comment by baoachun** [comment] 2022-03-03 01:54
Hi @rainyfly Could you please locate the cause and fix it?

**Comment by rainyfly** [comment] 2022-03-03 09:59
Hello, we noticed this warning, and fix it in https://github.com/PaddlePaddle/Paddle/pull/40133/, you can pull this pr and try again.

**Comment by lidanqing-vv** [comment] 2022-03-21 10:11
It is fixed so I close it

**Closed as completed by lidanqing-vv** 2022-03-21 10:11 UTC
Labels: Intel
