### ISSUE TITLE
Proto Rewrite, Transipile, Compile

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#9839] opened 2018-04-11 08:45 UTC
In Paddle, we talk a lot about Proto Rewrite, transpile and compile interchangeably. However, they usually involve significantly different works and technologies. This doc tries to discuss these 3 concepts and current Paddle situations.

**Proto Rewrite**
Proto is widely used as intermediate representation and passed through interfaces. There are so many ways to use protobuf. For example, 1. argument, 2. system configuration, 3. model representation and even 4. test generation.

Proto rewrite is common in deep learning community. Usually, the workflow is “original proto->in-memory data structure->rewrite logic->rewritten proto”. 

For example, in TensorFlow, 1. GraphDef proto is first converted to in-memory graph data structure. 2. The data structure is optimized in various ways, some ahead-of-time, some just-in-time. The goal is to finish the interpretation of the graph faster, with as few resource as possible (usually with some trade-off). 3. Finally, the execution plan (or result) can be dumped in another form of proto called RunMetadata, which can be used for profiling.

Another use of proto rewrite in TensorFlow is offline. The GraphDef proto goes through a series of pruning, rewrite, etc process. The end result is a different model representation that is better suited for inference on specific environment.

**Transpiler**
Transpiler is a type of compiler that takes the source code of a program written in one programming language as its input and produces the equivalent source code in another programming language. **A Transpiler translates between programming languages that operate at approximately the same level of abstraction**, while a traditional compiler translates from a higher level programming language to a lower level programming language.

**Traditional Compiler**
The name compiler is primarily used for programs that translate source code **from a high-level programming language to a lower level language** (e.g., assembly language, object code, or machine code) to create an executable program.

A compiler is likely to perform many or all of the following operations: preprocessing, lexical analysis, parsing, semantic analysis (syntax-directed translation), conversion of input programs to an intermediate representation, code optimization and code generation.

**Paddle**
Paddle performs rewrite of the program in several places. In DistributeTranspiler, the original program proto is rewritten to two different protos, one trainer proto to run on trainers, another ps proto to run on parameter servers. MemoryOptimizationTranspiler is doing some similar thing.

**In ideal situation, the rewrite logic only assumes the input as a pure data structure (abstraction), such as graph, tree, sequence of instructions, etc.** With only this assumption, the rewrite logic can be robust with respect to the change of model logic. 

Dependency Inversion
Model logic-->depends on-->Abstraction
Rewrite logic-->depends on-->Abstraction
Model logic-->doesn’t depend on-->Rewrite logic

However, **the current Paddle proto rewrite requires some model level logic, which results in some hard-coded things**. The result is that, these rewrite logics are not robust with respect to the other changes of the framework.

A short-term solution:
We abstract some the model logics. For example, in DistributeTranspiler, a set of ops are given a common abstraction called “optimization ops”. They are explicitly passed to DistributeTranspiler as arguments. In some sense, the rewrite logic no longer needs to understand whether the optimization ops are SGD or Adam. （hence only depend on abstraction).

Over the longer term, we should be more serious about these types of transpiler and avoid leaking model logic into the transpiler. To make it possible, **we should have a unified abstraction for the majority types of models we are going to support.** And the rewrite logic only depends on the unified abstraction.

**Comment by typhoonzero** [comment] 2018-04-11 09:12
Agree. Current DistributeTranspiler only works if the model is a "typical" deep learning network structure, other programs like distributed GAN is not supported.

Anyway, I was thinking about not to pass “optimization ops” to the transpiler, and let it find them automatically.

By the way, memory optimization is more like a "compiler-level optimization", and current SSA graph also uses this tech to "transpile" a program to run on multiple GPUs. Like gcc optimizations: in [here](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html), all operations trying to modify the program should be of this kind, we may need a way to organize them in the future.

**Comment by QiJune** [comment] 2018-04-11 11:28
- **Proto Rewriter**

The frontend of deep learning framework is usually Python. And nearly all deep learning frameworks will use serializable object such as protobuf/json to represent the neural network model generated by Python frontend. Tensorflow/caffe2/onnx/paddle use protobuf while Mxnet uses json.

We can do some optimizations at this level, and keep the input and output the same format.

Input protobuf ---> Optimization ---> Output protobuf

- **Transpiler** or **Compiler**

I think that transpiler and compiler are the same thing. The only diffierence is that in the code generation stage, transpiler may generate some high level code while compiler generates some low level code.

There are many optimizations we can do in transipler or compiler.

Input protobuf  ---> Optimization ---> Certain level code

The output can be CUDA code or LLVM IR or even assembly code.

- **Optimizations**

There are often two stages optimizations in deep learning framework.

In Tensorflow:
[Grappler](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/grappler/optimizers) is the first stage and [XLA ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler)is the second stage. 

In Mxnet:
[NNVM](https://github.com/dmlc/nnvm/tree/master/src/pass) can do some passes of optimization first and [TVM](https://github.com/dmlc/tvm) will do more fine-grained optimizations.

Optimizations in Grappler and NNVM are actually Proto Rewriter and XLA and TVM are actually Compiler or Transpiler.

**Comment by shanyi15** [comment] 2018-08-15 11:04
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:04 UTC
