### ISSUE TITLE
paddlepaddle是否支持类似于fm的组合特征变换

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#11758] opened 2018-06-27 03:16 UTC
最近准备在推荐系统中应用wide & deep模型，wide部分需要添加类似于fm的组合特征变换。
请问paddle现在有支持cross product的特征变换的layer吗？
我需要怎么实现呢？
我看官方的demo中 ，忽略了这部分

**Comment by jacquesqiao** [comment] 2018-06-28 05:14
我先看下然后给你回复~

**Comment by jacquesqiao** [comment] 2018-06-28 05:21
http://paddlepaddle.org/docs/develop/api/fluid/en/layers.html?highlight=cos_sim#cos-sim 看下这个 cos-sim

**Comment by jacquesqiao** [comment] 2018-06-28 05:38
另外请问你是在用v2还是用fluid版本？

**Comment by JayEworld** [comment] 2018-07-05 05:34
@jacquesqiao 我现在用的是v2版本

**Comment by shanyi15** [comment] 2018-08-15 10:20
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:20 UTC
Labels: User
