### ISSUE TITLE
Call pybind exposed "set_attr" failed: TypeError: set_attr(): incompatible function arguments. The following argument types are supported

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#6517] opened 2017-12-12 08:25 UTC
The code is:

```python
program.global_block().append_op(
...
attrs={
                "myprogram": str(someprogram.desc.serialize_to_string()),
}
)
```

Full error was:

```
Traceback (most recent call last):
  File "../python/paddle/v2/fluid/tests/book/test_recognize_digits_conv_dist.py", line 46, in <module>
    pserver_prog = exe.get_pserver_program(pserver_endpoint)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/executor.py", line 132, in get_pserver_program
    "GradList": [ p.name for p in self.param_grad_map[endpoint]["grads"]]
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/framework.py", line 424, in append_op
    op = Operator(self, op_desc, *args, **kwargs)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/framework.py", line 302, in __init__
    self.desc.set_attr(attr_name, attrs[attr_name])
TypeError: set_attr(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.v2.fluid.core.OpDesc, arg0: unicode, arg1: Variant) -> None

Invoked with: <paddle.v2.fluid.core.OpDesc object at 0x7f5263bcb6c0>, u'OptimizeProgram', '\n\r\x08\x00\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01'
```

**Comment by typhoonzero** [comment] 2017-12-15 05:44
Resolved by adding a single `set_serialize_attr` to accept `py:bytes` type resolves this problem.

**Comment by dzhwinter** [comment] 2017-12-15 06:13
Not agree with this solution. I still not understand why we need to set an attribute with `serialize program`. In the send op, can we just mark a program/block index, then the op will serialize it recursively?

**Comment by dzhwinter** [comment] 2017-12-15 06:15
An operator can receive an attribute of `set_serialize_attr` seems ugly,  can we figure out a more elegant way?

**Comment by typhoonzero** [comment] 2017-12-15 07:41
Yep, we need further discussion about this. One thing we must consider:

How to represent an operator can run a block internally. How to "recursively" represent a program?

If so, it seems that we should let `Operator` protobuf struct contain several blocks, e.g.

- if_else:
```
op:
  name: if_else
  inputs: ...
  outputs: ...
  attrs: ...
  blocks:
    block 0: condition
    block 1: true block
    block 2: else block
```

- while:
- recv:
```
op:
  name: recv
  ...
  blocks:
    block 0:
      op:
        name: while
        blocks:
          block 0: while condition (recved message)
          block 1: server side block
```

**Comment by shanyi15** [comment] 2018-08-15 11:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:11 UTC
