### ISSUE TITLE
test_recurrent_op failed

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6152] opened 2017-12-01 06:29 UTC
Please refer to the [log](https://paddleci.ngrok.io/viewLog.html?buildId=20035&buildTypeId=Paddle_PrCi&tab=buildLog)

```
[06:17:57] :	 [Step 1/1] F
[06:17:57] :	 [Step 1/1] ======================================================================
[06:17:57] :	 [Step 1/1] FAIL: test_backward (__main__.RecurrentOpTest2)
[06:17:57] :	 [Step 1/1] ----------------------------------------------------------------------
[06:17:57] :	 [Step 1/1] Traceback (most recent call last):
[06:17:57] :	 [Step 1/1]   File "test_recurrent_op.py", line 189, in test_backward
[06:17:57] :	 [Step 1/1]     num_grad[idx], ana_grad[idx], rtol=0.1).all())
[06:17:57] :	 [Step 1/1] AssertionError: False is not true
[06:17:57] :	 [Step 1/1] 
[06:17:57] :	 [Step 1/1] ----------------------------------------------------------------------
```

test_recurrent_op failed 3 times since yesterday, we should disable it temporarily.

**Comment by luotao1** [comment] 2017-12-01 06:47
Same error to me
```
[10:26:30] :	 [Step 1/1] test recurrent op forward
[10:26:30] :	 [Step 1/1] pd_output [-0.01419985]
[10:26:30] :	 [Step 1/1] 
[10:26:30] :	 [Step 1/1] py_output [-0.01419985]
[10:26:30] :	 [Step 1/1] .blocks {
[10:26:30] :	 [Step 1/1]   idx: 0
[10:26:30] :	 [Step 1/1]   parent_idx: -1
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "mean_1.tmp_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "x"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 2
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "static_rnn_1@memory_boot_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "static_rnn_1.tmp_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 2
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "_generated_var_1"
[10:26:30] :	 [Step 1/1]     type: STEP_SCOPES
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "Input"
[10:26:30] :	 [Step 1/1]       arguments: "x"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "Out"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1@memory_boot_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "fill_constant_batch_size_like"
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "value"
[10:26:30] :	 [Step 1/1]       type: FLOAT
[10:26:30] :	 [Step 1/1]       f: 0.0
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "dtype"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: 5
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "input_dim_idx"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: 1
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "shape"
[10:26:30] :	 [Step 1/1]       type: INTS
[10:26:30] :	 [Step 1/1]       ints: -1
[10:26:30] :	 [Step 1/1]       ints: 1
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "output_dim_idx"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: 0
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "initial_states"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1@memory_boot_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "inputs"
[10:26:30] :	 [Step 1/1]       arguments: "x"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "parameters"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "outputs"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "step_scopes"
[10:26:30] :	 [Step 1/1]       arguments: "_generated_var_1"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "recurrent"
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "is_train"
[10:26:30] :	 [Step 1/1]       type: BOOLEAN
[10:26:30] :	 [Step 1/1]       b: true
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "states"
[10:26:30] :	 [Step 1/1]       type: STRINGS
[10:26:30] :	 [Step 1/1]       strings: "static_rnn_1.tmp_1"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "step_block"
[10:26:30] :	 [Step 1/1]       type: BLOCK
[10:26:30] :	 [Step 1/1]       b: true
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "ex_states"
[10:26:30] :	 [Step 1/1]       type: STRINGS
[10:26:30] :	 [Step 1/1]       strings: "static_rnn_1@mem_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "reverse"
[10:26:30] :	 [Step 1/1]       type: BOOLEAN
[10:26:30] :	 [Step 1/1]       b: false
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "X"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "Out"
[10:26:30] :	 [Step 1/1]       arguments: "mean_1.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "mean"
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1] }
[10:26:30] :	 [Step 1/1] blocks {
[10:26:30] :	 [Step 1/1]   idx: 1
[10:26:30] :	 [Step 1/1]   parent_idx: 0
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "static_rnn_1.tmp_1"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]       lod_level: 0
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "x"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "elementwise_add_0.tmp_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]       lod_level: 0
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "static_rnn_1@mem_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   vars {
[10:26:30] :	 [Step 1/1]     name: "static_rnn_1.tmp_0"
[10:26:30] :	 [Step 1/1]     type: LOD_TENSOR
[10:26:30] :	 [Step 1/1]     lod_tensor {
[10:26:30] :	 [Step 1/1]       tensor {
[10:26:30] :	 [Step 1/1]         data_type: FP32
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]         dims: 1
[10:26:30] :	 [Step 1/1]       }
[10:26:30] :	 [Step 1/1]       lod_level: 0
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     persistable: false
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "X"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1@mem_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "Y"
[10:26:30] :	 [Step 1/1]       arguments: "x"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "Out"
[10:26:30] :	 [Step 1/1]       arguments: "elementwise_add_0.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "elementwise_add"
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "axis"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: -1
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "X"
[10:26:30] :	 [Step 1/1]       arguments: "elementwise_add_0.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "Out"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "rnn_memory_helper"
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "dtype"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: 5
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1]   ops {
[10:26:30] :	 [Step 1/1]     inputs {
[10:26:30] :	 [Step 1/1]       parameter: "X"
[10:26:30] :	 [Step 1/1]       arguments: "elementwise_add_0.tmp_0"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     outputs {
[10:26:30] :	 [Step 1/1]       parameter: "Out"
[10:26:30] :	 [Step 1/1]       arguments: "static_rnn_1.tmp_1"
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]     type: "rnn_memory_helper"
[10:26:30] :	 [Step 1/1]     attrs {
[10:26:30] :	 [Step 1/1]       name: "dtype"
[10:26:30] :	 [Step 1/1]       type: INT
[10:26:30] :	 [Step 1/1]       i: 5
[10:26:30] :	 [Step 1/1]     }
[10:26:30] :	 [Step 1/1]   }
[10:26:30] :	 [Step 1/1] }
[10:26:30] :	 [Step 1/1] 
[10:26:30] :	 [Step 1/1] test recurrent op forward
[10:26:30] :	 [Step 1/1] pd_output [ 1.5]
[10:26:30] :	 [Step 1/1] 
[10:26:30] :	 [Step 1/1] py_output [ 1.5]
[10:26:30] :	 [Step 1/1] .test recurrent op forward
[10:26:30] :	 [Step 1/1] pd_output [ 0.17529693]
[10:26:30] :	 [Step 1/1] 
[10:26:30] :	 [Step 1/1] py_output [ 0.17529693]
[10:26:30] :	 [Step 1/1] .test recurrent op forward
[10:26:30] :	 [Step 1/1] pd_output [ 0.68601424]
[10:26:30] :	 [Step 1/1] 
[10:26:30] :	 [Step 1/1] py_output [ 0.68601424]
[10:26:30] :	 [Step 1/1] F
[10:26:30] :	 [Step 1/1] ======================================================================
[10:26:30] :	 [Step 1/1] FAIL: test_backward (__main__.RecurrentOpTest2)
[10:26:30] :	 [Step 1/1] ----------------------------------------------------------------------
[10:26:30] :	 [Step 1/1] Traceback (most recent call last):
[10:26:30] :	 [Step 1/1]   File "test_recurrent_op.py", line 189, in test_backward
[10:26:30] :	 [Step 1/1]     num_grad[idx], ana_grad[idx], rtol=0.1).all())
[10:26:30] :	 [Step 1/1] AssertionError: False is not true
```

**Comment by shanyi15** [comment] 2018-08-15 11:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:11 UTC
