### ISSUE TITLE
Documentation on framework IR infrastructure

### ISSUE THREAD

**Issue by tpatejko** [PaddlePaddle/Paddle#13109] opened 2018-08-31 07:56 UTC
I'm looking at the framework IR and graph infrastructure. 

I would like to know how these passes are run. I can see that API for registering passes but I would like to know how to execute them.

**Comment by tpatejko** [comment] 2018-08-31 12:25
One more question: what's the difference between graph infrastructure in `fluid/framework/ir` and `fluid/inference/analysis`?

**Comment by panyx0718** [comment] 2018-09-01 13:16
Here is the design
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/ir/overview.md

You should only write pass using framework/ir
inference/analysis are inference-specific and no new passes should be added.

Here is an example of applying passes for training
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/parallel_executor.cc#L38

@Superjomn 
Can you provide example of applying passes for inference?

**Comment by Superjomn** [comment] 2018-09-01 14:29
Yes, I will write an doc about these topics.

**Comment by tpatejko** [comment] 2018-09-03 06:33
@panyx0718 @Superjomn Thanks for the information. 

I think right now we are interested in passes for inference. Does that mean that the better choice is to use `inference/analysis` graph infrastructure?

**Comment by luotao1** [comment] 2018-09-04 03:23
@tpatejko You can see #13197  at first.

**Comment by tpatejko** [comment] 2018-09-04 08:16
@luotao1 @Superjomn Thank you for the document.

I'm trying to use the `fc_fuse_pass` in executor:
https://github.com/tpatejko/Paddle/blob/2d5deb90190210166fb276440407c9873796d0f3/paddle/fluid/framework/executor.cc#L36-L44

I also used `USE_PASS` macro to add the pass:
https://github.com/tpatejko/Paddle/blob/2d5deb90190210166fb276440407c9873796d0f3/paddle/fluid/framework/executor.cc#L437

But I'm getting the following error when I try to run inference script in Python:
```
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
/home/tpatejko/.local/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: _Z31TouchPassRegistrar_fc_fuse_passv
```

Do you know what seems to be the issue?

**Comment by luotao1** [comment] 2018-09-04 08:25
@tpatejko #13133 update the static and shared library to support analysis and IR, you can merge with the latest code.

Besides, you can `#include "paddle/fluid/inference/api/paddle_inference_pass.h"` instead of `USE_PASS(XXX)`

But why you add `USE_PASS` in executor?

**Comment by tpatejko** [comment] 2018-09-04 09:24
@luotao1 I'm trying to run an existing pass to check how it works. What is your suggestion regarding correct pass execution?

**Comment by tpatejko** [comment] 2018-09-04 09:36
@luotao1 I rebased to the newest `develop` branch and modified executor according to your suggestions:

https://github.com/PaddlePaddle/Paddle/compare/develop...tpatejko:tpatejko/use-fc-fuse-pass

But I'm still getting:
```
/home/tpatejko/.local/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: _Z43TouchPassRegistrar_attention_lstm_fuse_passv
```

when I try to use `fc_fuse_pass`.

**Comment by luotao1** [comment] 2018-09-04 09:40
`USE_PASS` is not used in python related code.
You can run `ctest -R test_analyzer -V` to see it. https://github.com/PaddlePaddle/Paddle/blob/90b5be85cfd7423ca584dab2daea39e2d6aa15e2/paddle/fluid/inference/analysis/analyzer_tester.cc#L281-L285
compared with `base_predictor`, `predictor` use the pass.

**Comment by tpatejko** [comment] 2018-09-04 09:57
@luotao1 Thank you for your reply.

So how can I trigger C++ fusion passes when I run inference script implemented in Python?

**Comment by tpatejko** [comment] 2018-09-04 10:26
@luotao1 Thank you for your reply.

So how can I trigger C++ pass when I run python inference script? Are you suggesting using Predictors for that?

My idea would be to modify executor.cc and execute fusion passes there. Executor seems to be the only place where one can have access to an instance of `ProgramDesc` inference program.

However, for example `AnalysisPredictor` creates new instance of executor so it creates dependency: executor creates an instance of `AnalysisPredictor` that creates an instance of a new executor.

PS. I haven't had problem executing `graph_viz_pass`. Do you know what's the difference between `graph_viz_pass` and fusion passes?

**Comment by Superjomn** [comment] 2018-09-04 10:52
No, currently, the IR is not directly support python, just as the underlying framework.

I am working on a PR that has some support of controlling which pass to run. 

https://github.com/PaddlePaddle/Paddle/pull/13081/files#diff-2cf901e4cc3d122458722bef9dadf8faR154

For c++ inference application, the `AnalysisPredictor` is the only interface, and the C++ inference currently has no interface for python.

**Comment by tpatejko** [comment] 2018-09-04 11:38
@Superjomn Thanks for the information

At the moment, we don't want to call C++ inference passes directly from the Python code. What I wanted to do is to call `framework/ir` passes from within C++ code, from `Executor` in `executor.cc`, and an instance of the modified executor was created in the `infer.py` script through (pybind bindings).

However, when I try to run the script I get an undefined symbol error:
```
/home/tpatejko/.local/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: _Z43TouchPassRegistrar_attention_lstm_fuse_passv
```

That's a bit odd, because I managed to run `graph_viz_pass` that same way.

**Comment by Superjomn** [comment] 2018-09-04 14:17
The `graph_vis_pass` is used to visualize the SSA graph of the IR, while the `xxx_fuse_pass` is used to modify the IR graph to fuse some operators. 

Currently, all the `xxx_fuse_pass` are only used in inference, and the `AnalysisPredictor` calls these passes before the executor run.

If you want to optimize inference, you might need to write some C++ inference program using `AnalysisPredictor`.

**Comment by tpatejko** [comment] 2018-09-04 15:37
@Superjomn Thanks a lot for your explanation.

I wasn't fully aware of relation between inference engine and CAPI. I thought that inference engine and pass infrastructure could be used along with Python inference scripts, but it doesn't seem to be the case now, as CAPI is becoming a primary inferface for inference.

**Comment by lucywsq** [comment] 2018-09-20 17:03
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-09-20 17:03 UTC
Labels: Intel
