### ISSUE TITLE
Issue with commit https://github.com/PaddlePaddle/Paddle/commit/a76f7ed2eb02c9beb5e7b16ff7fede0f13477df8

### ISSUE THREAD

**Issue by juliecbd** [PaddlePaddle/Paddle#2908] opened 2017-07-16 21:57 UTC
Commit 
https://github.com/PaddlePaddle/Paddle/commit/a76f7ed2eb02c9beb5e7b16ff7fede0f13477df8#diff-01b00d8ba23682056ecc4e623b040a54

conflicts 

Removing         import py_paddle.swig_paddle as swig_api from the first line confilicts with line 38: 
tmp = swig_api.ParameterOptimizer.create(self.__opt_conf__)

===========
This is the error

python2.7/site-packages/paddle/v2/optimizer.py", line 38, in enable_types
    tmp = swig_api.ParameterOptimizer.create(self.__opt_conf__)
NameError: global name 'swig_api' is not defined

**Comment by livc** [comment] 2017-07-17 04:19
I got this error, too. 
Should we restore the first line `import py_paddle.swig_paddle as swig_api `? @reyoung

**Comment by lcy-seso** [comment] 2017-07-17 04:36
I got this error, too.

**Comment by lcy-seso** [comment] 2017-07-17 05:06
- I think the problem is imported names are bound to the current scope, so an import inside a `__init__()` function binds to a local name only.
- Maybe one solution is importing the module again. The cost is inexpensive because module imports are cached globally in sys.modules.
- I found this bug has been fixed by this PR https://github.com/PaddlePaddle/Paddle/pull/2907.

**Comment by lcy-seso** [comment] 2017-07-17 05:25
I found this bug has been fixed by this PR https://github.com/PaddlePaddle/Paddle/pull/2907, so I close this issue. If there is any other problem, please feel free to reopen it.

**Closed** 2017-07-17 05:25 UTC
