### ISSUE TITLE
PaddlePaddle.org updates

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/Paddle#9887] opened 2018-04-12 20:40 UTC
PaddlePaddle.org has several developer experience issues that we wish to fix in a complete overhaul of the website. I invite your views and comments on these issues created inside PaddlePaddle.org's repo. It is important that we hear from all contributors, and not just the maintainers of the website.

[Release-first](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/455)
 
[Navigation to target users, not Paddle developers](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/456)
 
[Function-driven tutorials](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/457)
 
[Content marketing through blog – well managed](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/458)
 
[Add commenting on “Book” and “Blog”](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/459)
 
[Acknowledge choice making through comparison pages to TF, PyTorch, mxnet](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/460)
 
[Bake in suggested use of Visual DL as a support tool](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/461)
 
[SEO](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/462)

**Comment by abhinavarora** [comment] 2018-04-17 17:54
@varunarora Do you think we should make a project and enlist more granular tasks?

**Comment by shanyi15** [comment] 2018-08-15 11:36
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
Labels: Website, 文档
