### ISSUE TITLE
Some result of cudnn operation is non-deterministic.

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#10266] opened 2018-04-27 08:58 UTC
To make computation faster, cudnn provides many algorithms for one operation, such as conv2d, but the result that provided by some of that algorithm is non-deterministic. More specific, 

```c++
typedef enum
{
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0         = 0,  // non-deterministic
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1         = 1,
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT       = 2,
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3         = 3,  // non-deterministic, algo0 with workspace
    // CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD  = 4, // not implemented
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD_NONFUSED = 5
} cudnnConvolutionBwdFilterAlgo_t;
```

Paddle uses [`cudnnGetConvolutionBackwardDataAlgorithm`](https://github.com/PaddlePaddle/Paddle/blob/d904b3dd1d40d03d22f17d9c49926d52f1fe86e6/paddle/fluid/operators/conv_cudnn_op.cu.cc#L271) to automatically choose which algorithm to use, based on data size, memory limits etc..

As so far, I have found  maxPool and conv2d are non-deterministic.

So if someone does the benchmark, please pay attention to those.

**Comment by shanyi15** [comment] 2018-08-15 10:27
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:28 UTC
