### ISSUE TITLE
step_gru可以输出固定步数么？

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#10431] opened 2018-05-05 13:35 UTC
如题，我做时间序列预测，需要step_gru每次都输出60步，请问该如何设置？

**Comment by Superjomn** [comment] 2018-05-06 08:06
可以直接 slice 前面60步

**Comment by hyo009** [comment] 2018-05-06 08:12
用proj = slice_projection(input=step_gru_output, slices=[(0, 60)])么？

**Comment by Superjomn** [comment] 2018-05-06 08:13
不确定这样可以。 但结果出来后用python slice下应该是可以的

**Comment by shanyi15** [comment] 2018-08-15 11:35
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
