### ISSUE TITLE
ParallelExecutor error : incompatible constructor arguments.

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14843] opened 2018-12-11 05:42 UTC
Hi everyone, I am trying to train model with distributed nccl2 mode. I am following the code of https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification/dist_train 
But when I am trying to create a ParallelExecutor I got following error:
``` 
 File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 166, in __init__
    build_strategy, num_trainers, trainer_id)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. paddle.fluid.core.ParallelExecutor(arg0: List[paddle.fluid.core.Place], arg1: Set[unicode], arg2: Set[unicode], arg3: paddle.fluid.core.ProgramDesc, arg4: unicode, arg5: paddle.fluid.core.Scope, arg6: List[paddle.fluid.core.Scope], arg7: paddle.fluid.core.ExecutionStrategy, arg8: paddle.fluid.core.BuildStrategy, arg9: int, arg10: int)

Invoked with: [<paddle.fluid.core.Place object at 0x7f1e62872f90>], set([u'fc1_shared_b', u'fc1_shared_w', u'fc2_shared_b', u'fc2_shared_w']), set([u'velocity_2', u'fc2_shared_b', u'fc1_shared_b', u'fc2_shared_w', u'@LR_DECAY_COUNTER@', u'fc1_shared_w', u'velocity_3', u'velocity_0', u'velocity_1']), <paddle.fluid.core.ProgramDesc object at 0x7f1e6283a810>, u'mean_0.tmp_0', <paddle.fluid.core.Scope object at 0x7f1e779e5570>, [], <paddle.fluid.core.ExecutionStrategy object at 0x7f1e62872c00>, <paddle.fluid.core.BuildStrategy object at 0x7f1e62872d20>, '2', '0'
```

I found that every argument feed into core.ParallelExecutor conformed to the argument type but still got such error.

**Comment by typhoonzero** [comment] 2018-12-11 08:51
The argument `num_trainers` and `trainer_id` should be of type int. If you are getting this from environment variables please do `int(os.getenv("XXX")`

**Comment by typhoonzero** [comment] 2018-12-11 08:53
Will try refine this error log in python side.

**Comment by TheodoreG** [comment] 2018-12-11 09:01
Thank you,  after I set num_trainers and trainer_id to int, it works.

**Comment by lucywsq** [comment] 2018-12-20 13:16
Since this issue has been solved , we will close it today for the sake of other user’s experience.
 If you still need to follow up on this question after closing, please feel free to reopen it.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed** 2020-05-22 10:16 UTC
