### ISSUE TITLE
Accuracy drop on INT8 Ernie QAT inference

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#24052] opened 2020-04-21 13:05 UTC
The commit https://github.com/PaddlePaddle/Paddle/commit/b89dd86fb65fc9095219aa4d37ad52728b8f689a introduced accuracy drop from 0.7936 to 0.7916 for INT8 Ernie QAT inference test (using the `qat2_int8_nlp_comparison.py` script) on a 6248 CLX machine. In our internal tests the commit makes the FP32-INT8 accuracy diff (0.8020 - 0.7916 = 0.0104) greater than > 0.01 and the test is failing.
What is your recommendation?

**Comment by luotao1** [comment] 2020-04-21 13:49
Could you help us find which Op accuracy diff? In this commit, we remain the same fp64 implementation of softmax op.

**Comment by lidanqing-vv** [comment] 2020-05-26 10:16
Machine: `Model name:            Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz`
Linux OS: 
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
```

commit `0be4b04d1370b5c1e438d2ef04d32559e1180c07`
```
2020-05-26 13:31:43,525-INFO: Total inference run time: 22.75 s
2020-05-26 13:31:43,558-INFO: INT8: avg accuracy: 0.796386
2020-05-26 13:31:43,558-INFO: --- Performance summary ---
2020-05-26 13:31:43,558-INFO: FP32: avg predictions per sec: 19.46, avg latency: 55.8963 ms
2020-05-26 13:31:43,558-INFO: INT8: avg predictions per sec: 128.25, avg latency: 8.8917 ms
2020-05-26 13:31:43,558-INFO: --- Accuracy summary ---
2020-05-26 13:31:43,558-INFO: Accepted accuracy drop threshold: 0.01. (condition: (FP32_acc - INT8_acc) <= threshold)
2020-05-26 13:31:43,558-INFO: FP32: avg accuracy: 0.802008
2020-05-26 13:31:43,558-INFO: INT8: avg accuracy: 0.796386
```


commit `b89dd86fb65fc9095219aa4d37ad52728b8f689a` (which is the commit mentioned)
```
2020-05-26 10:14:33,977-INFO: Total inference run time: 22.77 s
2020-05-26 10:14:34,010-INFO: INT8: avg accuracy: 0.796386
2020-05-26 10:14:34,010-INFO: --- Performance summary ---
2020-05-26 10:14:34,010-INFO: FP32: avg predictions per sec: 18.53, avg latency: 60.5278 ms
2020-05-26 10:14:34,011-INFO: INT8: avg predictions per sec: 127.71, avg latency: 8.8990 ms
2020-05-26 10:14:34,011-INFO: --- Accuracy summary ---
2020-05-26 10:14:34,011-INFO: Accepted accuracy drop threshold: 0.01. (condition: (FP32_acc - INT8_acc) <= threshold)
2020-05-26 10:14:34,011-INFO: FP32: avg accuracy: 0.802008
2020-05-26 10:14:34,011-INFO: INT8: avg accuracy: 0.796386
```

**Comment by lidanqing-vv** [comment] 2020-05-26 11:08
commit `56a714a19b88a9cd544e9c006c3e2132ea4e2b94` newest develop
```
2020-05-26 11:07:31,136-INFO: Total inference run time: 21.11 s
2020-05-26 11:07:31,172-INFO: INT8: avg accuracy: 0.794378
2020-05-26 11:07:31,172-INFO: --- Performance summary ---
2020-05-26 11:07:31,172-INFO: FP32: avg predictions per sec: 13.22, avg latency: 79.2025 ms
2020-05-26 11:07:31,173-INFO: INT8: avg predictions per sec: 151.15, avg latency: 8.2503 ms
2020-05-26 11:07:31,173-INFO: --- Accuracy summary ---
2020-05-26 11:07:31,173-INFO: Accepted accuracy drop threshold: 0.01. (condition: (FP32_acc - INT8_acc) <= threshold)
2020-05-26 11:07:31,173-INFO: FP32: avg accuracy: 0.802008
2020-05-26 11:07:31,173-INFO: INT8: avg accuracy: 0.794378
```

**Comment by lidanqing-vv** [comment] 2020-05-26 13:26
@ddokupil Hi, could you please help clarify what is the environment settings that have this error? I use 6248 but can not produce this accuracy drop. Thanks.

**Comment by lidanqing-vv** [comment] 2020-05-28 11:07
The cause of this issue is because daily benchmark script lack ops_to_quantize. I have aligned with @pmajchrzak  and now we have same script and results now.
So I close this issue

**Closed as completed by lidanqing-vv** 2020-05-28 11:07 UTC
Labels: Intel, int8
