### ISSUE TITLE
the double-buffer is starting

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#11630] opened 2018-06-21 07:42 UTC
I0621 12:50:18.562585 26082 TrainerInternal.cpp:162]  Batch=100 samples=24000 AvgCost=38.2618 CurrentCost=38.2618 Eval: classification_error=0.00567624  CurrentEval: classification_error=0.00567624 
I0621 13:14:17.388411 26082 Tester.cpp:111]  Test samples=14710 cost=5.41958 Eval: classification_error=0.000495873 
I0621 13:14:17.388619 26082 GradientMachine.cpp:112] Saving parameters to ./output/pass-00000-001
I0621 13:14:17.652643 26082 Util.cpp:213] copy conf/trainer_config.conf to ./output/pass-00000-001
I0621 13:45:23.430790 26082 TrainerInternal.cpp:179]  Pass=0 Batch=184 samples=44147 AvgCost=23.6796 Eval: classification_error=0.00331345 
I0621 14:08:50.739266 26082 Tester.cpp:111]  Test samples=14710 cost=4.50248 Eval: classification_error=0.000443509 
I0621 14:08:50.739598 26082 GradientMachine.cpp:112] Saving parameters to ./output/pass-00000
I0621 14:08:51.001824 26082 Util.cpp:213] copy conf/trainer_config.conf to ./output/pass-00000
I0621 14:08:51.002318 26082 DataProvider.h:328] the double-buffer is starting ...

集群训练过程中，然后就一直都没有动了，是啥原因？

**Comment by jacquesqiao** [comment] 2018-06-21 08:59
我在现在的代码里面没找到这个日志，这个是什么版本呀

**Comment by shanyi15** [comment] 2018-08-15 10:20
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:20 UTC
Labels: User
