### ISSUE TITLE
热启动word embedding的示例

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Paddle#8053] opened 2018-02-01 15:25 UTC
假设想做下面链接里的文本分类问题，word embedding是提前训练好的，如何热启动Fluid中的embedding参数。
https://github.com/PaddlePaddle/Paddle/wiki/Text-Classification-With-CNN-model

**Comment by gmcather** [comment] 2018-03-12 08:04
从mt任务中，发现word_emb的参数可以设成trainable=False
```python
src_pos_enc = layers.embedding(src_pos, size=[src_max_len, src_emb_dim], padding_idx=pos_pad_idx, param_attr=fluid.ParamAttr(name=pos_enc_param_name, trainable=False))
```

**Comment by gmcather** [comment] 2018-03-15 02:38
From the interface of layers.embeding, we can customize the Param_attr to import our pretrained embeding parameters. https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L184, 
```python
def embedding(input,
              size,
              is_sparse=False,
              padding_idx=None,
              param_attr=None, 
              dtype='float32'):
```

But the problem is how to customize our personal parameter, as I only found the commonly used parameters, such as Xavier, Uniform... in https://github.com/PaddlePaddle/Paddle/blob/d3fbede92dbaf85bc5094335cd1cf70ce6ec8ffb/python/paddle/fluid/initializer.py

**Comment by cheradam** [comment] 2018-03-28 01:25
At the issue-triage meeting，marked this issue as low priority。

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC

**Comment by mapingshuo** [comment] 2018-09-11 10:38
Hi，我遇到了类似的问题，在目前的fluid(我的版本0.14.0)中，可以参考下面的解决方案：https://github.com/PaddlePaddle/models/blob/d51ebfee8bf44e9ada2ba9a57434628485971ca1/fluid/sequence_tagging_for_ner/train.py#L107
