### ISSUE TITLE
Incorrect handling of bias_attr for fc and other layers

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#8419] opened 2018-02-13 00:18 UTC
According to the comment of nn.fc, if bias_attr is None, which is the default, there will be no bias for the layer.
https://github.com/PaddlePaddle/Paddle/blob/f82fa64a06f71700a99b641aeb8fc9ef16c0d940/python/paddle/v2/fluid/layers/nn.py#L135-L137

However, bias is still added to the computation even it is not set. This is caused by a bug of LayerHelper.append_bias_op(). It checks for whether bias_attr is defined at the following line:
https://github.com/PaddlePaddle/Paddle/blob/f82fa64a06f71700a99b641aeb8fc9ef16c0d940/python/paddle/v2/fluid/layer_helper.py#L357-L358
 However, bias_attr is always defined because the property access function:
https://github.com/PaddlePaddle/Paddle/blob/f82fa64a06f71700a99b641aeb8fc9ef16c0d940/python/paddle/v2/fluid/layer_helper.py#L72-L74

So there is no way not to use bias for fc layer (and other layers using same mechanism). It's easy to fix it. However, there are tuned models implicitly depending on the unexpected bug. If we fix this, we need to re-check the training of existing trained models.

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC
Labels: Bug
