### ISSUE TITLE
SSD 模型在用 CPU 训练自有训练集时候报Value shape mismatch错误。

### ISSUE THREAD

**Issue by HUSTGOC** [PaddlePaddle/Paddle#9948] opened 2018-04-16 09:16 UTC
![image](https://user-images.githubusercontent.com/13493253/38800426-d3ab981e-4199-11e8-81f0-8b1806a4457b.png)

求助！

**Comment by pkuyym** [comment] 2018-04-16 09:26
请参照这个issue https://github.com/PaddlePaddle/Paddle/issues/8530

**Comment by HUSTGOC** [comment] 2018-04-16 10:17
![image](https://user-images.githubusercontent.com/13493253/38803632-65a92eea-41a2-11e8-8625-07517b5c0f4e.png)
这句话真bu不懂

**Comment by yeyupiaoling** [comment] 2018-04-16 15:20
@HUSTGOC 
这个模型不是支持CPU吧？

>这句话真bu不懂
上那个问题是要使用已经训练过的模型来初始化模型的，

**Comment by shanyi15** [comment] 2018-08-15 11:36
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
Labels: User
