### ISSUE TITLE
Train and predict on cifar10 using vgg net.

### ISSUE THREAD

**Issue by gx-wind** [PaddlePaddle/Paddle#7787] opened 2018-01-23 09:03 UTC
Predict  the same output, no matter what input is?
```python
import numpy as np
import paddle.v2 as paddle
import paddle.v2.fluid as fluid

import sys

def vgg16_bn_drop(input):
    def conv_block(input, num_filter, groups, dropouts):
        return fluid.nets.img_conv_group(
            input=input,
            pool_size=2,
            pool_stride=2,
            conv_num_filter=[num_filter] * groups,
            conv_filter_size=3,
            conv_act='relu',
            conv_with_batchnorm=True,
            conv_batchnorm_drop_rate=dropouts,
            pool_type='max')

    conv1 = conv_block(input, 64, 2, [0.3, 0])
    conv2 = conv_block(conv1, 128, 2, [0.4, 0])
    conv3 = conv_block(conv2, 256, 3, [0.4, 0.4, 0])
    conv4 = conv_block(conv3, 512, 3, [0.4, 0.4, 0])
    conv5 = conv_block(conv4, 512, 3, [0.4, 0.4, 0])
    
    drop = fluid.layers.dropout(x=conv5, dropout_prob=0.5)
    fc1 = fluid.layers.fc(input=drop, size=512, act=None)
    bn = fluid.layers.batch_norm(input=fc1, act='relu')
    drop2 = fluid.layers.dropout(x=bn, dropout_prob=0.5)
    fc2 = fluid.layers.fc(input=drop2, size=512, act=None)
    return fc2

classdim = 10
data_shape = [3, 32, 32]

images = fluid.layers.data(name='pixel', shape=data_shape, dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')

print("train vgg net")
net = vgg16_bn_drop(images)

predicts = fluid.layers.fc(input=net, size=classdim, act='softmax')
cost = fluid.layers.cross_entropy(input=predicts, label=label)
avg_cost = fluid.layers.mean(x=cost)

optimizer = fluid.optimizer.Adam(learning_rate=0.001)
opts = optimizer.minimize(avg_cost)

accuracy = fluid.evaluator.Accuracy(input=predicts, label=label)

BATCH_SIZE = 128
PASS_NUM = 50

train_reader = paddle.batch(
    paddle.reader.shuffle(
        paddle.dataset.cifar.train10(), buf_size=128 * 10),
    batch_size=BATCH_SIZE)

# cpu train
#place = fluid.CPUPlace()

# gpu train
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
feeder = fluid.DataFeeder(place=place, feed_list=['pixel', 'label'])
exe.run(fluid.default_startup_program())

done = False
for pass_id in range(PASS_NUM):
    accuracy.reset(exe)
    for data in train_reader():
        loss, acc = exe.run(fluid.default_main_program(),
                            feed=feeder.feed(data),
                            fetch_list=[avg_cost] + accuracy.metrics)
        pass_acc = accuracy.eval(exe)
        print("pass_id=" + str(pass_id) + " loss:" + str(loss) + " acc:" + str(acc) + " pass_acc:" + str(
            pass_acc))
        #if pass_acc > 0.92:
        if pass_acc > 0.8:
            #fluid.io.save_persistables(exe, dirname="./cifar10", main_program=fluid.default_main_program())
            #fluid.io.save_params(exe, dirname="./cifar10_params", main_program=fluid.default_main_program())
            done = True
            print("train model done")
            break
            exit(0)
    if done:
        break

# then predict
new_program = fluid.default_main_program().prune(targets=predicts)
test_reader = paddle.batch(
    paddle.reader.shuffle(
        paddle.dataset.cifar.test10(), buf_size=500),
    batch_size=1)
feeder = fluid.DataFeeder(feed_list=['pixel'], place=place, program=new_program)

# test predict
for data in test_reader():
    out = exe.run(new_program,
        feed=feeder.feed([(data[0][0],)]),
        fetch_list=[predicts]
    )
    print(out)
```

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
