### ISSUE TITLE
Too lengthy implementation of TensorContainsNan and TensorContainsINF

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11949] opened 2018-07-03 23:52 UTC
The implementation contains three parts:

1.  VisitPlace (35 lines)
   https://github.com/PaddlePaddle/Paddle/blob/037ce12ee4f3167fc31f2fdd21e5390b42c806b8/paddle/fluid/platform/place.h#L97-L132
   
1. The CPU implementation of TensorContainsNaN (~100 lines)

   https://github.com/PaddlePaddle/Paddle/blob/7b54f16855ca3aaef6ff1cdb9bf7a4d4f1d8b6c1/paddle/fluid/framework/tensor_util.cc#L139-L241

1. The CUDA implementation (~100 lines)

https://github.com/PaddlePaddle/Paddle/blob/8370fa82789bc4f05a3239700681818b0ff224ae/paddle/fluid/framework/tensor_util.cu#L19-L117

There uses about 235 lines of C++ code to test if a tensor contains NaN or INF!

**Comment by lucywsq** [comment] 2018-08-28 02:28
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-08-28 02:28 UTC
Labels: Code Cleanup
