### ISSUE TITLE
Any documents to describe the the difference between PaddlePaddle definitions of operator and conventional definitions?

### ISSUE THREAD

**Issue by zhangyang0701** [PaddlePaddle/Paddle#12345] opened 2018-07-24 14:38 UTC
I noticed in the PaddlePaddle model (parsed from the binary model), the combination of conv + elementwise_add is equivalent to conventional convolution layer, and it seems a BN is equivalent to conventional combination of BN + scale.

Do we have a systematic description of the new definitions introduced by PaddlePaddle?

**Comment by lucywsq** [comment] 2018-10-26 03:59
Thanks for your suggestion  and we would concentrate on that. 
As this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 03:59 UTC

**Comment by shanyi15** [comment] 2018-10-26 06:06
http://paddlepaddle.org/documentation/docs/zh/1.0/beginners_guide/programming_guide/programming_guide.html
http://paddlepaddle.org/documentation/docs/zh/1.0/user_guides/design_idea/fluid_design_idea.html
hi，您看这两篇文档是否能帮到您呢？
