### ISSUE TITLE
paddle init 初始化 出错  use_gpu=True

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#8008] opened 2018-01-31 10:07 UTC
```

    import paddle.v2 as paddlev2

    paddlev2.init(use_gpu=True, trainer_count=1)
```

nvcc -V
Cuda compilation tools, release 8.0, V8.0.44
cudnn
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

0131 18:03:28.954254 23361 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1

You are running using the stub version of libcublas
F0131 18:03:29.371341 23361 hl_cuda_cublas.cc:137] Check failed: CUBLAS_STATUS_SUCCESS == g_cublasStat (0 vs. 54) Cublas Error: [cublas status]: unknown error [cublas init] Cublas create handle faild!
*** Check failure stack trace: ***
    @     0x7f1b6c4f4bcd  google::LogMessage::Fail()
    @     0x7f1b6c4f867c  google::LogMessage::SendToLog()
    @     0x7f1b6c4f46f3  google::LogMessage::Flush()
    @     0x7f1b6c4f9b8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1b6c4a57db  hl_cublas_init()
    @     0x7f1b6c4afbf0  hl_create_global_resources()
    @     0x7f1b6c4b0439  hl_specify_devices_start()
    @     0x7f1b6c4b085d  hl_start()
    @     0x7f1b6c43a55a  paddle::initMain()
    @     0x7f1b6c4dc5d1  initPaddle()
    @     0x7f1b6c083c29  _wrap_initPaddle
    @     0x7f1bc2c6d79f  PyEval_EvalFrameEx
    @     0x7f1bc2c710bd  PyEval_EvalCodeEx
    @     0x7f1bc2c6e345  PyEval_EvalFrameEx
    @     0x7f1bc2c710bd  PyEval_EvalCodeEx
    @     0x7f1bc2be7eb0  function_call
    @     0x7f1bc2bb5df3  PyObject_Call
    @     0x7f1bc2c6af97  PyEval_EvalFrameEx
    @     0x7f1bc2c710bd  PyEval_EvalCodeEx
    @     0x7f1bc2c6e345  PyEval_EvalFrameEx
    @     0x7f1bc2c710bd  PyEval_EvalCodeEx
    @     0x7f1bc2c711f2  PyEval_EvalCode
    @     0x7f1bc2c99f42  PyRun_FileExFlags
    @     0x7f1bc2c9b2d9  PyRun_SimpleFileExFlags
    @     0x7f1bc2cb100d  Py_Main
    @     0x7f1bc1eaebd5  __libc_start_main
    @           0x4007a1  (unknown)
    @              (nil)  (unknown)
.Aborted

**Comment by guoshengCS** [comment] 2018-02-01 08:16
请确认安装的Paddle包的版本是对应cuda和cudnn版本的

**Comment by liuhuiCNN** [comment] 2018-02-01 09:18
@guoshengCS 请问 pip install paddlepaddle-gpu使用的是那个版本的cuda和cudnn？
根据这个文档
http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/pip_install_cn.html
对应的版本是
cuda7.5_cudnn5_avx_openblas
我们使用了cuda7.5和cudnn5，但是问题依然存在。

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC
