### ISSUE TITLE
train interface in Paddle V2 API does not print average cost on the training set.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2974] opened 2017-07-20 00:46 UTC
Below is the training log generated by paddle v2 API:
```text
[INFO 2017-07-20 08:13:54,714 train.py:70] Pass 133, Batch 650, Cost 35.525531, {'classification_error_evaluator': 0.7351384162902832}
[INFO 2017-07-20 08:13:59,905 train.py:70] Pass 133, Batch 655, Cost 35.517285, {'classification_error_evaluator': 0.7425796985626221}
[INFO 2017-07-20 08:14:05,056 train.py:70] Pass 133, Batch 660, Cost 35.666832, {'classification_error_evaluator': 0.7405670285224915}
```

* The `train` interface only prints cost and evaluating result on current training batch, but no information is provided on average costs and evaluations up to now. 
* This is convenient for plotting the learning curve but is not convenient for model selection.
* Previously PaddlePaddle does provide both average costs and costs over current training batch.
* Though users can calculate the average training cost themselves, this is a very basic metric used in machine learning task. I think PaddlePaddle should implement it instead of leaving it to the users.

**Comment by shanyi15** [comment] 2018-08-15 11:14
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:14 UTC
Labels: enhancement
