### ISSUE TITLE
Any plans for online model serving?

### ISSUE THREAD

**Issue by yingfeng** [PaddlePaddle/Paddle#13395] opened 2018-09-14 06:36 UTC
Model serving has been provided according to some issues such as [this one](https://github.com/PaddlePaddle/Paddle/issues/4326), however, it's a naive solution for traditional deep learning, which means after the model have been finished training, it will be delivered to a dedicate server for prediction. 

However, one important feature for Paddle is sparse learning for advertising and recommendation, in these cases, the model might be huge that [distributed lookup table is inevitable](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/dist_train/distributed_lookup_table_design.md) ,additionally, the model is kept updating continuously, it means the parameters and weights should be replicated to the prediction server all the way. Does there exist any plan for such kinds of situation to support online prediction for business?

**Comment by velconia** [comment] 2018-09-17 07:20
>  to support online prediction for business 

Do you mean online training or something? Distributed Lookup table is designed for the huge embedding table, and the online training should be concat with the streaming data provider such as Spark

**Comment by yingfeng** [comment] 2018-09-17 07:47
No, I meant online serving. It's something like the diagram below:

![ps](https://user-images.githubusercontent.com/7248/45610953-5772d300-ba90-11e8-805c-942173f4b705.png)

The parameters from PS(distributed lookup table in Paddle) are replicated to the model server for online prediction.  Because the model is trained continuously, there exist a requirement for data pipeline to dump the parameters to the model server continuously, additionally, the model size is huge and therefore model partition is inevitable.

**Comment by velconia** [comment] 2018-09-17 12:27
Sry, but we do not support this kind of training mode now, maybe @jacquesqiao will know more about this.

And @yingfeng would you like to let us know why you need this? we will be appreciate to develop this feature if this is import for you and could benefits all the users.

**Comment by yingfeng** [comment] 2018-09-18 00:35
I think it's a typical context for both online advertising and recommendation, where the models are required to be updated continuously.

**Comment by lucywsq** [comment] 2018-10-26 06:51
Hello, this issue has not been updated in the past month. We will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours.
We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-26 06:51 UTC
Labels: User

**Comment by jackyhawk** [comment] 2018-12-11 04:22
where can i find the docs about paddple servering (and the model transfered from training machine to product machine?), thanks very much  @jacquesqiao
