### ISSUE TITLE
Basic Operators for Dynamic RNN with Executor

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#5288] opened 2017-11-01 21:49 UTC
```
1. RankSortLoDOp
      inputs: X
      outputs:  Out   Nx3 Matrix, int64_t   CPU
                MaxSeqLen   1x1 Tensor int64_t  GPU 
      attrs:  lod_level [default: 1 ]

2. ToArray:  -->  std::vector<LoDTensor>
      inputs:  X
               RankSortTable
      outputs:
               Out  --> std::vector<LoDTensor>
3. ToLoDTensor
      inputs: X --> std::vector<LoDTensor>  
              RankSortTable
      outputs:
            Out --> LoDTensor


4. ArrayRead
      inputs: X
              i   1x1 Tensor, int64_t
      outputs:
              Out
   Out = X[i]

   dX[i] = dOut

5. ArrayWrite
      inputs: X
              i
      outputs:
              Out
   if i >= Out.size():
      Out.resize(i+1)
   Out[i] = X

6. DyRNNMemory
      inputs: i  1x1 Tensor, int64_t
              step_scopes 
              boot_memory
              RankSortTable
      outputs:
              if i == 0:
                 Out = boot_memory // Note: Should sort by RankStable
              else:
                 Out = step_scopes[i-1][memory_name]
      attrs:
              memory_name

7. DyRNNOp
      inputs:
            RankSortTable
            inputs
            boot_memories
            parameters
            MaxSeqLen
      outputs:
            outputs
      attrs:
           condition : string 
            ...
```

**Comment by reyoung** [comment] 2017-11-01 21:51
Deadline: 11/03

**Comment by reyoung** [comment] 2017-11-01 21:54
```
8. LessThanOp
    inputs: a   N-dim tensor
                b   N-dim tensor
    outputs:
               Out  N-dim tensor : bool
```

**Comment by Superjom** [comment] 2017-11-01 22:15
Test case for `ToArray`

```
X:  shape, [10, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
X.LoD: 
[0, 3, 4, 10]

Out:
6 Tensors

0. [4, 0, 3]
1. [5, 1, 4]
2. [6, 2]
3. [7]
4. [8]
5. [9]
```
some codes to reference https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/tensor_array.cc#L130
@QiJune

**Comment by shanyi15** [comment] 2018-08-15 11:12
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:12 UTC
