### ISSUE TITLE
 Quantize transpiler for fixed-point Quantization training framework.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#10692] opened 2018-05-16 07:21 UTC
Related to #10552 and https://github.com/PaddlePaddle/Paddle/issues/10551

The user API is like:

```python

class QuantizeTranspiler:
	def transpile(self,
		          program,
		          weight_bits=8,
		          activation_bits=8,
		          quant_delay=0):
```

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
