### ISSUE TITLE
Need `.param` interface for the Variable that returned by layer function

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#6887] opened 2017-12-22 08:55 UTC
It is common to get the parameters of layers. However, it is not supported by fluid now.

It can be implemented by adding `.param` for Variables that returned by layers.

Example usages are:

```python
hidden = fc(input=[a, b], ...)
prediction = fc(input=hidden, ...)
...
exe.run(fetch=[hidden.param[0], hidden.param[1], hidden.bias, prediction.param])
```

**Comment by wangkuiyi** [comment] 2018-01-11 21:17
I didn't look into the related PR, but when I read your example code in the above comment:

```python
hidden = fc(...)
```

means `hidden` is a variable, represented by a `VarDesc` protobuf message; it doesn't make sense to access/add a property `param` of the variable?

**Comment by reyoung** [comment] 2018-01-12 04:41
Users cannot fetch parameters and its gradients for a layer, but to fetch them is very useful for debugging, unit tests. Users can figure out which parameter is not normal during training by observing its value and gradient. We can check parameters and gradients by feeding and fetching them in unit tests.

Layer functions should return Variables since the `Variable` is the basic data type in `ProgramDesc`. However, we need to provide a way for users to get parameters and gradients from layer function's return value. We have not implemented this feature in Fluid. 

Does it make sense to provide a decorator class for `VarDesc`? Such as 

```python
class LayerOutput(Variable):  # LayerOutput inherits Variable
   def params(self):
       ...
   def bias(self):
       ...
```

And we make all layer function to return a LayerOutput？

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
Labels: PythonAPI
