### ISSUE TITLE
prelu layer's insufficient in python api 

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#5243] opened 2017-10-31 09:13 UTC
The channel, height, width of output of prelu layer should be the same with the input. 
But, it was not specified in Python API.

so, it will be error in the following two situations:

###  First (No input channel specified after prelu)
```
#!/usr/bin/env python
# coding=utf-8

import paddle.v2 as paddle

def conv_layer(input,
               ch_out,
               filter_size,
               stride,
               padding = 0,
               ch_in=None):

    tmp = paddle.layer.img_conv(
            input=input,
            filter_size=filter_size,
            num_channels=ch_in,
            num_filters=ch_out,
            stride=stride,
            padding=padding)
    
    tmp = paddle.layer.prelu(tmp, partial_sum = 1)
    return tmp

data_size = 3 * 224 * 224
img = paddle.layer.data(name="image", type=paddle.data_type.dense_vector(data_size))

conv1 = conv_layer(img, 3, 1, 1, 0, ch_in = 3)
conv2 = conv_layer(conv1, 13, 3, 2, 1)
```
**error:**
```
Traceback (most recent call last):
  File "test1.py", line 33, in <module>
    conv2 = conv_layer(conv1, 13, 3, 2, 1)
  File "test1.py", line 19, in conv_layer
    padding=padding)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 403, in wrapper
    return method(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 2487, in img_conv_layer
    assert input.num_filters is not None
AssertionError
```

###  second 

```
#!/usr/bin/env python
# coding=utf-8

import paddle.v2 as paddle

def conv_layer(input,
               ch_out,
               filter_size,
               stride,
               padding = 0,
               ch_in=None):

    conv = paddle.layer.img_conv(
            input=input,
            filter_size=filter_size,
            num_channels=ch_in,
            num_filters=ch_out,
            stride=stride,
            padding=padding)
    
    tmp = paddle.layer.prelu(conv, partial_sum = 1)
    tmp = paddle.layer.addto(input=[conv, tmp])
    return tmp

data_size = 3 * 224 * 224
img = paddle.layer.data(name="image", type=paddle.data_type.dense_vector(data_size))

conv1 = conv_layer(img, 3, 1, 1, 0, ch_in = 3)
```
**error:**
```
Traceback (most recent call last):
  File "test1.py", line 28, in <module>
    conv1 = conv_layer(img, 3, 1, 1, 0, ch_in = 3)
  File "test1.py", line 22, in conv_layer
    tmp = paddle.layer.addto(input=[conv, tmp])
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 403, in wrapper
    return method(*args, **kwargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 3315, in addto_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3834, in Layer
    return layer_func(name, **xargs)
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 2819, in __init__
    input_index).height
AssertionError
```

**Comment by shanyi15** [comment] 2018-08-15 11:12
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:12 UTC
Labels: enhancement
