### ISSUE TITLE
线上突然报了这个，undefined symbol: _ZNSt6chrono3_V212system_clock3nowEv

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#8860] opened 2018-03-08 03:01 UTC
I0308 10:30:36.602178 40659 pipe_processor.cpp:530] read_stdout_func thread end...
I0308 10:30:36.602823 35368 pipe_processor.cpp:371] subprocess exited
I0308 10:30:36.605780  2044 pipe_processor.cpp:516] read_stdout_func thread begin...
I0308 10:30:36.605783  2045 pipe_processor.cpp:563] read_stderr_func thread begin...
**python27-gcc482/lib/python2.
7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZNSt6chrono3_V212system_clock3nowEv
I0308 10:30:37.589165  2044 pipe_processor.cpp:433] End-of-file reached.

**Comment by wangkuiyi** [comment] 2018-03-09 01:54
请贴一下你是怎么做的。以便其他人复现这个问题。

**Comment by VamWolf** [comment] 2018-03-10 02:58
.flume-resource-51a6daec-cdbe-4ac2-b400-114ac309717f/py_paddle/_swig_paddle.so: undefin
ed symbol: _ZNSt6chrono3_V212system_clock3nowEv
还有偶尔报的.
1. 训练好模型
2. bigflow add 到bigflow 环境中
3. 调用pythonswig 接口预估

            cmd = "chmod +x ./fake/python27-gcc482/bin/python && \
                    ./fake/python27-gcc482/bin/python \
                    fake/conf/predict.py -n \
                    fake/conf/trainer_config.py -w \
                    fake/model/pass-000%s -b \
                    fake/data/labels.list -d \
                    fake/data/dict.txt" % tradeid
            pc = pc_tmp.map(lambda x: x) \

**Comment by QiJune** [comment] 2018-03-12 02:47
我搜了一下这个错误，看到这里https://github.com/facebook/rocksdb/issues/606

这个错误是没有链接 `-lrt`造成的，你用`ldd`命令先看看依赖

**Comment by shanyi15** [comment] 2018-08-15 11:37
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:37 UTC
Labels: User
