### ISSUE TITLE
pre-commit yapf version is too low to automatically format python code in a good way.

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#11381] opened 2018-06-12 02:48 UTC
current code 
```
    def _get_inputs(self):
        return [fluid.layers.data(
                    name='state', shape=[self.hist_len, self.img_height, self.img_width], dtype='float32'),
                fluid.layers.data(
                    name='action', shape=[1], dtype='int32'), 
                fluid.layers.data(
                    name='reward', shape=[], dtype='float32'),
                fluid.layers.data(
                    name='next_s', shape=[self.hist_len, self.img_height, self.img_width], dtype='float32'),
                fluid.layers.data(
                    name='isOver', shape=[], dtype='bool')]
```
formatted by yapf 0.13(version currently used by paddle)
```
        return [
            fluid.layers.data(
                name='state',
                shape=[self.hist_len, self.img_height, self.img_width],
                dtype='float32'), fluid.layers.data(
                    name='action', shape=[1], dtype='int32'), fluid.layers.data(
                        name='reward', shape=[], dtype='float32'),
            fluid.layers.data(
                name='next_s',
                shape=[self.hist_len, self.img_height, self.img_width],
                dtype='float32'), fluid.layers.data(
                    name='isOver', shape=[], dtype='bool')
        ]
```
formatted by yapf 0.22
```
        return [
            fluid.layers.data(
                name='state',
                shape=[self.hist_len, self.img_height, self.img_width],
                dtype='float32'),
            fluid.layers.data(name='action', shape=[1], dtype='int32'),
            fluid.layers.data(name='reward', shape=[], dtype='float32'),
            fluid.layers.data(
                name='next_s',
                shape=[self.hist_len, self.img_height, self.img_width],
                dtype='float32'),
            fluid.layers.data(name='isOver', shape=[], dtype='bool')
        ]   
```
Can we upgrade yapf version?

**Comment by shanyi15** [comment] 2018-08-15 11:00
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:00 UTC
Labels: User, 屯
