### ISSUE TITLE
Executing Passes

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13191] opened 2018-09-03 14:24 UTC
In the overview document https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/ir/overview.md there is a call for the Executor on a graph, but I cannot see the appropriate method in the Executor class. How can one run Passes with Executor? I can see there is an API for registering passes, but do not know how they are triggered.

**Comment by sfraczek** [comment] 2018-09-03 15:14
I would like to join the question.
Should we rewrite Executor to do something like this https://github.com/PaddlePaddle/Paddle/compare/develop...tpatejko:tpatejko/fun-with-ir-passes#diff-9c62ba43f55bf11a4b8656844d20ffe1R142? 
Can we have passes launched by Python api too or only by C-api? Is there any executable entry-point that calls the passes?

**Comment by Superjomn** [comment] 2018-09-04 03:12
Currently, there is no overall Pass Manager like module, so for different application, there are some small ones.

For example, for inference, the `Analysis` module has its own IR manager

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/analysis/ir_pass_manager.cc#L38

**Comment by wojtuss** [comment] 2018-09-04 08:19
Currently, we have several fuses of operators implemented in python using the inference transpiler. We want to switch from transpiler to Passes. How should we approach this?
As far as I understand, we should create several Passes which implement the fuses. Then we should execute those Passes on the model graph using the PaddlePredictor(?) just after loading the model and before running the inference. Should we wrap the PaddlePredictor into a Pass Manager?
Does running the PaddlePredictor require exposing it to the python api, to be called from the python script before a call to `executor.run()` or can it be incorporated into the Executor constructor and initialization?
Please, help us arrange those things in the best way according to the Passes' design.

**Comment by luotao1** [comment] 2018-09-04 09:48
> Does running the PaddlePredictor require exposing it to the python api, to be called from the python script before a call to executor.run() or can it be incorporated into the Executor constructor and initialization

Running PaddlePredictor doesn't require exposing it to the python api. You can see https://github.com/PaddlePaddle/Paddle/issues/13109#issuecomment-418305737

**Comment by lucywsq** [comment] 2018-09-20 17:04
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-09-20 17:04 UTC
Labels: Intel
