### ISSUE TITLE
多机下update_method=nccl2,  打开memory_optimize后，运行报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#11367] opened 2018-06-11 11:28 UTC
**参数如下：**

```bash
batch_size: 32
cpus: 1
data_format: NCHW
data_path: 
data_set: flowers
device: GPU
gpus: 8
infer_only: False
iterations: 80
learning_rate: 0.001
memory_optimize: True
model: resnet
no_test: False
pass_num: 100
profile: False
skip_batch_num: 5
update_method: nccl2
use_cprof: False
use_fake_data: False
use_nvprof: False
use_reader_op: False
```

**运行结果如下，然后hang住：**
```bash
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO NET : Using interface eth0:10.255.123.15<0>
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO NET/IB : Using interface eth0 for sideband communication
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO NET/IB: [0] mlx5_0:1/RoCE 
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO Using internal Network IB
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
NCCL version 2.1.15+cuda9.0
yq01-jpaas-ai00-let0048:26470:26615 [1] INFO NET/IB: Dev 0 Port 1 qpn 1274 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO NET/IB: Dev 0 Port 1 qpn 1273 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1276 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO CUDA Dev 0, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26616 [2] INFO NET/IB: Dev 0 Port 1 qpn 1279 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1280 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26615 [1] INFO CUDA Dev 1, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1283 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26616 [2] INFO CUDA Dev 2, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1286 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1288 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1290 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26617 [3] INFO NET/IB: Dev 0 Port 1 qpn 1291 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1293 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26617 [3] INFO CUDA Dev 3, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1296 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26618 [4] INFO NET/IB: Dev 0 Port 1 qpn 1297 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1299 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26618 [4] INFO CUDA Dev 4, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1302 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26619 [5] INFO NET/IB: Dev 0 Port 1 qpn 1303 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1305 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26619 [5] INFO CUDA Dev 5, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1308 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26620 [6] INFO NET/IB: Dev 0 Port 1 qpn 1309 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1311 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26620 [6] INFO CUDA Dev 6, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1314 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26621 [7] INFO NET/IB: Dev 0 Port 1 qpn 1315 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1317 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26621 [7] INFO CUDA Dev 7, IB Ports : mlx5_0/1(SOC) 
yq01-jpaas-ai00-let0048:26470:26511 [0] INFO NET/IB: Dev 0 Port 1 qpn 1320 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO Using 256 threads
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO Min Comp Cap 6
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO Ring 00 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15

yq01-jpaas-ai00-let0048:26470:26614 [0] transport/net_ib.cu:204 WARN No module present for GPU Direct RDMA.

yq01-jpaas-ai00-let0048:26470:26621 [7] transport/net_ib.cu:204 WARN No module present for GPU Direct RDMA.
yq01-jpaas-ai00-let0048:26470:26619 [5] INFO Ring 00 : 5[5] -> 6[6] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26617 [3] INFO Ring 00 : 3[3] -> 4[4] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26618 [4] INFO Ring 00 : 4[4] -> 5[5] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26616 [2] INFO Ring 00 : 2[2] -> 3[3] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26620 [6] INFO Ring 00 : 6[6] -> 7[7] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26615 [1] INFO Ring 00 : 1[1] -> 2[2] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO 15 -> 0 via NET/IB/0
yq01-jpaas-ai00-let0048:26470:26614 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/direct pointer
yq01-jpaas-ai00-let0048:26470:26621 [7] INFO NET/IB: Dev 0 Port 1 qpn 1321 mtu 3 GID 0 (80FE/AAFBA3FEFF9A0DEE)
yq01-jpaas-ai00-let0048:26470:26470 [0] INFO Launch mode Parallel
mlx5: yq01-jpaas-ai00-let0048.yq01.baidu.com: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000030 00000000 00000000 00000000
00000000 00008813 09000529 08a7a3d2

yq01-jpaas-ai00-let0048:26470:26622 [7] transport/net_ib.cu:775 WARN NET/IB : Got completion with error 10, opcode 1, vendor err 136
yq01-jpaas-ai00-let0048:26470:26622 [7] INFO include/net.h:33 -> 1 [Net]
yq01-jpaas-ai00-let0048:26470:26622 [7] INFO transport/net.cu:385 -> 2
yq01-jpaas-ai00-let0048:26470:26622 [7] INFO transport.cu:147 -> 2 [Proxy thread]
```

**若关闭memory_optimize后，则可以正常跑**

**Comment by typhoonzero** [comment] 2018-06-20 01:28
Dup: https://github.com/PaddlePaddle/Paddle/issues/11446, `vendor err 136` means something was wrong with you RDMA driver or hardware.

**Comment by typhoonzero** [comment] 2018-06-28 12:09
Closing this for now, seems not a bug of enabling memory optimization.

**Closed by typhoonzero** 2018-06-28 12:09 UTC
