### ISSUE TITLE
Mac上源码编译问题

### ISSUE THREAD

**Issue by sheep0729** [PaddlePaddle/Paddle#12427] opened 2018-07-29 08:55 UTC
CMake Error at cmake/generic.cmake:147 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:paddle_inference_api>

  No target "paddle_inference_api"
Call Stack (most recent call first):
  cmake/generic.cmake:234 (merge_static_libs)
  paddle/fluid/inference/CMakeLists.txt:25 (cc_library)

**Comment by typhoonzero** [comment] 2018-08-17 10:58
Inference暂时不考虑支持mac编译，请在编译时加上参数`-DWITH_INFERENCE=OFF`

**Comment by lucywsq** [comment] 2018-09-20 16:24
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-09-20 16:24 UTC
