### ISSUE TITLE
Build ERROR after Fix hang bug of TCPStore 

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#43914] opened 2022-06-28 11:23 UTC
### 问题描述 Issue Description

Commit https://github.com/PaddlePaddle/Paddle/commit/4c9330d65a8028881eb27ebe5f421a89c96e1101 seems to be responsible of paddle build errors. 
![image](https://user-images.githubusercontent.com/10847947/176166652-69bd3e12-dc69-4237-8c04-3d443573befe.png)
![image](https://user-images.githubusercontent.com/10847947/176166692-3840b469-6c01-4f97-b2b1-6cadb2d671b1.png)

### 版本&环境信息 Version & Environment Information

Paddle branch: develop
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8.4.0
```
---
### CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

**Comment by shiyutang** [comment] 2022-06-29 02:23
please use cmake==3.16, gcc==8.2 and build on latest commit.

**Comment by Aganlengzi** [comment] 2022-06-29 06:52
I didn't reproduce it on my environment with your CMAKE parameters
<img width="467" alt="image" src="https://user-images.githubusercontent.com/5997715/176366004-c1d42a08-24ee-4f03-8a7c-4b783cf3cc9b.png">

It seems your compiler is more strict, if cmake==3.16, gcc==8.2 can not help, please try this PR: https://github.com/PaddlePaddle/Paddle/pull/43939

**Comment by Aganlengzi** [comment] 2022-07-05 07:58
@pmajchrzak hi, Please help check with this PR https://github.com/PaddlePaddle/Paddle/pull/44097
I could not reproduce without your environment, thank you!
You can do this in your Paddle:
```
git fetch upstream pull/44097/head:test
git checkout test
```
and then try build.

**Comment by pmajchrzak** [comment] 2022-07-05 09:27
> 
@Aganlengzi 
It works! 
Thanx 👍

**Comment by Aganlengzi** [comment] 2022-07-06 11:18
@pmajchrzak this PR https://github.com/PaddlePaddle/Paddle/pull/44093 has been merged, you can now using newest develop~

**Closed as completed** 2022-07-11 01:26 UTC
Labels: Intel, type/build, status/close
