### ISSUE TITLE
How to initialize a Fluid program?

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#10177] opened 2018-04-24 17:57 UTC
I think we need to address the problem below before merging startup program and main program into a single program:

1. Init reader when doing inference
  An inference program will run repeatedly, but we may have a reader inside an inference program, it should be initialized only once, not every time when the inference program runs. Merging the startup program and the main program essentially runs the initialization operators on every run.

1. Load parameters inside the Fluid program when doing inference.
  The [V4 API proposal](https://github.com/PaddlePaddle/Paddle/issues/9912) proposes to load parameters outside of the Fluid program:
    #### infer.py
    ```Python
    x = fluid.Tensor(name='x', shape=[13], dtype='float32')
    y_predict = fluid.layers.fc(name='y_predict', input=x, size=1, act=None)
    return y_predict
    ```

    #### main.py
    ```Python
    program = fluid.compile('./infer.py', params='./params')
    inputs = {
      'x': [2,4,64,36,7,4,3,2,4,6,5,9,8]
    }
    results = program.run(input=inputs)
    ```

    It would be more coherent with the Fluid design if the parameter loading is inside the Fluid program:

    #### infer.py
    ```Python
    fluid.load_parameters("./params.recordio")
    x = fluid.Tensor(name='x', shape=[13], dtype='float32')
    y_predict = fluid.layers.fc(name='y_predict', input=x, size=1, act=None)
    return y_predict
    ```

    #### main.py
    ```Python
    program = fluid.compile('./infer.py')
    program.init()
    inputs = {
      'x': [2,4,64,36,7,4,3,2,4,6,5,9,8]
    }
    results = program.run(input=inputs)
    ```

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
