### ISSUE TITLE
cpu_noavx_openblas 编译这个版本的时候报错了

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#11187] opened 2018-06-05 07:31 UTC
cpu_noavx_openblas 编译这个版本的时候报错了。该怎么解决呢？
是按照MKL相同的配置编译的，就改了一下CONFIG项。MKL版本是编译通过的。
从
CONFIGS('baidu/third-party/paddle-capi@paddle-capi-cpu-v0.2@git_tag',NeedOutput())
改成了
CONFIGS('baidu/third-party/paddle-capi-noavx@paddle-capi-noavx_1-0-0-1_PD_BL@git_tag',NeedOutput())

报错信息如下：
err:/home/opt/gcc-4.8.2.bpkg-r4/gcc-4.8.2.bpkg-r4/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../x86_64-baidu-linux-gnu/bin/ld: bc_out/baidu/third-party/paddle-capi-noavx/output/lib/libpaddle_capi_engine.a(MathFunctions.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/home/opt/gcc-4.8.2.bpkg-r4/gcc-4.8.2.bpkg-r4/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../x86_64-baidu-linux-gnu/bin/ld: note: 'dlsym@@GLIBC_2.2.5' is defined in DSO /opt/compiler/gcc-4.8.2/lib/libdl.so.2 so try adding it to the linker command line
/opt/compiler/gcc-4.8.2/lib/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

**Comment by jacquesqiao** [comment] 2018-06-05 09:39
https://stackoverflow.com/questions/29557683/undefined-reference-to-symbol-dlsymglibc-2-4 按这个教程调试一下？

**Comment by shanyi15** [comment] 2018-08-15 11:01
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:01 UTC
