### ISSUE TITLE
Transfer Learning for DS2

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4248] opened 2017-09-20 20:54 UTC
Users want to use deep speech 2 model for transfer learning. Users want to extract the speech features by `DS2` model, just like they extract image features by VGGNet.

And then, many interesting things could be done, for example.

* We can compare the similarity of two speakers. The difference will show how clear the input speech was, thus allowing us to determine how clear or unclear one's pronunciation of a phoneme may be.

**Comment by NorthStar** [comment] 2017-09-26 17:58
If we have a general enough guide on `transfer learning`, this should be a duplicate of #4243 .

**Comment by NorthStar** [comment] 2017-09-26 17:59
Duplicate of #4243

**Closed** 2017-09-26 18:00 UTC
Labels: HackMIT, InterestingIdea
