### ISSUE TITLE
The training framework of fixed point quantization.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#10551] opened 2018-05-10 03:24 UTC
####  Desgin
   - Add the Design doc  

PRs:
- [x] design doc:  https://github.com/PaddlePaddle/Paddle/issues/10552

####  C++  
  - fake_quantize_op
    - calculate sliding maximum value for the dequantization range.
    - quantize implementation
  - fake_dequantize_op  

PRs: 
- [x] fake_dequantize_op: https://github.com/PaddlePaddle/Paddle/pull/10965
- [ ] fake_dequantize_op:

#### Python transpiler:
Requirement: 
  - develop quantization transpiler to rewrite ProgramDesc to insert the fake_quantize_op and fake_dequantize_op.
    - Only insert the fake_quantize_op and fake_dequantize_op in the forward pass.
    - Do not change the inputs and outputs of the backward operator.
  - consider the batch-norm folding and quantization.

PRs:
- [x] implement training transpiler prototype #10693 
- [ ] Enhance the delay quantization for training.
- [ ] implement inference transpiler

#### Model verification.
  - Need to determine the baseline.

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
