### ISSUE TITLE
Potential conflict with matplotlib on macOS, paddle version 0.11.0

### ISSUE THREAD

**Issue by tidegu** [PaddlePaddle/Paddle#10434] opened 2018-05-06 07:00 UTC
**System environment:**

> MacBook Pro (Retina, 15-inch, Late 2013)
> 2.3G i7 / 16 GB / 512 GB / Iris 1536 MB + GT 750M
> macOS 10.12.6
> Python 2.7.15
> paddlepaddle 0.11.0 (cpu)

**Minimum reproducible code:**

```
#!/usr/bin/env python
import numpy as np
import paddle.v2 as paddle
import matplotlib.pyplot as plt
import pandas as pd

paddle.init(use_gpu=False, trainer_count=1)

ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()

plt.show()
```

**Expected result:**

> The plotting shows in a pop up window.

**Actual result:**

> Python crashes with following report:

> I0506 14:24:56.760939 3167491008 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
> *** Aborted at 1525587896 (unix time) try "date -d @1525587896" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGFPE (@0x7fffaa3728ab) received by PID 17720 (TID 0x7fffbccc13c0) stack trace: ***
>     @     0x7fffb3fb3b3a _sigtramp
>     @     0x7fffaa3728ac CUICoreThemeRenderer::DrawWindowFrameStandardNew()
>     @     0x7fffaa2eb92f CUIRenderer::Draw()
>     @     0x7fffaa2ee75e CUIDraw
>     @     0x7fff9c260f91 __44-[NSAppearance _drawInRect:context:options:]_block_invoke
>     @     0x7fff9cbfa313 -[NSCompositeAppearance _callCoreUIWithBlock:options:]
>     @     0x7fff9c260f4f -[NSAppearance _drawInRect:context:options:]
>     @     0x7fff9c3247e5 _NSDrawThemeBackground
>     @     0x7fff9c32407b -[NSThemeFrame _drawUnifiedToolbarWithState:inFrame:]
>     @     0x7fff9c323eb3 -[NSThemeFrame _drawUnifiedToolbar:]
>     @     0x7fff9c323cb3 -[NSThemeFrame _drawTitleBar:]
>     @     0x7fff9c323c42 -[NSThemeFrame _drawFrameInterior:clip:]
>     @     0x7fff9c323be4 -[NSThemeFrame drawFrame:]
>     @     0x7fff9c323ab1 -[NSFrameView drawRect:]
>     @     0x7fff9c3236f4 -[NSThemeFrame drawRect:]
>     @     0x7fff9c26df99 -[NSView _drawRect:clip:]
>     @     0x7fff9c2bdf2f -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]
>     @     0x7fff9c26bad2 -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:]
>     @     0x7fff9c26b2af -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:]
>     @     0x7fff9c2696d8 -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:]
>     @     0x7fff9c264fca -[NSView displayIfNeeded]
>     @     0x7fff9c2648db -[NSWindow displayIfNeeded]
>     @     0x7fff9c251fb3 -[NSWindow _doWindowWillBeVisibleAsSheet:]
>     @     0x7fff9c9b863e -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:]
>     @     0x7fff9c2506ce -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
>     @     0x7fff9c250263 -[NSWindow orderWindow:relativeTo:]
>     @     0x7fff9c302bab -[NSWindow makeKeyAndOrderFront:]
>     @        0x1196df90a FigureManager_show
>     @        0x10c5b2ad1 PyEval_EvalFrameEx
>     @        0x10c5ab5b2 PyEval_EvalCodeEx
>     @        0x10c535b9c function_call
>     @        0x10c50f7e3 PyObject_Call
> Floating point exception: 8

**Note:** Issue resolves after removing the line `paddle.init()`. However, this is mandatory in all paddlepaddle projects.

**Other information:**

I have recently upgraded Python to 2.7.15 from overwriting v2.7.10 for resolving package not found issue when installing paddlepaddle using `pip`. I do not remember if any other pip packages were installed before installing `paddlepaddle`, but after installing `paddlepaddle`, I installed `pandas`. This issue occurred when testing. I also tried to install `tensorflow` (including its dependencies), so the list of packages are as follows at this moment:

> absl-py==0.2.0
> astor==0.6.2
> backports.functools-lru-cache==1.5
> backports.weakref==1.0.post1
> bleach==1.5.0
> cycler==0.10.0
> enum34==1.1.6
> funcsigs==1.0.2
> futures==3.2.0
> gast==0.2.0
> graphviz==0.8.3
> grpcio==1.11.0
> html5lib==0.9999999
> kiwisolver==1.0.1
> Markdown==2.6.11
> matplotlib==2.2.2
> mock==2.0.0
> nltk==3.2.5
> numpy==1.14.3
> opencv-python==3.4.0.12
> paddlepaddle==0.11.0
> pandas==0.22.0
> pbr==4.0.2
> Pillow==5.1.0
> protobuf==3.5.2.post1
> pyparsing==2.2.0
> python-dateutil==2.7.2
> pytz==2018.4
> rarfile==3.0
> recordio==0.1.4
> requests==2.9.2
> scipy==1.0.1
> six==1.11.0
> subprocess32==3.2.7
> tensorboard==1.8.0
> tensorflow==1.8.0
> termcolor==1.1.0
> Werkzeug==0.14.1

**Comment by Superjomn** [comment] 2018-05-07 02:00
You'd better use the docker on mac, that is more stable.

**Comment by shanyi15** [comment] 2018-08-15 11:35
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:35 UTC
Labels: User
