### ISSUE TITLE
Convolution Weight in PaddlePaddle

### ISSUE THREAD

**Issue by JiahaoYao** [PaddlePaddle/Paddle#11567] opened 2018-06-19 08:24 UTC
The first convolutional layer in [resnet](https://github.com/PaddlePaddle/models/blob/develop/image_classification/resnet.py) is kernel 7x7, stride 2 channels 64. I download the weight of the resnet. It is in the shape of `(1, 9408)`, which is exactly `7x7x3x64`. Can I ask what is the shape of the weight in the `tf version`. It should be a 4-dim vector. But I am not sure whether it is `(7,7,3,64)` or `(3,64,7,7)` or anything else. Or can anyone show the implement of the Paddlepaddle convolution for me?

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
