### ISSUE TITLE
test_layer_norm_op generates a large number of UserWarnings

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#55358] opened 2023-07-12 07:49 UTC
### 问题描述 Please describe your issue

When debugging layer norm op, too many UserWarnings are generated.

- Are these warning message necessary? Is there any way to resolve these warnings? Hundreds of lines of warning message is annoying for users.
- We should use logger instead of print/std::cout like functions. Refer to [PR#53725](https://github.com/PaddlePaddle/Paddle/pull/53725). But I found print in [primapi.py#L269](https://github.com/PaddlePaddle/Paddle/blob/006bd959c70eed6f52ff16a290a2cbb6dd9102ee/python/paddle/incubate/autograd/primapi.py#L269C11-L269C11), which adds a lot of useless output when debugging.

To reproduce:
```
ctest -R test_layer_norm_op -V
```

Warnings:
```
1574: /opt/paddle/paddle/build/python/paddle/static/nn/common.py:3614: UserWarning: param_attr is only available with scale is True.
1574:   warnings.warn("param_attr is only available with scale is True.")
1574: /opt/paddle/paddle/build/python/paddle/static/nn/common.py:3625: UserWarning: bias_attr is only available with shift is True.
1574:   warnings.warn("bias_attr is only available with shift is True.")
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'input' in LayerNorm only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'x' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in cast only support bfloat16 in OneDNN now.
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/executor.py:1479: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
1574:   warnings.warn(error_info)
1574: I0712 06:06:28.014463  5429 interpretercore.cc:237] New Executor is Running.
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'input' in LayerNorm only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'x' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in fill_constant only support bfloat16 in OneDNN now.
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'input' in LayerNorm only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'x' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in fill_constant only support bfloat16 in OneDNN now.
1574:   warnings.warn(
1574: I0712 06:06:28.306679  5429 interpreter_util.cc:518] Standalone Executor is Used. 
```

**Comment by USTCKAY** [comment] 2023-07-12 08:11
Hi, you can disable these warning logs manually at your local workspace, and we will consider reducing log output. Thanks for your feedback!

**Comment by Wong4j** [comment] 2023-07-13 06:20
> Hi, you can disable these warning logs manually at your local workspace, and we will consider reducing log output. Thanks for your feedback!

Is there any FLAG to disable these warnings?

**Comment by USTCKAY** [comment] 2023-07-13 06:46
> 

As I know there is not. You can comment the print/warning code out and recompile Paddle to avoid these warnings.

**Comment by onecatcn** [comment] 2023-07-21 03:09
@Wong4j In addition to the work-around @USTCKAY provided above, we are also calling contributors to help resolve the issue : https://github.com/PaddlePaddle/Paddle/discussions/51794#discussioncomment-5342360 . Actually several contributors are interested in the task and are willing to join the team, but we still need a mentor to guide the team. If you, or anyone from the community are interested in mentoring the work, please contact us via [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)  or my wechat.

**Comment by RedContritio** [comment] 2023-07-28 14:10
We tried to identify the causes of the warnings and found 2 types of warnings as follows:

### 1. Invalid Parameters**

this type of warning is caused by the incorrect use of the `layer_norm` API in the unit tests.

> 1574: /opt/paddle/paddle/build/python/paddle/static/nn/common.py:3614: UserWarning: param_attr is only available with scale is True.
1574:   warnings.warn("param_attr is only available with scale is True.")
1574: /opt/paddle/paddle/build/python/paddle/static/nn/common.py:3625: UserWarning: bias_attr is only available with shift is True.
1574:   warnings.warn("bias_attr is only available with shift is True.")

### 2. Incompatible Testcase Condition

this type of warning is caused by running the ‘bfloat16’ test case on a device that does not support it.

> 1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'input' in LayerNorm only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'x' in cast only support bfloat16 in OneDNN now. 
1574:   warnings.warn(
1574: /opt/paddle/paddle/build/python/paddle/fluid/data_feeder.py:186: UserWarning: The data type of 'dtype' in cast only support bfloat16 in OneDNN now.
1574:   warnings.warn(

### Fix

Fixed in #55762.

**Comment by Wong4j** [comment] 2023-08-03 03:13
> ### 1. Invalid Parameters**
> ### 2. Incompatible Testcase Condition

更新一下issue信息，目前[PR#55762](https://github.com/PaddlePaddle/Paddle/pull/55762)已解决第一部分的Warnings，但仍有大量的warnings，是data_feeder.py和executor.py报的。需要进一步调查原因。

**Comment by Wong4j** [comment] 2023-08-09 15:04
@RedContritio 这个issue是否有更新呢？

**Comment by jzhang533** [comment] 2023-08-24 06:28
> 更新一下issue信息，目前[PR#55762](https://github.com/PaddlePaddle/Paddle/pull/55762)已解决第一部分的Warnings，但仍有大量的warnings，是data_feeder.py和executor.py报的。需要进一步调查原因。

#56448 is trying to remove warnings from executor.py, but since it changed file python/paddle/fluid/executor.py, which is in python/paddle/fluid folder, which is on the way of renaming, this PR will be merged after renaming is finished.

**Comment by Wong4j** [comment] 2023-09-20 05:49
更新：executor.py报的warning已解决，剩下data_feeder.py的warning未解决

**Comment by jzhang533** [comment] 2023-09-26 10:51
我又试着跑了一下。没能复现出来自data_feeder.py的warning。但是有大量的`Lowering composite forward ops` 开头的日志。

**Comment by Wong4j** [comment] 2023-09-27 12:58
我提了[PR57819](https://github.com/PaddlePaddle/Paddle/pull/57819)修复剩下的问题

**Closed as completed** 2023-10-10 02:41 UTC
Labels: NVIDIA, type/others, PFCC, status/close
