### ISSUE TITLE
Considering enhancing parameter server with DPDK 

### ISSUE THREAD

**Issue by yingfeng** [PaddlePaddle/Paddle#12190] opened 2018-07-17 11:33 UTC
I notice that paddle v2 fluid has been significantly changed since its legacy version. The idea to encapsulate the parameter server into the operator is great such that the program running on local machine and distributed environment could share the major codes. However, I also notice that the parameter server in fluid is based on either GRPC or BRPC, I think there exists remarkable margin for performance improvements as a result. Due to the simplicity of current encapsulation, I think it might be good ideas to change to other network stack such that communication overhead among ps nodes could be reduced a lot. 
For example, this [framework](https://github.com/senior7515/smf) is a seastar based RPC, it seems DPDK enhanced network could be easily integrated into Paddle to replace either GRPC or BRPC.

Another work is [eRPC](https://github.com/anujkaliaiitd/eRPC), which provides RoCE based RPC solution as well as DPDK(in future), it might also be a good candidate for communication improvements.

**Comment by gongweibao** [comment] 2018-07-18 08:08
Thanks! I will take a look at it!

**Comment by yingfeng** [comment] 2018-08-25 06:02
DPDK support is ready within [eRPC](https://github.com/anujkaliaiitd/eRPC), just FYI

**Comment by lucywsq** [comment] 2018-10-18 07:55
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-18 07:55 UTC
