### ISSUE TITLE
Thoughts about operators and functors

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7130] opened 2018-01-02 05:57 UTC
I've been writing implementations about manipulating `SelectedRows` and `Tensor` [calculations](https://github.com/PaddlePaddle/Paddle/pull/7045). Found several places that might be able to improve:

1. Operators' "Kernels" are in fact the same as `functors` or can be assembled by several operators or functors. For example, merge `SelectedRows` duplicated rows is a functor used both in adam_op and adagrad_op. And, many operators can also be reused in other operators which are now difficult to do.
2. Operators and Functors are not “lazy evaluated”.  I’ve written some code using [Expression templates](https://en.wikipedia.org/wiki/Expression_templates) at [here](https://gist.github.com/typhoonzero/5d03990b461bb4a5cb90331bfe302576) indicating how to do lazy evaluation. If we have Operators/Functors as “Expression templates”, the calculation is done at the last stage and probably using only one for-loop.

How to implement:

1. For eigen Operators/Functors, we can return the non evaluated tensor `Operations` in `Compute` call of current `Kernel` implement. And then evaluate the `Operations` only when necessary. Operators need to hold the expression object containing either `Functor expression` or `Eigen Operations` inside it.
2. For `Functors` that need standalone CUDA kernels, we can use “Expression templates” to implement functor expression.
3. A `Block` of operators will then be expanded as a large “Functor” containing both Eigen Operations and Functors, it’s type may look like: `….Add<Square<SparseAddTo<SparseMul<SelectedRows, SelectedRows>, Tensor>>, Scalar>….`

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
Labels: need be discussed
