### ISSUE TITLE
Segmentation fault in using JNI_CreateJavaVM with paddle 

### ISSUE THREAD

**Issue by rmalav15** [PaddlePaddle/Paddle#10456] opened 2018-05-07 10:40 UTC
Hey,

We are using [DeepSpeech](https://github.com/PaddlePaddle/DeepSpeech) in our project using provided docker image. First of all, terrific work in both PaddlePaddle and DeepSpeech.

In DeepSpeech they use [c++ decoder](https://github.com/PaddlePaddle/DeepSpeech/tree/develop/decoders) which is used with [swig](http://www.swig.org/tutorial.html) wrapper in the python code. To reproduce the error, we made a sample [github repo](https://github.com/rmalav15/swig_wrapper). For the project requirement we need to use [JNI_CreateJavaVM](https://github.com/rmalav15/swig_wrapper/blob/4cd328a755c5f77ffba34b87805b2799b97d0b9d/gfg.cpp#L45) to use java jar classes in our c++ code, which is in turn will be used in DeepSpeech python code using swig wrapper.

When we run demo [test.py](https://github.com/rmalav15/swig_wrapper/blob/master/test.py) (which doesn't import paddle), it runs prefectly. But when we add import paddle:
```
import gfg
import paddle.v2 as paddle

print gfg.fact(5)
print gfg.my_mod(3,4)
#gfg.vm()
gfg.main()
```

and run it, we get:
```
120
3
using pool:)
Segmentation fault (core dumped)
```

The stack trace is this (When we used JNI_CreateJavaVM in DeepSpeech Code):

> Received utterance[length=245760] from 10.158.19.119, saved to demo_cache/20180504155105_10.158.19.119.wav.
> *** Aborted at 1525449065 (unix time) try "date -d @1525449065" if you are using GNU date ***
> PC: @ 0x0 (unknown)
> *** SIGSEGV (@0x50) received by PID 7060 (TID 0x7fde57e0a700) from PID 80; stack trace: ***
> @ 0x7fde579e6390 (unknown)
> @ 0x7fde57bfe73c (unknown)
> @ 0x7fde57c07851 (unknown)
> @ 0x7fde57c02564 (unknown)
> @ 0x7fde57c06da9 (unknown)
> @ 0x7fde57407f09 (unknown)
> @ 0x7fde57c02564 (unknown)
> @ 0x7fde57408571 (unknown)
> @ 0x7fde57407fa1 dlopen
> @ 0x7fde133fce75 os::Linux::clock_init()
> @ 0x7fde13400049 os::init()
> @ 0x7fde1354cca2 Threads::create_vm()
> @ 0x7fde131aae64 JNI_CreateJavaVM
> @ 0x7fde13daf06e create_vm()
> @ 0x7fde13daf2dc main_fn()
> @ 0x7fde13d46af8 _wrap_main_fn
> @ 0x4c468a PyEval_EvalFrameEx
> @ 0x4c2765 PyEval_EvalCodeEx
> @ 0x4ca099 PyEval_EvalFrameEx
> @ 0x4c2765 PyEval_EvalCodeEx
> @ 0x4ca8d1 PyEval_EvalFrameEx
> @ 0x4c2765 PyEval_EvalCodeEx
> @ 0x4ca8d1 PyEval_EvalFrameEx
> @ 0x4c9d8f PyEval_EvalFrameEx
> @ 0x4c2765 PyEval_EvalCodeEx
> @ 0x4de6fe (unknown)
> @ 0x4b0cb3 PyObject_Call
> @ 0x4f492e (unknown)
> @ 0x4b0cb3 PyObject_Call
> @ 0x4ce5d0 PyEval_CallObjectWithKeywords
> @ 0x4e17e4 PyInstance_New
> @ 0x4b0cb3 PyObject_Call
> Segmentation fault (core dumped)

This sounds weird, but its actually happening. 

It looks like there is some problem in using threads. The[ JNI_CreateJavaVM](https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jni/spec/invocation.doc.html) function description  says that it "Loads and initializes a Java VM. The current thread becomes the main thread." Which is I think causing the problem. (I am not sure, I may be completely wrong).

Please let us know why its happening, It will be huge help.

Much Thanks

**Comment by Yancey1989** [comment] 2018-05-07 11:48
Sorry for hearing that, I'm not good at JNI, but I think maybe you can write another swig demo program instead of `import paddle` to confirm whether paddle caused the crash.

**Comment by rmalav15** [comment] 2018-05-07 11:59
Yes.
We have tried without importing paddle. We we run file [test.py](https://github.com/rmalav15/swig_wrapper/blob/master/test.py), which doesn't import paddle, It run perfectly and gives
```
120
3
using pool:)
Launched JVM! :)
```

I believe that problem is not JNI side, I think paddle is blocking some resources which causes the problem.

**Comment by rmalav15** [comment] 2018-05-07 12:11
You can easily reproduce error using [our repo](https://github.com/rmalav15/swig_wrapper).

**Comment by shanyi15** [comment] 2018-08-15 10:27
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:27 UTC
Labels: User, 屯
