### ISSUE TITLE
param_scope() not working in tests

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#13402] opened 2018-09-14 09:47 UTC
Hi,

The `param_scope()` method doesn't work inside tests. **Is it intentional?**
Here is the param_scope() method:
https://github.com/PaddlePaddle/Paddle/blob/af15f6f0380a3975239d7d4a6c7c682f4058d309/paddle/fluid/framework/ir/fuse_pass_base.h#L35

 This is troublesome because I can't write a test for my conv_bn_fuse_pass beacuse I use `scope` in it. This function works when run from a resnet50 pass test program. **What should I do?** I have noticed that other passes (like `fc_gru`) also use scope and they don't have tests.

**Comment by Superjomn** [comment] 2018-09-17 01:56
Yes, it is internal. 
But you can use an AnalysisPredictor to make the param_scope usable if you need to load a model.

Or you can manually set that attribute for the graph, reference https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/analysis/ir_pass_manager.cc#L35, but that is an empty scope, you need to create variables you need.

**Comment by sfraczek** [comment] 2018-09-18 12:16
Hi. Thank you for answering!
I did manage to test my pass with analysis predictor as you advised.

It would be great to have an easy unit testing capability for this. I could have more confidence in this code. Do you have any future plans regarding unit tests for passes? I didn't quite get what I would have to do exactly to create variables so that scope is not empty.

**Comment by Superjomn** [comment] 2018-09-18 12:21
Yes, I will enhance the logic around Tensor, Variable with IR.
The `param_scope` is an ugly way to support parameter modification in IR pass phase, I will do some refining latter.

**Comment by sfraczek** [comment] 2018-09-18 12:32
Ok! thanks.

**Comment by lucywsq** [comment] 2018-09-20 17:08
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by sfraczek** [comment] 2019-07-03 09:45
Hi,

The solution to this problem was invented here:
https://github.com/PaddlePaddle/Paddle/blob/3ece61f71e6b45b094e6864fcfa78f849654059f/paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass_tester.cc#L80
This issue can be closed form my point of view. Thank you.

**Closed as completed** 2019-07-10 01:05 UTC
Labels: question, Intel
