### ISSUE TITLE
Fixing versioning and timely release cycles

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/Paddle#9859] opened 2018-04-12 00:18 UTC
An unclear software versioning system is extremely confusing to users. Unfortunately, we have put ourselves in this situation right now with multiple interleaved versioning systems. This has created an extremely complex navigation structure on PaddlePaddle.org, and is much more confusing on the technology side – because everything is resolved using a lot of custom logic and hardcoded hooks. Even beyond the website, on other channels of outreach, it is impractical for a new user to figure out which release to focus on.

**Suggestion**: Move to a standardized versioning system, applied retroactively. The sooner we make this change, the easier it will be for us. We’d much rather educate the smaller current user-base about this change today, than justify this debt for a larger community In the future. This change might become far from possible in the future.  

A suggestion here would be to use the modern BIG integer versioning system for major releases, and use the digits after the decimal for continuous releases (very Microsoft OS style), similar to what we do today. And each version should strictly support only one version of the API (from now onwards).

As a result, the following changes may apply:
0.8 -> **v0.8**
0.9 -> **v1.0**
0.10 ->  **v2.0** (since this was where the v2 API was introduced)
0.11 -> **v2.1**
Fluid -> **v3.0 (Fluid)**

If you see advantages, the next major release (v4.0) may be released with a codename. But if it adds more confusion, we could avoid this. 

Additionally, if going backwards and updating the versions retroactively is not practical, we could just start from the next release (3.0) and continue that trend.

Here are some action items required for this change (all based on popular practices):
-	A new release for v3.0 will be made **only** with the Fluid API. This could be a quieter release, but will lock down of the major functional improvements of Fluid until this point – all newer feature milestones for 2018 will get ported for 3.x releases or 4.0. This will also become our new standard default for all new user engagement – v3.0 – instead of fluid-through-develop or fluid-on-v0.11.
-	None of the APIs (and thus, none of the code snippets) for past releases will be changed. Only labels, references in tutorials, and branches will need to change. A versioning disclaimer and guide should make this clear. This is some work, yes, but it is necessary work.
-	For channels where we distribute PaddlePaddle (pip, docker), we may leave the old versioning numbers as is, and add identical releases for their new version numbers. That is the reason none of the former version numbers clash with the newer ones (apart from 0.8, which remains untouched).
-	Issues in former supported-versions should continue to be fixed and released until minor releases and release candidates after the decimal. One idea here would be to only keep supporting each BIG version release for a fixed period of time.
-	We could possibly start co-versioning other Paddle repos / tools with the big integer versions. So, for example, when we release Paddle 3.0, we could leapfrog VisualDL (which is now nearing v 1.0, a fairly arbitrary choice) to 3.0 at the same time. And then when the next major release is made, all other supporting tools are concurrently given a release with the big version number too. There is no reason any user needs to understand that v0.7 of one Paddle tool works with v3.0 or Paddle and so on. This is, to put in DL words, convoluted. This brings everyone onto the same page and shows much more momentum to the public. TensorFlow does something similar today.

We need to discuss the implications on model compatibility. Model versioning, particularly backwards compatibility at the pace we are moving at, is complex and needs to justified in great length and depth of discussion.

## Part 2

Secondly, we also don’t have a predictable release cycle. This one is obvious – most great software in the world defaults to a release cycle, along with exceptions for major overhauls. Based on what there is general consensus on, this cycle can be determined to be 6 months or 1 year. What is important is that the duration between releases be consistent, if not exactly the same, for most part.

Additionally, everyone at all times of development should know the version we are working towards, and the key value propositions of this release – which will be discussed In a transparent roadmap separately.

**Comment by varunarora** [comment] 2018-05-07 22:49
I talked to @wangkuiyi about this, and the resolution is to not change version names. Instead, we will default API versions associated version names. So the versions, as we publish in our documentation, are going to be:

- **develop** *(Fluid)*
- ... [whatever comes next] *(Fluid)*
- **v0.11.0** *(Fluid)*
- **v0.10.0** *(v2)*

v0.8.0 and v0.9.0 documentations are not going to show up on PaddlePaddle.org, as is already the case.

To users, we should be talking about release versions instead of API versions. API versions can be an idea known to developers of PaddlePaddle.

**Comment by panyx0718** [comment] 2018-05-08 00:51
Sorry, I missed this issue.

I agree that we need to have regular feature tracking and release cycle.

Have we considered this versioning scheme:
https://www.tensorflow.org/programmers_guide/version_compat#semantic_versioning_20
https://semver.org/

In general, we don't release big version (e.g. 1.x) unless we are sure that our API is stable and will be backward compatible.

**Comment by panyx0718** [comment] 2018-05-08 00:55
One benefit of semantic versioning is, our user can safely upgrade from, say 1.0 to 1.1, without worrying about any API compatibility issues. A big version change, say from 1.9 to 2.0, clearly signals potential backward incompatible changes.

**Comment by varunarora** [comment] 2018-05-09 20:54
@panyx0718 100% agree with your points. As shown here, in theory, we are doing semantic versioning already: http://paddlepaddle.org/docs/develop/documentation/fluid/en/dev/releasing_process_en.html.

Unfortunately, while we are not making backwards incompatible changes to the API just yet, we have created namespaces to introduce new APIs. Like `v2` and `fluid`. Imho, we should have released big version with `v2` after we decided to not actively work on it, and then kept small versions to keep iterating on the Fluid API. I have more ideas here for the upcoming releases: #10468.

If we believe that the next version / announcement is actually a stable release for Fluid, we should jump to a big version. The problem is that we have ended up in non-hard deadline for when we think Fluid will be ready and stable - and as a 4 year old project, never entered the major stable releases. Perhaps my suggestion is technical here, but perhaps it is changing how we think about managing how/when we distribute Paddle to the world. The longer we deprioritize stability and big releases, the more we jeopardize our ability to be to find a place in people's minds for deep learning (alternatively, one could make the argument that we try to be like Apple and do the greatest things much after the world has seen the technology, but its not like we are doing that either).

**Comment by shanyi15** [comment] 2018-08-15 11:04
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:04 UTC
