### ISSUE TITLE
What the correct version of protoc 

### ISSUE THREAD

**Issue by zhaofenqiang** [PaddlePaddle/Paddle#8798] opened 2018-03-06 10:33 UTC
I compiled the C-API following this [guide](http://paddlepaddle.org/docs/develop/documentation/zh/howto/capi/compile_paddle_lib_cn.html) on ubuntu16.04.

Firstly, I encountered this error:

> /home/zfq/Paddlepaddle/fluid/framework/attribute.h:23:49: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory

So I built the /paddle/fluid/framework/framework.pb.h by `protoc framework.proto  --cpp_out=.` and protoc's version is 2.6.1.
And then I encountered the error

> /home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

So I update the protoc to 3.5.1 following the [official guide](https://github.com/google/protobuf/blob/master/src/README.md).
This time the error is:

> /home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/zfq/Paddle/paddle/fluid/framework/framework.pb.h:14:2: error: #error your headers.
 #error your headers.

So I want to know what is the correct version of protoc.
Thanks!

**Comment by guoshengCS** [comment] 2018-03-06 11:33
The version 3.1 can work correctly for me.

**Comment by zhaofenqiang** [comment] 2018-03-07 01:34
Thank you! That works for me~

**Comment by bolt163** [comment] 2018-03-12 05:44
简直是坑爹的，我能说baidu提供的这些库是最难用的，没有之一；辣鸡！

**Comment by wangyang59** [comment] 2018-03-15 22:59
I have encountered similar problem. 
> In file included from /home/wangyang59/Projects/Paddle/paddle/fluid/framework/op_desc.h:19:0,
                 from /home/wangyang59/Projects/Paddle/paddle/fluid/framework/block_desc.h:23,
                 from /home/wangyang59/Projects/Paddle/paddle/fluid/platform/device_tracer.cc:23:
/home/wangyang59/Projects/Paddle/paddle/fluid/framework/attribute.h:23:49: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
 #include "paddle/fluid/framework/framework.pb.h"
                                                 ^
compilation terminated.
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o] Error 1
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/all] Error 2

I temporally solved it by manually compile the `framework.proto` using the built `protoc`. It seems that the cmake didn't do the protoc compilation automatically.

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC
Labels: User
