### ISSUE TITLE
First round parameters of trainer and pserver was NOT identical

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#11843] opened 2018-06-29 08:20 UTC
The parameters and bias in our program will be initialised with the code below:

```python
    def set_default_param_initializer(self):                                    
        """                                                                     
        Set the default initializer for the parameter with Xavier.              
                                                                                
        Args:                                                                   
            None.                                                               
                                                                                
        Returns:                                                                
            None.                                                               
        """                                                                     
        self.set_default_initializer(Xavier())                                  
                                                                                
    def set_default_bias_initializer(self):                                     
        """                                                                     
        Set the default initializer for the bias with Constant(0.0).            
                                                                                
        Args:                                                                   
            None.                                                               
                                                                                
        Returns:                                                                
            None.                                                               
        """                                                                     
        self.set_default_initializer(Constant(0.0)) 
```

The bias was inited with 0.0f;

And the params was inited with uniform_random_seed(0):

```CPP
    if (seed == 0) {                                                               
      seed = std::random_device()();                                               
    }      
```

So it's true random if the program was ran in single-machine mode.

However, in distributed mode, the pserver will initialise all parameters randomly too, which will lead to the difference between params in pserver and params in trainer:

```
Weigth w1 in Trainer -> uniform_random_seed(0) -> [0.4, 0.3, 0.5]
Weigth w1 in Trainer -> uniform_random_seed(0) -> [0.4, 0.3, 0.5]
```

This difference will be eliminated after the first round of training, but it means that the first round params was NOT identical and the training in first round means nothing...

**Comment by velconia** [comment] 2018-06-29 09:05
Actually we could add a new initializer here, maybe called the ```remote_initializer``` or ```pserver_initializer```, which will use recv_op to receive the params from pserver initialise the params in trainer

**Comment by velconia** [comment] 2018-06-29 09:08
@typhoonzero which name would u prefer here, ```remote_initializer``` or the ```pserver_initializer```?

**Comment by shanyi15** [comment] 2018-08-15 10:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:59 UTC
