### ISSUE TITLE
The difference between REGISTER_OP and REGISTER_OPERATOR

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7147] opened 2018-01-02 12:44 UTC
I see some ops using `REGISTER_OPERATOR`, while others using `REGISTER_OP` .  For examples,
- `REGISTER_OPERATOR(sum, ops::SumOp, ops::SumOpMaker, ops::SumGradMaker, ops::SumOpVarTypeInference);`
- `REGISTER_OP(conv2d, ops::ConvOp, ops::Conv2DOpMaker, conv2d_grad, ops::ConvOpGrad);`

What's the difference between them? And how we choose when we write a new op?

**Comment by chengduoZH** [comment] 2018-01-03 03:10
I'm a little confused about this, too. It's hard to see what these two macros do.

**Comment by chengduoZH** [comment] 2018-01-03 03:17
`REGISTER_OP` is clearer.
`REGISTER_OP(op_name, op_infershape, op_maker_class, grad_op_name,  grad_op_infershape)`
`grad_op_maker_class` will use the [default](https://github.com/PaddlePaddle/Paddle/blob/87f46ebb368929feae76b7d909944b317d7dad92/paddle/framework/op_registry.h#L159).

**Comment by jacquesqiao** [comment] 2018-01-03 04:55
目前REGISTER_OPERATOR是真正做register的宏，REGSITER_OP本省也会调用REGISTER_OPERATOR,
REGISTER_OPERATOR需要op实现下边几个类：
 - OpProtoAndCheckerMaker
- GradOpDescMakerBase
- VarTypeInference
- InferShapeBase

有一些op没有单独实现InferShapeBase和GradOpDescMakerBase，而是把InferShape放在了op_with_kernel里面，这样的话可以使用REGSITER_OP来注册，如果独立实现了InferShapeBase和GradOpDescMakerBase，就可以使用REGISTER_OPERATOR来注册，最终应该都统一到使用REGISTER_OPERATOR来注册。这一块确实还需要整理一下。

**Comment by luotao1** [comment] 2018-01-03 05:04
> 这一块确实还需要整理一下。

请问有整理计划么，大概什么时候会完成呢？

**Comment by luotao1** [comment] 2018-01-03 06:28
related #7158

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
