### ISSUE TITLE
meet "Unexpected branch" error in CacheOnePassInMemory

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/Paddle#808] opened 2016-12-09 09:55 UTC
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by gaoshan2006** [comment] 2016-12-09 10:02
After I compiled and installed, I run the demo "export PYTHONPATH=`pwd`   ./train.sh". But the test case run some time, an error occurs as bellows:
.......................................................
I1209 17:43:14.912488 51984 TrainerInternal.cpp:205] ___fc_layer_0__.w0   avg_abs_val=0.0975923   max_val=0.270491    avg_abs_grad=1.54177     max_grad=2.47025    
I1209 17:43:14.912603 51984 TrainerInternal.cpp:205] ___fc_layer_0__.wbias avg_abs_val=0.0126017   max_val=0.0126019   avg_abs_grad=2.51462     max_grad=2.51462    

I1209 17:43:14.912660 51984 TrainerInternal.cpp:163]  Batch=2000 samples=256000 AvgCost=0.202445 CurrentCost=0.167631 Eval: classification_error_evaluator=0.0825937  CurrentEval: classification_error_evaluator=0.0636719 
I1209 17:43:14.912695 51984 DataProvider.h:351] the double-buffer is starting ...
F1209 17:43:14.912730 51984 PyDataProvider2.cpp:1009] Unexpected branch
*** Check failure stack trace: ***
    @     0x3fff9230cf8c  (unknown)
    @     0x3fff9230fa0c  (unknown)
    @     0x3fff9230c9b4  (unknown)
    @     0x3fff92310634  (unknown)
    @         0x102a9444  paddle::CacheOnePassInMemory::reset()
    @         0x102acb0c  paddle::PyDataProvider2::resetImpl()
    @         0x102acde4  paddle::PyDataProvider2::reset()
    @         0x1033f098  paddle::Tester::testOnePeriod()
    @         0x10318ed4  paddle::Trainer::trainOnePass()
    @         0x1031cb40  paddle::Trainer::train()
    @         0x1013db50  main
    @     0x3fff91e64580  generic_start_main.isra.0
    @     0x3fff91e64774  __libc_start_main
    @              (nil)  (unknown)
/bin/paddle: line 81: 51984 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

I checked the source code, The error is from reset() in file "PyDataProvider2.cpp",   It looks the code should not run into this branch normally. But why this error occurred ? Thanks

**Comment by gaoshan2006** [comment] 2016-12-09 10:04
The error is from here:

 virtual bool reset() {
    if (objPool_->empty() && droppedPool_->empty()) {
      return true;
    } else if (objPool_->empty()) {
      std::swap(objPool_, droppedPool_);
      return false;
    } else {
      **LOG(FATAL) << "Unexpected branch";** <--------why did code run into this branch ?      }
  }

**Comment by luotao1** [comment] 2017-07-19 08:16
Too old to close this issue. If the problem is not resolved, please reopen the issue.

**Closed** 2017-07-23 07:03 UTC
