### ISSUE TITLE
使用gpu进行预测时，报错Check failed: stat == CUBLAS_STATUS_SUCCESS (1 vs. 0) [cublas status]: not initialized 

### ISSUE THREAD

**Issue by shell-no-shell** [PaddlePaddle/Paddle#11624] opened 2018-06-21 05:22 UTC
错误如下，麻烦问一下怎么解决
*** Check failure stack trace: ***
    @     0x7ffdb5d26bcd  google::LogMessage::Fail()
    @     0x7ffdb5d2a67c  google::LogMessage::SendToLog()
    @     0x7ffdb5d266f3  google::LogMessage::Flush()
    @     0x7ffdb5d2bb8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffdb5cd8ab7  hl_matrix_mul()
    @     0x7ffdb5b445c7  paddle::GpuMatrix::mul()
    @     0x7ffdb5b44c21  paddle::GpuMatrix::mul()
    @     0x7ffdb5980759  paddle::MixedLayer::forward()
    @     0x7ffdb5a30f4d  paddle::NeuralNetwork::forward()
    @     0x7ffdb58d409d  _wrap_GradientMachine_forward
    @           0x4b4cb9  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x526d1a  gen_iternext
    @           0x4b1fee  PyEval_EvalFrameEx
    @           0x526d1a  gen_iternext
    @           0x4b1fee  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x529340  function_call
    @           0x4238a0  PyObject_CallFunctionObjArgs
    @     0x7ffde66f6ea9  baidu::rpc::CallMethodImpl()
    @     0x7ffde66f88fc  baidu::rpc::CallPythonMethod()

**Comment by jacquesqiao** [comment] 2018-06-21 11:39
这个日志看不太出来问题，有更详细的日志或者代码么

**Comment by jacquesqiao** [comment] 2018-06-21 11:41
https://github.com/PaddlePaddle/Paddle/issues/5669 这里看起来已经修复了，你是不是要升级一下版本？

**Comment by shell-no-shell** [comment] 2018-06-21 11:53
@jacquesqiao 在百度rpc框架中调用的 相当于一个http服务 应该也是多线程一类的处理 我用的python  5669是c-api，是同步升级的吗

**Comment by jacquesqiao** [comment] 2018-06-22 01:54
`python 5669`是啥

**Comment by shell-no-shell** [comment] 2018-06-22 11:25
@jacquesqiao 。。。。 https://github.com/PaddlePaddle/Paddle/issues/5669

**Comment by muyunzhe** [comment] 2018-06-25 05:45
@jacquesqiao 这个问题 麻烦尽快帮忙解决下，上线部署急用

**Comment by ktlichkid** [comment] 2018-06-25 06:51
能否请提供更详细的日志和出错的代码？

**Comment by shell-no-shell** [comment] 2018-06-25 08:46
@ktlichkid 在机器上进程加载模型 预测是没有问题，现在模型的加载预测是运行在一个框架中的一个线程，是不是多个线程的时候，使用gpu会有问题

**Comment by shanyi15** [comment] 2018-08-15 10:20
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:20 UTC
Labels: User
