### ISSUE TITLE
FP32 latency growth for ERNIE model

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#27136] opened 2020-09-07 10:10 UTC
Using application:
```
cd /root/models/benchmark/Inference/c++/ernie
KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 ./run.sh -1 1 /data/PaddlePaddle/trained_models/ERNIE/ernie_fp32_model /data/PaddlePaddle/datasets/ernie/Ernie_dataset/1.8w.bs1

```
which is get from the repository: 
https://github.com/PaddlePaddle/benchmark.git

for measuring latency
it can be observed that latency grows significant (so performance drops) and permanently starting from the commit: f9066e6a6fcfaea2c7bdf19762eb630c7a0a7985

This observation is for *fp32* only

There were more latency growths before but from the mentioned commit this not getting better

![image](https://user-images.githubusercontent.com/10847947/92377000-bf9aa380-f103-11ea-8a2c-29f61411b774.png)

**Comment by luotao1** [comment] 2020-09-07 11:59
@pmajchrzak What's your machine?
@OliverLPH Could you help see it, since our benchmark doesn't catch this error.
<img width="895" alt="图片" src="https://user-images.githubusercontent.com/6836917/92385491-90585680-f144-11ea-8367-9b1e6b5b9cca.png">
And what's our machine?

**Comment by pmajchrzak** [comment] 2020-09-07 12:13
Measured on:
```
Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 20
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3900.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 28160K
```
Seems that on skylake this not appeared

**Comment by luotao1** [comment] 2020-09-07 12:16
@pmajchrzak Do you run this ernie model every day?

**Comment by pmajchrzak** [comment] 2020-09-07 12:16
yes, for almost each commit

**Comment by pmajchrzak** [comment] 2020-09-07 12:17
Maybe something was changed in benchmark repository

**Comment by pmajchrzak** [comment] 2020-09-07 12:27
This is almost probably true of a change to the benchmark repository that occurred sometime around August 27-30

**Comment by pmajchrzak** [comment] 2020-09-07 12:41
Maybe here?
https://github.com/PaddlePaddle/benchmark/commit/b928a069cbe77a3a0b12706422b63241fcdbfc11

**Comment by OliverLPH** [comment] 2020-09-07 12:52
@luotao1 
Our machine's cpu is `Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz`

@pmajchrzak 
I will check this issue on my local machine.

**Comment by OliverLPH** [comment] 2020-09-08 03:41
@pmajchrzak @luotao1 
I test this issue on `6271C CPU` local machine, but I got same results as our performance monitor.

My test steps are as following
```
workdir=$(cd $(dirname $0); pwd

# download Ernie float32 model
mkdir -p ${workdir}/Data/Ernie_fp32_model
cd ${workdir}/Data/Ernie_fp32_model
wget http://paddle-inference-dist.bj.bcebos.com/int8/QAT_models/fp32/ernie_fp32_model.tar.gz
tar -xvf ernie_fp32_model.tar.gz

# download NLP dataset
mkdir -p ${workdir}/Data/NLP_data
cd ${workdir}/Data/NLP_data
wget http://paddle-inference-dist.bj.bcebos.com/int8/Ernie_dataset.tar.gz
tar -xzvf Ernie_dataset.tar.gz

export GLOG_logtostderr=1
export KMP_AFFINITY="verbose,granularity=fine,compact,1,0"

fp32_model=${workdir}/Data/Ernie_fp32_model/ernie_fp32_model
data=${workdir}/Data/NLP_data/Ernie_dataset/1.8w.bs1
./run.sh -1 1 $fp32_model $data
```

This is ernie fp32 inference log, FYI
[ernie_fp32_tid1.log](https://github.com/PaddlePaddle/Paddle/files/5185909/ernie_fp32_tid1.log)

I will try to reproduce on `6148` machine later

**Comment by pmajchrzak** [comment] 2020-09-08 04:10
@OliverLPH 
> I will try to reproduce on `6148` machine later

And maybe try for different SHA of https://github.com/PaddlePaddle/benchmark/
before 08/26/2020 and after 08/30/2020

**Comment by OliverLPH** [comment] 2020-09-08 05:07
> @OliverLPH
> 
> > I will try to reproduce on `6148` machine later
> 
> And maybe try for different SHA of https://github.com/PaddlePaddle/benchmark/
> before 08/26/2020 and after 08/30/2020

Still on `6271 cpu` 
I have tried [f25597](f25597e5a54bbe9c756eb9b83d4881c05b7cdc13) (sep 7) and [40e8b9](https://github.com/PaddlePaddle/benchmark/commit/40e8b92502fc244efc7a499e5a0d35da73509914
) (Aug 17) of https://github.com/PaddlePaddle/benchmark.git  repo, inference average latency is around 236.454 ms which is the same as previous measurements

**Comment by OliverLPH** [comment] 2020-09-08 06:43
@pmajchrzak 
I tried following inference lib on `Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz` machine, but I still can't reproduce your results.
```shell 
GIT COMMIT ID: d6ee0868a45a80b6560f1e70c3a41ed4064683d0
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
CXX compiler version: 4.8.5
```
Test environment is based on docker image `hub.baidubce.com/paddlepaddle/paddle:latest-dev`, gcc 4.8.5.
Could you plz try this image again on your `6148` machine? And what's your test environment?

[cpu_6148_ernie_fp32_tid1.log](https://github.com/PaddlePaddle/Paddle/files/5186497/ernie_fp32_tid1.log)
![image](https://user-images.githubusercontent.com/14963836/92441276-808e5000-f1e0-11ea-8749-667c5b1e8fb6.png)

**Comment by pmajchrzak** [comment] 2020-09-08 08:09
@OliverLPH 
I will try to run sequence of git SHAs and try to find the cause.

**Comment by OliverLPH** [comment] 2020-09-08 09:27
@pmajchrzak 
Thanks for your effort~
could you provide more about you environment info? I want to compare difference between our environments.

**Comment by pmajchrzak** [comment] 2020-09-08 10:14
Our docker file based on paddlepaddle/paddle:latest-dev
and we run tests under Ubuntu 16_04

**Comment by lidanqing-vv** [comment] 2020-09-22 23:32
@pmajchrzak  Can I close this issue? If it still exist, provide more details as issue description

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by pmajchrzak** [comment] 2020-10-01 06:41
Yes, I think this issue can  be closed.

**Closed as completed** 2020-10-01 08:14 UTC
Labels: Intel
