### ISSUE TITLE
CUDA version issue when using PaddlePaddle through NVIDIA container

### ISSUE THREAD

**Issue by ahinchoi** [PaddlePaddle/Paddle#67982] opened 2024-09-04 01:38 UTC
### 问题描述 Issue Description

Hello,
First of all, thank you for creating this wonderful package!
I am trying to use PaddlePaddle by creating a docker image that pulls from the containers maintained on the official NVIDIA NGC catalog. 
[https://catalog.ngc.nvidia.com/orgs/nvidia/containers/paddlepaddle/tags](url) 
I am doing this by creating a vscode.Dockerfile that contains the following:

`FROM {the container copied from the above website}
# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
# Change ubuntu repository to Kakao mirror
RUN sed -i 's|http://[a-z]\+.[ubuntu.com](http://ubuntu.com/)|https://mirror.kakao.com/|g' /etc/apt/sources.list
# Configure python repository with Kakao mirror
RUN printf "%s\n"\
    "[global]"\
    "index-url=https://mirror.kakao.com/pypi/simple/"\
    "extra-index-url=https://pypi.org/simple/"\
    "trusted-host=[mirror.kakao.com](http://mirror.kakao.com/)"\
    > /etc/pip.conf && pip install --no-cache-dir -U pip && pip install --no-cache-dir idna jupyter
# Install essential packages
RUN apt-get update -qq && apt-get install -qqy\
        sudo\
        tzdata\
        vim\
        tmux\
        curl\
        jq\
        git\
        libgl1-mesa-glx\
        libglib2.0-0\
        ffmpeg x264 libx264-dev
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN pip install opencv-python albumentations numpy SimpleITK pydicom==2.1.1 Pillow scipy matplotlib tqdm natsort seaborn easydict resnest scikit-learn h5py monai scikit-learn ffmpeg-python
RUN apt clean && rm -rf /var/lib/apt/lists/*
# Install and launch VS Code Server
ENTRYPOINT ["sh", "-c", "\
    curl -x '' -sSkL https://gpu-cluster.mi2rl.co/public/vscode/fetch.sh | sh && \
    code tunnel --no-sleep --accept-server-license-terms --log error --name $SUBDOMAIN"]`

When run with `docker-compose -up --build` on ubuntu, this successfully creates a docker image which I can then access through VScode. 

The problem is that no matter which version of the container I download, the CUDA version is constantly one version lower than what is required by PaddlePaddle, and therefore I cannot use the package. For example, pulling from container version 23.11 gives me CUDA version 12.2.0, while the package requires 12.3.0. 

I have tried to just update my CUDA version, but this, for some unknown reason, just breaks my system. 

Is there any way through which I might solve this issue?

Thank you for your time in advance.

### 版本&环境信息 Version & Environment Information

Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 22.04
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: N/A
CMake version: version 3.25.1
Libc version: glibc 2.35
Python version: 3.10.12

CUDA version: 12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
cuDNN version: 8.9.5
Nvidia driver version: 535.183.01
Nvidia driver List: 
GPU 0: NVIDIA TITAN RTX

**Comment by warrentdrew** [comment] 2024-09-04 06:20
Hello, an easy way to get a docker image with cuda 12.3 might be to run
`docker pull paddlepaddle/paddle:3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6`
which pulls the image from dockerhub. 
All the paddle images from dockerhub are available here: 
https://hub.docker.com/r/paddlepaddle/paddle/tags?page=&page_size=&ordering=&name=

**Comment by ahinchoi** [comment] 2024-09-04 07:42
Thank you! That solved the issue.. 
Although I'm still wondering why the official container would provide incompatible versions of CUDA and PaddlePaddle.

**Comment by jeng1220** [comment] 2024-09-25 06:46
@ahinchoi ,
Could you please run this command?
```sh
docker run --gpus all nvcr.io/nvidia/paddlepaddle:23.11-py3 python -c 'import paddle; paddle.utils.run_check()'
```
The correct return should be:
```sh
==================
== PaddlePaddle ==
==================

NVIDIA Release 23.11 (build 73911559)
Paddle Version 2.5.2

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright (c) 2016-2023 PaddlePaddle Authors. All Rights Reserved

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for Paddle.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

I0925 06:40:06.448657     1 interpretercore.cc:237] New Executor is Running.
W0925 06:40:06.450043     1 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.4, Runtime API Version: 12.3
W0925 06:40:06.455236     1 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
I0925 06:40:06.715168     1 interpreter_util.cc:518] Standalone Executor is Used.
Running verify PaddlePaddle program ...
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

> For example, pulling from container version 23.11 gives me CUDA version 12.2.0, while the package requires 12.3.0.

The NVIDIA Optimized Frameworks 23.11 used CUDA 12.3.0 instead of 12.2.0. Please see the [release note](https://docs.nvidia.com/deeplearning/frameworks/mxnet-release-notes/rel-23-11.html). 
Every docker image has prebuilt PaddlePaddle and was verified before release.

**Comment by onecatcn** [comment] 2024-10-24 02:12
@ahinchoi I hope the answer provided above has resolved your issue. Please kindly close the issue if the issue is resolved, or share your test result otherwise.

**Comment by onecatcn** [comment] 2024-10-31 02:06
we are closing the issue since no response was provided

**Closed as completed by onecatcn** 2024-10-31 02:06 UTC
Labels: NVIDIA, type/build, status/close
