### ISSUE TITLE
attr_type 接口返回值错误

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#10951] opened 2018-05-26 09:16 UTC
在 python fluid 中，使用 attr_type(attr_name) 对 padding_idx 进行类型获取时，会返回 AttrType.??? 而不是 AttrType.LONG。

  ops {
    inputs {
      parameter: "Ids"
      arguments: "src_wordseq"
    }
    inputs {
      parameter: "W"
      arguments: "embedding_0.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "embedding_0.tmp_0"
    }
    type: "lookup_table"
    attrs {
      name: "padding_idx"
      type: LONG
      l: -1
    }
    attrs {
      name: "is_distributed"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "is_sparse"
      type: BOOLEAN
      b: true
    }
    is_target: false
  }

**Comment by Yancey1989** [comment] 2018-05-28 02:06
Hi，麻烦提供下可以复现的代码片段吧。

**Comment by shanyi15** [comment] 2018-08-15 11:35
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:35 UTC
Labels: User
