### ISSUE TITLE
Performance drop in models GoogleNetV1, Demark, Feature, VGG16 and VGG19

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#34458] opened 2021-07-28 09:58 UTC
Along with the cf3ddd3b29314cb50953b231a6de7eb82563bcab commit (22.06.2021), a performance drop was noticed on the develop branch for several of the analyzed models:

- GoogleNetV1
- Demark
- Feature
- VGG16
- VGG19

#### SKX:
```
           Turbo: OFF
            Name: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 28
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3800.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 39424K
```

#### CLX:
```
           Turbo: OFF
            Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 20
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3900.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 28160K
```

#### CPX:
```
           Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 4200.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 33792K
```
## The system on which the measurements were made:
UBUNTU 18.04

## CMAKE parameters used:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```
### TA_IC_googlenetV1:
```
/usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000  --batch_size=1  --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/googlenet/model
```
### TA_IC_demark:
```
/usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000 --batch_size=1 --infer_model=/data/PaddlePaddle/models/demark
```
### TA_IC_feature:
```
/usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000  --batch_size=1  --infer_model=/data/PaddlePaddle/models/feature
```
### TA_I8_IC_vgg16_int8:
```
OMP_NUM_THREADS=1 /usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --enable_int8=true --enable_fp32=false --infer_data=/data/PaddlePaddle/1G/imagenet/val.bin --warmup  --batch_size=1   --iterations=700  --cpu_num_threads=1 --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/int8v2/vgg16/model
```
### TA_I8_IC_vgg16_fp32:
```
OMP_NUM_THREADS=1 /usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --enable_int8=false --enable_fp32=true --infer_data=/data/PaddlePaddle/1G/imagenet/val.bin --warmup  --batch_size=1   --iterations=700  --cpu_num_threads=1 --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/int8v2/vgg16/model
```
### TA_I8_IC_vgg19_int8:
```
OMP_NUM_THREADS=1 /usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --enable_int8=true --enable_fp32=false --infer_data=/data/PaddlePaddle/1G/imagenet/val.bin --warmup  --batch_size=1   --iterations=700  --cpu_num_threads=1 --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/int8v2/vgg19/model
```
### TA_I8_IC_vgg19_fp32:
```
OMP_NUM_THREADS=1 /usr/bin/time -v /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --enable_int8=false --enable_fp32=true --infer_data=/data/PaddlePaddle/1G/imagenet/val.bin --warmup  --batch_size=1   --iterations=700  --cpu_num_threads=1 --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/int8v2/vgg19/model
```
## COMMENTS:

1. Along with the decline in performance, it can be noticed an increase in memory consumption by the application. The exception is the Demark model, in which a decrease in memory consumption was observed (and yet the performance also decreased)
2. The same commit is responsible for the decrease in the accuracy values in the models:
VGG16 INT8: before: 0.7204 after: 0.7180
VGG19 INT8: before: 0.7256 after: 0.7235

#### SKX:
![SKX](https://user-images.githubusercontent.com/10847947/127301481-f4d93fba-6c86-481d-a4d7-8e5ce008368d.PNG)

#### CLX:
![CLX](https://user-images.githubusercontent.com/10847947/127301503-3bbe7ffa-c2cc-4a1a-935e-4c7c7d038e8b.PNG)

#### CPX:
![CPX](https://user-images.githubusercontent.com/10847947/127301517-3ed743f6-e0c2-404c-8e35-698397ab3554.PNG)

**Comment by bjjwwang** [comment] 2021-07-28 10:18
Thanks for sharing. We will try to find a conclusion in one day or two.

**Comment by lidanqing-vv** [comment] 2021-08-04 07:44
@bjjwwang Are you able to reproduce it, do you need any support ?

**Comment by baoachun** [comment] 2021-08-05 05:27
@pmajchrzak 
This PR [34625](https://github.com/PaddlePaddle/Paddle/pull/34625) is to fix the performance degradation problem. In order to ensure that all the above model performance degradation problems are solved, could you please verify it based on the new code？Because we lack some models.

**Comment by pmajchrzak** [comment] 2021-08-05 08:36
> This PR [34625](https://github.com/PaddlePaddle/Paddle/pull/34625) is to fix the performance degradation problem. In order to ensure that all the above model performance degradation problems are solved, could you please verify it based on the new code？Because we lack some models.

It seems the performance drop has been fixed. The results returned to the level before the decline

**Comment by baoachun** [comment] 2021-08-05 09:10
> > This PR [34625](https://github.com/PaddlePaddle/Paddle/pull/34625) is to fix the performance degradation problem. In order to ensure that all the above model performance degradation problems are solved, could you please verify it based on the new code？Because we lack some models.
> 
> It seems the performance drop has been fixed. The results returned to the level before the decline

OK，thanks！

**Comment by baoachun** [comment] 2021-08-05 10:52
> > This PR [34625](https://github.com/PaddlePaddle/Paddle/pull/34625) is to fix the performance degradation problem. In order to ensure that all the above model performance degradation problems are solved, could you please verify it based on the new code？Because we lack some models.
> 
> It seems the performance drop has been fixed. The results returned to the level before the decline

What's more, there is another problem, our CI did not find the model performance degradation problem, but you have. Is there anything special about the setup you tested?

**Comment by pmajchrzak** [comment] 2021-08-05 12:03
We have our own, separate validation system in which we test the optimization models that our internal team works or has worked on. Whenever possible, we pass each new commit (on develop branch) through our system.

The description of this issue includes the details of our setup (including turbo off) and the command lines used. Nothing else out of the ordinary.

**Comment by baoachun** [comment] 2021-08-06 03:06
> We have our own, separate validation system in which we test the optimization models that our internal team works or has worked on. Whenever possible, we pass each new commit (on develop branch) through our system.
> 
> The description of this issue includes the details of our setup (including turbo off) and the command lines used. Nothing else out of the ordinary.

Got it，thanks.

**Comment by lidanqing-vv** [comment] 2021-08-09 03:33
Thank you a lot! I close this issue.

**Closed as completed by lidanqing-vv** 2021-08-09 03:33 UTC
Labels: Intel
