### ISSUE TITLE
capi infer 报错

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#9498] opened 2018-03-29 09:48 UTC
本地capi测试可以infer，但线上运行报错
```
F0329 17:02:42.385035 13654 SequencePoolLayer.cpp:59] Check failed: starts->getData()[newBatchSize_] == input.getBatchSize() (32694 vs. 43) 
*** Check failure stack trace: ***
    @     0x7fb7041c476d  google::LogMessage::Fail()
    @     0x7fb7041c821c  google::LogMessage::SendToLog()
    @     0x7fb7041c4293  google::LogMessage::Flush()
    @     0x7fb7041c972e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb704212138  paddle::SequencePoolLayer::forward()
    @     0x7fb704263b7d  paddle::MaxLayer::forward()
    @     0x7fb7043284bd  paddle::NeuralNetwork::forward()
    @     0x7fb704212138  paddle::SequencePoolLayer::forward()
    @     0x7fb704263b7d  paddle::MaxLayer::forward()
    @     0x7fb7043284bd  paddle::NeuralNetwork::forward()
    @     0x7fb7041c0676  paddle_gradient_machine_forward
    @     0x7fb704212138  paddle::SequencePoolLayer::forward()
    @     0x7fb704263b7d  paddle::MaxLayer::forward()
    @     0x7fb7043284bd  paddle::NeuralNetwork::forward()
    @     0x7fb7041c0676  paddle_gradient_machine_forward
    @     0x7fb703f11cdf  TrafficModel::traffic_predict()
    @     0x7fb703f123c3  TrafficModel::predict()
    @           0x7b6742  rc::CnnPredictor::predict()
    @           0x7b6c83  rc::CnnPredictor::predict()
    @           0x7ae754  rc::Predictor::do_predict()
    @           0x7ae954  rc::Predictor::do_predict()
    @     0x7fb706e631c3  start_thread
    @     0x7fb70342c12d  __clone
    @              (nil)  (unknown)
```

**Comment by reyoung** [comment] 2018-03-29 10:19
这个现象应该是数据处理有问题。请确定下本地跑的数据和线上跑的数据，格式一致。

**Comment by yeyupiaoling** [comment] 2018-04-02 03:19
@reyoung 
说到这个，我顺便问一下，CAPI的要怎么处理图像，看这个问题：#8884

**Comment by shanyi15** [comment] 2018-08-15 11:37
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:37 UTC
Labels: User, Waiting for User Feedback, 屯
