### ISSUE TITLE
集群训练出现list index out of range错误，但是data_reader没有任何问题

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#11505] opened 2018-06-15 04:04 UTC
Fri Jun 15 11:59:08 2018[1,6]<stderr>:[INFO 2018-06-15 11:59:08,071 video_mean_provider_copy_1.py:33] label_dict len: 6300313
Fri Jun 15 11:59:12 2018[1,10]<stderr>:F0615 11:59:12.354856 23684 PyDataProvider.cpp:367] Check failed: (obj) != nullptr Python Error: <type 'exceptions.IndexError'> : list index out of range
Fri Jun 15 11:59:12 2018[1,10]<stderr>:Python Callstack: 
Fri Jun 15 11:59:12 2018[1,10]<stderr>:            /home/normandy/maybach/313782/workspace/paddle/paddle/trainer/PyDataProviderWrapper.py : 363
Fri Jun 15 11:59:12 2018[1,10]<stderr>:            /home/normandy/maybach/313782/workspace/paddle/paddle/trainer/PyDataProviderWrapper.py : 529
Fri Jun 15 11:59:12 2018[1,10]<stderr>:            /home/normandy/maybach/313782/workspace/paddle/paddle/trainer/PyDataProviderWrapper.py : 475
Fri Jun 15 11:59:12 2018[1,10]<stderr>:Call function getNextBatch failed.
Fri Jun 15 11:59:12 2018[1,10]<stderr>:*** Check failure stack trace: ***
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0xe97e4c  google::LogMessage::Fail()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0xe97da4  google::LogMessage::SendToLog()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0xe97839  google::LogMessage::Flush()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0xe9a5fa  google::LogMessageFatal::~LogMessageFatal()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0x5f13f0  paddle::PyDataProvider::getNextBatchInternal()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @           0x5ce1c2  paddle::DoubleBuffer::asyncLoadBatch()
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @     0x7fa69c08a8a0  execute_native_thread_routine
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @     0x7fa69cb201c3  start_thread
Fri Jun 15 11:59:12 2018[1,10]<stderr>:    @     0x7fa69b7fb12d  __clone
Fri Jun 15 11:59:12 2018[1,10]<stderr>:./train.sh: line 207:  3002 Aborted                 PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ '[' 134 -ne 0 ']'
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ kill_pserver2_exit
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ ps aux
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ grep paddle_pserver2
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ grep paddle_cluster_job
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ grep -v grep
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ cut -c10-14
Fri Jun 15 11:59:12 2018[1,10]<stderr>:+ xargs kill -9
Fri Jun 15 11:59:13 2018[1,10]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Fri Jun 15 11:59:13 2018[1,10]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Fri Jun 15 11:59:13 2018[1,10]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Fri Jun 15 11:59:13 2018[1,10]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Fri Jun 15 11:59:13 2018[1,10]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Fri Jun 15 11:59:13 2018[1,10]<stderr>:+ get_stack
Fri Jun 15 11:59:13 2018[1,10]<stderr>:+ set +x

**Comment by kuke** [comment] 2018-06-16 04:44
请问是否在本地验证过data reader？看起来像数据的问题

**Comment by cbstyle** [comment] 2018-06-20 02:44
小数据量，本地测data reader没问题~ 而且看集群日志，都是在数据load完之后才出现这个问题的

**Comment by shanyi15** [comment] 2018-08-15 11:34
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:34 UTC
Labels: User
