### ISSUE TITLE
[Highest priority] FP32 transformer-like model inference acceleration

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#37930] opened 2021-12-07 13:06 UTC
ref to https://github.com/oneapi-src/oneDNN/issues/1207

**Comment by baoachun** [comment] 2021-12-09 02:37
@lidanqing-intel

**Comment by lidanqing-vv** [comment] 2021-12-13 09:19
![771787280](https://user-images.githubusercontent.com/47151829/145784895-4fe85368-3506-4507-97ba-66dec423d55d.jpg)
**线程数** means : thread_num

**Comment by lidanqing-vv** [comment] 2022-01-17 07:28
@lidanqing-intel Use Paddle new executor for multithreading performance benchmark.

**Comment by lidanqing-vv** [comment] 2022-02-15 10:26
@jczaja This issue has highest priorty, higher than conv3d mkldnn. VIT-OCR single thread performance is slow and need to be improved

**Comment by jakpiase** [comment] 2022-02-18 20:45
@lidanqing-intel How can I run these models? If I will have some steps to reproduce the performance and how to run them, I can start working on it

**Comment by jakpiase** [comment] 2022-02-21 17:00
I have an idea how to speed it up (fc+reshape2+transpose2 fuse), but it can be done only after merging PR related adding memory-descriptor into tensor class

**Comment by lidanqing-vv** [comment] 2022-03-10 14:12
Instructions to run the models is in attachment of #PADDLEQ-1691

**Comment by lidanqing-vv** [comment] 2022-04-18 06:42
VIT-OCR fp32 model is improved by PR https://github.com/PaddlePaddle/Paddle/pull/41776. Single thread 4% rise. More improvement will be added.

**Comment by lidanqing-vv** [comment] 2022-05-07 09:15
I think deepmd multi-threading also have same issue. That multithreading does not scale

**Comment by yaomichael** [comment] 2022-05-23 13:28
@baoachun @jiangjiajun can you help remove keyword "multithreading" from the title, as we agreed?
On the other side, @jczaja is still working on further improve single thread performance.

**Comment by lidanqing-vv** [comment] 2022-05-24 13:35
@baoachun  
Since this issue is opened, several fusions related to VIT-OCR have been merged, like `conv + gelu` and `fc + gelu` and `fc + elementwise_add`.
The performance table should be updated.
Could you please tell us which machine the performance in the table is tested, we will test this VIR-OCR with newest develop and update the performance table

**Comment by lidanqing-vv** [comment] 2022-05-30 03:50
Hi, @Silv3S  Since achun left this work. Could you please update VIT-OCR performance of recent develop here ?

**Comment by jczaja** [comment] 2022-05-31 14:21
@yaomichael We need following details to start investigate this issue:
1. Paddle oneDNN
- Paddle SHA 
- Paddle cmake commandline
- commandline of test for Paddle oneDNN
2. onnx runtime
- SHA of onnx runtime
- commandline of building onnx runtime
- commands used to export model  and run model
3. platform spec where experiments took place

**Comment by tsocha** [comment] 2022-06-10 12:01
@yaomichael any update on @jczaja questions?

**Comment by tsocha** [comment] 2022-06-28 12:14
@lidanqing-intel @baoachun were can I find a VIT-OCR model in ONNXRuntime format?
Was it generated or is it stored somewhere?

**Comment by tsocha** [comment] 2022-09-07 13:19
There is a performance difference of MatMul and Softmax operators in oneDNN Jit code versus ONNXRuntime.
The issue has been reported to oneDNN library, it's under investigation.

**Closed as completed** 2023-01-11 11:38 UTC
Labels: high priority, Intel, status/close
