### ISSUE TITLE
OCR Q3 Plan

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#10350] opened 2018-05-02 13:20 UTC
### 1. east检测 (8周)
目标： 对齐baseline
上线模型training数据集：100W级别

#### 1.1 所需op

- p0: dice-loss  （2周*1人）@wanghaoshuang
- p1: 多边形的非最大抑制 (2周*1人)  @ocr
- p2: IoU loss （2周*1人）@ocr
- p3: Cos loss  （2周*1人）@wanghaoshuang

#### 1.4 效果验证 （4周 * 2人）@ocr + @wanghaoshuang

- benchmark training 效果对齐(icdar15)
- 预测库效果对齐（caffe）

#### 2.2 Attention （4周 * 1人）@shiwenguo + @wanghaoshuang

- 1d attention效果验证
- 2d attention效果验证

#### 3.1 所需ops

-  roi_perspective op

#### 3.3 合并DataReader

TODO:
- 确认tensorflow&caffe model转fluid model 
- 确认具体人力
- 是否可开源
- 确定east检测分支开发环境

**Comment by shanyi15** [comment] 2018-08-15 10:27
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:27 UTC
