### ISSUE TITLE
run capi sequence demo error (with capi cpu lib)

### ISSUE THREAD

**Issue by kurakimai** [PaddlePaddle/Paddle#6867] opened 2017-12-22 03:42 UTC
Capi lib link
https://paddleci.ngrok.io/viewLog.html?buildId=20609&buildTypeId=Manylinux1_CpuAvxCp27cp27mu&tab=artifacts

Run dense demo successed
Run sequence demo failed

It seems that lstm module in cpu lib still use gpu implemention

I1222 11:29:11.853574 30862 Util.cpp:166] commandline:  --use_gpu=False
I1222 11:29:11.856750 30862 GradientMachine.cpp:94] Initing parameters..
I1222 11:29:11.861506 30862 GradientMachine.cpp:101] Init parameters done.
F1222 11:29:11.866292 30862 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7fd5988f8ccd  google::LogMessage::Fail()
    @     0x7fd5988fc77c  google::LogMessage::SendToLog()
    @     0x7fd5988f87f3  google::LogMessage::Flush()
    @     0x7fd5988fdc8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd598d15073  hl_stream_synchronize()
    @     0x7fd5989d040e  paddle::LstmLayer::forwardBatch()
    @     0x7fd5989d1b62  paddle::LstmLayer::forward()
    @     0x7fd598a8c5ed  paddle::NeuralNetwork::forward()
    @     0x7fd5988f4c56  paddle_gradient_machine_forward
    @           0x40158d  main
    @     0x7fd5984dfbd5  __libc_start_main
    @           0x4010e9  (unknown)
    @              (nil)  (unknown)

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
Labels: User
