### ISSUE TITLE
Build Error in macOS 10.12 with Paddle Release V0.9.0

### ISSUE THREAD

**Issue by wondervictor** [PaddlePaddle/Paddle#1318] opened 2017-02-13 02:09 UTC
protobuf version 2.6.1
```
17 errors generated.
make[2]: *** [proto/CMakeFiles/paddle_proto.dir/DataConfig.pb.cc.o] Error 1
make[1]: *** [proto/CMakeFiles/paddle_proto.dir/all] Error 2
make: *** [all] Error 2
```

**Detail**

```
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:47:9: error:
      'OSAtomicCompareAndSwap32' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32(old_value, new_value,
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:502:9: note:
      'OSAtomicCompareAndSwap32' has been explicitly
      marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldVal...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:61:13: error:
      'OSAtomicCompareAndSwap32' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  } while (!OSAtomicCompareAndSwap32(old_value, new_value,
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:502:9: note:
      'OSAtomicCompareAndSwap32' has been explicitly
      marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldVal...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:68:10: error:
      'OSAtomicAdd32' is deprecated: first deprecated in
      macOS 10.12 - Use
      std::atomic_fetch_add_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  return OSAtomicAdd32(increment, const_cast<Atomi...
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:146:9: note:
      'OSAtomicAdd32' has been explicitly marked
      deprecated here
int32_t OSAtomicAdd32( int32_t __theAmount, volati...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:73:10: error:
      'OSAtomicAdd32Barrier' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_fetch_add() from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  return OSAtomicAdd32Barrier(increment, const_cas...
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:161:9: note:
      'OSAtomicAdd32Barrier' has been explicitly marked
      deprecated here
int32_t OSAtomicAdd32Barrier( int32_t __theAmount...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:77:3: error:
      'OSMemoryBarrier' is deprecated: first deprecated in
      macOS 10.12 - Use std::atomic_thread_fence() from
      <atomic> instead [-Werror,-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:749:9: note:
      'OSMemoryBarrier' has been explicitly marked
      deprecated here
void    OSMemoryBarrier( void );
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:85:9: error:
      'OSAtomicCompareAndSwap32Barrier' is deprecated:
      first deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong() from <atomic>
      instead [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32Barrier(old_value...
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:518:9: note:
      'OSAtomicCompareAndSwap32Barrier' has been
      explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t _...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:138:9: error:
      'OSAtomicCompareAndSwap64' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64(old_value, new_value,
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:628:9: note:
      'OSAtomicCompareAndSwap64' has been explicitly
      marked deprecated here
bool    OSAtomicCompareAndSwap64( int64_t __oldVal...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:152:13: error:
      'OSAtomicCompareAndSwap64' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  } while (!OSAtomicCompareAndSwap64(old_value, new_value,
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:628:9: note:
      'OSAtomicCompareAndSwap64' has been explicitly
      marked deprecated here
bool    OSAtomicCompareAndSwap64( int64_t __oldVal...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:159:10: error:
      'OSAtomicAdd64' is deprecated: first deprecated in
      macOS 10.12 - Use
      std::atomic_fetch_add_explicit(std::memory_order_relaxed)
      from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  return OSAtomicAdd64(increment, reinterpret_cast...
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:231:9: note:
      'OSAtomicAdd64' has been explicitly marked
      deprecated here
int64_t OSAtomicAdd64( int64_t __theAmount,
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:164:10: error:
      'OSAtomicAdd64Barrier' is deprecated: first
      deprecated in macOS 10.12 - Use
      std::atomic_fetch_add() from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
  return OSAtomicAdd64Barrier(increment,
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:247:9: note:
      'OSAtomicAdd64Barrier' has been explicitly marked
      deprecated here
int64_t OSAtomicAdd64Barrier( int64_t __theAmount,
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:5:
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.h:22:
In file included from /usr/local/include/google/protobuf/generated_message_util.h:44:
In file included from /usr/local/include/google/protobuf/stubs/once.h:81:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:184:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:173:9: error:
      'OSAtomicCompareAndSwap64Barrier' is deprecated:
      first deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong() from <atomic>
      instead [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:645:9: note:
      'OSAtomicCompareAndSwap64Barrier' has been
      explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t _...
        ^
In file included from /Users/vic/Downloads/Paddle-0.9.0/build/proto/DataConfig.pb.cc:12:
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:413:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<unsigned
      int,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_FIXED32>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(uint32, ...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:414:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<unsigned
      long long,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_FIXED64>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(uint64, ...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:415:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<int,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_SFIXED32>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(int32, T...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:416:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<long
      long,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_SFIXED64>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(int64, T...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:417:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<float,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_FLOAT>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(float, T...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:383:23: error:
      comparison of integers of different signs: 'int' and
      'const uint32' (aka 'const unsigned int')
      [-Werror,-Wsign-compare]
    for (int i = 0; i < new_entries; ++i) {
                    ~ ^ ~~~~~~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:418:1: note:
      in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<double,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_DOUBLE>'
      requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(double, ...
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:409:10: note:
      expanded from macro
      'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive...
         ^
17 errors generated.
make[2]: *** [proto/CMakeFiles/paddle_proto.dir/DataConfig.pb.cc.o] Error 1
make[1]: *** [proto/CMakeFiles/paddle_proto.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gangliao** [comment] 2017-02-13 02:15
The problem is from macOS 10.12 which replaced its atomic interface. You can git pull paddle develop branch, we already solved this issue. @wondervictor

**Comment by wondervictor** [comment] 2017-02-13 02:49
However, another error occurred
```
  To build lapack in libopenblas, you need to set gfortran compiler: cmake ..
  -DCMAKE_Fortran_COMPILER=...
```
I have installed MKL in my mac.

**Comment by gangliao** [comment] 2017-02-13 02:50
OK. You can set `cmake -DMKL_ROOT=xxx ..` @wondervictor

**Comment by gangliao** [comment] 2017-02-13 03:23
Any update? @wondervictor

**Comment by wondervictor** [comment] 2017-02-13 03:24
OK, thx~

**Comment by gangliao** [comment] 2017-02-14 02:20
This issue is solved, so I close it

**Closed** 2017-02-14 02:20 UTC
