### ISSUE TITLE
trainer seems does not retry connect to pserver in fault tolerant training

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#5189] opened 2017-10-28 07:39 UTC
```
nt/client.go:95 github.com/PaddlePaddle/Paddle/go/pserver/client/client.go:110]"
t=2017-10-28T07:31:09+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:09+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:10+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:10+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:20+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:20+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:21+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:21+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:25+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:25+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:31+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:31+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:33+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:33+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
processing  /pfs/mulan/home/yanxu05@baidu.com/mnist/train-00046
t=2017-10-28T07:31:40+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:40+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:42+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:42+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:44+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:44+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:50+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:50+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:51+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:51+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:52+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:52+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:55+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:55+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
t=2017-10-28T07:31:56+0000 lvl=eror msg="error send grads" error="connection is shut down" stack="[c/cclient.go:217 _obj/_cgo_gotypes.go:174]"
t=2017-10-28T07:31:56+0000 lvl=eror msg="error get params" error="connection is shut down" stack="[c/cclient.go:234 _obj/_cgo_gotypes.go:187]"
```

**Comment by shanyi15** [comment] 2018-08-15 11:13
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:13 UTC
