### ISSUE TITLE
格拉姆矩阵

### ISSUE THREAD

**Issue by Leezhaohui** [PaddlePaddle/Paddle#11552] opened 2018-06-19 01:48 UTC
v2版本怎么通过卷积神经网络的输出定义其feature map的格拉姆矩阵

**Comment by reyoung** [comment] 2018-06-19 04:39
V2支持矩阵转置  
https://github.com/PaddlePaddle/Paddle/blob/49f23e63a9e6e5ad7b9c772e4f2cafae66206330/python/paddle/trainer_config_helpers/layers.py#L2232
矩阵乘法
https://github.com/PaddlePaddle/Paddle/blob/49f23e63a9e6e5ad7b9c772e4f2cafae66206330/python/paddle/trainer_config_helpers/layers.py#L35

应该可以拼出来计算格拉姆矩阵的操作。

**Comment by Leezhaohui** [comment] 2018-06-19 04:45
看了v2的API，感觉full_matrix_projection的用法不太明白，能实现两个layer的矩阵相乘吗？

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:22 UTC
Labels: User
