### ISSUE TITLE
[Discuss] How to verify the correction of the implementation of op when the input's shape is bigger?

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#10168] opened 2018-04-24 06:18 UTC
Currently, we have completed many ops' forward and backward and ensured their basic function in small data shape by the unit test. But we can't 100% confirm that there is no error in code implementation because the input shape is too small in our unit test, some error may appear only when the input shape is bigger.
Now, there are two implementations in this case, #9120 and #10150. Although the two bug has been fixed, it takes a long time to locate it. I am not sure whether other ops are in this case too. So how can we avoid this error happen again?

One solution that I think of is to increase the input’s shape of Op and put it on CE to verify its correctness.

**Comment by shanyi15** [comment] 2018-08-15 11:03
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:03 UTC
