### ISSUE TITLE
Refine backward doc

### ISSUE THREAD

**Issue by JiayiFeng** [PaddlePaddle/Paddle#7127] opened 2018-01-02 03:59 UTC
This part of `backward.md` needs refine:

> When implementing a specific op, the developer is also asked to implement its backward version, called grad_op. A grad_op takes gradients of its corresponding op's outputs, and calculate gradients of the op's inputs. During the building of a model's backward part, the framework creates each forward op's grad_op, and then string them together in reverse order of forwarding part. In this way, gradients spread from the end to the beginning of the model, in another word, from the loss to parameters.

@reyoung 's commit:

> `grad_op` is not the backward version of the forward operator.
> We maintain a mapping between an operator and operators that will produce its gradient. It is not a `one-to-one` mapping. Operators in `backward stage`(I do not think there should be a `backward stage`.However, to make it easy to understand, I just assume operators in Block can be split into two stages) can be used in forward stage.

See https://github.com/PaddlePaddle/Paddle/pull/7123#discussion_r159170550

**Comment by shanyi15** [comment] 2018-08-15 11:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:10 UTC
