### ISSUE TITLE
Could not create a primitive descriptor while running quantized model with MKLDNN

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#42972] opened 2022-05-25 02:33 UTC
### bug描述 Describe the Bug

We have test quantized mobilenet with PaddlePaddle develop version(not sure the commit id, but it's nightly build version 2022.05.24)

And find that while infer with different batch size, it will throw an error `Could not create a primitive descriptor for a reorder primitive`

The quantized model is running well with PaddlePaddle v2.3, but in 2.3 we need preprocess the quantized model by [this script](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/save_quant_model.py)

In develop, we only need to use `enable_mkldnn_int8` instead of preprocessing the quantized model.
[quant_bug.tar.gz](https://github.com/PaddlePaddle/Paddle/files/8767459/quant_bug.tar.gz)

**Comment by yeliang2258** [comment] 2022-05-25 09:32
In our tests, we found that in Paddle's 2.3 and dev versions, the resnet50 quantization model did not get accelerated on the cpu, even slower than FP32, but running the same model and script in version Paddle 2.2 can get a significant acceleration, related The model, reproduction script and test data are in the network disk link.

My cpu is Intel(R) Xeon(R) Gold 6271 with avx512_vnni support.

Link: https://pan.baidu.com/s/1Cz10shHRKlw_x4f0rUxImQ 
Extraction code: mrvp

My test results are as follows:
Paddle2.3 + MKLDNN +  FP32：397.18ms
Paddle2.2 + MKLDNN + INT8 + save_quant_model ：111.59ms，
Paddle2.2 + MKLDNN + INT8 + save_quant_model ：529.34ms
Paddle develop + MKLDNN  + INT8 + mkldnnint8：539.26ms
![image](https://user-images.githubusercontent.com/30516196/173009415-37d8074f-e071-4108-9f11-bc727fbdd952.png)

**Comment by wozna** [comment] 2022-06-13 12:18
> In our tests, we found that in Paddle's 2.3 and dev versions, the resnet50 quantization model did not get accelerated on the cpu, even slower than FP32, but running the same model and script in version Paddle 2.2 can get a significant acceleration, related The model, reproduction script and test data are in the network disk link.
> 
> My cpu is Intel(R) Xeon(R) Gold 6271 with avx512_vnni support.
> 
> Link: https://pan.baidu.com/s/1Cz10shHRKlw_x4f0rUxImQ Extraction code: mrvp
> 
> My test results are as follows: Paddle2.3 + MKLDNN + FP32：397.18ms Paddle2.2 + MKLDNN + INT8 + save_quant_model ：111.59ms， Paddle2.2 + MKLDNN + INT8 + save_quant_model ：529.34ms Paddle develop + MKLDNN + INT8 + mkldnnint8：539.26ms ![image](https://user-images.githubusercontent.com/30516196/173009415-37d8074f-e071-4108-9f11-bc727fbdd952.png)

Thank you very much for your report. The reason for this performance drop is the FC mkldnn operator, which for a batch size greater than one started very slowing down. Due to the fact that we have not found the reason, for now, we have turned off FC Mkldnn by default for INT8, but to be able to run it for some cases, I added the EnableMkldnnFcPasses option in this PR https://github.com/PaddlePaddle/Paddle/pull/43462

**Comment by yeliang2258** [comment] 2022-06-14 02:30
In addition, the speed of MobileNetV1 is expected, the speed of int8 is about 2 times that of FP32 . When I tested it, it was the same batch size as Resnet50, and there should also be FC in it. What might be the reason that this model did not slow down?

**Comment by wozna** [comment] 2022-06-14 10:06
@yeliang2258 What I found so far is that in the Resnet50 model there is a pattern `reshape2+matmul+elementwise_add` and those fuse passes are performed:  `reshape2 + matmul-> matmul` _(gpu_cpu_reshape2_matmul_fuse_pass)_ , and then `matmul + elementwise_add-> fc `_(fc_fuse_pass)_. When I turned off the first pass `reshape2 + matmul-> matmul`,  quantized FC MKLDNN does not slow down and performance is as expected. As far as I understand, MKLDNN does not have this case optimized for FC with this reshape2.

**Comment by wozna** [comment] 2022-06-15 15:21
@jiangjiajun I have found which commit caused this error `Could not create a primitive descriptor for a reorder primitive`. 
We're going to find the exact source of the problem, but for now I prepared PR that reverts part that caused this bug.https://github.com/PaddlePaddle/Paddle/pull/43564.

**Comment by jakpiase** [comment] 2022-06-16 01:05
Hi, a proper fix for that issue is here: #43567. Since original problem is resolved, we don't need to revert changes related to softmax

**Comment by lidanqing-vv** [comment] 2022-06-16 12:27
I have tested, and after the fixes merged, now `python test.py --model_path=/home/Issue_42972/quant_bug/MobileNet_quan` has passed.

Used public Paddle commit id: `8bc1c82d88d705e436291b1450e1ba3ead5ae867`
@yeliang2258 Hence, can we close this issue?

![image](https://user-images.githubusercontent.com/47151829/174069217-ee3d4845-9fa6-417e-9402-c28787cae63a.png)

**Comment by yeliang2258** [comment] 2022-06-17 01:43
> I have tested, and after the fixes merged, now `python test.py --model_path=/home/Issue_42972/quant_bug/MobileNet_quan` has passed.
> 
> Used public Paddle commit id: `8bc1c82d88d705e436291b1450e1ba3ead5ae867` @yeliang2258 Hence, can we close this issue?
> 
> ![image](https://user-images.githubusercontent.com/47151829/174069217-ee3d4845-9fa6-417e-9402-c28787cae63a.png)

I tested this problem and found it fixed. But I don't think the problem of performance degradation of resnet50 has been completely solved.

**Closed as completed** 2022-06-20 07:01 UTC
Labels: Intel, type/bug-report, status/close
