### ISSUE TITLE
fluid capi bug!

### ISSUE THREAD

**Issue by gramce** [PaddlePaddle/Paddle#10689] opened 2018-05-16 06:08 UTC
，在读取python导出的fluid模型的时候，对于
luid.layers.fc(out, size = size, act="relu")
这种full connect layer， 没有做act处理

就是 直接把 fluid.layers.fc(out, size = size） 给了出来，没做relu处理

**Comment by gongweibao** [comment] 2018-05-16 07:50
![image](https://user-images.githubusercontent.com/10721757/40103686-e76a659e-5920-11e8-821b-262ea13c44af.png)

**Comment by gongweibao** [comment] 2018-05-16 07:51
```
就是把我的fluid python模型
用capi调用 发现结果不一致
然后具体把每一步的结果打出来了
```

**Comment by gramce** [comment] 2018-05-16 07:54
out = fluid.layers.fc(out, size = size, name = "outnet_con"+str(size))
        out = paddle.fluid.layers.relu(out)

改成这样就一致了

**Comment by gramce** [comment] 2018-05-16 08:15
应该是存的问题，就是python没把这个信息存上，我又用python加载了一次，好像也没有，具体你们再看吧

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
Labels: Bug, User, 屯
