### ISSUE TITLE
pybind incorrectly binding numpy.float32 value to int attribute

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#7369] opened 2018-01-10 01:18 UTC
In pybind, python float value cannot be bound to C++ int  arguments. However, if a value is obtained using numpy computation, its type is numpy.float32/64. This type is not recognized as float by PyFloat_Check at type_caster::load() in  the pybind11/cast.h. Ant it is converted to int value by PyLong_AsLong().

The variant_caster in protobuf.cc will go through all types of the variant and try to convert to each type. A numpy.float or list<numpy.float> will be first converted to int or vector<int> and causes enforce error.

We need to either explicitly handle numpy.float in variant_caster of explicitly convert to numpy.floats to python float. One way to do this is to convert numpy.float  to python float in Operator.__init__

The following is the relevant code segment is pybind11:

        if (std::is_floating_point<T>::value) {                                                                                    
            if (convert || PyFloat_Check(src.ptr()))                                                                                    
                py_value = (py_type) PyFloat_AsDouble(src.ptr());                                                                                    
            else                                                                                    
                return false;                                                                                    
        } else if (sizeof(T) <= sizeof(long)) {                                                                                    
            if (PyFloat_Check(src.ptr()))                                                                                    
                return false;                                                                                    
            if (std::is_signed<T>::value)                                                                                    
                py_value = (py_type) PyLong_AsLong(src.ptr());                                                                                    
            else                                                                                    
                py_value = (py_type) PyLong_AsUnsignedLong(src.ptr());                                                                                    
        } else {

**Comment by shanyi15** [comment] 2018-08-15 11:39
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:39 UTC
