### ISSUE TITLE
I find a bug in 'fluid.layers.softmax()' on version 0.15.

### ISSUE THREAD

**Issue by Albelt** [PaddlePaddle/Paddle#14000] opened 2018-10-20 10:57 UTC
Hi, I think there is a bug in *verion 0.15's softmax function*.
* I'm training a vgg16 network on my own image data, when I debug my code, I find that the network's output  list is abnormal. Since fully-connected layer with softmax activation should output a list of probabilites which could impossible be negative numbers, however the results are as follow:
![image](https://user-images.githubusercontent.com/35684393/47254847-ed3bbc80-d499-11e8-9f8c-3f2d91d2cae1.png)

* It's quite strange, but when I change the version to 0.14, it came back to normal
![image](https://user-images.githubusercontent.com/35684393/47254896-7fdc5b80-d49a-11e8-89d6-4b958b11f99c.png)

**Comment by Yancey0623** [comment] 2018-10-21 04:37
Thanks @Albelt , can you try the latest version: `v1.0.1`? we have many bug fix on this version. If the problem persists, please update this issue.

**Comment by lucywsq** [comment] 2018-11-30 02:42
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-11-30 02:42 UTC
Labels: User
