### ISSUE TITLE
Even with -DWITH_PYTHON=OFF cmake still wants pip

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11581] opened 2018-06-19 16:31 UTC
I am trying to build Paddle on a Lenovo P51 laptop computer with Ubuntu 16.04 without using Docker.

The following command

```
cmake -DWITH_GPU=OFF -DWITH_PYTHON=OFF -DWITH_TESTING=ON ..
```

caused an error

```
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1095 (file):
  file problem creating directory: /pip/src/pip-stamp
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2411 (_ep_set_directories)
  paddle/api/CMakeLists.txt:107 (ExternalProject_Add)


CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1097 (message):
  dir '/pip/src/pip-stamp' does not exist after file(MAKE_DIRECTORY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2411 (_ep_set_directories)
  paddle/api/CMakeLists.txt:107 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
See also "/home/yi/work/paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/yi/work/paddle/build/CMakeFiles/CMakeError.log".
```

**Comment by wangkuiyi** [comment] 2018-06-19 16:35
The error was caused by the following CMake snippet

https://github.com/PaddlePaddle/Paddle/blob/59729902950a022607d4ec6636e9412014b4860f/paddle/api/CMakeLists.txt#L104-L120

Is this because that unit test needs Python?

**Comment by gangliao** [comment] 2018-06-20 02:59
This code should be erased.  Long long ago, `ExternalProject_Add` in PaddlePaddle supports to build python bin/lib from source code `${PYTHON_SOURCES_DIR}` which already been deleted since it's too tricky to build python under the different OS.  This snippet surely is forgotten somewhere.

**Comment by shanyi15** [comment] 2018-08-15 10:21
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:21 UTC
