### ISSUE TITLE
test_lstm_unit_op failed

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#5185] opened 2017-10-28 00:32 UTC
```
[00:29:26] :	 [Step 1/1] 166/243 Test #168: test_lstm_unit_op ...........................***Failed    2.41 sec
[00:29:26] :	 [Step 1/1] FF
[00:29:26] :	 [Step 1/1] ======================================================================
[00:29:26] :	 [Step 1/1] FAIL: test_check_grad (__main__.LstmUnitTest)
[00:29:26] :	 [Step 1/1] ----------------------------------------------------------------------
[00:29:26] :	 [Step 1/1] Traceback (most recent call last):
[00:29:26] :	 [Step 1/1]   File "test_lstm_unit_op.py", line 34, in test_check_grad
[00:29:26] :	 [Step 1/1]     self.check_grad(['X', 'C_prev'], ['C', 'H'])
[00:29:26] :	 [Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 382, in check_grad
[00:29:26] :	 [Step 1/1]     "Gradient Check On %s" % str(gpu_place))
[00:29:26] :	 [Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 334, in __assert_is_close
[00:29:26] :	 [Step 1/1]     self.assertLessEqual(max_diff, max_relative_error, err_msg())
[00:29:26] :	 [Step 1/1] AssertionError: Gradient Check On GPUPlace(0) Variable X max gradient diff 1.000000 over limit 0.005000, the first error element is 0, 0.006427, 0.000000
[00:29:26] :	 [Step 1/1] 
[00:29:26] :	 [Step 1/1] ======================================================================
[00:29:26] :	 [Step 1/1] FAIL: test_check_output (__main__.LstmUnitTest)
[00:29:26] :	 [Step 1/1] ----------------------------------------------------------------------
[00:29:26] :	 [Step 1/1] Traceback (most recent call last):
[00:29:26] :	 [Step 1/1]   File "test_lstm_unit_op.py", line 31, in test_check_output
[00:29:26] :	 [Step 1/1]     self.check_output()
[00:29:26] :	 [Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 315, in check_output
[00:29:26] :	 [Step 1/1]     self.check_output_with_place(place, atol)
[00:29:26] :	 [Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 304, in check_output_with_place
[00:29:26] :	 [Step 1/1]     "Output (" + out_name + ") has diff at " + str(place))
[00:29:26] :	 [Step 1/1] AssertionError: Output (C) has diff at GPUPlace(0)
[00:29:26] :	 [Step 1/1] 
[00:29:26] :	 [Step 1/1] ----------------------------------------------------------------------
```

**Comment by chengduoZH** [comment] 2017-11-10 05:19
Duplicate of #5123

**Closed** 2018-04-12 02:16 UTC
