### ISSUE TITLE
PaddlePaddle distributed training API

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2306] opened 2017-05-27 17:39 UTC
Here is the API design of PyTorch.distributed: https://github.com/pytorch/pytorch/issues/241.  It looks very similar to MPI by means of

1. has the concept process group, which is the concept "world" in MPI
1. has the concept of rank, which is a 0-based id of processes.
1. processes take actions according to their ranks.
1. processes communicate and synchronize with each other by calling `send`, `recv`, etc MPI style functions.

I personally believe that MPI is very flexible and able to describe various concurrent algorithms. But it is not friendly to fault-recovery.  It seems that pytorch.distributed would be good for researchers who work on relatively small datasets and/or on a small group of computers/GPUs.  However, PaddlePaddle, as an industrial application platform cannot follow this style.

**Comment by helinwang** [comment] 2017-05-30 20:53
From Pytorch's example:
```python
import torch.distributed
torch.distributed.init_process_group(backend='tcp')
my_rank = torch.distributed.get_rank()
num_processes = torch.distributed.get_num_processes()

...

if my_rank == 0:
    torch.distributed.send(tensor, 1)
else:
    tensor = torch.distributed.recv(0)

...

result = torch.distributed.all_reduce(tensor)
```
They are doing peer to peer communication (no parameter server). I think besides it's harder to implement fault tolerance, there are two more problems from my understanding:

1. Can't do Async SGD.
1. Can't do sparse update.

**Comment by typhoonzero** [comment] 2017-05-31 07:21
> The message-passing paradigm is attractive because of wide portability and can be used in communication for distributed-memory and shared-memory multiprocessors, networks of workstations, and a combination of these elements. The paradigm can apply in multiple settings, independent of network speed or of memory architecture.

From Wikipedia: https://en.wikipedia.org/wiki/Message_Passing_Interface#Concepts

This scheme enables applications to access memory of other nodes in the cluster directly through TCP or special hardware(shared memory scheme). So applications are heavily bound with MPI implementations like OpenMPI. 

Modern data processing and communication frameworks intend to use more general and cheaper solution, often clusters using x86_64 chips with 10G fiber networking. Huge clusters also use SDN(software defined network) to provide a bunch of virtual separated network environment on the same cluster. Data processing jobs on this type of general cluster can do all their work through ethernet communication, whatever the communication scheme is.

In general, when we design the cluster communication scheme, it must be general, it should be able to run on PC as well as bare-metal servers and on the cloud.

**Comment by helinwang** [comment] 2017-08-24 20:24
Possible duplicate of https://github.com/PaddlePaddle/Paddle/issues/2306 , closing this, please go to that issue for discussion.

**Closed by helinwang** 2017-08-24 20:24 UTC
Labels: need be discussed
