### ISSUE TITLE
[Feature] Adaptation of the new quantization method for mkldnn.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#37422] opened 2021-11-22 08:40 UTC
1. For output activation of ops, slim will insert QuantizeLinear and DequantizeLinear operation which named after ```quantize_linear``` and ```dequantize_linear```.
<img width="363" alt="图片" src="https://user-images.githubusercontent.com/22114318/142825558-ad164f56-50f0-4cd7-a8ad-509def8a548a.png">

2. For trainable parameters of ops, slim first quantizes and saves the weight in low bits, and then inserts an dequantize operation before entering op for calculation.
<img width="812" alt="图片" src="https://user-images.githubusercontent.com/22114318/142826303-23da22a2-3616-487e-acdc-fa626938ca69.png">

3. ```quantize_linear```
The quantization process requires two parameters, scale and zero_point, both of which are 1-dimensional tensors. 
<br>The quantitative formula is: ```y=saturate(round(x/scale)+zero_point)```.

- **Attributes**:
    - ```quant_axis```: INT32, optional. 
    In the ```per-axis``` quantification method, the axis on which the dimension is quantified. If this property is not set, the quantization method defaults to ```per-layer``` quantization. For convolution input ```[batch, channel, H, W]```, when the quantization method is ```channel-wise```, ```quant_axis``` is 1.
    - ```bit_length```: INT32, default is 8.
    The number of bits occupied by the quantized numerical precision, currently only supports quantization as a signed integer.

- **Inputs**:
    - ```X```: FP32.
    - ```Scale```: FP32 <br> When the quantization method is ```layer-wise```, the size of the ```Scale``` is 1. When the quantization method is ```axis-wise```, the size of the ```Scale``` is equal to the size of the input tensor in the axis dimension.
    - ZeroPoint: INT32, optional.  <br> The size is the same as the ```Scale```. The value range depends on ```bit_length```, when ```bit_length``` is 8, the value range of the Tensor is within the value range of Int8.
 
- **Outputs**:
    - ```Y```: INT32. <br> The shape of Y is the same as X. The value range depends on ```bit_length```, when ```bit_length``` is 8, the value range of the Tensor is within the value range of Int8.
 
4. ```dequantize_linear```
According to ```scale```, ```zero_point``` and ```quant_axis```, the low-precision value Tensor is inversely quantized into a high-precision value Tensor. <br> The de-quantitative formula is: ```y=(x-zero_point)*scale```.

- **Attributes**:
    - ```quant_axis```: INT32, optional. 
    In the ```per-axis``` de-quantification method, the axis on which the dimension is de-quantified. If this property is not set, the de-quantization method defaults to ```per-layer``` de-quantization. For convolution input ```[batch, channel, H, W]```, when the de-quantization method is ```channel-wise```, ```quant_axis``` is 1.
    - ```bit_length```: INT32, default is 8.
    The number of bits occupied by the quantized numerical precision, currently only supports quantization as a signed integer.

- **Inputs**:
    - ```X```: INT32. <br> The value range depends on ```bit_length```, when ```bit_length``` is 8, the value range of the Tensor is within the value range of Int8.
    - ```Scale```: FP32 <br> When the de-quantization method is ```layer-wise```, the size of the ```Scale``` is 1. When the de-quantization method is ```axis-wise```, the size of the ```Scale``` is equal to the size of the input tensor in the axis dimension.
    - ZeroPoint: INT32, optional.  <br> The size is the same as the ```Scale```. The value range depends on ```bit_length```, when ```bit_length``` is 8, the value range of the Tensor is within the value range of Int8.

- **Outputs**:
    - ```Y```: FP32. <br> The shape of Y is the same as X. 

Testing model: http: https://paddle-inference-dist.bj.bcebos.com/temp/quantized_mobilenetv1.tar.gz

Refer to the definition of quantization operation in ONNX:
[quantizelinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#quantizelinear)
[DequantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#DequantizeLinear)

**Comment by lidanqing-vv** [comment] 2021-11-24 08:30
https://github.com/onnx/onnx/blob/master/docs/Operators.md#quantizelinear

**Comment by lidanqing-vv** [comment] 2021-11-24 08:34
1. Change the save_quant_model to fit this new quant model
2. Then transform python file to C++ pass.

**Comment by lidanqing-vv** [comment] 2021-12-05 12:11
Hi, @baoachun I can not download this model, the URL looks not reachable from outside. Could you please try drag the model into comment box?

**Comment by lidanqing-vv** [comment] 2021-12-24 05:31
quantize_linear detected.
channel-wise quantization detected.
scale_var_name:  batch_norm_8.tmp_4.scale scale_value:  [0.001]
channel-wise show up in dequantize_linear op
![image](https://user-images.githubusercontent.com/47151829/147320456-6689de0c-9473-45af-91e9-4d6ce17d2828.png)

![image](https://user-images.githubusercontent.com/47151829/147435660-574b8c49-9394-4682-9bb1-c466afb02f3c.png)

**Comment by lidanqing-vv** [comment] 2021-12-27 04:01
- python->C++ refactoring PR:
https://github.com/PaddlePaddle/Paddle/pull/38437
- Adapt new quant-aware model (have bug in save graph with removing quant-dequant op)
https://github.com/lidanqing-intel/Paddle/tree/develop-new-quant-strategy
oneDNN support
```
+    conv_attr.set_zero_points(DNNL_ARG_SRC, /* mask */ 0, {1});
+    conv_attr.set_zero_points(DNNL_ARG_DST, /* mask */ 0, {1});
+    conv_attr.set_zero_points(DNNL_ARG_WEIGHTS, /* mask */ 0, {1});
```
- GPU solution reference: https://github.com/PaddlePaddle/Paddle/blob/c396ee65c88aba6711b94db2bd9496ad60c019cd/paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc#L384

**Comment by lidanqing-vv** [comment] 2021-12-30 09:38
@wozna

**Comment by baoachun** [comment] 2021-12-31 08:11
python->C++ move to new PR: https://github.com/PaddlePaddle/Paddle/pull/38643

**Comment by baoachun** [comment] 2021-12-31 08:17
@lidanqing-intel @wozna  I am wondering whether we can refer to the quantization pass of the GPU to do the mkldnn quantization pass scheme. Because there are a lot of weight processing in the current Python script, it is not in line with the design function of pass, and the code is difficult to maintain. For example, this pass involves transferring data between multiple passes. As far as I know, this situation is currently not supported. I can only save the information in the graph. In addition, there are many weight operations in the pass, such as reshape, transpose, etc., which will bring a huge workload to our later maintenance. In view of this, I still hope that we re-discuss and plan the implementation plan. Thanks!

**Comment by lidanqing-vv** [comment] 2022-01-12 11:10
Tobe refined:
Concerns:
1. Ask issue about Scale propagation

2. zero-point issue, it is fine，dnnl::reorder support it. 
```
+    conv_attr.set_zero_points(DNNL_ARG_SRC, /* mask */ 0, {1});
+    conv_attr.set_zero_points(DNNL_ARG_DST, /* mask */ 0, {1});
+    conv_attr.set_zero_points(DNNL_ARG_WEIGHTS, /* mask */ 0, {1});
```
3. GRU does not support signed int8. We need to recalculate. Is it true that the quant model input is always singed int8. Even it is unsigned, it will be noted through zero-point. What if we get some value different from 128. That will only mean quant model is wrong, hence We should use "assert zero-point 128" in GRU quant model.

4. Those passes and its influence on collected scales. Feel like now we have to change some passes. Like squash, scale etc. Like for scale_conv fuse passes. we have to recalculate the scales. So we will need int8 passes ?? We will have to figure out how many passes will be influence the existing changes.

Steps:

1. We do this in passes. We get scales and zero-point. We should put already these values as attributes of this op.
2. Second pass. Remove all fake quant and fake dequant.
3. Running all mkldnn int8 passes. And at the end of whole process, we can propogate the scales that is propogatable. Look for typical ops (stored propogatable_op_lists) How to mark in the graph. Then we need dequantize op somewhere or use force_fp32_output. Only question is how to propogate the scales, it could be done in similar way in quant2, but could be different, because before we will have done the propogation, we were saving scales for each tensor. Even reshape and transpose will also be done like this. Before we put input and output scale in tensor, but now where do we put the scale. The only concern is that is worrying the method that how to finish int8 pattern. How to finalize int8 calculation and reorder to fp32.

   1. fp32 mkldnn passes (actually int8 mkldnn passes, which means we should already consider ops fusion caused scales recalculation)
   2. insert quantize, dequantize around convs, cpu_quantize_pass, (Before we get tensor with scales from quant2_mkldnn_pass, now we don't use tensor, have to reconsider, currently it should be in target op In_Scale attribute value) We will still need cpu_quantize_squash_pass to safely finalize all int8 calculation

**Comment by lidanqing-vv** [comment] 2022-01-19 08:47
Confirmed: oneDNN does support asymetric quantization. https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html
Now adding zero-points into Paddle conv mkldnn op
https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/doc/knobs_attr.md

We should just reuse GPU GPU passes:
```
const std::vector<std::string> kTRTSubgraphPasses({
  "conv_affine_channel_fuse_pass",  //
      "adaptive_pool2d_convert_global_pass",
      "conv_eltwiseadd_affine_channel_fuse_pass",  //
      "shuffle_channel_detect_pass",               //
      "quant_conv2d_dequant_fuse_pass",            //
      "delete_quant_dequant_op_pass",              //
      "delete_quant_dequant_filter_op_pass",       //
      // "fc_fuse_pass",                                 //
      "simplify_with_basic_ops_pass",           //
      "embedding_eltwise_layernorm_fuse_pass",  //
      "multihead_matmul_fuse_pass_v2",          //
      "multihead_matmul_fuse_pass_v3",          //
      "skip_layernorm_fuse_pass",               //
      "conv_bn_fuse_pass",                      //
      "unsqueeze2_eltwise_fuse_pass",           //
      "squeeze2_matmul_fuse_pass",              //
      "reshape2_matmul_fuse_pass",              //
      "flatten2_matmul_fuse_pass",              //
      "map_matmul_v2_to_mul_pass",              //
      "map_matmul_v2_to_matmul_pass",           //
      "map_matmul_to_mul_pass",                 //
      "fc_fuse_pass",                           //
      "conv_elementwise_add_fuse_pass",         //
      "add_support_int8_pass",
      "tensorrt_subgraph_pass",  //
      "conv_bn_fuse_pass",       //
#if CUDNN_VERSION >= 7100  // To run conv_fusion, the version of cudnn must be
                           // guaranteed at least v7
// cudnn8.0 has memory leak problem in conv + eltwise + act, so we
// disable the pass.
#if !(CUDNN_VERSION >= 8000 && CUDNN_VERSION < 8100)
      "conv_elementwise_add_act_fuse_pass",   //
      "conv_elementwise_add2_act_fuse_pass",  //
#endif
#endif
      "transpose_flatten_concat_fuse_pass",
});
```

**Comment by yaomichael** [comment] 2022-05-24 07:28
notes from 5/20 meeting:
@wozna is taking further optimization from @lidanqing-intel, and expect to deliver in early Q3.

**Comment by wozna** [comment] 2022-09-02 07:54
Hi, @baoachun @yeliang2258  I'm working on this issue on changes made previously by Danqing here https://github.com/PaddlePaddle/Paddle/pull/42106 where there is still an accuracy problem. From what I can see, one-scale gathering is missing there, and that's probably why it doesn't work properly. WIP
I'm also doing a review for https://github.com/PaddlePaddle/Paddle/pull/45416#pullrequestreview-1094442832 where `quantize_linear` and `dequantize_linear` are also used and it is called ONNX Format. Additional element is ScaleFilePath here. Do you also know if there are any differences?

**Comment by yeliang2258** [comment] 2022-09-02 08:54
@wozna Hi, ScaleFilePath stores the scale information of all tensors in the quantize model. This file was added recently. Maybe the problem of lack of scale you mentioned can be solved after loading this file.

**Comment by wozna** [comment] 2022-09-30 07:39
This new quantization method was done by @yeliang2258  in https://github.com/PaddlePaddle/Paddle/pull/45416. 
There are to PR also connected to this https://github.com/PaddlePaddle/Paddle/pull/45920 and https://github.com/PaddlePaddle/Paddle/pull/46378. 

ZeroPoint is not done yet. OneDNN has this option so it is possible to add it. @yeliang2258  do you know if any of new models use this ZeroPoint value for data shift?

**Comment by yaomichael** [comment] 2022-10-09 06:13
> This new quantization method was done by @yeliang2258 in #45416. There are to PR also connected to this #45920 and #46378.
> 
> ZeroPoint is not done yet. OneDNN has this option so it is possible to add it. @yeliang2258 do you know if any of new models use this ZeroPoint value for data shift?

@wozna I consulted @yeliang2258 and he confirmed PaddleSlim (the team for quant models) supports only symmetric quantization, so all models should have zeropoint be 0.

**Closed as completed** 2023-01-11 11:38 UTC
Labels: high priority, Intel, status/close
