### ISSUE TITLE
fc_op slows on multi-instance inference

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#17153] opened 2019-04-29 04:13 UTC
When profile multi-instance inference on pyramid_dnn, we find fc_op slows on it.
### command:
- one instance:
```
./paddle/fluid/inference/tests/api/test_analyzer_pyramid_dnn --infer_model=third_party/inference_demo/pyramid_dnn/model/ --infer_data=third_party/inference_demo/pyramid_dnn/data.txt --gtest_filter=Analyzer_Pyramid_DNN.profile --paddle_num_threads=1 --repeat=10000 --zero_copy --warmup --num_threads=1
```
- two instance:
```
./paddle/fluid/inference/tests/api/test_analyzer_pyramid_dnn --infer_model=third_party/inference_demo/pyramid_dnn/model/ --infer_data=third_party/inference_demo/pyramid_dnn/data.txt --gtest_filter=Analyzer_Pyramid_DNN.profile --paddle_num_threads=1 --repeat=10000 --zero_copy --warmup --num_threads=2
```
### result (latency)

| | fc_op | remove fc_op, i.e use mul+add |
|---|---|---|
|1 threads|  0.13118 | 0.141566 |
|2 threads|0.291523   |0.152074  |

The remove fc_op codes are:
```
--- a/paddle/fluid/inference/tests/api/analyzer_pyramid_dnn_tester.cc
+++ b/paddle/fluid/inference/tests/api/analyzer_pyramid_dnn_tester.cc
@@ -110,6 +110,7 @@ void SetConfig(AnalysisConfig *cfg) {
   if (FLAGS_zero_copy) {
     cfg->SwitchUseFeedFetchOps(false);
   }
+  cfg->pass_builder()->DeletePass("fc_fuse_pass");
 }
```

**Comment by luotao1** [comment] 2019-04-29 04:14
@jianhang-liu @bingyanghuang @LeoZhao-Intel @yihuaxu Could you help see it?

**Comment by bingyanghuang** [comment] 2019-04-29 06:50
Got it. @yihuaxu will help on this.

**Comment by yihuaxu** [comment] 2019-04-29 07:36
Just tried it on 2650V4, but this issue can not be duplicated. Please refer to the below result. How about your CPU model?

![image](https://user-images.githubusercontent.com/4131969/56881918-8aecf580-6a94-11e9-8ce5-b4eddf62a77d.png)

**Comment by luotao1** [comment] 2019-04-29 07:39
What's your compile option?

**Comment by yihuaxu** [comment] 2019-04-29 07:45
cmake .. -DWITH_INFERENCE_API_TEST=ON -DWITH_INFERENCE=ON -DWITH_TESTING=ON -DON_INFER=ON

**Comment by luotao1** [comment] 2019-04-29 07:51
I find the reason: when I enable `WITH_NGRAPH=ON`, it slows. But `WITH_NGRAPH=OFF`, the result is normal. 
@baojun-nervana Could you help see it?

**Comment by luotao1** [comment] 2019-04-29 08:56
Maybe the same problem in https://github.com/PaddlePaddle/Paddle/issues/15599#issuecomment-458900208

**Comment by yihuaxu** [comment] 2019-04-30 01:31
Tried to use WITH_NGRAPH option on 2650V4, please refer to the below.

cmake .. -DWITH_INFERENCE_API_TEST=ON -DWITH_INFERENCE=ON -DWITH_TESTING=ON -DON_INFER=ON -DWITH_NGRAPH=ON


  | fc_op | remove fc_op,   i.e use mul+add
-- | -- | --
1   threads | 0.131179 | 0.137998
2   threads | 0.135886 | 0.141909

**Comment by luotao1** [comment] 2019-04-30 02:03
Do you use the image `paddlepaddle/paddle_manylinux_devel:cuda7.5_cudnn5`?

**Comment by ghost** [comment] 2019-05-05 03:45
@luotao1 Leo Zhao will help to check this issue. BTW, seems that I can't assign this issue directly to him since I can't find his name in assignee.

**Comment by LeoZhao-BJ** [comment] 2019-05-05 06:03
@luotao1 can you share the cmake options ? with my cmake options, I can't reproduce this issue.

BTW, for multi-instance case, by my investigation, ngraph path still doesn't support, if users enable ngraph in force, it will cause segment fault, so it means this issue may not be introduced by ngraph.

**Comment by luotao1** [comment] 2019-05-05 06:22
>  with my cmake options

What's your cmake option and docker image?
- My: `cmake .. -DWITH_INFERENCE_API_TEST=ON -DWITH_TESTING=ON -DON_INFER=ON -DWITH_NGRAPH=ON -DWITH_GPU=OFF -DWITH_MKLDNN=ON`
- `paddlepaddle/paddle_manylinux_devel:cuda7.5_cudnn5`

> ngraph path still doesn't support, if users enable ngraph in force, it will cause segment fault

Do you mean `FLAGS_use_ngraph=true` to run?

**Comment by LeoZhao-BJ** [comment] 2019-05-05 06:26
> > with my cmake options
> 
> What's your cmake option and docker image?
> 
> * My: `cmake .. -DWITH_INFERENCE_API_TEST=ON -DWITH_TESTING=ON -DON_INFER=ON -DWITH_NGRAPH=ON -DWITH_GPU=OFF -DWITH_MKLDNN=ON`
> * `paddlepaddle/paddle_manylinux_devel:cuda7.5_cudnn5`

I use similar cmake options, but not in docker, I will try it later.

> > ngraph path still doesn't support, if users enable ngraph in force, it will cause segment fault
> 
> Do you mean `FLAGS_use_ngraph=true` to run?

just add "--use_ngraph --use_analysis=false"  in cmd, then it will force to use ngraph

**Comment by luotao1** [comment] 2019-05-05 06:32
> just add "--use_ngraph --use_analysis=false" in cmd, then it will force to use ngraph

Could it use ngraph? I don't try it.

I mean when I build with `-DWITH_NGRAPH`, the fc_op slows on multi-instance inference on MKL.

**Comment by LeoZhao-BJ** [comment] 2019-05-05 06:38
I understand your question, this issue happens with -DWITH_NGRAPH, but not due to ngraph execution.

With your cmake options, I still can't reproduce on local 2699 machine, but if it occurs in docker, some possible reasons are compilation related, I will try to reproduce in docker env first.

**Comment by luotao1** [comment] 2019-05-05 06:44
> on local 2699 machine

Which gcc version do you use? I think it's related with gcc 4.8.

**Comment by LeoZhao-BJ** [comment] 2019-05-05 06:45
gcc version 5.4.0 20160609 on my machine

**Comment by LeoZhao-BJ** [comment] 2019-05-05 09:46
@luotao1 I can reproduce this issue in docker, seems the rootcause is that, in docker env OMP_NUM_THREADS is not well set, hence for multi-instance case, many omp threads spawned which makes performance bad inversely.  Just set  OMP_NUM_THREADS=1, this issue is gone.
I am trying to find which code make this setting different between local and docker.

**Comment by LeoZhao-BJ** [comment] 2019-05-05 10:14
not related with docker or local, the rootcause is just OMP thread as said before, I can reproduce locally.
seems ngraph stack modified OMP setting in initialization in somewhere which makes setting inconsistent in different instance.

**Comment by LeoZhao-BJ** [comment] 2019-05-06 02:11
ngraph is not the rootcause, even with "-DWITH_NGRAPH=OFF" on both local machine and docker, I can still reproduce this issue.  But whatever the cmake options, if set OMP_NUM_THREADS=1, this issue is always gone.
The rootcause seems be in OMP thread num setting in somewhere in PaddlePaddle.

**Comment by LeoZhao-BJ** [comment] 2019-05-06 02:47
The rootcause is omp_set_num_threads() just applies to the thread being called, it means if this thread launches parallel compute, omp will spawn the number of threads set. 
While in current test framework, it creates another new thread to do predictor->run or zerocopyrun only, which lost omp thread setting in predictor::Init() in main thread,  to avoid this scenario, call paddle::platform::SetNumThreads again in Run().

**Closed as completed** 2019-05-07 01:24 UTC
Labels: Intel

**Comment by LeoZhao-BJ** [comment] 2019-05-07 01:40
@luotao1 please remove ngraph label for this issue since it is not related.

**Comment by luotao1** [comment] 2019-05-07 01:44
@LeoZhao-Intel Done
