### ISSUE TITLE
如何使用op对vector和sequence进行concat操作？

### ISSUE THREAD

**Issue by gavin1332** [PaddlePaddle/Paddle#11336] opened 2018-06-11 01:36 UTC
如题

**Comment by Yancey1989** [comment] 2018-06-11 01:57
vector可以使用[concat](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/tensor.py#L115), sequence可以使用[merge_lod_tensor](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py#L102)

**Comment by gavin1332** [comment] 2018-06-11 09:05
@Yancey1989

**Comment by Yancey1989** [comment] 2018-06-11 11:58
目前Fluid中使用[lod_tensor](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/concepts/lod_tensor.md) 来表示sequence相关的操作。

> 我是指将一个vector拼接到sequence头部，比如原sequence长度为10，拼接vector后长度变为11

那希望拼接后的LoD信息是什么样的呢？

**Comment by gavin1332** [comment] 2018-06-12 01:29
e.g. batch_size=3, lod=[[0, 3, 5, 10]] 拼接后 [[0, 4, 7, 13]]，即每个序列长度加1。

另外，关于你提到的merge sequence用的merge_lod_tensor op，我看了python前端，里边的in_true，in_false以及mask等参数让我很难理解，函数说明也不够详细，可以帮忙解释一下吗？我感觉两个sequence merge不应该输入一个x和y就够啦？

**Comment by shanyi15** [comment] 2018-08-15 11:01
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:01 UTC
Labels: User, 屯
