### ISSUE TITLE
编译第三方依赖protobuf中的protoc时runtime path被移除导致的错误

### ISSUE THREAD

**Issue by Cwndmiao** [PaddlePaddle/Paddle#7482] opened 2018-01-12 08:26 UTC
编译paddlepaddle时需从github上克隆protobuf，再编译出protoc放到<build_dir>/third_party/install/protobuf/bin目录下，后续编译过程中会调用protoc对.proto文件进行再编译。

我在厂内按照[http://wiki.baidu.com/pages/viewpage.action?pageId=452849673](http://wiki.baidu.com/pages/viewpage.action?pageId=452849673)中所述方法用gcc-4.8.2编译paddlepaddle，遇到protoc不能正常运行的错误。

![image](https://user-images.githubusercontent.com/2132839/34866089-449e21fa-f7b6-11e7-8ec8-9826fc6c5af8.png)

经调查，发现<build_dir>/third_party/install/protobuf/bin目录下的protoc文件rpath被修改。

![image](https://user-images.githubusercontent.com/2132839/34865548-15415280-f7b4-11e7-8dc4-b4d1ef2b8514.png)

而正常编译出来的protoc文件rpath是这样的，故造成后续编译出错。

![image](https://user-images.githubusercontent.com/2132839/34865576-4282233c-f7b4-11e7-9230-1c30291649a9.png)

解决方案为在protobuf.cmake中增加“-DCMAKE_SKIP_RPATH=ON”。 #7481

**Comment by shanyi15** [comment] 2018-08-15 11:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:09 UTC
