### ISSUE TITLE
test_seq_concat_op fails

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#8290] opened 2018-02-09 01:04 UTC
@Yancey1989 I saw you are the main contributor to `test_seq_concat_op.py` could you take a look or assign to more relevant person? Thanks!

```
python test_seq_concat_op.py
E.E.E.E.
======================================================================
ERROR: test_check_grad (__main__.TestSeqConcatOp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_seq_concat_op.py", line 68, in test_check_grad
    self.check_grad(['x0'], 'Out')
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 376, in check_grad
    user_defined_grads)
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 409, in check_grad_with_place
    in_place=in_place) for input_to_check in inputs_to_check
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 155, in get_numeric_gradient
    y_pos = get_output()
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 114, in get_output
    op.run(scope, place)
EnforceNotMet: enforce ins[0]->NumLevels() > level failed, 0 <= 1
The levels of all the input LoDTensors should be greater than the specify level at [/home/helin/repo/Paddle/paddle/operators/sequence_concat_op.h:92]
PaddlePaddle Call Stacks: 
0       0x7f967a7c14a7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f967a99414ep paddle::operators::SequenceConcatOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 4478
2       0x7f967b3abfc4p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1508
3       0x7f967a7a0cadp
4       0x7f967a7dcfe4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
5             0x4cad00p PyEval_EvalFrameEx + 28048
6             0x4c2705p PyEval_EvalCodeEx + 597
7             0x4ca7dfp PyEval_EvalFrameEx + 26735
8             0x4c2705p PyEval_EvalCodeEx + 597
9             0x4ca088p PyEval_EvalFrameEx + 24856
10            0x4c2705p PyEval_EvalCodeEx + 597
11            0x4ca088p PyEval_EvalFrameEx + 24856
12            0x4c2705p PyEval_EvalCodeEx + 597
13            0x4ca088p PyEval_EvalFrameEx + 24856
14            0x4c9d7fp PyEval_EvalFrameEx + 24079
15            0x4c2705p PyEval_EvalCodeEx + 597
16            0x4de858p
17            0x4b0c93p PyObject_Call + 67
18            0x4c6ef6p PyEval_EvalFrameEx + 12166
19            0x4c2705p PyEval_EvalCodeEx + 597
20            0x4de69ep
21            0x4b0c93p PyObject_Call + 67
22            0x4f452ep
23            0x4b0c93p PyObject_Call + 67
24            0x552397p
25            0x4b0c93p PyObject_Call + 67
26            0x4c9f9fp PyEval_EvalFrameEx + 24623
27            0x4c2705p PyEval_EvalCodeEx + 597
28            0x4de858p
29            0x4b0c93p PyObject_Call + 67
30            0x4c6ef6p PyEval_EvalFrameEx + 12166
31            0x4c2705p PyEval_EvalCodeEx + 597
32            0x4de69ep
33            0x4b0c93p PyObject_Call + 67
34            0x4f452ep
35            0x4b0c93p PyObject_Call + 67
36            0x552397p
37            0x4b0c93p PyObject_Call + 67
38            0x4c9f9fp PyEval_EvalFrameEx + 24623
39            0x4c2705p PyEval_EvalCodeEx + 597
40            0x4de858p
41            0x4b0c93p PyObject_Call + 67
42            0x4c6ef6p PyEval_EvalFrameEx + 12166
43            0x4c2705p PyEval_EvalCodeEx + 597
44            0x4de69ep
45            0x4b0c93p PyObject_Call + 67
46            0x4f452ep
47            0x4b0c93p PyObject_Call + 67
48            0x552397p
49            0x4b0c93p PyObject_Call + 67
50            0x4c9f9fp PyEval_EvalFrameEx + 24623
51            0x4c9d7fp PyEval_EvalFrameEx + 24079
52            0x4c9d7fp PyEval_EvalFrameEx + 24079
53            0x4c2705p PyEval_EvalCodeEx + 597
54            0x4de69ep
55            0x4b0c93p PyObject_Call + 67
56            0x4f452ep
57            0x4b0c93p PyObject_Call + 67
58            0x4f42a7p
59            0x4b669cp
60            0x4b0c93p PyObject_Call + 67
61            0x4c9f9fp PyEval_EvalFrameEx + 24623
62            0x4c2705p PyEval_EvalCodeEx + 597
63            0x4c24a9p PyEval_EvalCode + 25
64            0x4f19efp
65            0x4ec372p PyRun_FileExFlags + 130
66            0x4eaaf1p PyRun_SimpleFileExFlags + 401
67            0x49e208p Py_Main + 1736
68      0x7f9712bde830p __libc_start_main + 240
69            0x49da59p _start + 41


======================================================================
ERROR: test_check_grad (__main__.TestSeqConcatOpLevelZeroNestedSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_seq_concat_op.py", line 68, in test_check_grad
    self.check_grad(['x0'], 'Out')
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 376, in check_grad
    user_defined_grads)
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 409, in check_grad_with_place
    in_place=in_place) for input_to_check in inputs_to_check
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 155, in get_numeric_gradient
    y_pos = get_output()
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 114, in get_output
    op.run(scope, place)
EnforceNotMet: enforce ins[0]->NumLevels() > level failed, 0 <= 0
The levels of all the input LoDTensors should be greater than the specify level at [/home/helin/repo/Paddle/paddle/operators/sequence_concat_op.h:92]
PaddlePaddle Call Stacks: 
0       0x7f967a7c14a7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f967a99414ep paddle::operators::SequenceConcatOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 4478
2       0x7f967b3abfc4p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1508
3       0x7f967a7a0cadp
4       0x7f967a7dcfe4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
5             0x4cad00p PyEval_EvalFrameEx + 28048
6             0x4c2705p PyEval_EvalCodeEx + 597
7             0x4ca7dfp PyEval_EvalFrameEx + 26735
8             0x4c2705p PyEval_EvalCodeEx + 597
9             0x4ca088p PyEval_EvalFrameEx + 24856
10            0x4c2705p PyEval_EvalCodeEx + 597
11            0x4ca088p PyEval_EvalFrameEx + 24856
12            0x4c2705p PyEval_EvalCodeEx + 597
13            0x4ca088p PyEval_EvalFrameEx + 24856
14            0x4c9d7fp PyEval_EvalFrameEx + 24079
15            0x4c2705p PyEval_EvalCodeEx + 597
16            0x4de858p
17            0x4b0c93p PyObject_Call + 67
18            0x4c6ef6p PyEval_EvalFrameEx + 12166
19            0x4c2705p PyEval_EvalCodeEx + 597
20            0x4de69ep
21            0x4b0c93p PyObject_Call + 67
22            0x4f452ep
23            0x4b0c93p PyObject_Call + 67
24            0x552397p
25            0x4b0c93p PyObject_Call + 67
26            0x4c9f9fp PyEval_EvalFrameEx + 24623
27            0x4c2705p PyEval_EvalCodeEx + 597
28            0x4de858p
29            0x4b0c93p PyObject_Call + 67
30            0x4c6ef6p PyEval_EvalFrameEx + 12166
31            0x4c2705p PyEval_EvalCodeEx + 597
32            0x4de69ep
33            0x4b0c93p PyObject_Call + 67
34            0x4f452ep
35            0x4b0c93p PyObject_Call + 67
36            0x552397p
37            0x4b0c93p PyObject_Call + 67
38            0x4c9f9fp PyEval_EvalFrameEx + 24623
39            0x4c2705p PyEval_EvalCodeEx + 597
40            0x4de858p
41            0x4b0c93p PyObject_Call + 67
42            0x4c6ef6p PyEval_EvalFrameEx + 12166
43            0x4c2705p PyEval_EvalCodeEx + 597
44            0x4de69ep
45            0x4b0c93p PyObject_Call + 67
46            0x4f452ep
47            0x4b0c93p PyObject_Call + 67
48            0x552397p
49            0x4b0c93p PyObject_Call + 67
50            0x4c9f9fp PyEval_EvalFrameEx + 24623
51            0x4c9d7fp PyEval_EvalFrameEx + 24079
52            0x4c9d7fp PyEval_EvalFrameEx + 24079
53            0x4c2705p PyEval_EvalCodeEx + 597
54            0x4de69ep
55            0x4b0c93p PyObject_Call + 67
56            0x4f452ep
57            0x4b0c93p PyObject_Call + 67
58            0x4f42a7p
59            0x4b669cp
60            0x4b0c93p PyObject_Call + 67
61            0x4c9f9fp PyEval_EvalFrameEx + 24623
62            0x4c2705p PyEval_EvalCodeEx + 597
63            0x4c24a9p PyEval_EvalCode + 25
64            0x4f19efp
65            0x4ec372p PyRun_FileExFlags + 130
66            0x4eaaf1p PyRun_SimpleFileExFlags + 401
67            0x49e208p Py_Main + 1736
68      0x7f9712bde830p __libc_start_main + 240
69            0x49da59p _start + 41


======================================================================
ERROR: test_check_grad (__main__.TestSeqConcatOpLevelZeroSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_seq_concat_op.py", line 68, in test_check_grad
    self.check_grad(['x0'], 'Out')
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 376, in check_grad
    user_defined_grads)
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 409, in check_grad_with_place
    in_place=in_place) for input_to_check in inputs_to_check
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 155, in get_numeric_gradient
    y_pos = get_output()
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 114, in get_output
    op.run(scope, place)
EnforceNotMet: enforce ins[0]->NumLevels() > level failed, 0 <= 0
The levels of all the input LoDTensors should be greater than the specify level at [/home/helin/repo/Paddle/paddle/operators/sequence_concat_op.h:92]
PaddlePaddle Call Stacks: 
0       0x7f967a7c14a7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f967a99414ep paddle::operators::SequenceConcatOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 4478
2       0x7f967b3abfc4p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1508
3       0x7f967a7a0cadp
4       0x7f967a7dcfe4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
5             0x4cad00p PyEval_EvalFrameEx + 28048
6             0x4c2705p PyEval_EvalCodeEx + 597
7             0x4ca7dfp PyEval_EvalFrameEx + 26735
8             0x4c2705p PyEval_EvalCodeEx + 597
9             0x4ca088p PyEval_EvalFrameEx + 24856
10            0x4c2705p PyEval_EvalCodeEx + 597
11            0x4ca088p PyEval_EvalFrameEx + 24856
12            0x4c2705p PyEval_EvalCodeEx + 597
13            0x4ca088p PyEval_EvalFrameEx + 24856
14            0x4c9d7fp PyEval_EvalFrameEx + 24079
15            0x4c2705p PyEval_EvalCodeEx + 597
16            0x4de858p
17            0x4b0c93p PyObject_Call + 67
18            0x4c6ef6p PyEval_EvalFrameEx + 12166
19            0x4c2705p PyEval_EvalCodeEx + 597
20            0x4de69ep
21            0x4b0c93p PyObject_Call + 67
22            0x4f452ep
23            0x4b0c93p PyObject_Call + 67
24            0x552397p
25            0x4b0c93p PyObject_Call + 67
26            0x4c9f9fp PyEval_EvalFrameEx + 24623
27            0x4c2705p PyEval_EvalCodeEx + 597
28            0x4de858p
29            0x4b0c93p PyObject_Call + 67
30            0x4c6ef6p PyEval_EvalFrameEx + 12166
31            0x4c2705p PyEval_EvalCodeEx + 597
32            0x4de69ep
33            0x4b0c93p PyObject_Call + 67
34            0x4f452ep
35            0x4b0c93p PyObject_Call + 67
36            0x552397p
37            0x4b0c93p PyObject_Call + 67
38            0x4c9f9fp PyEval_EvalFrameEx + 24623
39            0x4c2705p PyEval_EvalCodeEx + 597
40            0x4de858p
41            0x4b0c93p PyObject_Call + 67
42            0x4c6ef6p PyEval_EvalFrameEx + 12166
43            0x4c2705p PyEval_EvalCodeEx + 597
44            0x4de69ep
45            0x4b0c93p PyObject_Call + 67
46            0x4f452ep
47            0x4b0c93p PyObject_Call + 67
48            0x552397p
49            0x4b0c93p PyObject_Call + 67
50            0x4c9f9fp PyEval_EvalFrameEx + 24623
51            0x4c9d7fp PyEval_EvalFrameEx + 24079
52            0x4c9d7fp PyEval_EvalFrameEx + 24079
53            0x4c2705p PyEval_EvalCodeEx + 597
54            0x4de69ep
55            0x4b0c93p PyObject_Call + 67
56            0x4f452ep
57            0x4b0c93p PyObject_Call + 67
58            0x4f42a7p
59            0x4b669cp
60            0x4b0c93p PyObject_Call + 67
61            0x4c9f9fp PyEval_EvalFrameEx + 24623
62            0x4c2705p PyEval_EvalCodeEx + 597
63            0x4c24a9p PyEval_EvalCode + 25
64            0x4f19efp
65            0x4ec372p PyRun_FileExFlags + 130
66            0x4eaaf1p PyRun_SimpleFileExFlags + 401
67            0x49e208p Py_Main + 1736
68      0x7f9712bde830p __libc_start_main + 240
69            0x49da59p _start + 41


======================================================================
ERROR: test_check_grad (__main__.TestSeqConcatOplevelOneNestedSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_seq_concat_op.py", line 68, in test_check_grad
    self.check_grad(['x0'], 'Out')
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 376, in check_grad
    user_defined_grads)
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 409, in check_grad_with_place
    in_place=in_place) for input_to_check in inputs_to_check
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 155, in get_numeric_gradient
    y_pos = get_output()
  File "/home/helin/repo/Paddle/python/paddle/v2/fluid/tests/unittest/op_test.py", line 114, in get_output
    op.run(scope, place)
EnforceNotMet: enforce ins[0]->NumLevels() > level failed, 0 <= 1
The levels of all the input LoDTensors should be greater than the specify level at [/home/helin/repo/Paddle/paddle/operators/sequence_concat_op.h:92]
PaddlePaddle Call Stacks: 
0       0x7f967a7c14a7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f967a99414ep paddle::operators::SequenceConcatOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 4478
2       0x7f967b3abfc4p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1508
3       0x7f967a7a0cadp
4       0x7f967a7dcfe4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
5             0x4cad00p PyEval_EvalFrameEx + 28048
6             0x4c2705p PyEval_EvalCodeEx + 597
7             0x4ca7dfp PyEval_EvalFrameEx + 26735
8             0x4c2705p PyEval_EvalCodeEx + 597
9             0x4ca088p PyEval_EvalFrameEx + 24856
10            0x4c2705p PyEval_EvalCodeEx + 597
11            0x4ca088p PyEval_EvalFrameEx + 24856
12            0x4c2705p PyEval_EvalCodeEx + 597
13            0x4ca088p PyEval_EvalFrameEx + 24856
14            0x4c9d7fp PyEval_EvalFrameEx + 24079
15            0x4c2705p PyEval_EvalCodeEx + 597
16            0x4de858p
17            0x4b0c93p PyObject_Call + 67
18            0x4c6ef6p PyEval_EvalFrameEx + 12166
19            0x4c2705p PyEval_EvalCodeEx + 597
20            0x4de69ep
21            0x4b0c93p PyObject_Call + 67
22            0x4f452ep
23            0x4b0c93p PyObject_Call + 67
24            0x552397p
25            0x4b0c93p PyObject_Call + 67
26            0x4c9f9fp PyEval_EvalFrameEx + 24623
27            0x4c2705p PyEval_EvalCodeEx + 597
28            0x4de858p
29            0x4b0c93p PyObject_Call + 67
30            0x4c6ef6p PyEval_EvalFrameEx + 12166
31            0x4c2705p PyEval_EvalCodeEx + 597
32            0x4de69ep
33            0x4b0c93p PyObject_Call + 67
34            0x4f452ep
35            0x4b0c93p PyObject_Call + 67
36            0x552397p
37            0x4b0c93p PyObject_Call + 67
38            0x4c9f9fp PyEval_EvalFrameEx + 24623
39            0x4c2705p PyEval_EvalCodeEx + 597
40            0x4de858p
41            0x4b0c93p PyObject_Call + 67
42            0x4c6ef6p PyEval_EvalFrameEx + 12166
43            0x4c2705p PyEval_EvalCodeEx + 597
44            0x4de69ep
45            0x4b0c93p PyObject_Call + 67
46            0x4f452ep
47            0x4b0c93p PyObject_Call + 67
48            0x552397p
49            0x4b0c93p PyObject_Call + 67
50            0x4c9f9fp PyEval_EvalFrameEx + 24623
51            0x4c9d7fp PyEval_EvalFrameEx + 24079
52            0x4c9d7fp PyEval_EvalFrameEx + 24079
53            0x4c2705p PyEval_EvalCodeEx + 597
54            0x4de69ep
55            0x4b0c93p PyObject_Call + 67
56            0x4f452ep
57            0x4b0c93p PyObject_Call + 67
58            0x4f42a7p
59            0x4b669cp
60            0x4b0c93p PyObject_Call + 67
61            0x4c9f9fp PyEval_EvalFrameEx + 24623
62            0x4c2705p PyEval_EvalCodeEx + 597
63            0x4c24a9p PyEval_EvalCode + 25
64            0x4f19efp
65            0x4ec372p PyRun_FileExFlags + 130
66            0x4eaaf1p PyRun_SimpleFileExFlags + 401
67            0x49e208p Py_Main + 1736
68      0x7f9712bde830p __libc_start_main + 240
69            0x49da59p _start + 41


----------------------------------------------------------------------
Ran 8 tests in 0.127s

FAILED (errors=4)

```

**Comment by Yancey1989** [comment] 2018-02-10 01:28
Thanks, I'll follow up this issue.

**Comment by shanyi15** [comment] 2018-08-15 11:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:08 UTC
