### ISSUE TITLE
 Aborted at 1528944632 (unix time) try "date -d @1528944632" if you are using GNU date

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#11480] opened 2018-06-14 10:31 UTC
Centos7 paddle0.13gpu  mnist.py报错
"*** Aborted at 1528944632 (unix time) try ""date -d @1528944632"" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 58181 (TID 0x7fab2e3ad740) from PID 80; stack trace: ***
    @     0x7fab2dbc36d0 (unknown)
    @     0x7fab2e1a7d56 _dl_relocate_object
    @     0x7fab2e1b07ac dl_open_worker
    @     0x7fab2e1ab914 _dl_catch_error
    @     0x7fab2e1afccb _dl_open
    @     0x7fab2d21b082 do_dlopen
    @     0x7fab2e1ab914 _dl_catch_error
    @     0x7fab2d21b142 __GI___libc_dlopen_mode
    @     0x7fab2d1f2b45 init
    @     0x7fab2dbc0e70 __GI___pthread_once
    @     0x7fab2d1f2c5c __GI___backtrace
    @     0x7fab266ae643 (unknown)
    @     0x7fab266aeb80 (unknown)
    @     0x7fab2669583b (unknown)
    @     0x7fab2de1795c (unknown)
    @     0x7fab2de19d7a PyNumber_Multiply
    @     0x7fab2deb1430 PyEval_EvalFrameEx
    @     0x7fab2de362b8 (unknown)
    @     0x7fab2deafc41 PyEval_EvalFrameEx
    @     0x7fab2de362b8 (unknown)
    @     0x7fab2de31d2f (unknown)
    @     0x7fab2deafc41 PyEval_EvalFrameEx
    @     0x7fab2deb703d PyEval_EvalCodeEx
    @     0x7fab2deb453c PyEval_EvalFrameEx
    @     0x7fab2deb703d PyEval_EvalCodeEx
    @     0x7fab2deb7142 PyEval_EvalCode
    @     0x7fab2ded057f (unknown)
    @     0x7fab2ded173e PyRun_FileExFlags
    @     0x7fab2ded29c9 PyRun_SimpleFileExFlags
    @     0x7fab2dee3b7f Py_Main
    @     0x7fab2d100445 __libc_start_main
    @           0x40066e (unknown)

gzip: stdout: Broken pipe
Segmentation fault (core dumped)
"

**Comment by chengduoZH** [comment] 2018-06-14 11:08
您跑的是什么模型？

**Comment by DDDivano** [comment] 2018-06-15 04:33
mnist.py

**Comment by chengduoZH** [comment] 2018-06-15 04:59
您是怎么安装的paddle，模型用的是V2还是Fluid，另外可以把模型代码贴一下吗？我这边好复现

**Comment by yeyupiaoling** [comment] 2018-06-15 07:29
@chengduoZH 他复现了我的问题：https://github.com/PaddlePaddle/Paddle/issues/11478#issuecomment-397266490

**Comment by shanyi15** [comment] 2018-08-15 11:35
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:35 UTC
Labels: User
