### ISSUE TITLE
capi v2 多线程使用问题

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#9880] opened 2018-04-12 10:57 UTC
线上多线程共用一个模型预测在成功预测完一些样本后会报错。
单机测试capi，在每个线程中初始化单独的模型可以顺利预测，但只初始化一个模型，通过struct传入thread共用会出现预测出一些结果后报错，不知原因。所有本地使用的样本都一样，输入格式应该没问题
```
enter thread1
this is thread1, thread id is 3907217152
enter thread2
this is thread2, thread id is 3915609856
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
thread2 model predict successfully!
thread1 model predict successfully!
F0412 10:25:28.660399   477 SequencePoolLayer.cpp:59] Check failed: starts->getData()[newBatchSize_] == input.getBatchSize() (32745 vs. 43) 
*** Check failure stack trace: ***
thread1 model predict successfully!
thread1 model predict successfully!
    @     0x7fe9ed83e76d  google::LogMessage::Fail()
    @     0x7fe9ed84221c  google::LogMessage::SendToLog()
thread1 model predict successfully!
    @     0x7fe9ed83e293  google::LogMessage::Flush()
    @     0x7fe9ed84372e  google::LogMessageFatal::~LogMessageFatal()
thread1 model predict successfully!
    @     0x7fe9ed88c138  paddle::SequencePoolLayer::forward()
    @     0x7fe9ed8ddb7d  paddle::MaxLayer::forward()
    @     0x7fe9ed9a24bd  paddle::NeuralNetwork::forward()
    @     0x7fe9ed83a676  paddle_gradient_machine_forward
thread1 model predict successfully!
    @           0x4031b3  TrafficModel::traffic_predict()
thread1 model predict successfully!
    @           0x4041d0  TrafficModel::predict()
thread1 model predict successfully!
    @           0x405ac0  thread2()
    @     0x7fe9ec9b71c3  start_thread
    @     0x7fe9eccb412d  __clone
    @              (nil)  (unknown)
Aborted
```

**Comment by gongweibao** [comment] 2018-04-12 11:05
使用方式你参考这个：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference/multi_thread

**Comment by hyo009** [comment] 2018-04-13 04:47
多线程中调用同个预测模型时必须互斥么？

**Comment by gongweibao** [comment] 2018-04-13 06:34
https://github.com/PaddlePaddle/Paddle/blame/develop/paddle/capi/examples/model_inference/multi_thread/main_gpu.c#L70
这个其实不需要，可能是为了有序的打印结果。

**Comment by shanyi15** [comment] 2018-08-15 11:36
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:36 UTC
Labels: 屯
