### ISSUE TITLE
Some issues in the `framework.py`

### ISSUE THREAD

**Issue by JiayiFeng** [PaddlePaddle/Paddle#10460] opened 2018-05-07 12:26 UTC
Last weekend I tried to implement the `trainer.test()` in our newest design (#10248 ). During this, I noticed that a few functions and interfaces of `framework.py` are implemented in quite twisty ways. Some of them only make users confused while the others may result in serious bugs. Since `framework.py` is the pivot of our Python API, I propose to polish `framework.py` first before further development on Python API.

Here are some issues I have noticed in the `framework.py`:

1. `Variable` and `Parameter` are using `**kwarg` as it's `__init__` inputs. With `**kwarg`, users are likely to be confused about what is exactly required to create a `Variable` and `Parameter`. 

https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L152-L163

https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L1182

2. Some code in the `__init__` of `Variable` is used to handle the situation that the variable to be created has existed. In this part of code, we check each attribute of `Variable` one by one to make sure the existing variable is consistent with the one to be created, which makes the code extremely long. Is there any way to simplify this part?

https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L167-L236

3. The function of `var()` is opposite in `Block` and `Scope`. If the queried variable not exists, the `var()` of `Block` will throw an exception while the one of `Scope` will create it.

The `var()` of `Block`:
https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L717-L723

The `var()` of `Scope`:
https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/paddle/fluid/framework/scope.cc#L51-L59

4. The `clone_variable()` of `Block` does not clone all attributes of variables correctly. `capacity`, `error_clip` and `stop_gradient` are omitted. And why all cloned `Variable`'s `persistable` are True?

https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L960-L990

5. In the `Program`'s `clone` interface. The new `Program` is created with the old one's C++ desc instead of the Python object itself. However, some information only exists in Python(e.g., error_clip, stop_gradient, ...). It mean a `Program` cannot be cloned entirely with this interface. 

https://github.com/PaddlePaddle/Paddle/blob/f43b71b242467d665c134262c2b7167cef622757/python/paddle/fluid/framework.py#L1030-L1054

**Comment by panyx0718** [comment] 2018-05-08 00:44
1. Agree that we should do the clean up. Not sure why was kwargs used? In some usecases, it is needed. But we should avoid it if it's not necessary.

2. Those seems to be necessary checks to me. BTW, I notice "error_clip" doesn't have comments...

3. This is not good, I think we should make them consistent if there aren't special reason. At least, they should be make the behavior clearly documented.

4. sounds like a bug...perhaps need a test.

5. Similar to 4.

**Comment by tonyyang-svail** [comment] 2018-05-08 21:48
@JiayiFeng Thanks for this detailed list. I agree that we need to refactor `framework.py` before moving on to add more API.

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
Labels: Code Cleanup
