### ISSUE TITLE
clip_op gradient calculation is wrong.

### ISSUE THREAD

**Issue by wanglei828** [PaddlePaddle/Paddle#12597] opened 2018-08-08 22:11 UTC
In https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/clip_op.h
The clip grad functor is defined like this:

template <typename T>
class ClipGradFunctor {
 public:
  explicit ClipGradFunctor(const T min, const T max) : min_(min), max_(max) {}
  HOSTDEVICE T operator()(const T& x, const T& y) const {
    return (y > min_ && y < max_) ? **x** : 0;
  }

 private:
  T min_;
  T max_;
};

I think the gradient calculation is wrong, it should be:
return (y > min_ && y < max_) ? **1** : 0;

**Comment by dzhwinter** [comment] 2018-08-09 15:24
It's not. 
Here we are caculate the dx, not the dy/dx, according to the equation of dx = dy, so here we will fill with dy instead of 1.

**Comment by lucywsq** [comment] 2018-09-20 16:28
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-09-20 16:28 UTC
