### ISSUE TITLE
[High priority bug] Need to fix mkldnn conv3d

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#38693] opened 2022-01-04 10:44 UTC
![图片](https://user-images.githubusercontent.com/22114318/148046949-e4ff4143-ee91-4dd7-9f1a-eac8c624f13e.png)

Steps to reproduce:

1. Pull this pr https://github.com/PaddlePaddle/Paddle/pull/38692
2. cmake with `-DWITH_TESTING=ON`, then build paddle.
3. ~~`ctest -R test_mkldnn_conv3d -V`~~ `ctest -R test_mkldnn_conv3d_op -V`

**Comment by baoachun** [comment] 2022-01-04 10:44
@lidanqing-intel

**Comment by jczaja** [comment] 2022-02-08 09:55
@pawelpiotrowicz will investigate a problem

**Comment by pawelpiotrowicz** [comment] 2022-02-09 14:02
I can't reproduce the issue , I used latest code . I tested Release & Debug version. 
```
commit f71241b9d13cb524d2a4753c974813fdda2919fe (upstream/develop)
Author: Yiqun Liu <liuyiqun01@baidu.com>
Date:   Tue Feb 8 20:47:28 2022 +0800
Rename partial function name TensorReduceFunctorImpl to TensorReduceImpl. (#39388)
```

![errok](https://user-images.githubusercontent.com/48519735/153216129-10890a7c-23f4-45c5-beb9-dd82a7608964.png)

**Comment by baoachun** [comment] 2022-02-10 02:24
Sorry for the typo in the name of the unit test.

**Comment by lidanqing-vv** [comment] 2022-02-14 07:10
@pawelpiotrowicz  Hi, Baoachun updated that the UT is `ctest -R test_mkldnn_conv3d_op -V`

**Comment by jczaja** [comment] 2022-03-25 12:10
@baoachun , @lidanqing-intel I have PR (#40923, still fixing CI) that fixes this issue. This PR includes PR with unit test e.g #38692 . There one thing to know. Execution of this test (as measured on my CLX server ) takes over an hour e.g. "Ran 1 test in 4452.513s".  If you thing this is too long then modify PR #38692 so it is shorter. If additional time in CI is not a problem then I will try have my PR merged.

**Closed as completed** 2022-04-18 07:28 UTC
Labels: Intel
