### ISSUE TITLE
Smart handling of the attribute type

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#8418] opened 2018-02-12 22:23 UTC
Some operators have float attributes. It is quite often that a user will provide an integer value for a float attribute. This will cause paddle to generate the following error:

paddle.v2.fluid.core.EnforceNotMet: Cannot get attribute max by type f, its type is i at [/home/wei/code/baidu/idl/dl/robot/external/paddle/paddle/fluid/framework/attr\
ibute.h:131]

We should have some way to avoid this. For bool attribute, we also should allow 0 or 1 in addition to True or False as value.

**Comment by shanyi15** [comment] 2018-08-15 11:38
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:38 UTC
