### ISSUE TITLE
why we need save the model file twice?

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#11700] opened 2018-06-25 14:27 UTC
https://github.com/PaddlePaddle/Paddle/blob/67ab324090116c9b4eb34fd30449def4d134adc8/python/paddle/fluid/io.py#L173-L185

Inside the snippet I have pasted, the vars have been saved twice. First, why we need to use different op `save`, `save_combine` to save them?
Second, considering that we are using the parallel executor for accelerating the execution,  these save operator will be executed at the same time(because they are the graph leaf node, no more dependency on it), If we have thousands parameters, then we will keep it busy of open and close file, that may cause the mem_anony and mem_cached grow rapidly.

**Comment by panyx0718** [comment] 2018-06-26 01:28
I think the save_op is created in a different program from the train program? So it won't be run by the parallel executor?

**Comment by panyx0718** [comment] 2018-06-26 01:32
perhaps save api should have an option to pick combined/not-combined? so that it's saved once?

**Comment by Superjomn** [comment] 2018-06-26 05:03
Yes, I think one default option is ok.

**Comment by shanyi15** [comment] 2018-08-15 11:00
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:00 UTC
