### ISSUE TITLE
test_run_program random failure

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#41180] opened 2022-03-30 15:37 UTC
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
```
 $ python3.7 tools/summary_env.py
****************************************
Paddle version: 2.2.2
Paddle With CUDA: False

OS: Ubuntu 18.04
Python version: 3.7.12

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************
```
- 复现步骤
```
$ echo "
FROM paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install python3 python3-pip -y

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.2.2 && \
    sed -i 's/BRPC_DEPS brpc/BRPC_DEPS brpc ssl crypto/g' Paddle/paddle/fluid/framework/CMakeLists.txt

RUN pip install --upgrade pip && \
    pip install -r Paddle/python/requirements.txt

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="70" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=OFF \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=OFF \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.7

RUN cd Paddle/build && make -j`nproc`
" > Dockerfile
$ docker build -t paddle .
$ docker run -it --rm paddle bash -c 'set -xe; cd Paddle/build; for i in `seq 1 5000`; do ctest -R test_run_program_op --output-on-failure; done'
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
`test_run_program_op` failed randomly. The error log is following
```
+ ctest -R test_run_program_op --output-on-failure
Test project /home/Paddle/build
    Start 955: test_run_program_op
1/1 Test #955: test_run_program_op ..............***Failed    4.01 sec
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0330 09:31:10.555384 59953 init.cc:202] AVX is available, Please re-compile on local machine
W0330 09:31:10.754853 59953 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0330 09:31:10.757567 59953 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
/home/Paddle/build/python/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
test_run_program_op failed
 ...E.
======================================================================
ERROR: test_check_grad (test_run_program_op.TestRunProgramOpWithFC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 262, in test_check_grad
    self.check_grad()
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 70, in check_grad
    self.check_grad_with_place(place)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 120, in check_grad_with_place
    actual_grads = self.calc_dygraph_grad(place)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 205, in calc_dygraph_grad
    attrs=self.attrs)
  File "/home/Paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: In user code:

    File "/home/Paddle/tools/test_runner.py", line 63, in <module>
      main()
    File "/home/Paddle/tools/test_runner.py", line 47, in main
      res = unittest.TextTestRunner(stream=buffer).run(tests)
    File "/usr/lib/python3.7/unittest/runner.py", line 176, in run
      test(result)
    File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
      return self.run(*args, **kwds)
    File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
      test(result)
    File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
      return self.run(*args, **kwds)
    File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
      test(result)
    File "/usr/lib/python3.7/unittest/case.py", line 676, in __call__
      return self.run(*args, **kwds)
    File "/usr/lib/python3.7/unittest/case.py", line 628, in run
      testMethod()
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 312, in test_check_output
      self.check_output()
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 61, in check_output
      self.check_output_with_place(place)
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 112, in check_output_with_place
      actual_outs = self.calc_dygraph_output(place)
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 176, in calc_dygraph_output
      self.program_desc, self.fwd_op_num = self.get_program_desc()
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 94, in get_program_desc
      fwd_op_num = self.build_model()
    File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_run_program_op.py", line 336, in build_model
      is_sparse=True)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/Paddle/build/python/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/Paddle/build/python/paddle/fluid/framework.py", line 238, in __impl__
      return func(*args, **kwargs)
    File "/home/Paddle/build/python/paddle/fluid/input.py", line 334, in embedding
      'padding_idx': padding_idx
    File "/home/Paddle/build/python/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/Paddle/build/python/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/Paddle/build/python/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: ShapeError: The dimensions of the 'lookup table' must be 2. But received lookup table's dimensions = 1, lookup table's shape = [0].
      [Hint: Expected table_dims.size() == 2, but received table_dims.size():1 != 2:2.] (at /home/Paddle/paddle/fluid/operators/lookup_table_v2_op.cc:51)
      [operator < lookup_table_v2 > error]  [operator < run_program > error]

----------------------------------------------------------------------
Ran 5 tests in 1.932s

FAILED (errors=1)

0% tests passed, 1 tests failed out of 1
```

**Comment by GuoxiaWang** [comment] 2022-03-31 01:35
这个问题应该和 [41182](https://github.com/PaddlePaddle/Paddle/issues/41182) 类似的

**Comment by zlsh80826** [comment] 2022-03-31 06:14
@GuoxiaWang 
The error message is completely different.

**Comment by GuoxiaWang** [comment] 2022-03-31 06:17
@zlsh80826  ok,  I try to find the problem.

**Comment by Aurelius84** [comment] 2022-03-31 06:56
@zlsh80826 I suppose that it's caused by Python `id` re-use mechanism. You can replace `_hash_with_id` with
```python
self.attrs['program_id'] = _hash_with_id(self.program_desc, self) # add self to calculate hash id
```

Under `run_program`, we have an `ExecutorCache` for each ProgramDesc, and it use the returned hash id as key. Becuse the python `id` re-use mechanism, `ExecutorCache` may not create a new Executor for ProgramDesc in differnt unittest.

Note: The underly Executor is a stateful calss and holds ProgramDesc as memeber.

**Comment by zlsh80826** [comment] 2022-03-31 07:23
@Aurelius84 
1. I tried to print the values of `_hash_with_id(self.program_desc)`, but I find the hash value is different in each run. I suppose the same program_desc should generate the same hash_value, right?
2. Will `_hash_with_id(self.program_desc, self)` solve the problem? If the problem is caused by hash collision, then the problem may still exist after adding the `self` as the hash key.

**Comment by Aurelius84** [comment] 2022-04-01 01:37
@zlsh80826 
`_hash_with_id()` uses arguments `id` information to calculate hash value. In each Python process,  `ExecutorCache` will be descontructed after exitting process. We have complex logic for `_hash_with_id `(pass many arguments as 'salt') but this unittest doesn't do this. That's why we suggest you pass `self` into  `_hash_with_id`. It can work.

**Comment by zlsh80826** [comment] 2022-04-01 01:53
@Aurelius84 got it. Could you file a PR to resolve this issue?

**Comment by Aurelius84** [comment] 2022-04-06 02:24
@zlsh80826 Thanks,  I will file a PR to fix this, merged: https://github.com/PaddlePaddle/Paddle/pull/41200

**Comment by zlsh80826** [comment] 2022-04-08 08:27
Thank @Aurelius84, I will have a try. If it works well, I will close this issue.

**Closed as completed** 2022-04-21 03:22 UTC
Labels: NVIDIA
