### ISSUE TITLE
Paddle 转换 ONNX格式

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#11846] opened 2018-06-29 08:30 UTC
Paddle 如何转换 ONNX格式？VisualDL的Graph使用。

**Comment by kuke** [comment] 2018-06-29 08:50
FYI https://github.com/PaddlePaddle/paddle-onnx

**Comment by xiaolv3366** [comment] 2018-06-29 09:05
VisualDL的Graph支持原生态的PaddlePaddle格式吗？
还是只支持ONNX格式？
如果只支持ONNX格式，Paddle如何转换ONNX格式？

**Comment by xiaolv3366** [comment] 2018-06-29 09:06
@kuke Paddle Fluid -> ONNX convertor?  Paddle V2可以转吗？

**Comment by kuke** [comment] 2018-06-29 11:45
VisualDL  应该是支持onnx格式的，目前只支持fluid模型的转换，v2并不支持。

**Comment by xiaolv3366** [comment] 2018-07-02 02:59
VisualDL的Graph不支持自家的PaddlePaddle格式。

**Comment by shanyi15** [comment] 2018-08-15 10:19
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:19 UTC
