### ISSUE TITLE
test_analyzer_transformer random fails on compare

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#16316] opened 2019-03-20 05:28 UTC
http://ci.paddlepaddle.org/viewLog.html?buildId=72226&tab=buildLog&buildTypeId=Paddle_PrCiPython35Night&logTab=tree&filter=all&_focus=13745
```
[23:57:29][ RUN      ] Analyzer_Transformer.compare
[23:57:29]I0319 23:55:10.920542 17062 analyzer_transformer_tester.cc:176] The number of samples to be test: 8
[23:57:29]I0319 23:55:10.922397 17062 tester_helper.h:65] AnalysisConfig {
[23:57:29]  NativeConfig {
[23:57:29]    PaddlePredictor::Config {
[23:57:29]      model_dir: 
[23:57:29]    }
[23:57:29]    use_gpu: 0
[23:57:29]    device: 0
[23:57:29]    fraction_of_gpu_memory: 0.00219227
[23:57:29]    specify_input_name: 1
[23:57:29]    cpu_num_threads: 1
[23:57:29]  }
[23:57:29]  prog_file: /root/.cache/inference_demo/transformer/model/model
[23:57:29]  param_file: /root/.cache/inference_demo/transformer/model/params
[23:57:29]  enable_ir_optim: 1
[23:57:29]  enable_ir_optim: 1
[23:57:29]  use_feed_fetch_ops: 1
[23:57:29]  use_tensorrt: 0
[23:57:29]  use_mkldnn: 0
[23:57:29]}
[23:57:29]W0319 23:55:10.925616 17062 init.cc:153] AVX is available, Please re-compile on local machine
[23:57:29]I0319 23:55:11.322595 17062 tester_helper.h:278] Running thread 0, warm up run...
[23:57:29]I0319 23:55:44.447240 17062 helper.h:270] ====== batch_size: 8, repeat: 1, threads: 1, thread id: 0, latency: 33124.5ms, fps: 0.0301891 ======
[23:57:29]I0319 23:55:44.447353 17062 tester_helper.h:301] Thread 0 run 1 times...
[23:57:29]I0319 23:56:17.681612 17062 helper.h:270] ====== batch_size: 8, repeat: 1, threads: 1, thread id: 0, latency: 33234.2ms, fps: 0.0300895 ======
[23:57:29]W0319 23:56:17.688809 17062 init.cc:153] AVX is available, Please re-compile on local machine
[23:57:29]--- Running analysis [ir_graph_build_pass]
[23:57:29]--- Running analysis [ir_analysis_pass]
[23:57:29]--- Running IR pass [infer_clean_graph_pass]
[23:57:29]--- Running IR pass [attention_lstm_fuse_pass]
[23:57:29]--- Running IR pass [seqpool_concat_fuse_pass]
[23:57:29]--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
[23:57:29]--- Running IR pass [fc_lstm_fuse_pass]
[23:57:29]--- Running IR pass [mul_lstm_fuse_pass]
[23:57:29]--- Running IR pass [fc_gru_fuse_pass]
[23:57:29]--- Running IR pass [mul_gru_fuse_pass]
[23:57:29]--- Running IR pass [seq_concat_fc_fuse_pass]
[23:57:29]--- Running IR pass [fc_fuse_pass]
[23:57:29]---  detected 12 subgraphs
[23:57:29]--- Running IR pass [repeated_fc_relu_fuse_pass]
[23:57:29]--- Running IR pass [squared_mat_sub_fuse_pass]
[23:57:29]--- Running IR pass [conv_bn_fuse_pass]
[23:57:29]--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
[23:57:29]--- Running IR pass [is_test_pass]
[23:57:29]--- Running IR pass [identity_scale_op_clean_pass]
[23:57:29]--- Running analysis [ir_params_sync_among_devices_pass]
[23:57:29]--- Running analysis [ir_graph_to_program_pass]
[23:57:29]I0319 23:56:24.455240 17062 analysis_predictor.cc:396] == optimize end ==
[23:57:29]I0319 23:56:24.456599 17062 tester_helper.h:278] Running thread 0, warm up run...
[23:57:29]W0319 23:56:24.456904 17062 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
[23:57:29]W0319 23:56:24.456938 17062 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
[23:57:29]W0319 23:56:24.456956 17062 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
[23:57:29]I0319 23:56:56.635799 17062 helper.h:270] ====== batch_size: 8, repeat: 1, threads: 1, thread id: 0, latency: 32179.1ms, fps: 0.031076 ======
[23:57:29]I0319 23:56:56.635892 17062 tester_helper.h:301] Thread 0 run 1 times...
[23:57:29]W0319 23:56:56.636173 17062 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
[23:57:29]W0319 23:56:56.636209 17062 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
[23:57:29]W0319 23:56:56.636229 17062 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
[23:57:29]I0319 23:57:28.508708 17062 helper.h:270] ====== batch_size: 8, repeat: 1, threads: 1, thread id: 0, latency: 31872.8ms, fps: 0.0313748 ======
[23:57:29]/paddle/paddle/fluid/inference/tests/api/tester_helper.h:82: Failure
[23:57:29]      Expected: size
[23:57:29]      Which is: 645
[23:57:29]To be equal to: ref_size
[23:57:29]      Which is: 666
[23:57:29]/paddle/paddle/fluid/inference/tests/api/tester_helper.h:89: Failure
[23:57:29]      Expected: pdata_ref[j]
[23:57:29]      Which is: 6444
[23:57:29]To be equal to: pdata[j]
[23:57:29]      Which is: 23118
[23:57:29]/paddle/paddle/fluid/inference/tests/api/tester_helper.h:89: Failure
[23:57:29]      Expected: pdata_ref[j]
[23:57:29]      Which is: 10
[23:57:29]To be equal to: pdata[j]
[23:57:29]      Which is: 855
```

**Comment by luotao1** [comment] 2019-03-20 05:30
@yihuaxu @bingyanghuang @jianhang-liu Could you help see it?

**Comment by LeoZhao-BJ** [comment] 2019-03-20 06:53
trying to reproduce locally

**Comment by LeoZhao-BJ** [comment] 2019-03-21 05:41
@luotao1 

Did it happen just once? or need special env? I see this was old CI build without mkldnn enabled in transformer yet, I try latest code, can't reproduce locally with hundreds of test on 2699v3 machine, please monitor this issue once it happens again.

**Comment by luotao1** [comment] 2019-03-21 06:56
Got it.

**Comment by luotao1** [comment] 2019-03-21 07:09
@LeoZhao-Intel It fails on our CI yesterday night as well.
http://ci.paddlepaddle.org/viewLog.html?buildId=72666&buildTypeId=Paddle_PrCiPython35Night&tab=buildLog&_focus=53857

**Comment by LeoZhao-BJ** [comment] 2019-03-21 07:34
@luotao1  any guide for setting up same env with CI ?

**Comment by luotao1** [comment] 2019-03-21 08:02
You can refer to the build log,  which has complete image info and cmake options.
For example, it use `paddlepaddle/paddle_manylinux1_devel_cuda8.0_cudnn7` images.
http://ci.paddlepaddle.org/viewLog.html?buildId=72666&buildTypeId=Paddle_PrCiPython35Night&tab=buildLog&_focus=160

**Comment by ghost** [comment] 2019-03-25 15:11
@luotao1 I checked log and found the error (compare) occur on a build with AVX=OFF.
- Build log: 
   _[23:02:22] :	 [Step 1/1]         -DWITH_AVX=OFF_
- Runtime log:
   _[23:59:50] :	 [Step 1/1] W0320 23:49:52.179419 15817 init.cc:153] AVX is available, Please re-compile on local machine_

When run "compare" test case in Transformer model, the only difference between the original graph and the optimized graph (by analysis config) is "FC". I did check the difference between "Mul" op (before fuse) and "FC" op (after fuse).
- Mul OP: call blas.MatMul()
- FC OP: call inline function FCCompute() which will directly call JIT function.

I doubt whether JIT selection has some issues when AVX=OFF. @tensor-tang Could you have a quick look here?

**Comment by tensor-tang** [comment] 2019-03-25 17:16
Did not get your point.
`FCCompute` still call `blas.MatMul`.

https://github.com/PaddlePaddle/Paddle/blob/de3b70a101dabd48e0659ddb4df4651b882aeafa/paddle/fluid/operators/math/fc_compute.h#L28

And JITKernel has unit tests and pass on AVX=OFF.

**Comment by tensor-tang** [comment] 2019-03-25 17:27
Besides, the size is different 

> [23:57:29]/paddle/paddle/fluid/inference/tests/api/tester_helper.h:82: Failure [23:57:29] Expected: size [23:57:29] Which is: 645
 [23:57:29]To be equal to: ref_size [23:57:29] Which is: 666

**Comment by LeoZhao-BJ** [comment] 2019-03-26 03:25
In CI build, for transformer test, only profile, fuse_statis and compare were enabled, mkldnn is disabled.
For first failure on size, the correct value should be 666, that means Analysis path gets wrong result, wondering where the defect is. 
On local machine, even with same cmake options without GPU, it is hard to reproduce, trying to find another way to reproduce firstly.

**Comment by luotao1** [comment] 2019-03-26 03:37
Is it related to #16233

**Comment by luotao1** [comment] 2019-03-26 03:39
Is it related to #16088?

**Comment by ghost** [comment] 2019-03-26 03:44
@luotao1 No. This "random failure" issue fail due to different "comparation" between native predict and analysis predict. The only "applied" pass in Transformer model is "FC fuse". And it happen on a build with both MKL OFF and AVX OFF.

**Comment by LeoZhao-BJ** [comment] 2019-03-26 03:45
I remember this patch was merged for some days, should not occur if it really fixed the issue.
@luotao1  in recent days, this issue is still there, and from failure points, the values are exactly same with previous build. it looks like not a random issue.

**Comment by luotao1** [comment] 2019-03-27 03:28
http://ci.paddlepaddle.org/viewLog.html?buildId=75982&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all&_focus=18076
```
[02:56:04]	/paddle/paddle/fluid/inference/tests/api/tester_helper.h:82: Failure
[02:56:04]	      Expected: size
[02:56:04]	      Which is: 858
[02:56:04]	To be equal to: ref_size
[02:56:04]	      Which is: 666
[02:56:04]	/paddle/paddle/fluid/inference/tests/api/tester_helper.h:89: Failure
[02:56:04]	      Expected: pdata_ref[j]
[02:56:04]	      Which is: 9917
[02:56:04]	To be equal to: pdata[j]
[02:56:04]	      Which is: 6588
[02:56:04]	/paddle/paddle/fluid/inference/tests/api/tester_helper.h:89: Failure
[02:56:04]	      Expected: pdata_ref[j]
[02:56:04]	      Which is: 4084
[02:56:04]	To be equal to: pdata[j]
[02:56:04]	      Which is: 855
```
New error on new machine.

**Comment by yihuaxu** [comment] 2019-04-10 06:12
From the test result, PR #16756 can fix issue.

**Closed as completed** 2019-04-12 02:46 UTC
Labels: Intel
