### ISSUE TITLE
在集群上进行分布式训练时会不定时出现错误SocketChannel.cpp:101] Check failed: len > 0...

### ISSUE THREAD

**Issue by wkr114** [PaddlePaddle/Paddle#9579] opened 2018-04-02 12:54 UTC
模型：
https://github.com/PaddlePaddle/book/blob/develop/06.understand_sentiment/train.py
教程里的stacked_lstm_net， stracked_num=5.

并行数parallel为10，修改过trainer的cpu， memory，参数服务器的pserver的cpu，memory，以及batch size等参数，始终会出现以下报错。

重复相同的任务，每次出现错误的地方不同。

报错信息如下：
F0402 12:13:25.661372    72 SocketChannel.cpp:101] Check failed: len > 0  peer=10.1.93.9 curIov=7 iovCnt=122 iovs[curIov].base=0x7efc7198c059 iovs[curIov].iov_len=196583
*** Check failure stack trace: ***
    @     0x7efc826c50dd  google::LogMessage::Fail()
    @     0x7efc826c7428  google::LogMessage::SendToLog()
    @     0x7efc826c4bcb  google::LogMessage::Flush()
    @     0x7efc826c82fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7efc824e8954  paddle::SocketChannel::writev()
    @     0x7efc824e9ae8  paddle::SocketChannel::writeMessage()
    @     0x7efc824ea804  paddle::ProtoClient::send()
    @     0x7efc82c3e76e  paddle::ParameterClient2::sendParallel()
    @     0x7efc82625f04  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7efcbccc7c80  (unknown)
    @     0x7efcc76156ba  start_thread
    @     0x7efcc734b3dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)
job returned 134...setting pod return message...

**Comment by seiriosPlus** [comment] 2018-04-03 02:49
你好，能提供一下你的执行环境么， 包括paddle,以及系统环境

**Comment by wkr114** [comment] 2018-04-04 07:25
paddle用的是paddle v2，本地系统是CentOS，使用过多个集群，报的是相同的错误

**Comment by HugoLian** [comment] 2018-08-08 16:27
@wkr114 我也遇到相同的问题了，请问最后解决了么？

**Comment by shanyi15** [comment] 2018-08-15 11:04
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:04 UTC
Labels: User
