### ISSUE TITLE
Some issue about crop_op and reshape_op

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#6533] opened 2017-12-12 11:26 UTC
Currently, the shape is as an attribute in the  `crop_op` and `reshape_op`, I think it's unwise. 
Imagine that when these op are used to process text data, and the last batch of the data is less than batch_size, `reshape_op` will go wrong. The case is [here](https://github.com/dzhwinter/benchmark/pull/16).
So, in my opinion, shape should be used as a OP input.
@kuke @wanghaoshuang

**Comment by kuke** [comment] 2017-12-12 13:07
OK, I will move ```shape``` to the input of ```reshape_op```.

**Comment by shanyi15** [comment] 2018-08-15 11:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 11:11 UTC
