### ISSUE TITLE
Temporarily disable test_understand_sentiment.py

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#10482] opened 2018-05-08 06:20 UTC
The previous teamcity CI setting has some issues, causing some test failures cannot be caught. So some previous PR modifications are wrong. 
To enable continue working, I temporarily disable test_understand_sentiment.py in #10480 https://github.com/PaddlePaddle/Paddle/pull/10480/commits/e87b345d50076d0f66f30ab2b46b907a8b711a43.

**Comment by shanyi15** [comment] 2018-08-15 10:26
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:26 UTC
