### ISSUE TITLE
windows下的docker 安装 （Docker‘s installtion for win10,64bit）

### ISSUE THREAD

**Issue by u5tony** [PaddlePaddle/Paddle#11751] opened 2018-06-26 14:19 UTC
您好，我在win10,64位，普通家庭版的环境下，安装从官网下载的docker tools总是在双击桌面快捷方式Docker Quickstart Terminal，的情况下报错，显示如下（the mistake is）
Starting "default"...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:
VBoxManage.exe: error: The virtual machine 'default' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\u5tony\.docker\machine\machines\default\default\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
Looks like something went wrong in step ´Checking status on default´... Press any key to continue...
谢谢您的帮助，thanks for your help.

![tim 20180626221848](https://user-images.githubusercontent.com/23191627/41918453-f46d2f86-798e-11e8-854b-af8c0c2880ed.png)

**Comment by qingqing01** [comment] 2018-06-27 01:41
可以参考docker官方的issue: https://github.com/docker/toolbox/issues/473

**Comment by u5tony** [comment] 2018-06-27 05:48
试过了，由于是win10 家庭版暂时不支持@qingqing01

**Comment by qingqing01** [comment] 2018-06-27 13:26
@u5tony 那现在是什么情况？还有问题吗？

**Comment by u5tony** [comment] 2018-06-27 13:33
就是在windows下两种方法都装不上，我刚刚换用在windows下装Ubuntu，在Ubuntu下试试。 @qingqing01

**Comment by shanyi15** [comment] 2018-08-15 11:34
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 11:34 UTC
Labels: User
