### ISSUE TITLE
编译Android实例程序，cmake出错 The C++ compiler ** is not able to compile a simple test program

### ISSUE THREAD

**Issue by ZoeZxt** [PaddlePaddle/Paddle#10050] opened 2018-04-19 06:19 UTC
hi， 我按照网页想编一个demo在Android手机上测试，
到 [Step 2，编译示例程序] 进行cmake时出错了，DANDROID_STANDALONE_TOOLCHAIN 设置的路径是上一步【Android平台编译指南】下载的android-ndk-r14b，解压后的路径。
http://www.paddlepaddle.org/docs/develop/mobile/benchmark/tool/C/README.cn.html

命令及错误信息如下，是版本不对吗？
$ **cmake .. -DANDROID_ABI=armeabi-v7a -DANDROID_STANDALONE_TOOLCHAIN=/Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64  -DPADDLE_ROOT=/Users/baidu/paddlepaddle/Paddle/install_android -DCMAKE_BUILD_TYPE=MinSizeRel**
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
-- Check for working CXX compiler: /Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
-- Check for working CXX compiler: /Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -- broken
CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  **The C++ compiler

    "/Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++"

  is not able to compile a simple test program.**

  It fails with the following output:

    Change Dir: /Users/baidu/paddlepaddle/Mobile/benchmark/tool/C/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_95f49/fast"
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_95f49.dir/build.make CMakeFiles/cmTC_95f49.dir/build
    Building CXX object CMakeFiles/cmTC_95f49.dir/testCXXCompiler.cxx.o
    /Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++    -ffunction-sections -fdata-sections -mfpu=neon     -o CMakeFiles/cmTC_95f49.dir/testCXXCompiler.cxx.o -c /Users/baidu/paddlepaddle/Mobile/benchmark/tool/C/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    /Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++: /Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++: cannot execute binary file
    make[1]: *** [CMakeFiles/cmTC_95f49.dir/testCXXCompiler.cxx.o] Error 126
    make: *** [cmTC_95f49/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/baidu/paddlepaddle/Mobile/benchmark/tool/C/build/CMakeFiles/CMakeOutput.log".
See also "/Users/baidu/paddlepaddle/Mobile/benchmark/tool/C/build/CMakeFiles/CMakeError.log".

**Comment by ZoeZxt** [comment] 2018-04-19 08:17
可能是 DANDROID_STANDALONE_TOOLCHAIN 配置的独立工具链路径错误导致的。看上一步$docker run -it --rm -v $PWD:/paddle -e "ANDROID_ABI=armeabi-v7a" -e "ANDROID_API=21" usename/paddle-android:dev 执行的结果中，路径应该是 --install-dir=/opt/toolchains/arm-android-21

但/opt 并没有toolchains 目录，所以，上一步生成的独立工具链路径到底是哪里呢？？

**Comment by ZoeZxt** [comment] 2018-04-19 10:02
我自己重新生成独立工具链也报错，
prebuilt 路径下只有linux-x86_64 但命令运行起来在找darwin-x86_64，这是怎么回事呢，也找不到可以配置的参数~~
android-ndk-r14b/build/tools/make-standalone-toolchain.sh --arch=arm --platform=android-21 --install-dir=/opt/toolchains/arm-android-21 --verbose
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
## COMMAND: python android-ndk-r14b/build/tools/make_standalone_toolchain.py --arch arm --api 21 --stl gnustl --install-dir=/opt/toolchains/arm-android-21
Could not find GCC/binutils: **/Users/baidu/paddlepaddle/Paddle/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64**
ERROR: Failed to create toolchain.

**Comment by shanyi15** [comment] 2018-08-15 10:28
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed by shanyi15** 2018-08-15 10:28 UTC
Labels: User
