### ISSUE TITLE
How to use conv_op?

### ISSUE THREAD

**Issue by rationme** [PaddlePaddle/Paddle#13050] opened 2018-08-29 10:02 UTC
'EnforceNotMet: enforce in_dims.size() == filter_dims.size() failed, 4 != 1
Conv input dimension and filter dimension should be the same. at [/paddle/paddle/fluid/operators/conv_op.cc:49]'

when i run my code 
`main_program, feed=feeder.feed(data),fetch_list=[l2_cost])`
and 
`def CSRNet(input,label):
    def conv_block(ipt, filter_list,pool_size = 2):
        return fluid.nets.img_conv_group(
        input=ipt,
        pool_size=pool_size,
        pool_stride=pool_size,
        conv_num_filter=filter_list,
        conv_filter_size=3,
        conv_act='relu',
        conv_with_batchnorm=False,
        conv_batchnorm_drop_rate=1,
        pool_type='max')

    frontend_conv1 = conv_block(input,[64,64])

    frontend_conv2 = conv_block(frontend_conv1,[128,128])

    frontend_conv3 = conv_block(frontend_conv2 ,[256, 256,256])

    frontend_conv4 = conv_block(frontend_conv3,[512,512,512],1)`

I can't find where the  input dimension is?how to use it?

**Comment by velconia** [comment] 2018-08-29 12:08
Could u please print the ```filter_list``` out, it seems that the input filter's dims were incorrect

**Comment by lucywsq** [comment] 2018-10-10 09:20
Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by lucywsq** 2018-10-10 09:20 UTC
Labels: User
